### ISSUE TITLE
Add repositioning for proximity and hover lights

### ISSUE THREAD

**Issue by FlyingFlambe** [microsoft/MixedRealityToolkit-Unity#10043]
## Describe the problem

I frequently work with models that use a different origin position than the origin point that's needed for a given child/parent model. Without the ability to change a component's origin position, such as with proximity and hover lights, I don't have as much flexibility when providing a good UX.

![image](https://user-images.githubusercontent.com/22328598/124031074-7bdb9800-d9bc-11eb-904e-1a195f986c0a.png)

## Describe the solution you'd like

By repositioning the origin point of a light, I won't need to use a large radius that may affect other models nearby. Similar to colliders in Unity, the ability to reposition the origin would be helpful!

## Describe alternatives you've considered

The most I can do is to make the radii unnecessarily large so that the material saturates the color enough for it to be noticeable. The downside is that it affects adjacent models that also have hover/proximity lights enabled on their materials. I also can't create a dummy child game object and use the light component scripts there, since the primary game object is what uses the material for lighting.

![image](https://user-images.githubusercontent.com/22328598/124031258-b5ac9e80-d9bc-11eb-99fe-e728f0dd7cb0.png)

(I realize that proximity lights are better for near interactions than hover lights, but I thought I'd mention them as well since the issues are similar.)

**Comment by elbuhofantasma** [comment]
Hello @FlyingFlambe thanks for your feature request! I have assigned the Urgency-Later label because this seems like it would be a significant refactor and it is not failing to build.

**Comment by keveleigh** [comment]
@Cameron-Micka Is this something that's supported in any form today?

**Comment by Cameron-Micka** [comment]
Hi @FlyingFlambe, thank you for bringing this request up. It would be easy to add a local offset to the light's position, but I'm curious if you could achieve this already with a child gameobject? 

The hover light and proximity light behave a lot like Unity's built-in [point light](https://docs.unity3d.com/Manual/Lighting.html) since they are a component which get their transformation from the transform component of the gameobject they are attached to. 

In your case could you add a child gameobject to the the renderer you are trying to illuminate then add a hover/proximity light component to that child gameobject? Then you could set the child's local position to a value that corresponds to the required offset. Would that work for your scenario?

**Comment by FlyingFlambe** [comment]
> Hi @FlyingFlambe, thank you for bringing this request up. It would be easy to add a local offset to the light's position, but I'm curious if you could achieve this already with a child gameobject?
> 
> In your case could you add a child gameobject to the the renderer you are trying to illuminate then add a hover/proximity light component to that child gameobject? Then you could set the child's local position to a value that corresponds to the required offset. Would that work for your scenario?

I'll look into this and get back to you on it.

**Comment by FlyingFlambe** [comment]
Yep that solution works, thanks.
