### ISSUE TITLE
Get the thermal stage of Hololens

### ISSUE THREAD

**Issue by BrunoVarelaKitAr** [microsoft/MixedRealityToolkit-Unity#10061]
## Describe the problem

We want to check the thermal stage of the Hololens to check how some features of our app behave when the hololens temperature gets warmer. We discovered that we can retrieve this information using the device portal rest API but for that, we need to have the hololens in Developer mode settings and also have a login for the Hololens.
This pre requisites for a production setting are really complicated to manage.

## Describe the solution you'd like

Have some sort of package/Function in MRTK that gives us this information.

## Describe alternatives you've considered

There is none.

**Comment by MaxWang-MS** [comment]
Thanks for the feature request! Unfortunately this is something that MRTK cannot offer right now because currently there is no platform API for the thermal stage. Please submit a feature request to the appropriate team through [feedback hub on your HoloLens device](https://docs.microsoft.com/hololens/hololens-feedback).
