### ISSUE TITLE
NullReferenceException when setting ManipulationHandler.ConstraintOnRotation early

### ISSUE THREAD

**Issue by hermann-noll** [microsoft/MixedRealityToolkit-Unity#10089]
## Describe the bug

For some application we have to add the `ManipulationHandler` component via code, when proceeding to set the necessary property values a `NullReferenceException` is thrown when setting `ConstraintOnRotation`.
Looking at the source a null check seems to be missing as there is just a couple lines further down for the `UseLocalSpaceForConstraint` property.

## To reproduce

1. Add `ManipulationHandler` via script
2. Immediately set `ConstraintOnRotation` to some value
3. Observe exception being thrown

## Expected behavior

No exception being thrown and constraint being set successfully. 

## Your setup (please complete the following information)

- Unity 2020.3.6f1
- MRTK 2.7.2

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

This might be a duplicate of [#7463](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7463), I could not understand what kind of exception was happening in that issue or whether this was *only* an Android issue. This one is cross-platform.

**Comment by Zee2** [comment]
Hi there @hermann-noll ! I wanted to check to make sure this issue is actually about `ManipulationHandler`, as we've deprecated this class and completely replaced it with `ObjectManipulator`. At this time, we won't be making any improvements or fixes to `ManipulationHandler` because it's been entirely subsumed by the new + improved `ObjectManipulator`. 

If it's possible, I'd recommend migrating to `ObjectManipulator` as soon as possible, and see if your issue is resolved.

**Comment by hermann-noll** [comment]
Migrating did help with that bug ( and some other shortcoming with constraints).
Nevertheless it would have been an easy fix whilst `ManipulationHandler` is still available and advertised (in the docs)
