### ISSUE TITLE
Update Project Settings Window to change backend to .NET

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1011]
Unity recently made project default to IL2CPP backend.

Or give the option to choose between the two.

**Comment by LanceMcCarthy** [comment]
Note: This issue will only present itself if you used the Unity Installer's default selected options (it has IL2CPP and .NET scripting selected by default). If you uncheck IL2CPP during installation, Unity will default to .NET because it's the only installed option.

Otherwise, having a `Use .NET` checkbox in the "Apply Project Settings" menu option would be very helpful.

**Comment by StephenHodgson** [comment]
@LanceMcCarthy thanks for pointing this out.
