### ISSUE TITLE
Constrain Object Manipulation within Collider/Region

### ISSUE THREAD

**Issue by atarng-medivis** [microsoft/MixedRealityToolkit-Unity#10139]
## Overview
Currently there exists ways to constrain the move axis to X-Y-Z axes.

Is there a way to add a constraint for movement to be restricted to within a collider? (Eg. within a box/sphere etc.)

## Mixed Reality Toolkit release version
2.3.0

**Comment by elbuhofantasma** [comment]
Hello @atarng-medivis thank you for submitting this Constraint Manager feature request! 

I spoke with @CDiaz-MS and she thinks that it sounds like you would like to define the greater bounds of where an object can be moved externally. This can be achieved by creating an external Bounds and then check if the position of the object is within the Bounds using Unity's [bounds.Contains](https://docs.unity3d.com/ScriptReference/Bounds.html). 
 
 I would also encourage you to investigate upgrading to the latest version of the MRTK as a lot of improvements have been made since version 2.3.0. However there are some breaking changes between 2.3.0 and 2.7.2 to be aware of. You can find that information in our [Release Notes](https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/release-notes/mrtk-27-release-notes?view=mrtkunity-2021-05).

I am going to close this issue, but please feel free to re-open if this does not solve your query.
