### ISSUE TITLE
Gaze cursor not reappearing

### ISSUE THREAD

**Issue by Spoon2311** [microsoft/MixedRealityToolkit-Unity#10165]
## Describe the bug

When starting the app the gaze cursor is visible, when the hands appear in the line-of-sight the normal hand cursors appear.
But then when taking my hands behind my back again the gaze cursor does not reappear.

## To reproduce

Create a normal Hololens 2 app with OpenXR and using the eyegaze cursor also as an input (NOT the head cursor)

## Expected behavior

When the Hololens doesn't recognize my hands anymore it should switch to back to the gaze-cursor.
This was still the behavior during MRTK 2.5 and when using older versions of Unity. (Previous app of mine still has the desired behaviour)

## Screenshots

https://user-images.githubusercontent.com/59868550/129758501-905b098d-9414-4dd6-948c-3e8f1cbe1fbe.mp4

Here a video on the behavior, please watch with sound as I'm further explaining the issue.

## Your setup (please complete the following information)

- Unity Version [2020.3.16f1 & 2020.3.6f1]
- MRTK Version [2.7.2]
- OpenXR Plugin  [1.2.8]
- Mixed Reality OpenXR Plugin [1.0.1]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by elbuhofantasma** [comment]
Hi @Spoon2311 thank you for your Gaze Cursor issue submission. The scenario that you described is now expected behavior, as we are trying to match the HoloLens 2 Shell behavior. 

You can enable/disable the Gaze cursor using [PointerUtils.cs](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/SDK/Features/Utilities/PointerUtils.cs).

You can use the "SetGazePointerBehavior" class from lines 218-236 in PointerUtils.cs to enable or disable the Gaze pointer at runtime. With the "Set[input type]RayPointerBehavior" classes, you can use the [PointerBehavior Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.mixedreality.toolkit.input.pointerbehavior?view=mixed-reality-toolkit-unity-2020-dotnet-2.7.0) to enable or disable the pointers at runtime by passing the proper PointerBehavior Enum value for disabling or enabling the pointers.

I am going to close this issue, but please feel free to re-open it if you need more information.

**Comment by astaikos316** [comment]
@elbuhofantasma I have been trying to use the PointerUtils to try and re-enable the gaze cursor when hands are not in field of view, but the PointerBehaviour enums are not clear.  There is either AlwaysOn, AlwaysOff, or Default.  When hands aren't tracked, i would like to know how to re-enable the gaze cursor.  Tried setting the SetGazePointerBehavior to Default in a Start function of one mf my scripts but it had no change.
