### ISSUE TITLE
Requesting access to Extended Eye Tracking API

### ISSUE THREAD

**Issue by 962557346** [microsoft/MixedRealityToolkit-Unity#10230]
## Describe the problem
Hi!
I'm currently working on a project that requires left and right eye gaze vectors for obtaining eye gaze depth. Current Eye tracking SDK of HoloLens 2 doesn't provide left and right eye gaze vectors, only offering the single (cyclopean) eye gaze direction and hit position. 

## Describe the solution you'd like
We found [Extended Eye Tracking SDK](https://github.com/magdavuko/mixed-reality-1/blob/d7531c7d233adf33af188c24f2a194b6696db9bf/mixed-reality-docs/mr-dev-docs/develop/native/extended-eye-tracking.md) provides `TryGetLeftEyeGazeInTrackerSpace` and `TryGetRightEyeGazeInTrackerSpace` functions for calculating left eye gaze and right eye gaze. We want to request access to extended ET API. We found the [URL](https://github.com/magdavuko/mixed-reality-1/blob/4f087f80ac5f8a6c13877f3b2cd4875e3eb9cb51/mixed-reality-docs/mr-dev-docs/design/requesting-access-to-extended-et-api). The instructions request us to reach out to Microsoft Mixed Reality team (mail: TDB). However, I don't know the specfic email. Can you tell me how I can obtain the approval of using the Extended Eye Tracking APIs? 

## Describe alternatives you've considered
Additionally, for our use case, falling back to single (cyclopean) eye gaze tracking is not an option.
Thank you very much.

## Additional context
![image](https://user-images.githubusercontent.com/24918185/134343334-08613568-c4e2-42ef-a3a9-aa82ba42bac9.png)

**Comment by polar-kev** [comment]
Hey @962557346, I'll reach out to internal teams and get back to you.

**Comment by 962557346** [comment]
> Hey @962557346, I'll reach out to internal teams and get back to you.

Thank you very much. Looking forward to your prompt reply.

**Comment by polar-kev** [comment]
Additional context provided by @962557346 in #10238 
```
In brief, my questions can be three-fold as follows:

I just want to run the Extended Eye Tracking SDK in the developer mode of HoloLens 2. Do I need to request the custom capability? If don't need, how can I compile the script in Unity that uses the EyeGazeTrackerWatcher class successfully?
If need, how can I contact the Microsoft Mixed Reality team? We found the URL. The instructions request us to reach out to Microsoft Mixed Reality team (mail: TDB). However, I don't know the specfic email. I posted the question in #10230 , but it seems to have no follow-up development.
If need, how can I obtain the Signature Hash of the uwp signing cert? I tried many methods but they don't work. The issue describes this question, but I also don't know how to sign the sln of Visual Studio 2019 with SHA256 cert?
```

**Comment by polar-kev** [comment]
Hey @962557346, some answers to your questions.

**Do I need to request the custom capability? If don't need, how can I compile the script in Unity that uses the EyeGazeTrackerWatcher class successfully?**
Yes, you need to be granted access to use the Extended Eye Tracking SDK.

**If need, how can I contact the Microsoft Mixed Reality team? We found the URL. The instructions request us to reach out to Microsoft Mixed Reality team (mail: TDB).** 
In order to process this request, can you help please answer the following:

- Can you provide more context on your scenario that requires eye gaze depth?
- How do you intend to use the gaze vectors? For interaction? For something else?
- How many devices will you be using this on?
If you prefer to keep your scenario private, feel free to reach out to me directly on the HoloDeveloper Slack.

**Comment by 962557346** [comment]
@polar-kev Hi, Kevin. Thanks for your reply. I have answered your questions on the HoloDeveloper Slack.

**Comment by polar-kev** [comment]
Closing as per our discussion on slack.
