### ISSUE TITLE
Spatial Awarness System doesn't work in Holographic Remoting Player v2.7.1 from build

### ISSUE THREAD

**Issue by Nox7atra** [microsoft/MixedRealityToolkit-Unity#10293]
## Describe the bug

Spatial Awarness System doesn't work in Holographic Remoting Player

## To reproduce

1. Follow steps from this tutorial (OpenXR) https://docs.microsoft.com/en-us/learn/modules/pc-holographic-remoting-tutorials/
2. Add HolographicRemoting prefab to any Sample scene with spartial awarness system and build. For example SpatialAwarenessMeshDemo

## Expected behavior

Spartial Awarness system builds spatial mesh.

## Your setup (please complete the following information)

- Unity Version 2020.3.21f
- MRTK Version v2.7.2
- Holographic Remoting Player v.2.7.1.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

All systems works well except Spatial Awarness System. There are no errors, If i try to resume system by CoreServices.SpatialAwarenessSystem.ResumeObservers(); it says warning that "System already started" but it doesn't build spatial mesh. With Remoting from editor it works well (with some problems but works), that why I think that configuration OK. (I'm using DefaultMixedRealitySpatialAwarnessSystemProfile). Render, Hand Tracking and other systems works well

**Comment by polar-kev** [comment]
Hey @Nox7atra, we've seen some issues with Unity 2020.3.21f. Can you try testing on an earlier version of Unity 2020.3 LTS?

Also, which version of the Microsoft Mixed Reality OpenXR plugin are you using?

**Comment by Nox7atra** [comment]
1.1.2

**Comment by polar-kev** [comment]
Thank you.
FYI @keveleigh. Is this expected on either of these versions?

**Comment by keveleigh** [comment]
> Thank you. FYI @keveleigh Kurtis Eveleigh FTE. Is this expected on either of these versions?

It's not! From initial tests on the OpenXR plugin side, this may be MRTK-specific.

**Comment by Nox7atra** [comment]
So maybe right now there are any workaround?

**Comment by polar-kev** [comment]
No workaround yet @Nox7atra. Thanks for reporting this.

**Comment by keveleigh** [comment]
@Nox7atra Are you building for Windows Standalone or UWP? If Windows Standalone, looks like there are a couple issues. If UWP, there's still one!

One of the issues is that the OpenXR observer is only set to UWP. You can fix this by cloning the profile and updating the "Supported Platforms" dropdown: 
![image](https://user-images.githubusercontent.com/3580640/145260270-5f339aa1-b1f9-45b2-99b5-b45905045984.png)

In addition, there's currently a bug where the observer fails to be fully created if XR isn't running at app startup. This hasn't been a problem for editor remoting, but we're hitting it for app remoting due to the (likely) longer time between start and XR becoming initialized.

I've opened #10366 to fix both issues.

**Comment by Nox7atra** [comment]
I'm building standalone. And I can't set XR Initialize in startup, because with this settings i can't build holographic remoting app

**Comment by keveleigh** [comment]
> I'm building standalone. And I can't set XR Initialize in startup, because with this settings i can't build holographic remoting app
> 
> Thank you!

Yeah, unfortunately with the second bug, I can't think of a good workaround for now...luckily, we should be able to get the fix in for 2.7.3!

**Comment by keveleigh** [comment]
Going to close this out, as the fix is now in 2.7.3 and is making its way into the main branch via #10375
