### ISSUE TITLE
mixed reality toolkit camera issue

### ISSUE THREAD

**Issue by MiPa12** [microsoft/MixedRealityToolkit-Unity#10321]
## Describe the bug

I need to switch between multiple devices (Desktop and VR) so I need to switch between different cameras. When I start in the desktop mode an Event System, a Mixded Reality Input Module and a GazeProvider is added automatically to my Desktop camera component (because it has the MainCamera tag), but I only need those components when I'm in the VR mode (VR camera). How can I prevent this? Do I need to disable the Mixed Reality Toolkit when I'm not using it?

Thanks.

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.17f1]
- MRTK Version [e.g. v2.7]

## Target platform (please complete the following information)

- WMR immersive
- OpenXR

**Comment by davidkline-ms** [comment]
@MiPa12, thank you for raising this issue. This is something we have thought about off and on since the beginnings of MRTK v2. Unfortunately, resourcing and other critical issues kept us from fully investigating proper camera management and switching between desktop and immersive environments.

Your idea of selectively enabling and disabling the Mixed Reality Toolkit object sounds reasonable. I would definitely recommend doing some careful testing to ensure that there are no unexpected side effects of repeated switching between these views. One expected side effect of enabling MRTK later during runtime would be some momentary frame rate issues, as systems are cold started. 

We have added a research item for this type of camera management to our v3 backlog. Thanks again for bringing it to our attention.
