### ISSUE TITLE
Updating Hololens build via Windows computer

### ISSUE THREAD

**Issue by A-Ivan** [microsoft/MixedRealityToolkit-Unity#10466]
## Describe the problem

Updating Hololens (Hololens 2) currently requires going to, in Hololens, Settings -> Update & Security -> Windows Update. Because Hololens could go into sleep/hibernate mode if not being worn/moved, it can get difficult to update the device as it may not constantly be used during this download/update time.

## Describe the solution you'd like

It would be great if there were to be some way to manage this through Windows. For instance, get the current Hololens build version, check for updates, and update the device (having an option to disable sleep/hibernate), restart, through the Windows Device Portal and/or the [Microsoft Hololens app](https://www.microsoft.com/en-us/p/microsoft-hololens/9nblggh4qwnx).

I'm not sure if a similar solution already exists, but I wasn't able to find any information in the [Hololens Update document](https://docs.microsoft.com/en-us/hololens/hololens-updates) or the [Windows Device Portal document](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/using-the-windows-device-portal).

**Comment by MaxWang-MS** [comment]
Hi @A-Ivan, as mentioned in the windows device portal doc page you linked there are sleep settings that set the length of time to wait before the device goes to sleep when it's plugged in and when it's on battery. I suggest that you modify that setting to keep your device on while installing updates. Otherwise I am not aware of any feature that allows you to update your device from PC besides a full reset with the recovery tool. Please consider submitting a feature request to the appropriate team through [feedback hub on your HoloLens device](https://docs.microsoft.com/hololens/hololens-feedback).
