### ISSUE TITLE
[Request for comments] MRTK "v3" versioning

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#10476]
In developing the next major version of MRTK ("code name v3" 😃 ), we are working on a new product and packaging strategy based heavily around SemVer 2.0. This would be very different from the current "all packages have synchronized version numbers" approach that MRTK v2 currently employs.

Pro:
* It is easy to set expectations on the level of change in MRTK packages (SemVer 2.0)
* Packages without changes will NOT have their version number changed (SemVer 2.0)
* Packages can be more easily serviced independently and as needed
  * Would enable an 'out of band' single package release to address an impactful bug.
* This strategy is employed by Unity in their Package Manager

Con:
* Not synchronizing version numbers leads to potential confusion around which packages work together
* What should the release be labeled?
* Potential confusion regarding required Unity version(s).

# Our proposal

The leading proposal (as of Feb 18, 2022), is the version the MRTK _product_ using the year and month of publication (ex: 2023.07). Each release would be documented with the collection of independently versioned packages. The following are hypothetical releases and a subset of their associated packages.

**MRTK 2023.07**
| Package | Included version | Supported versions |
| --- | --- | --- |
| Core | 3.2.0 | 3.2.* |
| Data binding | 2.0.0 | 2.0.* |
| Input | 3.1.7 | 3.1.7 <= version < 3.2.0 |

**MRTK 2023.10**
| Package | Included version | Supported versions |
| --- | --- | --- |
| Core | 3.2.3 | 3.2.3 <= version < 3.3.0 |
| Data binding | 2.0.0 | 2.0.* |
| Input | 4.0.0 | 4.0.* |

# Questions for the community

* Is this a confusing system?
* Are there any assumptions around required Unity version?
* Are there alternatives that you prefer?

Thanks for reading and sharing your thoughts. We will review all feedback and update this "RFC" as we land the plan of record.

**Comment by eusebiu** [comment]
Strictly versioning wise, it is better to have a single version than many, but in this packages approach there is no other real solution. I do not see any value in having an umbrella version (i.e. MRTK 2023.07) when we already have the packages' versions; the devs will always use the packages versions when reporting an issue (like MRTK.Core 3.1.4 or whatever). Not confusing, but not needed/valuable. What will happen if you fix two issues on the same month? The package will get a version bump but the label will be equivalent with the normal versioning (like 2023.07.1?).
Now, technically speaking the team can solve any impactful bug even in v2 and release a hotfix like 2.7.3.1 for all packages - so, I don't see this as a pro argument. 
Regarding Unity version, most likely you will have some conflicts (in the future) with either Unity or XRI and this will be out of your control (but that's fine as MRTK is for Unity in the end).
Depending on how many packages will be in the end, it might be hard for some developers to mention that Core is at v3.3.1, Input at 3.0.2 to give a full picture of the setup, especially when (s)he does not know where the issue is - MRTK is perceived as a whole.

**Comment by robbbbbb** [comment]
I love the idea of you being able to ship fixes more quickly by isolating packages, that'd be great.

I hate the idea of the version numbering becoming more confusing.

I think it might help if you could clarify how SemVer will be applied wrt API compatibility between the packages. Perhaps this is an accidental by-product of the limited examples you've given, but I can see that in all cases you essentially have:

- Included = X.Y.Z
- Supported = X.Y.* (where * >= Z)

So basically the 'product' ships with a version for each package, and you're free to install any higher patch version of that package? If that's the case, then it feels like this is worth stating explicitly as a rule rather than just assuming it's convention (though also worth calling it out explicitly in each row of those tables, which I assume will be included with all release notes).

Secondly, it seems to not actually be following SemVer 2.0, which states that incompatible API changes should always lead to an increment of the major version number (so, for example Core going from 3.2 to 3.3 should not make it incompatible with anything). I may have misunderstood your intention in these examples though.

I assume that though you haven't stated it here, both Input and Data Binding depend on Core, and not vice-versa. On that basis both of them will need to state that dependency in their package manifests. Presumably the collective set of those constraints is what would constitute your 'product' constraints? Like @eusebiu I think introducing that idea of a 'product' with a version number in to this is probably going to produce more confusion than it clears up. I am imagining github issues, slack posts, tutorial preambles and just general conversations between developers, all becoming harder to understand because 
- sometimes people are saying "MRTK 2022.9" (but not whether they're using the included packages or later ones) 
- sometimes they're saying "MRTK Core 3.2.1" (but haven't specified the other packages) 
- sometimes they're just plain getting it wrong because it's confusing and saying "MRTK 3.2"

It feels to me like currently it shouldn't be all that hard to support fixing bugs in isolation and getting them released, because you're already making the code modular by splitting it across multiple packages. So we could still have a single monolithic version number, which just gets regular patch increments (like now). 

The complexity of course comes when users also want those fixes backported to earlier versions. Unity handles this with LTS releases and a best-effort policy for back-porting as many fixes as is feasible in those effected LTS releases. Admittedly their success in achieving this is limited, and sometimes if an issue is a hard blocker you just have to accept upgrading through a couple of full Unity versions to get the fix you need.

**Comment by robbbbbb** [comment]
> Are there any assumptions around required Unity version?

The biggest issue for us is scenarios where we get caught in a pincer-movement of incompatibilities. A hypothetical example:
- Unity 2023.x breaks something (as they often do) related to rendering or stabilisation
- The latest HoloLens OS version doesn't exhibit the issue, but earlier ones do, we need to support all of them, so we're stuck for a while and can't upgrade Unity until they fix it
- As we're waiting, MRTK updates and latest now only supports Unity > 2023.x

This kind of scenario seems to happen really often, usually I suspect because the internal OS team and the internal Unity team only ever use and test the latest versions of their own and each others' software. It's not really the MRTK team's fault, but by not keeping MRTK working with earlier Unity versions it will make it harder to keep adopting the latest MRTK version.

So very explicit clarity about supported (and fully tested) Unity version horizons to go with each package version would be extremely helpful.

**Comment by eusebiu** [comment]
> 

Yes, I completely agree - right now (on a project which requires some thing MRTK specific - i.e. Oculus visualizer to be present) I am stuck with MRTK 2.6.2 on Unity 2021.1.27 and I cannot upgrade Unity because of some issues in MRTK 2.7.x.

**Comment by keveleigh** [comment]
> I do not see any value in having an umbrella version (like MRTK 2023.07) when we already have the packages' versions; the devs will always use the packages versions when reporting an issue (like MRTK.Core 3.1.4 or whatever).

I think I agree with this. Especially if we move away from

> The 'product' version is more of a point-in-time indicator for when a set of packages was released. The current plan is to release a full set of packages on a predictable cadence and assign these releases a yyyy.mm tag.

Maybe there's less value in these versioned snaps when we start versioning each package independently. We could mark some set of packages as the LKG (last known good) set, but adding _another_ version to that set could make things more complicated than they need to be. And even enforcing some cadence of releases as opposed to releasing whenever we have compelling changes. We can still plan towards specific dates, but maybe it doesn't have to be specifically regular.

**Comment by waynebaby** [comment]
Proposal MRTK 2023.07(as of Feb 18, 2022)  looks like a combination suggestion group to me. So first thing I feel must be the naming.  What about "MRTK Bundle 2023.07"

We do need this official suggestions on combinations of packages who are working best together, 
and yes it was surly confusing when new grouping system became the major versioning system.

Can we keep  this bundle system, but make it less important, maybe implement something (packages installing templates) in MRFT?  In that case old users will not feel a big impact on mindset, and new user can actually receive additional aids in beginning of development.

**Comment by davidkline-ms** [comment]
> @waynebaby
Can we keep this bundle system, but make it less important, maybe implement something (packages installing templates) in MRFT? In that case old users will not feel a big impact on mindset, and new users can actually receive additional aids in the beginning of development.

We have already begun thinking about evolving MRFT along the lines you describe. I envision a feature that will let customers filter for 'last known good' and _maybe_ the ability to "hide MRTK v2".

**Comment by waynebaby** [comment]
> > @waynebaby
> > Can we keep this bundle system, but make it less important, maybe implement something (packages installing templates) in MRFT? In that case old users will not feel a big impact on mindset, and new users can actually receive additional aids in the beginning of development.
> 
> We have already begun thinking about evolving MRFT along the lines you describe. I envision a feature that will let customers filter for 'last known good' and _maybe_ the ability to "hide MRTK v2".

Awesome news!

**Comment by davidkline-ms** [comment]
Thanks for all the feedback!
