### ISSUE TITLE
[Bug] Cannot show Oculus controllers with hand meshes (1)

### ISSUE THREAD

**Issue by pokemon9757** [microsoft/MixedRealityToolkit-Unity#10577]
Previously submitted as https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10562#issue-1217236912
@RogPodge My issue was closed before I received a correct answer. Please help me review it :) Thank you

**Comment by RogPodge** [comment]
Extremely tardy on this response. Sorry, as we've been swamped with MRTK3 work.

I think as of Oculus Integration 39.0 (the new minimum version that MRTK 2.x supports), using local avatar hands (hand meshes) with controller models is no longer an option. Unfortunately, MRTK does not have any built in visualization components to allow for a controller + hand mesh visualization scenario. We advise just using a controller model or using solely hand tracking, rather than mixing the two.

I hope this helped answer your question.

**Comment by pokemon9757** [comment]
Ah so that's why. Thanks for your response! :)
