### ISSUE TITLE
OpenXR Fov in Unity Editor too small for Hololens 2

### ISSUE THREAD

**Issue by dsf5644s6sdf** [microsoft/MixedRealityToolkit-Unity#10579]
## Describe the bug

I have a problem after switching from Unity integrated XR to Open XR. The Unity Editor FOV 29 deg, although the Hololens 2 FOV is 54 deg. How can I increase the FOV of my Main Camera in Unity so it's the same as the actual Hololens 2 FOV through the visor? The FOV slider doesn't work once connected via Holographic Remoting.

## To reproduce

Unity: 2020.3.26f1
MRTK: 2.7.3
MR OpenXR Plugin: 1.2.1

And run Holographic remoting.

## Expected behavior

The Unity Editor FOV should match the actual Hololens 2 FOV. 
The FOV is correct when I switch to the old Unity integrated XR or to Windows Mixed Reality, but then other problems occur. 

## Screenshots

![fov](https://user-images.githubusercontent.com/17873816/167885904-2ae6395e-66c8-427a-9f63-0e2752589501.png)

## Your setup (please complete the following information)

Unity: 2020.3.26f1
MRTK: 2.7.3
MR OpenXR Plugin: 1.2.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by JakobAnarkyLabs** [comment]
I think that this is because the FOV Axis on your Unity camera is set to Vertical. And as far as I know, the vertical field of view of the HoloLens2 is around 29 degrees. The horizontal field of view should be around 43 degrees, and then the field of view measured diagonally should be around 52 degrees.

**Comment by keveleigh** [comment]
I haven't looked into the specifics of the numbers for the HL2 FoV, but I believe the above comment about vertical/horizontal FoV is correct. The camera parameters are set directly from values provided by the runtime, so they should be correct! And it should be obvious otherwise, because the same camera render will appear on-device.
