### ISSUE TITLE
MRTK3 with Oculus Quest 2 via Steam VR can't directly use controllers

### ISSUE THREAD

**Issue by keli95566** [microsoft/MixedRealityToolkit-Unity#10652]
## Describe the bug

When I ran the MRTK 3 branch ( MRTKDevTemplate Unity project) I can't use the Oculus Quest 2 touch controllers. Hand tracking works great, but as soon as I move the controller, it returns to the Steam VR home. This occurs for all the example scenes in the MRTKDevTemplate.  I am running the MRTK through steam VR via the Oculus Air link

## To reproduce

1. Go to MRTK 3 Branch, the MRTKDevTemplate Unity project
2. Without building to standalone Android app, directly run any of the example scenes in Editors. Steam VR will launch and play games through the air link.
3. Move the controllers and it will flash quit the application. There is no way to resume it. 

## Expected behavior

We should be able to use the touch controllers normally via steam VR just as we use it through the standalone Quest 2 . 

## Your setup (please complete the following information)

- Unity Version [2021 LTS]
- MRTK Version [3.0 preview]

## Target platform (please complete the following information)

Steam VR + Oculus Quest 2

**Comment by Zee2** [comment]
Controllers work over Link on the default Oculus runtime with Oculus Link. We haven't tested with SteamVR + Quest yet... could you give the default Oculus runtime + Link a try and make sure that works? I'll bring @keveleigh in on this because this might be an OpenXR quirk.

Can you send a picture of the interaction profiles you have enabled in the OpenXR settings?

**Comment by Zee2** [comment]
Closing as stale, needs more info. @keli95566, please reopen with additional info if the issue is persisting! Thanks so much 👓
