### ISSUE TITLE
Native Unity plugin for Windows UIAutomation API

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#10735]
Investigate and prototype a native plugin for Unity that responds to the Windows UIAutomation API for accessibility.

**Comment by mwcampbell** [comment]
@davidkline-ms I think we should collaborate on this. @DataTriny and I are working on a prototype Unity plugin for making games accessible with our [AccessKit](https://github.com/AccessKit/accesskit) project. AccessKit is only implemented on Windows so far (using UIA), but a Mac implementation is coming sometime this year, and hopefully an implementation for at least one mobile platform as well. AccessKit uses a push-based approach that I think is particularly well-suited for cases like this where minimizing the overhead of a foreign function interface like P/Invoke is important, because the Unity plugin can push one serialized accessibility tree per frame to the native code.
