### ISSUE TITLE
SDK UX components are not in a "usable" state, making it hard for designers to build screens.

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10741]
## Describe the issue
The SDK library contained with the MRTK UX Components package are not in an organised fashion to make it obvious to designers to build screens with, most notably:

* Canvas and 3D components are intermixed and it is not immediately apparent which should be used.
* Prefab dependencies are intermixed with prefabs themselves, making it hard to see / find the prefabs required.
* There seems a LOT more emphasis on the older 3D UX over the newer (recommended?) canvas UX
* The makeup of the UX prefabs is too complex.  There should be individual HANDLER scripts to manage a specific UX component so a developer doesn't have to go rummaging through several layers of components in a prefab just to change a labels text.
* Multiple "copies" of prefabs (not even variants) that simply change a single option. This is far better handled through docs than multiple copies of a prefab (looking at you Toggles)

## Feature area

Ideally, the UX landscape needs looking at from a consumers point of view and stop depending on examples so much in order to show how to actually use the UX components.

3D UX and Canvas UX either should have separate dedicated areas or even be split up in to separate packages.  But there MUST be parity.  If there is a 3D control, there must be a 1-1 UX equivalent.

Have some guest blogs / videos ACTUALLY showing building a screen using ONLY the UX prefabs, DO NOT rely on examples.  Showing a designer (because it's designers not programmers who really build screens) how to construct UX is far better than just showing them an end product and going tada (no designer wants to spend ages going back and to with the examples to figure out what went wrong when building their own UX)

**Comment by Zee2** [comment]
Hi @SimonDarksideJ, we're definitely still working on the organization of the folder structure, among other things.

I'm curious about your comment about parity between non-Canvas and Canvas controls; where are you seeing there to be a discrepancy? We know that the theming system is not yet ported to Canvas (for a variety of reasons).

In addition, both types of UX controls are fully 3D, so there's not "3D" vs "Canvas" controls; they're just a different type of rendering the same sort of controls. 

There are *very few* Canvas prefabs, intentionally, because the entire purpose of the Canvas-based paradigm is that the Canvas controls are totally customizable/resizable/reflowable without requiring the "prefab hell" that we have with the non-canvas components. The fact that there's only a single button prefab for Canvas is entirely intentional! In addition, the fact that lists are all dynamically constructed + laid out means that we don't need (or really want) bespoke prefabs for lists of buttons/items/etc. 

We've had a lot of success with our designers enjoying these new systems in-house, but we can definitely work on some design showcases demonstrating the design + layout process from scratch for newcomers.

**Comment by Zee2** [comment]
Going to be writing some blog posts + better documentation coming up. The above PRs should make the current experience significantly better (especially as I work on expanding #10950 with even more menu entries).
