### ISSUE TITLE
Feature Request: Add OpenXR bindings to the default MRTK Input Actions.inputactions asset

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10752]
## Describe the problem

Add OpenXR generic bindings to the default MRTK Input asset

## Describe the solution you'd like

Zappys playground includes additional OpenXR bindings that should be included with the default MRTK Input Actions Asset.  This is currently creating friction for anyone trying to test their projects on devices other than the HoloLens.

Granted, the primary focus of the MRTK is on Microsoft Headsets, however, since the move to OpenXR for the HoloLens, there is no reason to restrict or add additional friction for developers wanting to also support other devices.

The configuration already exists and works in Zappys Playground, so this should simply be ported to the default MRTK configuration

## Describe alternatives you've considered

Forcing developers to try and find the correct bindings for default OpenXR configuration adds unnecessary friction.

**Comment by Zee2** [comment]
For posterity's sake, could you list the particular actions here you'd like to be included in our actions asset by default? Very helpful for work tracking... :)

**Comment by SimonDarksideJ** [comment]
For the most part, the improvements in the Zappys playground configuration (which is easily spottable by doing a quick comparison between the MRTK.Input config and the config that Zappys uses), highlights there are several additional "Fallback composites" employed in that demonstration, such as, the "Position" Property which employs the following composite configuration

```
                    "name": "Vector 3 Fallback",
                    "id": "14aeff85-d719-43ff-a124-b1cd7ca8686d",
                    "path": "Vector3Fallback",
                    "interactions": "",
                    "processors": "",
                    "groups": "",
                    "action": "Position",
                    "isComposite": true,
                    "isPartOfComposite": false
                },
                {
                    "name": "first",
                    "id": "ae101942-9eaa-4c53-a388-cafc3fd89bdf",
                    "path": "<XRController>{LeftHand}/pointerPosition",
                    "interactions": "",
                    "processors": "",
                    "groups": "Generic XR Controller",
                    "action": "Position",
                    "isComposite": false,
                    "isPartOfComposite": true
                },
                {
                    "name": "second",
                    "id": "6580b669-0651-401c-9779-85ef22689130",
                    "path": "<XRController>{LeftHand}/devicePosition",
                    "interactions": "",
                    "processors": "",
                    "groups": "Generic XR Controller",
                    "action": "Position",
                    "isComposite": false,
                    "isPartOfComposite": true
                },
```

**Comment by keveleigh** [comment]
> there are several additional "Fallback composites" employed in that demonstration, such as, the "Position" Property which employs the following composite configuration

Ooh, it looks like that project cloned our profile to add some things, at the expense of not taking our latest changes. The updates to our input actions profile in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10749 should accomplish the same thing they added (which was mainly adding `<OculusHMD>/centerEyePosition` as a binding for eye gaze, but not as a fallback composite so it might have unexpected behavior on some devices 😬)

We had to remove the fallback composite you pasted above due to a change in the Unity input system. https://github.com/Unity-Technologies/InputSystem/pull/1405

Specifically, from their changelog:
> If an binding of higher complexity "consumes" a given input, all bindings waiting to consume the same input will automatically get skipped. So, if a "Shift+B" binding composite consumes a "B" key press, a binding to "B" that is waiting in line will get skipped and not see the key press.

This was leading to the fallback composites "consuming" device position even if they only used pointer position, which meant our other action binding to _just_ device position was always being skipped. We've been in talks with Unity on how best to approach this, but it's still in progress.

I'll work on getting the two input actions profiles reconciled, but I'm not currently aware of any OpenXR interaction profile that provides a device pose but not a pointer pose. Am I missing a scenario?

**Comment by SimonDarksideJ** [comment]
Other than ensuring that both the basic OpenXR as well as the Microsoft XR bindings are managed in a single configuration and ensuring such demos are not creating additional configurations for no reason (as it confuses developers).
Then that would be awesome @keveleigh :D

**Comment by Zee2** [comment]
Bindings in the Template should be updated to parity across devices. Will need to revisit Zappy at some point to update.
