### ISSUE TITLE
[MRTK3] Constraint Manager - Rotation Constraint is missing

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#10762]
## Describe the bug

In the Constraint Manager options, many constraint options that were available in MRTK2 is missing in MRTK3.
For example, Rotation Constraint is missing which is needed to make the object stay vertical while moving/manipulating.

![2022-07-18 15_29_33](https://user-images.githubusercontent.com/13754172/179681436-b0849dcf-90a8-4f56-81d5-3b822d63facc.png)

**Comment by Zee2** [comment]
The reason most of the constraints are still missing is because we want to rewrite the constraints/solvers system into a single unified system, a la #10759 . @RogPodge do you think we should add/port the rest of the legacy constraints even though we really don't like the existing constraints/solvers situation?

**Comment by cre8ivepark** [comment]
> The reason most of the constraints are still missing is because we want to rewrite the constraints/solvers system into a single unified system, a la #10759 . @RogPodge do you think we should add/port the rest of the legacy constraints even though we really don't like the existing constraints/solvers situation?

I see! I thought it was an editor UI bug not showing the full list of constraints.

**Comment by holomatt** [comment]
This issue is currently blocking our project from proceeding to use ObjectManipulator for anchor manipulation - we'd like to use RotationAxisConstraint, but it'd unclear how to add it back in. Similarly, MoveAxisConstraint is fairly essential. I have use cases for pretty much all of the constraints including MaintainApparentSize, but those two are the P0's for us currently.

**Comment by RogPodge** [comment]
Closed with #11085
