### ISSUE TITLE
Release notes in the GitHub page for the MRTK3 Previews

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10835]
## Describe the issue
A clear and concise what the issue

Can we please add a release notes list for the MRTK3 previews on the GitHub readme page, to inform developers of the changes between releases.

Currently, the only release notes on the GitHub site (at least) are for MRTK2.

**Comment by keveleigh** [comment]
Yep! We're trying out a Releases page under the Discussions tab for release notes: https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/categories/releases

Since MRTK3 is a collection of packages that may or may not actually align in version after we hit 3.0.0, we're trying to find a way to mark releases without putting a tag on the entire repo, which could lead to confusion about the state of the repo at each tag.

**Comment by SimonDarksideJ** [comment]
Yeah, that eventually got pointed out to me @keveleigh , Just needs a reference / link on the front page so people can find it.

But pretty please, LIST known issues, do not make people to have go and search and possibly find problems :D

**Comment by Zee2** [comment]
@SimonDarksideJ, we've had discussions internally about the best way to list known issues. It would just end up essentially being a copy-pasted list of everything on the GitHub issues board... do you think that would be useful to folks? (Especially if/when people discover more issues!)

**Comment by SimonDarksideJ** [comment]
A list of titles as links to the issues (just copy the hyperlink from the issue and Github autocorrects it), so people can investigate if they want to.

But definitely a list so people can see the known issues at time of release when upgrading.

Not a dynamic list, just follow change note rules and list what was known when the release was cut

**Comment by Zee2** [comment]
Sounds good. We'll keep it in mind for future releases!

Also, FYI, we'll be keeping changelogs on both the Docs site and on the individual release announcements; they'll simply link to each other.
