### ISSUE TITLE
Canvas Example Scene no longer allows to draw using RayInteractor

### ISSUE THREAD

**Issue by Clandguth** [microsoft/MixedRealityToolkit-Unity#10886]
## Describe the bug

Cannot use air tap on the Canvas Example

## To reproduce

1. Air tap and attempt to move around on the canvas example
2. Observe no drawing on the Canvas

## Expected behavior

User can draw using AirTap on the canvas example

## Video

https://user-images.githubusercontent.com/110259320/185198329-ddb9c751-8701-4df0-b5d5-d0aa02307fa6.mp4

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- Commit Version 064f7cf9dd7eaa6addf29b3ed2706ed683fe7fe2

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
This was intentionally removed by @RogPodge in #10751 :(

**Comment by Clandguth** [comment]
@Zee2 Especially with how difficult it is to interact with the pen, or draw with the hand-cursor I think this should be re-evaluated

**Comment by keveleigh** [comment]
Agreed on the re-evaluation proposal. It feels unfortunate to restrict this to near interactions only 😢 from my recollection, the airtap drawing _did_ work, it was just a visual bug that the far ray snapped to the initial point. We should use this issue to track fixing that

**Comment by Clandguth** [comment]
Just another note:
On Quest 2, if the user is using controllers, this especially inhibits the ability to use the canvas effectively.

I would also hope that the user could interact with the pen using AirTap, but thats another feature that would need to be added in.

**Comment by RogPodge** [comment]
I strongly feel that we should not have the far air tap interactions in the example scene in its current state, because of how the far ray snapping very clearly looks like a bug visually. I don't want to re-enable interactions which are clearly unpolished or added as an afterthought.

For what it's worth, the whiteboard script is an examples-only component at the moment, so I don't think it's a feature we're shipping with our core set of MRTK UX controls.

As for interacting with the pen with AirTap, I think that is easily implementable, but it definitely makes the pen experience super wonky, and I think that though it'd help improve the immersion/authenticity of the scene, it goes against what we want the pen to represent/the way we want it to be used. Maybe this indicates we should have some sort of "hand snapping" solver or mechanism to bring the pen near the user's grip or something?
