### ISSUE TITLE
RoundedRectMask2D causes graphical occlusion issues when a Canvas element is moved

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#10957]
## Describe the bug

While the RoundedRectMask2D  component effectively masks content in containers, such as a ScrollView, this only works when the UI is presented face on to the user.

If the UI Content is moved beyond 180 degrees of the user view, say placing a UI Element on a wall or in a different place in the scene, this causes occlusion issues for the content being masked.

## To reproduce

1. Create a new MRTK3 project
2. Create a canvas in the scene, with a MRTK canvas scroll rect using the RoundedRectMask2D to mask the viewport/content
3. Add some content so it is visible
4. Add a Object Manipulator to the ScrollRect to allow it to be moved in the scene (same as what used to be possible with the 3D UI of MRTK2)
5. Run either via Holo Remoting or on device, grab the ScrollRect and move it around
6. See the occlusion of the content being masked changing based on the direction the scrollrect is moved to.

## Expected behavior

Masked content should only be masked in relation to the users view and remain constant, not be affected by its place in the scene

## Your setup (please complete the following information)

- Unity Version 2020.3.37f1
- MRTK Version V3 Pre 10

## Target platform (please complete the following information)

- HoloLens 2
- OpenVR

**Comment by Zee2** [comment]
Interesting. I haven't been able to repro this at all. The CanvasExample sample scene already has this setup with the main UI right in front of the user, and it looks and behaves just fine.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/5544935/187739586-baf7d53e-8bb9-4905-ae79-0efe46ffed79.png">

The area highlighted in orange is a ScrollRect with the rounded rect mask, and you can pick up this UI and move it around just fine. 

I believe the issue may be that you're trying to put the mask on the wrong object? Or something of the sort? Otherwise, I don't know how that issue would be happening. Can you check our sample scene setup and make sure your scroll rect is similarly configured?

**Comment by Zee2** [comment]
I'm wondering if the issue is that you're trying to use objectmanipulator on an object *inside* the canvas. We recommend only ever manipulating the top-level canvas object (or, for even better performance, have a separate non-canvas "root" object above the Canvas that you use as your manipulation transform root). @SimonDarksideJ let me know what your setup looks like, and how it's different from our sample scene.

**Comment by SimonDarksideJ** [comment]
> I'm wondering if the issue is that you're trying to use objectmanipulator on an object _inside_ the canvas. 

Well, that is what the issue was relating to.

However, the alternative is not a real workable solution as it would require separate canvases for ANY UI object you would want to move in a scene.  Being an AR solution, almost ANY UI element is likely to be movable / interactable, as it was in MRTK2 days, else what is the reason to use a Canvas at all?  UI in AR is almost never static.

And if this is the case, then ALL of the samples need updating to reflect that fact, else they are not real world examples, IN a HoloLens
