### ISSUE TITLE
Scrollbar of dropdown not working on built application

### ISSUE THREAD

**Issue by BalintOXIT** [microsoft/MixedRealityToolkit-Unity#10963]
## Describe the bug

Used the basic TMP_Dropdown from MRTK Examples and on built version (in hololens2) the scrollbar events not working.
The dropdown open in a right place, but can't click to the scrollbar handler and can't scroll it.
On editor it works well

## To reproduce

1. Add extra items to tmp_dropdown (in hand interaction examples scene) [to Dropdown gameobject's TMP_Dropdown items] 
2. Build the application on hololens2
3. Open and interaction examples and try to scroll down the TMP_Dropdown
4. See the scrollbar at dropdown not working, only choosing items

## Expected behavior

Can scroll on objects of the dropdown

## Screenshots

-

## Your setup (please complete the following information)

- Unity Version [e.g. 2020.3.35f1]
- MRTK Version [e.g. v2.8.2]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Are you using OpenXR? If so, there's a bit of a quirk with airtap and the old input system, leading to a "submit" being sent on airtap instead of the previous method of being able to select the dropdown and scroll it.

There's a potential workaround at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10304#issuecomment-1040503841, if you're able to give it a try! Thanks!

**Comment by BalintOXIT** [comment]
That was the problem, sorry for the late reply.
