### ISSUE TITLE
[HighPri, Regression] Canvas materials are incorrect

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11008]
## Describe the bug

It looks like when we moved to Linear, the Canvas-based UI materials were not updated and all of their colors now appear incorrect.

<img width="382" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/5544935/190038022-8fd8d614-0d6e-495f-8e11-ff02accc1c8e.png">

(Left, non-Canvas. Right, Canvas)

Before the switch to Linear, the two designs were fully consistent and identical. It seems like when we moved to Linear, somehow the Canvas materials were not correctly updated alongside the non-Canvas materials.

<img width="257" alt="image" src="https://user-images.githubusercontent.com/5544935/190038352-94ce9267-fffc-4fe5-99bd-2a5bf1969afa.png">

(grid is Canvas, pin button is non-Canvas)

## To reproduce

Look at any Canvas UX control.

## Expected behavior

Canvas and non-Canvas controls should be indistinguishable visually and both follow correct MRDL color guidance.

## Screenshots

<img width="382" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/5544935/190038022-8fd8d614-0d6e-495f-8e11-ff02accc1c8e.png">

<img width="257" alt="image" src="https://user-images.githubusercontent.com/5544935/190038352-94ce9267-fffc-4fe5-99bd-2a5bf1969afa.png">

## Context

The switch to Linear happened here: #10871.

**Comment by brdystudios** [comment]
@Zee2  Found the reason. Canvas materials in our StandardAssets package were properly updated to linear. 

I used the wrong one CanvasBackplate.mat from the MRGT package for the NearMenu and HandMenu prefab examples. So only NearMenu and HandMenu examples need to be updated, no effect on button control since our tearsheets are using StandardAssets. 

I'll open the PR for these updates.

Thanks!

<img width="611" alt="2022-09-13 19_01_56-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3" src="https://user-images.githubusercontent.com/79679221/190042264-5165adfe-b64d-4f7a-b849-f7a3b280686f.png">

**Comment by cre8ivepark** [comment]
@Zee2 Found the reason. Canvas materials in our StandardAssets package were properly updated to linear.

I used the wrong one CanvasBackplate.mat from the MRGT package for the NearMenu and HandMenu prefab examples. So only NearMenu and HandMenu examples need to be updated, no effect on button control since our tearsheets are using StandardAssets.

I'll open the PR for these updates.

Thanks!

<img width="611" alt="2022-09-13 19_01_56-MRTKDevTemplate - NearMenuExamples - Universal Windows Platform - Unity 2020 3 3" src="https://user-images.githubusercontent.com/13754172/190042542-f6e8f70e-917b-430e-ab80-6bf94d071ca3.png">

**Comment by cre8ivepark** [comment]
Opened PR #11009
