### ISSUE TITLE
Installing Microsoft Spatializer 2.0.37 results in a checksum error

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#11031]
Installing Microsoft Spatializer 2.0.37 using the MR Feature tool results in a checksum error:
"An error occurred while resolving packages:
  Project has invalid dependencies:
    com.microsoft.spatialaudio.spatializer.unity: TAR_ENTRY_INVALID: checksum failure"

This does not happen when installing 1.x versions

## Steps to reproduce the behavior:

1. Install
2. Observe error

## Expected behavior

No error 

## Screenshots

![image](https://user-images.githubusercontent.com/4129183/190894938-d00ea38a-99f8-47bf-b048-d959a8e75072.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.39f1
- MRTK Version 3.0.0-pre1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MaxWang-MS** [comment]
It seems that this is due to a networking issue. Could you share the log with us in case it has some useful information? The easiest way to access the log is to go to Settings > Diagnostics.
![image](https://user-images.githubusercontent.com/68253937/181645056-0e77b791-a667-4d69-b533-329b91d53c70.png)

You could also try enabling "Overwrite existing package files" under Settings > Download and then try again with a new project. Also please let us know what version of MRFT you are using.

**Comment by Zee2** [comment]
@davidkline-ms updates on this one?

**Comment by LocalJoost** [comment]
The odd thing is - I try to repro it again today, to get the log file that was asked for - and I don't see the problem anymore. Has something been fixed on the other end?

**Comment by MaxWang-MS** [comment]
This is most likely due to some networking issue that resolved itself when you retried. Closing the issue for now.
