### ISSUE TITLE
Domain reloads being forced due to immutable assets being altered in packages

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#11057]
## Describe the bug

We are hitting a major annoyance (unclear whether this has a direct runtime impact as yet) where domain reloads are being forced because all the animated parts of the MRTK ux are changing the materials themselves held in side the MRTK packages.

Seeing a lot of errors similar to

```
The package cache was invalidated and rebuilt because the following immutable asset(s) were unexpectedly altered:
  Packages/com.microsoft.mrtk.standardassets/Materials/CompressedButtonMaterial/CanvasFrontplate.mat
```

This appears to affect all the materials used in the UX system at different points.

Immutable assets in the MRTK packages should not be getting altered, because the packages are immutable.  Changes only apply to the package cache temporarily until Unity checks for changes (which is indeterminate, Unity does it when it feels like it, such as a scene change), when Unity finds the package altered it causes a domain reload of the package freezing the editor (and possibly causing freezes in runtime? Unclear.

This would have not been in an issue in the way MRTK 2 was managed as all assets were mutable in the assets folder.

## To reproduce

1. Open a scene using MRTK UX
2. Navigate and use the screen
3. Transition to another scene also using UX
4. See error (maybe)

## Expected behavior

No domain reloads from using the MRTK and no alteration of assst in immutable packages.

## Your setup (please complete the following information)

- Unity Version 2020.3.39f1
- MRTK Version 3 Preview 11

## Target platform (please complete the following information)

- Any

**Comment by Zee2** [comment]
@SimonDarksideJ thanks for catching this. This is surprising, internally we use this workflow widely with immutable packages and don't have any issues, so there must be something MRTK specific here we haven't configured correctly.

@Cameron-Micka for reference, there seems to be an issue with CanvasMaterialAnimators trying to alter the material assets themselves in immutable packages... pretty strange. I'll go check the settings on the CMAs to make sure they're set correctly.

**Comment by Cameron-Micka** [comment]
@Zee2 good to know! This is odd since a CMA will either instance a material or mutate and restore it. Maybe the restore process is resulting in different yaml being saved to disk? Here is [the logic](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/blob/main/com.microsoft.mrtk.graphicstools.unity/Runtime/Utilities/MaterialRestorer.cs) to capture and restore the material state.

**Comment by Zee2** [comment]
Testing right now @Cameron-Micka. If this is a CMA-wide issue, I'd be very surprised that $internal has not hit this (or at least hasn't complained)

**Comment by Cameron-Micka** [comment]
@Zee2 yeah, that is odd since most internal projects are using immutable packages. Plus, CMAs haven't changed in a long time. One idea is maybe we don't call `AssetDatabase.SaveAssets();` if we determine the asset is in an immutable package? Or, maybe we don't need to call `AssetDatabase.SaveAssets();` at all and leave it up to the user to do a File > Save Project? Let me know if you need extra eyes for investigations.

@SimonDarksideJ that's great to know! Any screenshots would be appreciated, it might help us repo.

**Comment by keveleigh** [comment]
@Cameron-Micka In that snapshot code, we're making a copy of the material anyway. Can we not just assign that copy to the runtime object and make changes directly on the copy instead of treating it as a snapshot, therefore leaving the original on-disk material fully untouched?

It's all editor-only logic, and we're making a copy anyway, so it seems a bit simpler to not have to manage a cache and handle restoring anything.

**Comment by Cameron-Micka** [comment]
> @Cameron-Micka In that snapshot code, we're making a copy of the material anyway. Can we not just assign that copy to the runtime object and make changes directly on the copy instead of treating it as a snapshot, therefore leaving the original on-disk material fully untouched?

I do like that idea, but I worry it would break existing users since someone might assume a shared material is being driven by a single animator. For example, if you have a single CMA animating a single Image component's material and 10 other Image components without CMAs using that same material, then the other 10 Images will no longer animate if the one with the CMA animates the copied material.

I did some local testing and was unable to reproduce this. But! Thinking though it I think the best things to do is to remove the save to disk and leave it up to Unity and/or the user to do this:
![image](https://user-images.githubusercontent.com/13305729/193142688-ccd24c8d-3d7a-4c69-afed-3da7d3f2d8b1.png)

This way the material gets restored in memory, but not on disk. I think it's a fringe case that that material was saved to disk during the CMA's animation (which is what I was trying to protect against here). What do other folks think? 

Else I could do [this check](https://forum.unity.com/threads/check-if-asset-inside-package-is-readonly.900902/) before the save?

**Comment by SimonDarksideJ** [comment]
As requested, while we were testing on Friday, I managed to capture this shot of a button who's materials has been altered.  Happens when a button has been pushed and the users hand has moved away. Touching other buttons does not clean the effect and other buttons receive the same effect.
"Sometimes" the screen will refresh and the effect is reset, or of the user moves close to the button it "may" clear it, but not always.  
Obviously this should NOT happen.

![Snag_3fce79](https://user-images.githubusercontent.com/1793042/193562700-02641986-2676-462b-bf43-b3d52faf084a.png)
Hope that helps @Cameron-Micka / @Zee2

**Comment by Zee2** [comment]
@SimonDarksideJ , testing here now on my "dogfood" project that consumes packages like an external customer. Will report back!

**Comment by Zee2** [comment]
https://user-images.githubusercontent.com/5544935/193703469-90ee8040-22ea-4c93-bfa9-62bb954eea3f.mp4

@SimonDarksideJ here's me trying to repro. Don't see anything unusual happening when exiting play mode; tested having the material actively being animated while exiting Play, still nothing. Am I not doing this right? :D 

(and nothing in the logs, ofc)

**Comment by Zee2** [comment]
Hey @SimonDarksideJ. Unfortunately, none of us have been able to repro this... this is something we really want to keep an eye out for, so if you have any tips on how to reproduce this, please reopen this. This is an important workflow concern for us and we'd love to figure out what's going wrong here.
