### ISSUE TITLE
ARSessionOrigin disagrees that TPD(InputSystem) is a valid pose driver

### ISSUE THREAD

**Issue by dudziakl** [microsoft/MixedRealityToolkit-Unity#11153]
## Describe the bug

TrackedPoseDriver script is missing on Main Camera object on vanilla MRTK XR Rig prefab and when running Play mode there is a warning in the console log:
> Camera "Main Camera" does not use a AR Pose Driver or a Tracked Pose Driver, so its transform will not be updated by an XR device.  In order for this to be updated, please add either an AR Pose Driver or a Tracked Pose Driver.
> UnityEngine.XR.ARFoundation.ARSessionOrigin:Awake () (at Library/PackageCache/com.unity.xr.arfoundation@4.2.6/Runtime/AR/ARSessionOrigin.cs:209)

## Workaround:
1. Open MRTK XR Rig prefab then Camera Offset then select Main Camera in the Hierarchy view
2. Click on Add Component and manually add Tracked Pose Driver script 

## To reproduce

1. Create a new Unity project
3. Import MRTK3
4. Create an empty scene and remove all content
5. Add MRTK XR Rig prefab and MRTKInputSimulator to the scene
6. Hit the Play button and see the warning (Camera "Main Camera" does not use a AR Pose Driver or a Tracked Pose Driver...)  in Console log

## Expected behavior

Warning should not appear in Play mode

## Your setup (please complete the following information)

- Unity Version 2021.3.12f1 & 2020.3.40f1
- MRTK Version 3.0.0-pre.12

## Target platform (please complete the following information)

- HoloLens 2 (OpenXR)
- PC/Desktop (OpenXR)

**Comment by keveleigh** [comment]
This is something I'm actively tracking with Unity and the ARFoundation team.
Currently there are three "pose drivers" that are usable on the camera:

![image](https://user-images.githubusercontent.com/3580640/198685986-477c245e-3f87-4a5b-9c25-253b936d702a.png)

ARFoundation 4.x only checks for the existence of the first two, while all three are valid for camera pose driving.

ARFoundation 5.x [deprecated AR Pose Driver](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@5.1/api/UnityEngine.XR.ARFoundation.ARPoseDriver.html) and recommends the Input System's TrackedPoseDriver:

![image](https://user-images.githubusercontent.com/3580640/198686214-a3f5f3c4-0710-4872-b9a1-04ffbcede882.png)

Unfortunately, because Unity 2020 is currently our min version for MRTK3, we can't adopt ARFoundation 5.x (it declares itself to only be valid for Unity 2021+)

![image](https://user-images.githubusercontent.com/3580640/198686431-2d869b70-ffc5-4472-875c-fa776fcef20a.png)

Ideally, ARFoundation 4.x will be updated to support any of the three. I'll keep this thread updated as that conversation continues.

**Comment by Zee2** [comment]
Renaming to track the ongoing external bug.

**Comment by Zee2** [comment]
Will be resolved by #11345 and bump to ARF 5.0 and 2021.
