### ISSUE TITLE
Critical build issue with the MRTK "Standard" Shader

### ISSUE THREAD

**Issue by SimonDarksideJ** [microsoft/MixedRealityToolkit-Unity#11151]
## Describe the bug

We hit an issue through our automation whereby the MRTK Standard Shader is being stripped during our automated builds (for some reason it is not stripped when doing a manual build, automation seems more aggressive in stripping)

Obviously, this creates severe issues when trying to load remote models and applying the shader through code at runtime.

However, the bigger issue is that we tried to address this by adding the MRTK Standard shader to Unity's "Always included shader" list in the Graphical settings, but this causes any Unity build (even local) to fail due to the sheer number of variations that Unity tries to build.

## To reproduce

1. Create a new Unity project and install the MRTK
2. (optional) configure the Project for MRTK, including OpenXR
3. Add the MRTK Standard shader to the "Always Included Shaders" list
4. Try and do a build for UWP

## Expected behavior

The build should work and produce a build

## Screenshots

![image](https://user-images.githubusercontent.com/1793042/198286042-33300359-8232-46af-a1e5-dbed7c2b4e1f.png)

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.11f1]
- MRTK Version [e.g. v3.0.Preview10]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by Zee2** [comment]
Assigning @Cameron-Micka here for MRGT build issue.

@SimonDarksideJ could you share what sort of way you're doing your automated build? Script, etc? @keveleigh wasn't there something we ran into earlier with stripping in our CI?

**Comment by Cameron-Micka** [comment]
Hey @SimonDarksideJ, thank you for filing this issue. Unity will strip the shader if it finds it is not referenced by any scenes you have specified in the build settings. 

You could add the shader to the always include settings, but because it is an uber shader with millions of variants you will have to use a [shader variant collection](https://docs.unity3d.com/Manual/shader-variant-collections.html) to specify which variants you need. 

That being said, for your use case: 

> when trying to load remote models and applying the shader through code at runtime

I'd recommend making a "default" material for the models you plan on loading and then instantiating new instances of that material in code rather than making a new material completely programmatically. You can reference this material in a scene you build or in the streaming assets folder.

The default material should have the settings you need to enable specified at build time. If you need to enable/disable shader keywords dynamically at runtime, then you will need to fall back to your previous method and use a shader variant collection.

**Comment by SimonDarksideJ** [comment]
I would say so @AMollis , considering it is currently impossible to build an MRTK project through automation where the content is not already in the project (downloaded) and using the MRTK Standard shader.  EXACT same solution works in a standalone build.

Ultimately, the general feeling is that the MRTK standard shader is too big and should really be broken up into smaller chunks as it causes way too many issues once you have the need for variants, for instance, turning mult-compile for even one or two properties results in MILLIONS of variants which Unity cannot handle.

**Comment by Cameron-Micka** [comment]
Hi @SimonDarksideJ! I agree with you that the _MRTK/Standard_ shader grew quite a bit (especially in the MRTK2) days. In MRTK3 we've done some work to move many, not all, of the UI materials to using [bespoke shaders](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/architecture/mrdl-mrgt#back-plate). We've also done some work to ensure we don't abuse the `multi_compile` and have [slimmed down the list](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/blob/main/com.microsoft.mrtk.graphicstools.unity/Runtime/Shaders/GraphicsToolsStandard.shader#L182) a bit.

I'm curious for this issue if you had a chance to try the above suggestion? https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11151#issuecomment-1293941312 This has worked for other customers when loading content dynamically. If it doesn't work for you, I'd love to hear that as well. 

As for the stripping during automated builds, we've not seen that locally in our automated builds. So that might take some more info or investigation from @AMollis and team. Dropping the _MRTK/Standard_ (or _Graphics Tools/Standard_) into the "Always included shader" list may sound like an easy fix, but that's not generally recommended by Unity for "uber" shaders. For example, if you drop the _Universal Render Pipeline/Lit_ shader into that list you will spend around 20 minutes per build generating tens of thousands of shader variants your project doesn't need: 

![image](https://user-images.githubusercontent.com/13305729/223184103-1a0d42f0-fa3f-46d0-9c20-2ce1dbb9d2c7.png)

It's recommended to curate a material you need for your dynamic content or build a shader variant collection.

**Comment by SimonDarksideJ** [comment]
Actually, dropping the MRTK shader into the "Always Included List" is the worst thing you can do, we found in testing that this even prevented local builds because there were simply TOO MANY varients to compile, it easily passes the max 2 million mark.

**Comment by SimonDarksideJ** [comment]
> In MRTK3 we've done some work to move many, not all, of the UI materials to using [bespoke shaders](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/architecture/mrdl-mrgt#back-plate). We've also done some work to ensure we don't abuse the `multi_compile` and have [slimmed down the list](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/blob/main/com.microsoft.mrtk.graphicstools.unity/Runtime/Shaders/GraphicsToolsStandard.shader#L182) a bit.

Yes, however, we found that in some cases removing the multi-compile from certain keywords degraded the quality too much and caused artefacts, we had to re-add two to bring the quality level back up.

**Comment by Railboy** [comment]
@SimonDarksideJ you may want to re-read @Cameron-Micka's comments. He doesn't appear to be saying what you seem to think he's saying.

**Comment by AMollis** [comment]
@SimonDarksideJ , thank you for reporting the issue with the MRTK Standard Shader. To help us troubleshoot it, could you please provide a simple project that shows how it gets stripped during an automated build? We appreciate your cooperation and we will look into it as soon as possible.
