### ISSUE TITLE
Question: How can you change the color of UI objects with the CanvasBackplate.mat attached (NearMenue, Buttons etc.)

### ISSUE THREAD

**Issue by HaiKonofanDesu** [microsoft/MixedRealityToolkit-Unity#11244]
## Describe the issue
I want to experiment a bit with different colors but also want to use given Prefabs like the NearMenue Prefab. Sadly the material including the colors are locked and can't be edited. Unpacking the prefab change nothing. The CanvasBackplate.mat is in the Packages and my new Material is under Assets/Materials.

i use MRTK3 pre 12

EDIT: Found in the docs that it's not suggested to change colors?

## Feature area
Searching for material gives lot of cool features but I can't try them out because I can't access the material.

## Existing doc link
https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/rendering/mrtk-standard-shader?view=mrtkunity-2022-05

## Additional context
![image](https://user-images.githubusercontent.com/101000327/203726115-dd847331-76ac-4f15-a22e-9580018999d4.png)

**Comment by HaiKonofanDesu** [comment]
PS: 
https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/mixed-reality-design-language.md

Something with the formatting here seems wrong

**Comment by Zee2** [comment]
Hi @HaiKonofanDesu, the formatting in that link seems messed up because it uses MSDocs-specific formatting. You can see the official docs (formatted) here: https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-uxcomponents/packages/uxcomponents/mixed-reality-design-language

As for changing colors: we'll recommend using the UI theming system that should be ready by GA. There's an early version of the theming system that's currently set up for the non-canvas UI prefabs, but we're still working on the theming story and it's subject to change by the time GA comes out. I'd hold off on experimenting with colors/style until then, if possible.
