### ISSUE TITLE
Ensure that the color space is set to Gamma for Quest 2 development

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#11258]
This issue tracks ensuring that our docs have a mention that the colorspace should be set to Gamma for development on Quest2.

Issue discovered here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11237

**Comment by MaxWang-MS** [comment]
Have we confirmed this is actually an issue for MRTK3? The shaders etc. in MRTK3 are different from MRTK2.

**Comment by Zee2** [comment]
Should this be a validator rule?

**Comment by Clandguth** [comment]
In my MRTK3 testing on Quest 2 , it was properly set to gamma and I did not see any issues or errors with the setup

**Comment by akash14darshan** [comment]
As for issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11237
For me, the fix for me I could not afford gamma color space. It happened if I was using same material asset on multiple windows.
The fix was to use different material for each window.

Is it really a good idea to enforce gamma for all unity projects using mrtk?

**Comment by MaxWang-MS** [comment]
@akash14darshan We don't have official support for linear color space in MRTK2. If linear color space is a requirement for your project, we recommend using MRTK3 (currently in preview).
