### ISSUE TITLE
MRTK3 input package misses dependency on glTFast

### ISSUE THREAD

**Issue by NorbertNemec** [microsoft/MixedRealityToolkit-Unity#11294]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/209

___

## Describe the bug

The package com.microsoft.mrtk.input contains .glb files that require the glTFast package to be imported in Unity. The MRTKDevTemplate depends on "com.atteneder.gltfast": "https://github.com/atteneder/glTFast.git#v4.8.3"

Any external project that depends on com.microsoft.mrtk.input shows errors on attempting to import the Left/RightControllerModel.prefab files.

## To reproduce

1. Create empty project
2. Import  com.microsoft.mrtk.input
3. See error messages
4. add git dependency on https://github.com/atteneder/glTFast.git#v4.8.3
5. See error disappear

## Expected behavior

com.microsoft.mrtk.input should bring all its required dependencies (not sure whether a git-dependency is possible and acceptable at that point?)

## Screenshots

![image](https://user-images.githubusercontent.com/45229256/207293519-fd041b6d-591a-47a1-a72b-62af0855655f.png)

## Your setup (please complete the following information)

- Unity 2021.3.5f1
- MRTK v3.0.0-pre.12.18

**Comment by keveleigh** [comment]
Ah yeah, we've been a little torn on how to approach this. I don't believe we have an explicit dependency on glTFast specifically, just a dependency on _some_ glTF importer. I've been hesitant to enforce consumers of MRTK3 to import glTFast, as we had several issues filed about the MRTK2 importer and it conflicting with various other importers of choice (like TriLib's in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9653).

> (not sure whether a git-dependency is possible and acceptable at that point?)

Unfortunately, this is another sticking point. Since glTFast is not distributed in either Unity's feed or the public MRTK feed, MRFT isn't able to resolve the dependency and it'll be a manual step for every developer who imports the input package. I've had some ideas around upgrading MRFT to support git dependencies, but I haven't had time to look into it yet.

**Comment by NorbertNemec** [comment]
Perhaps it is easiest to sidestep the issue by converting the two .glb files to something that Unity can handle directly?
