### ISSUE TITLE
Perf regression in UpdateLineVisuals

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedRealityToolkit-Unity#11343]
## Describe the bug

`MRTKLineVisual.UpdateLineVisual` is allocing 2 KB every frame, even when no hands are even visible in the scene.

![image](https://user-images.githubusercontent.com/5544935/210663176-0f5eac20-3f6a-4f1a-b955-3c537f73b57d.png)

## To reproduce

Open empty MRTK scene. Run scene. Check profiler.

## Expected behavior

No per frame alloc, especially not when the rays are even visible!

## Your setup

- MRTK3 latest

**Comment by RogPodge** [comment]
Digging into this issue also revealed that we'd get a bunch of gc alloc costs when active holding a selection on an object in the input simulator. This is because our selection value would never quite hit 0 or 1. The PR #11344 adds a deadzone to the input simulator to allow the axis value to finally reach the target value of 0 or 1.

**Comment by shaynie** [comment]
Tested - no repro.  No per frame allocations now.  Looks like the above fix worked.
