### ISSUE TITLE
TouchScreenKeyboard is not showing or is positioned behind the camera

### ISSUE THREAD

**Issue by Zaniyar** [microsoft/MixedRealityToolkit-Unity#11384]
## Describe the bug
TouchScreenKeyboard is positioned at the center/behind the camera, which makes it impossible to see or type on the keyboard. 

https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/ux-building-blocks/system-keyboard?view=mrtkunity-2022-05

## To reproduce

Have a button and trigger the keyboard open function on click: 

`    keyboard = TouchScreenKeyboard.Open("", TouchScreenKeyboardType.Default, false, false, false, false);
`

## Expected behavior
Keyboard should be positioned well in front of the user/camera, and not behind the persons view.

![image](https://user-images.githubusercontent.com/4472438/213182206-25b151b9-66d8-44ea-9949-5c4dbee64aa5.png)

## Your setup (please complete the following information)

- Unity Version 2022.1.0f1
- MRTK Version 3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

I tried to use the InputFieldExamples.unity, but this also didn't work in my project.

**Comment by AMollis** [comment]
The work here would be to add support to position the native keyboard using Windows' [HolographicKeyboard.SetPlacementOverride](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.holographic.holographickeyboard.setplacementoverride?view=winrt-22621) method.

Using [HolographicKeyboard.SetPlacementOverride](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.holographic.holographickeyboard.setplacementoverride?view=winrt-22621), MRTK3 could provide a mechanism allowing an application to position the keyboard.  This would also require some sort of UX to allow the users to position the keyboard, since calling [HolographicKeyboard.SetPlacementOverride](https://learn.microsoft.com/en-us/uwp/api/windows.applicationmodel.holographic.holographickeyboard.setplacementoverride?view=winrt-22621) will disable the system's affordances for moving the keyboard.

**Comment by AMollis** [comment]
@Zaniyar for MRTK3 please our [`WindowsMRKeyboard`](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk3/com.microsoft.mrtk.input/NativeKeyboard/WindowsMRKeyboard.cs) component when showing the keyboard.  When using `WindowsMRKeyboard` we are unable to reproduce the issue you describe.
