### ISSUE TITLE
Fail to move up to Unity 2021.3

### ISSUE THREAD

**Issue by Xispeo** [microsoft/MixedRealityToolkit-Unity#11467]
## Describe the bug

My project functions with Unity 2021.1 and I fail to deploy on Hololens2 Unity 2021.2 and 2021.3
4 spheres appear and infinitely turn after launch, while launching the app in the editor functions
I had to disable burst in order to compile

## Expected behavior

I expect the app to function after getting built with Unity 2021.3 but not only with 2021.1, I need to move my project to 2021.3

## Your setup (please complete the following information)

- Unity Version 2021.1.28/2021.2.19/2021.3.22
- MRTK Version 2.8.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

- XR pluging management 4.3.3
- OpenXR plugin 1.4.3/1.7.2

**Comment by shaynie** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/11465 will update MRTK3 to Unity 2021.3.  We're waiting on build pipeline agent changes to merge it, but you are welcome to check it out.  The crash you are seeing starting on HL2 is due to a bug in the input system package.  Upgrading the InputSystem package to 1.5.1 should get you going.

**Comment by Xispeo** [comment]
Thank you !
