### ISSUE TITLE
HoloLens 2 Does Not Load Unity Splash Screen in ARM 64 Release Build

### ISSUE THREAD

**Issue by HaomiaoZ** [microsoft/MixedRealityToolkit-Unity#11541]
## Describe the bug

Initially I have a project with Unity 2020.3.30f1. I opened it with Unity 2021.3.23f1 and then deployed the project to HoloLens 2 with ARM64 Release Build. The application will stuck at the 4 white dots for a while then exit the application. 

## To reproduce

1. Setup a project with MixedRealityFeatureTool in 2020.3.30f1.
2. Open the project in 2021.3.23f1.
3. Deploy to HoloLens 2 with ARM 64 Release build.
4. Run the application.

## Expected behavior

Should see a "Made with Unity" Splash Screen after 4 white dots spinning, and the program should run

## Your setup (please complete the following information)

- Unity Version 2020.3.30f1 -> 2021.3.23f1
- MRTK Version 2.8.2 or 2.8.3

## Target platform (please complete the following information)
- HoloLens 2

## Additional context

Looks like a similar problem should be already fixed? https://learn.microsoft.com/en-us/windows/mixed-reality/develop/unity/known-issues?source=recommendations

Let me know if you need any additional information.

**Comment by AMollis** [comment]
@HaomiaoZ are you able to share what version the "[Mixed Reality OpenXR plugin for Unity](https://github.com/microsoft/Unity-MR-Plugin)" you are using.   

Also, can you share a simplified application that demonstrates this failure?

We are not able to reproduce this locally.  It's possible that there is something specific to how your project is configured.

**Comment by HaomiaoZ** [comment]
![image](https://user-images.githubusercontent.com/43716969/236514623-6866271e-b88b-41e6-9a78-af4cf97d1092.png)
I am using 1.8.0 for Mixed Reality OpenXR plugin for Unity.

Here is a project sample that has problem locally on my side: https://github.com/HaomiaoZ/Unity_Test_Project

**Comment by AMollis** [comment]
@HaomiaoZ unfortunately I was unable to reproduce the issue with the sample project you provided.  Here are the repro step I tied.

1. Cloned https://github.com/HaomiaoZ/Unity_Test_Project
2. Opened test project in Unity 2020.3.30f1 
3. Changed build settings to UWP
4. Played test project in Unity 2020.3.30f1 editor
5. Closed Unity Editor
6. Opened same test project in Unity 2021.3.23f1 (upgraded)
7. Disabled "run in background" per MSFT Open XR Validation window 
8. Built UWP VS solution with Unity 2021.3.23f1
9. Compiled VS solution and created APPX for ARM 64 using MASTER configuration and using latest Visual Studio 2022
10. Deployed APPX to HL2
11. Launched APPX on HL2
12. APPX ran successfully 

At this time, I don't believe this issue is related to MRTK.  If you still hit issues running your application, please open an issue using the Feedback App on your HoloLens 2.  This could be a platform issue, and the feedback app will gather telemetry that our team can use to investigate further.

**Comment by HaomiaoZ** [comment]
Sounds good, thanks a lot!

**Comment by HaomiaoZ** [comment]
@AMollis  I figured out the problem on my side. It is the same problem as described in #10015. After removing Oculus data provider. The test project won't crash on my side on HoloLens 2 with ARM64 Release build. Coincidentally, There are some problem with reproduction at that point as well. I can also provide a unity player log if you need.

**Comment by AMollis** [comment]
Thank you @HaomiaoZ
