### ISSUE TITLE
Microsoft HoloLens 2 Emulator April 2023 Documentation 

### ISSUE THREAD

**Issue by Victor-x1** [microsoft/MixedRealityToolkit-Unity#11544]
## Feature area
The doc doesn't mention the latest version of Hololens 2 Emulator. The last version mentioned is the January 2023 update. Latest version is April 2023 Update.

## Existing doc link
https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/hololens-emulator-archive

If this is about something in an existing document, please provide link:
The table needs to be updated with the following link:

Microsoft HoloLens 2 Emulator Windows Holographic, version 22H2 April 2023 Update (10.0.20348.1542) 
Download: https://go.microsoft.com/fwlink/?linkid=2230976

## Additional context
This is low priority.
Documentation on Hololens 2 Release notes
https://learn.microsoft.com/en-us/hololens/hololens-release-notes

**Comment by Victor-x1** [comment]
Latest Hololens 2 Firmware is 20348.1542 (22H2 April 2023)
https://learn.microsoft.com/en-us/hololens/hololens-recovery

**Comment by AMollis** [comment]
@Victor-x1 I'll pass this information along to the product team.  But I'll close this issue, since it is not related to MRTK.

I recommend opening an issue in the documentation github.  Scroll down to the button of the page and click the feedback button.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/36461279/236730881-3aeaa518-3b83-4a74-b334-1d3cc8569b18.png">
