### ISSUE TITLE
MRTK3 triggerPressed is overly sensitive

### ISSUE THREAD

**Issue by ryan-motive** [microsoft/MixedRealityToolkit-Unity#11629]
### This issue has been migrated a new [MRTK repository](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity), and the status of this issue will now be tracked at the following location:

 - https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/issues/82

___

## Describe the bug

<XRController>{...}/triggerPressed fires when hand is in a natural position, causing Activate and UI Press to be invoked when the hand is held in a natural position. Users need to hold fingers stiffly in order to avoid activating.

## To reproduce

Point at an interactable object (e.g. a grabbable) and let hand rest into a natural position (fingers slightly curled). Object will be grabbed.

## Expected behavior

Hand/finger posture should have to be more pronounced in order to fire "triggerPressed"

## Screenshots

N/A

## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.18f1]
- MRTK 3 3.0.0-pre.16
-
## Target platform (please complete the following information)

- HoloLens 2

## Additional context

Meta "pinch" action is far more restrictive and requires a natural movement in order to activate. This implementation results in many unexpected activations and button pushes.

**Comment by ryan-motive** [comment]
Happy to see this added to "future" but is there any way to adjust this in the current version? 😆

**Comment by AMollis** [comment]
@ryan-motive have you tried change the "Hand Aggregator Subsystem" settings?  The "Pinch" settings meet be able to help you out.

<img width="817" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/36461279/146321f1-af41-48f6-a3a4-2567006ab405">

Otherwise, we have plans to use Unity XRI's recently added hand support, perhaps during this time we will be able to address your concerns more.  However, switching to XRI's hand support will come post-GA

**Comment by ryan-motive** [comment]
Didn't realize this was there! This is great, I'll try it out.

**Comment by ryan-motive** [comment]
Hm, doesn't seem to make a difference. Does this impact the triggerPressed action?

**Comment by iantrobinson** [comment]
I've been running into the same issue. I've tried adjusting those values as well and it seems to have little effect if any at all.

**Comment by halfpasttense** [comment]
Same issue here. Increasing the range of those values has helped a little but finger tapping on Quest is still broken. The main issue is that a single finger tap can very often be recognized as multiple taps, which is obviously an issue. This can be easily fixed by simply having a short timeout window after a finger tap is recognized during which another finger tap cannot be activated. This works great anywhere I can build it into my own code, but it needs to be built in system wide so it behaves correctly with things like MRTK buttons.
