### ISSUE TITLE
RegisteredServiceProvider 

### ISSUE THREAD

**Issue by Cyasi** [microsoft/MixedRealityToolkit-Unity#11784]
Hello!

## Describe the issue
Where ist the RegisteredServiceProvider and how do i open it? 

I use Unity 2021.3.29f1 mit MRTK and want to use the SceneLoader. It doesnt appear under components and seems not to be included in my project so i found out its part of SceneTransition. But i cannot find how to install this extension and add it to the project. The doc says "To enable the extension, open your RegisteredServiceProvider profile." but i cannot find it anywhere in unity. 

## Feature area
Its nowhere explained for absolute newbies what the RegisteredServiceProvider profile is and how to find it.

## Existing doc link
[link](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/features/extensions/scene-transition-service?view=mrtkunity-2022-05)

## Additional context
I am very new to MRTK, looked through docs and vids already but could not find anything unfortunately.

**Comment by AMollis** [comment]
@Cyasi , I think that documentation you want is at https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk2/configuration/mixed-reality-configuration-guide?view=mrtkunity-2022-05#scene-system-settings

This helps you setup the MRTK2 scene system resource.

‼️ Important.   For all new applications, we highly recommend using MRTK3 instead of MRTK2.  MRTK3 is better supported.  You can find MRTK3 documentation at  https://mixedrealitytoolkit.org
