### ISSUE TITLE
Sample Scene Issues

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedRealityToolkit-Unity#11791]
From the example hub sample scenes, going to the scene understanding scene (experimental) does not seem to work, and one of the eye scrolling examples has text outside of the intended box. 

Repro'd in Unity 2021.3 and 2023.

**Comment by AMollis** [comment]
@marlenaklein-msft is this still an issue?

**Comment by AMollis** [comment]
Thank you for your issue. Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority security issues.  Unfortunately, this issue does not meet the necessary priority and will be closed.  If you have any concerns or questions, please reply to this issue.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.mixedrealitytoolkit.org%2F&data=05%7C02%7Camollis%40zune.net%7Caa50b235e6724f3792bc08dbf68112c7%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638374806447484283%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rGinz4nDEkKnK3S4%2Bdh2ioHeh0y46CFeM5vYp5YF0BI%3D&reserved=0).

Thank you for your continued support of the Mixed Reality Toolkit!
