### ISSUE TITLE
Eye Tracking not working when enabled

### ISSUE THREAD

**Issue by EstebanKITAR** [microsoft/MixedRealityToolkit-Unity#11809]
## Describe the bug

The eye tracking feature works almost consistently in our project in the HoloLens 2 but a recent occurrence of the cursor not moving and the service confirming the Gaze Provider was enabled has raised the concern that something is missing, or a bug may be present.

## To reproduce

The Input settings for Gaze Provider are the following:
![GazeProviderSettings](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/123187744/369d406f-2014-4b88-835f-72c6333c10d3)

The code used to enable the eye tracking on runtime is the following:
![EnableEyeTrackingCodeSnipet](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/123187744/a4184560-1d36-455c-9de8-ed330e7f2a2a)

## Expected behavior

The eye tracking feature should work following the user's eyes when the lines are executed.

## Your setup

Our project running on Unity v2021LTS and MRTK 2.8.2.

## Target platform

- HoloLens 2

**Comment by AMollis** [comment]
We appreciate your feedback and thank you for reporting this issue.

Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority issues. Unfortunately, this issue does not meet the necessary priority and will be closed. If you strongly feel that this issue deserves more attention, please open a new issue and explain why it is important.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://www.mixedrealitytoolkit.org).

Thank you for your continued support of the Mixed Reality Toolkit!

If you need developer support on HoloLens, please open a support ticket @ https://aka.ms/hl2devsupport
