### ISSUE TITLE
Lighting Scene is not taking effect in Scene system

### ISSUE THREAD

**Issue by LazyWood** [microsoft/MixedRealityToolkit-Unity#11808]
Create 2 lighting scene with SunLight and moonlight direction light (different color and intense)

Open Example Hub example scene.

Enable the lighting scene.

add SunLight And MoonLight Scene into the array

Set sunlight as default scene

start with the Example Hub Scene

sunlight scene is loaded and the direction light in the scene is disable. no light in the scene

-------------------------------
I had the same problem，Unity engine only "direct light "cant use，other light can use.
Unity 2021.3.4，MRTK 2.8.2

**Comment by AMollis** [comment]
We appreciate your feedback and thank you for reporting this issue.

Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority issues. Unfortunately, this issue does not meet the necessary priority and will be closed. If you strongly feel that this issue deserves more attention, please open a new issue and explain why it is important.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://www.mixedrealitytoolkit.org).

Thank you for your continued support of the Mixed Reality Toolkit!
