### ISSUE TITLE
Interactive Ability between Python Script and Unity

### ISSUE THREAD

**Issue by AbhiG7** [microsoft/MixedRealityToolkit-Unity#11804]
I would like to be able to interact back and forth with a python script through my Unity game. I know there's Python for Unity, but that seems to just run a single Python script from start to finish.

I was wondering, is there a way to run a Python script in Unity and have information go back and forth between the script and Unity in real time so that it's interactive? A basic example would be to have a button in Unity that causes a change in the Python script every time it's clicked.

I wasn't sure how to label this request/question so I labeled it as a feature request. Please let me know if this is possible to do in Unity?

**Comment by AMollis** [comment]
Hi @AbhiG7 

We appreciate your feedback and thank you for reporting this issue. 

Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority security issues.  Unfortunately, this issue does not meet the necessary priority and will be closed. If you strongly feel that this issue deserves more attention, please open a new issue and explain why it is important.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://www.mixedrealitytoolkit.org).

Thank you for your continued support of the Mixed Reality Toolkit!
