### ISSUE TITLE
Vertical FOV drop makes CameraFOVChecker.cs result incorrect

### ISSUE THREAD

**Issue by EstebanKITAR** [microsoft/MixedRealityToolkit-Unity#11810]
## Describe the bug

There is a vertical displacement of the Field Of View that is always downwards and only perceived when deploying in the HoloLens 2.  UIs that appear centered in the Unity Editor are then placed _far up_ in the deployed version running in the HoloLens. The amount of vertical offset has been calculated empirically as 32 cms down at a distance of 1 meter.

The script provided by MRTK ([CameraFOVChecker.cs](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/CameraFOVChecker.cs)) to detect a point in space is inside the FOV frustum gives false positives because of this issue.

![VerticalDisplacement](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/123187744/c9b7eb2e-9291-4108-b291-3679039135f4)

## To reproduce

Use any example Vector3 in the upper edge of the frustum and even though CameraFOVChecker gives a positive result the point is not visible in the HoloLens 2 because FOV is moved downwards.

## Expected behavior

Frustum drawn in Unity and used by CameraFOVChecker be the same as the one in the device.

## Screenshots

If it helps, the composed video when recording from the device is not displaced, resembling more what is visualized in the Unity Editor than what is truly seen by the user.

## Your setup (please complete the following information)

Our project running on Unity v2021LTS and MRTK 2.8.2.
## Target platform (please complete the following information)

- HoloLens 2

**Comment by AMollis** [comment]
We appreciate your feedback and thank you for reporting this issue.

Microsoft Mixed Reality Toolkit version 2 (MRTK2) is currently in limited support. This means that Microsoft is only fixing high priority issues. Unfortunately, this issue does not meet the necessary priority and will be closed. If you strongly feel that this issue deserves more attention, please open a new issue and explain why it is important.

Microsoft recommends that all new HoloLens 2 Unity applications use MRTK3 instead of MRTK2.

Please note that MRTK3 was released in August 2023. It features an all-new architecture for developing rich mixed reality experiences and has a minimum requirement of Unity 2021.3 LTS. For more information about MRTK3, please visit [https://www.mixedrealitytoolkit.org](https://www.mixedrealitytoolkit.org).

Thank you for your continued support of the Mixed Reality Toolkit!
