### ISSUE TITLE
Pinch Gesture Broken in MRTK 2.8.3 with Windows Versions higher than 10.0.20348.1540

### ISSUE THREAD

**Issue by kijz** [microsoft/MixedRealityToolkit-Unity#11822]
## Describe the bug

- Pinch gesture is not recognized anymore when both the Windows and MRTK version are installed
- `MRTK 2.7.3` Pinch gesture still works
- Windows `10.0.20348.1540` and `MRTK 2.8.3` still works
- After updating Windows (to 11), pinch gesture is not recognized in Unity builds
- I can only confirm that `10.0.20348.1540` still works and `11.0.22621.1272` does not work, but i think it might correlate with win10 -> 11

## To reproduce

- Hololens with Windows `10.0.20348.1540`
- Hololens with latest Windows version (win11)
- Download `HandInteractionExamples` from `MRTK 2.8.3`
- Compare with `HandInteractionExamples` from `MRTK 2.7.3`
- `MRTK 2.7.3` Pinch gesture works
- `MRTK 2.8.3` Pinch gesture does not work

1. Build `HandInteractionExamples` Scene
2. Try interacting with the Sliders

## Expected behavior

- Pinch gesture should work in all versions

## Your setup (please complete the following information)

- `Unity 2022.3.21f`
- `MRTK 2.7.3 / 2.8.3`
- `Windows 10.0.20348.1540` / latest windows update

## Target platform (please complete the following information)

- HoloLens 2 Build

**Comment by AMollis** [comment]
@fkajzer we are unable to reproduce this issue. Given the issue happens after updating to latest version of OS.  That sounds like an OS issue. Can you please open a support ticket at https://aka.ms/hldevsupport, someone on the support team will help gather telemetry and help diagnose the failure.

**Comment by maurice-ach** [comment]
@AMollis, I would like to confirm that I am also experiencing this issue on my HL device with version 22621.1272. I am puzzled as to why you are unable to reproduce this, especially since it involves Microsoft's default example for hand interactions with the latest Windows version.

It seems that other vendors are encountering similar problems with pinch gestures, as discussed here: [Pinch action not working](https://forum.magicleap.cloud/t/pinch-action-not-working/3235).

I would greatly appreciate it if someone from your team could investigate this matter. It appears to be a systematic issue with MRTK that can be easily replicated. Thank you for your attention to this matter.

**Comment by HopeSuffers** [comment]
We were able to solve the problem with the great help of the Microsoft supporter nathan. We used the _Hand Interaction Profile_. This works with the win 10 versions of HoloLens.

On win 11 this no longer works and you have to use the _Microsoft Hand Interaction Profile_.

![image](https://github.com/microsoft/MixedRealityToolkit-Unity/assets/80710247/c025cc90-06a2-4598-856d-b0a69b7f60a7)

And that did the trick for us. It strangely behaves a bit different on ARM64 builds were this wasn't an issue. We are on ARM32 though.
