### ISSUE TITLE
Speech recognition is not supported on this machine error

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#1190]
I've started getting a speech recognition error as of the most recent updates.
```
UnityException: Speech recognition is not supported on this machine.
UnityEngine.Windows.Speech.PhraseRecognizer.CreateFromKeywords (System.String[] keywords, UnityEngine.Windows.Speech.ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/artifacts/generated/Metro/runtime/SpeechBindings.gen.cs:47)
UnityEngine.Windows.Speech.KeywordRecognizer..ctor (System.String[] keywords, UnityEngine.Windows.Speech.ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/Runtime/Export/Windows/Speech.cs:221)
HoloToolkit.Unity.InputModule.SpeechInputSource.Start () (at Assets/HoloToolkit/Input/Scripts/InputSources/SpeechInputSource.cs:70)
```

Though not sure if this is MRTK problem and not a Unity or Windows issue as there have been updates to all three.

**Comment by StephenHodgson** [comment]
Make sure you have `Get to know me` enabled in your Privacy/Speech, Inking, & Typing menu.

**Comment by song1shuai** [comment]
Have same issue , pretty sure  Privacy/Speech enabled , and mic plugin .  better to check  
PhraseRecognitionSystem.isSupported before create KeywordRecognizer . Otherwise, it will crash the app

**Comment by genereddick** [comment]
In my case it was an issue with the latest Windows update breaking Cortana & Speech services. Details on a fix at the link: But I'm adding the isSupported check in any case. Thanks!

https://aka.ms/Ksyux5
Issue: After upgrading from Build 16299.0 to 16299.15, you might lose all previously installed Feature-on-Demand (FOD) packages such as Windows Media Player, language features, etc. during the upgrade. If you upgraded to Build 16299.15 from an older build such as Build 16296 – you are not impacted.

**Comment by StephenHodgson** [comment]
Thanks for the update!

**Comment by PaulvdBles** [comment]
For me the solution is to set English (US) as primary language. It will install some additional speech recognition parts in Windows 10.

**Comment by MohsenneChaverdie** [comment]
It happens to me today. I don't why, but it turns out to be a certificate issue. I removed the generated one from my project and it worked again.

**Comment by gianidiny** [comment]
NO Solution Find!!!

`UnityException: Speech recognition is not supported on this machine.
UnityEngine.Windows.Speech.PhraseRecognizer.CreateFromKeywords (System.String[] keywords, ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/artifacts/generated/Metro/runtime/SpeechBindings.gen.cs:47)
UnityEngine.Windows.Speech.KeywordRecognizer..ctor (System.String[] keywords, ConfidenceLevel minimumConfidence) (at C:/buildslave/unity/build/Runtime/Export/Windows/Speech.cs:221)
SpeechRecognitionEngine.Start () (at Assets/Scripts/SpeechRecognitionEngine.cs:55)`

Still a computer with again this puzzle with their function I walk today and tomorrow I do not want!

Me the problem and surely on Unity3D!
I have exactly the same problem of writing here on the issue but I garentie well to have WINDOWS10 and that my unity 5.6.4 P2 this really works great!!!  

Purpose 

Since I've wanted to do the update of Unity3D 2018 not only the application no longer works! But same Unity3D no longer work!  (Problem of Unity Package Manager with a file manifest. JSON or elsewhere nothing is also solved at the same time! Short end This is not the topic!)

So NOW.

I Reinstall Unit 5.6.4 P2 and magically!
!!! Nothing WORKS!!!
While my Windows10 and always the same WINDOWS10!
The Cortana Application always works very well!
That my microphones is well acctiver!

So I think that I'm going to tear my hair! I was working on this project and now it say UnityException: Speech recognition is not supported on this machine.
UnityEngine. Windows. Speech. PhraseRecognizer. CreateFromKeywords (System. String [] keywords, ConfidenceLevel minimumConfidence)...... blah bla...!
I'm going crazy!
If someone can help me find a solution please?! Before I be go bald! Or to me throw out of the window with my computer.

In you, thanks in advance!

**Comment by gianidiny** [comment]
THX for the projects 
i have resolut my problem here
`https://github.com/lightbuzz/speech-recognition-unity`

thank you 
see you later

**Comment by HjoshM** [comment]
I have done all the above, but I still get the "UnityException: Speech recognition is not supported on this machine" error message. I would appreciate any help...

**Comment by davidkline-ms** [comment]
Please confirm that speech works on your system in a non-HoloToolkit / non-Unity application. Cortana would be a good one to try.

Thanks and please let us know what you find,

**Comment by HjoshM** [comment]
@davidkline-ms Thanks for your response. The `PhraseRecognitionSystem.isSupported` in my Unity program returns `false` despite having a `Windows 10 Enterprise` with `Cortana` enabled. However, when I click on the `Start Menu `button, `Cortana` does not appear in my apps, neither does its button appear above the `Windows` icon...

**Comment by comicxmz001** [comment]
@HjoshM I had this issue recently after upgrading windows to 17134. If you haven's resolved your issue, maybe try:
 
Check mic is enabled in project settings and **download En-US language pack**. Somehow, additional non-display languages seem to be removed after the system update.

Note. You do NOT have to switch your display language, region, nor enable Get To Know You. Just downloading that US language pack will do the job.

**Comment by payyavula** [comment]
I am using Unity 2018.3.6f1 and Holotoolkit 2017.4.30 and I am getting "UnityException: Speech recognition is not supported on this machine" while running the app from visual studio.  sometimes it works and other times I get this exception.  Restarting hololens helps, but this issue comes back after running this app few times.  I checked settings and enabled mic for this app.

**Comment by Yoyozilla** [comment]
Moving discussion to Stackover flow since this seems like a non-mrtk bug.

**Comment by zxzkf1992** [comment]
@gianidiny 
This error occurred when I tested my project today.
And before i have this error everything works good with speech recognition!
I can be sure that the windows settings are completely correct and the Cortana Application always works very well !
I have tried many methods, including reinstalling windows system.
Can you tell me how you solved this problem?
