### ISSUE TITLE
Should add existing controllers to controllerDictionary in Awake instead of OnInteractionSouorceUpdated

### ISSUE THREAD

**Issue by timGerken** [Microsoft/MixedRealityToolkit-Unity#1194]
After talking with @keveleigh , by "noticing" controllers in OnInteractionSourceUpdated, we try to add the same controller multiple times to the dictionary which causes a collections exception.

https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/1ad7ffe208b2b2ed22bedee490ab69ba5128c584/Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs#L199

Instead, we should get all the controllers currently tracked from the InteractionManager and add them to the dictionary in Awake() and then rely on InteractionSourceDetected to notice any new controllers.

**Comment by timGerken** [comment]
via #1195

**Comment by keveleigh** [comment]
This method still produces a single duplicate add if the object is in the scene at the start, since we'll be attempting an add in both the new loop and in the first SourceDetected event. I have an incoming PR which uses a loadingControllers list to keep track of any controllers that are in the process of being added.

**Comment by keveleigh** [comment]
via #1196
