### ISSUE TITLE
Sharing Hololenses don't Sync their positions correctly

### ISSUE THREAD

**Issue by kyleWillson** [Microsoft/MixedRealityToolkit-Unity#1319]
So I have a shared experience that has 1 Instructor and multiple Viewers.  However when I start the application on all the devices their positions aren't Synced together.  So if I start an Instructor in Position A and then start a Viewer in Position B (Real world positions).  The synchronized positioning is skewed by the distance vector between Position A and Position B.  So the only way they can be somewhat synchronized is if I start each app in the same exact real world position.

So for example when I start the app in different positions, the Cubes that get placed where a HL is (from RemoteHeadManager) are in a different position based on the distance vector from where each application was loaded.

I know there is a solution for this.  Do I need to give each HoloCamera a world anchor?  Enable Spatial Mapping?  If someone could please let me know this is extremely time sensitive.

**Comment by MrMatthias** [comment]
you need at least one anchor, you could then add all players as child and sync their relative position to that anchor

**Comment by kyleWillson** [comment]
When you mean add all players as a child, do you mean the cube position that is generated from RemoteHeadManager? Or what?

**Comment by MrMatthias** [comment]
The origin is based on where you started the app, so you can't sync the worldposition, you have to use a common reference point (world anchor) and synchornize the viewer's relative position, relating to that reference point

**Comment by NeerajW** [comment]
1. You don't need spatial mapping for World Anchors. They use visual tracking data and not depth data.
2. Yes much like RemoteHeadManager will broadcast relative positions of cubes/users based on the common anchor sphere that has been established. Each player becomes a child of that common anchor point sphere. So once the main speaker establishes an anchor point, others can start using the same. 
3. If speaker 1 makes the anchor, then other people need to have the same tracking points he saw since anchors work using visual tracking so making them walk around the space to build good tracking is a must.

**Comment by jayhersk** [comment]
Is the SharingWorldAnchorManager script supposed to sync the positions automatically? Or am I supposed to send the positioning of the anchor from one device to another somehow? Right now I can see the same holograms on each device but they are shifted depending on where I was looking when I started my app. Any advice is appreciated.

Best,
Jaylin

**Comment by kyleWillson** [comment]
@jayhersk ,  I also encounter that problem as well, and it's quite annoying.  @NeerajW  do you have a fix for that?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
