### ISSUE TITLE
stop adjusting the camera zoom and height in unity

### ISSUE THREAD

**Issue by RICKASHEYE** [Microsoft/MixedRealityToolkit-Unity#1360]
how to stop unity from adjusting the height and the zoom and just keep it at nothing and at how it is in the editor before playing the scene?

**Comment by keveleigh** [comment]
You can call `XRDevice.SetTrackingSpaceType(TrackingSpaceType.Stationary);`, which will cause your app to start at (0, 0, 0), like HoloLens and how it looks in the editor before playing.

However, we currently have [some lines in `BoundaryManager` that call that method](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs#L111 ) and might overwrite any changes you make. We should probably remove them or make them more configurable. I'll address this in #1339, since it's related.
