### ISSUE TITLE
Internet connection slowdown

### ISSUE THREAD

**Issue by DMCKITT** [Microsoft/MixedRealityToolkit-Unity#1416]
## Overview
When running ANY internet based application in Mixed Reality (Store, Browser, Holograms, etc.), the internet connection gets very slow. (Down to 4 bytes/s) I won't get better, even after shutdown of mixed reality portal. Restarting the router helps.

## Expected Behavior
Access internet in fullspeed.

## Actual Behavior
Connection slowdown.

## Steps to reproduce
_(Links to sample github project preferred)_
Start Mixed Reality Portal, go into mixed reality and open up any internet-based application. eg. Store or Holograms.

## Unity Editor Version
Not Relevant

## Mixed Reality Toolkit Release Version
Not Relevant

## Note:
This my first bug report, so please excuse me if I did anything wrong. I found bug reports of the portal here, so I also posted it here. If it belongs somewhere else, please tell me.

**Comment by brean** [comment]
Seems like this is a problem with your router or network, maybe even a hardware defect on your device because I can not reproduce this. Also this is not a bug in the Unity Mixed Reality Toolkit, so it does not belong here. I would try to switch to another network and if it is also slow there contact the Microsoft support.

**Comment by StephenHodgson** [comment]
If the editor version and the toolkit version are not relevant, then it's safe to assume that this issue isn't relevant to the repository.
