### ISSUE TITLE
Sharing Examples Crash / How to use undocumented

### ISSUE THREAD

**Issue by drakep** [Microsoft/MixedRealityToolkit-Unity#1438]
## Overview
When putting sharing examples on Hololens when attempting to enter an IP the experience crashes with first UI interaction
## Expected Behavior
Ability to type in IP of host to start shared space example experience
## Actual Behavior
Experience crashes
## Unity Editor Version
2017.2.0f3
## Mixed Reality Toolkit Release Version
v1.2017.2.0 Master release tag?

**Comment by StephenHodgson** [comment]
Please fill out repro steps

**Comment by cstensonpv** [comment]
I'm experiencing a this issue aswell any progress?

**Comment by GAnatoliy** [comment]
Not, sure if it is the same issue since in my case app crushes during start (we start interact with sharing service immediately after start).

The issue was that device capabilities for network interaction were disabled (after moving to 2017.2.1, probably I accidentally clear them by Mixed Reality Toolkit menu). 

Probably it is a bug that system doesn't give appropriate info/logs about issue and just crush.

I was able to detect issue in debug mode (on emulator) when set Debbuger type set to mixed in vs.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
