### ISSUE TITLE
GazeManager's Raycast Layer Masks should be removed

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1445]
The `GazeManager`'s `RaycastLayerMask` should be coming from the `FocusManager.PrioritizedRaycastLayerMasks`.

It's only use is currently in `SpatialUnderstandingBasicCursor`, which should be updated to also use the `FocusManager.PrioritizedRaycastLayerMasks`

**Comment by jbienzms** [comment]
Just adding a comment here that there doesn't appear to be a `FocusManager.PrioritizedRaycastLayerMasks` property. There is a _field_ but it is called `FocusManager.pointingRaycastLayerMasks`. 

If this is intended to be the prioritized layer mask for all input devices, then the word 'pointer' should probably be removed from the field and it should be renamed to **PrioritizedRaycastLayerMasks** as you have suggested. However, if there is any intent to have a different layer mask for Gaze than Pointers, the separation could remain in GazeManager as it is.

One of the things that we've been looking at lately is how many cross-dependencies we have between behaviors. GazeManager does not currently reference FocusManager but FocusManager does reference GazeManager. Before this change is made, we should evaluate it thoroughly to make sure it's the right design choice. Especially since it is a breaking change.

**Comment by StephenHodgson** [comment]
Well, in the new paradigm of the `FocusManager` the gaze is treated as a pointer.

I'd like to see a way to create optional layer makes for each pointer in a single place, ideally in the focus manager.

**Comment by StephenHodgson** [comment]
Going to address this in vNEXT
