### ISSUE TITLE
Starting App while tracking is lost player starts at origin

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#1455]
## Overview
When the tracking is lost and the app is started, even with MRTP5 that fixes the tracking resume bug, the player starts with the head in the floor. The controllers are actually at the correct height, one can see them floating above the head. Once tracking is resumed, it gets fixed.
Putting the head further up in that case doesn't work, because the camera still receives 0 readings.

## Expected Behavior
The player is always above the floor

## Actual Behavior
If the app is started in tracking lost state, the player starts at 0,0,0.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
MRTP5

## Mixed Reality Toolkit Release Version
most current

**Comment by cre8ivepark** [comment]
@Alexees @keveleigh Had similar issues, while repeated teleportation, the eye level goes down to the floor level and cannot be recovered without restarting the app. Temporarily fixed the issue by forcing y position of the MixedRealityCameraParent to 0. MixedRealityCameraParent starts with y = 0 but with repeated teleportation, it is randomly changed to -1.x value. Since my app does not have elevated surface, forcing y = 0 didn't have any side effect but I think there could be a better solution.

**Comment by Alexees** [comment]
@cre8ivepark Sorry to disappoint you. It's not the same issue, the one with teleporting changes height over time is a different one. This is a holdover from the recovery bug that was fixed with MRTP5.
