### ISSUE TITLE
Cannot build using 2017.2.1f1

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit-Unity#1539]
Using the same version editor as the MRTK is now apparently is maintained in, trying to build an actual app from a test scene will result in:
![image](https://user-images.githubusercontent.com/4129183/34081192-070c5148-e34a-11e7-995f-ddd7e8fc52b6.png)
Building in MRTP5 still works. What is the recommended Unity editor version to use>

**Comment by ivan2007** [comment]
Hi,
I can build and deploy but after a while I get this:
![image](https://user-images.githubusercontent.com/17752475/34084709-6fb21792-e385-11e7-8d97-a972216ccb81.png)
Tested with GrabMechanics, Unity 2017.2.1f1 and Dev branch
Ivan

**Comment by StephenHodgson** [comment]
@LocalJoost are you using IL2CPP?

**Comment by keveleigh** [comment]
I'm unable to repro with .NET or IL2CPP.

I've seen this message before on various versions of Unity, not just this latest one. It seems like it's caused by some process hanging around keeping access to the .pdb (maybe Visual Studio?), which causes Unity to be unable to copy/delete the new one.

The Mixed Reality Toolkit doesn't touch the .pdb file.

**Comment by LocalJoost** [comment]
Utterly annoying. I had this for two days, really consistently. And now I try to repro it myself and you guess it - it works. Lesigh.
