### ISSUE TITLE
HoloToolkit-Examples folder feedback from developers

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#1599]
## Overview
Currently with all the tests and examples being under same folder without clarity and documentation is a big mess to maintain and understand. Developers find it hard to find useful content in there.
Filing an issue to discuss ways to solve this.

**Below is verbatim feedback received:**

The MRTK

-	The developer told me that the previous release of the toolkit was too buggy but it’s much better with the last holiday release
-	There is too many samples and they are not explicit enough on their goals. He told me you’re quickly lost. He also told me he has launched several samples and had no idea of what he was supposed to do with them. He’s suggesting a kind of splash screen at the beginning of the scene indicating the main purpose of it (grabbing objects, UI, teleport, etc.)
-	He’s suggesting we should filter the samples in 2 categories: basic & advanced. He would have loved starting with a “basic” samples category showing very basic stuff: how to just display the controllers, how to add a child object on it, etc.
-	He told me that most of the samples didn’t work out of the box
-	We’re missing a sample showing how to have a pointer attached to both controllers at the same time. He’s suggesting to add a simple sample showing how to fire objects from both controllers on targets.

**Comment by Railboy** [comment]
@cre8ivepark and I have discussed ways to improve the clarity of existing samples as a stopgap while a strategy for a true overhaul is worked out. Titles & splash screens, better visual consistency - all superficial changes but they would have an immediate positive impact.

**Comment by DDReaper** [comment]
My main concern is that the majority of the scenes in the "Examples" folder are not Examples.  They are tests.
Ideally, like the HL250 course, the examples should walk through scenarios for helping to implement features, kinda like how the VRTK does it (only better).

Was considering focusing on this once the namespace stuff is done.

The Grab Mechanics is a good example of an Example (teaches you several ways to "grab"), however it is very isolated.

Personally, most of what we have should be relegated to the "Tests" project and we should start afresh with newer examples, all using the same assets / styles and enforcing good practice for informing the user how to use "stuff"

**Comment by brean** [comment]
I agree that it makes sense to clean up the examples, adapt them so they build on existing tutorials that are build on each other and are linked to the examples (I think they should link to and reuse the [Microsoft Academy Tutorials](https://developer.microsoft.com/en-us/windows/mixed-reality/academy) as base and then extend from there).

I think it is also quite confusing that the examples use different base components. For example most in the UX-folder uses its own ui-component implementation, so do the scenes in the prototyping-folder. I noticed this when I tried to get a unified button example (see #1323).

Because there are different ways to do stuff (like buttons) I think it is hard for a new user to decide which way to go, and because the examples have different goals I understand that there are duplicates.

I think it would help if we had a unified UI system (default ui-components that will be extended in every example so we can build a learning curve and reuse existing components).

**Comment by StephenHodgson** [comment]
I think a lot of the examples should probably get moved into the academy, and removed from the core toolkit itself, leaving just test scenes.

**Comment by NeerajW** [comment]
The goal of examples was to exemplify toolkit usage by adding value like UI paradigms or color pickers etc. Tests were never meant to be in examples. Something broke along the way here.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
