### ISSUE TITLE
Remove null coalescence uses in MRTK

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1638]
There's a few places where we're using null coalescence for object's that inherit from `UnityEngine.Object`.

Instead we should use `Object != null`.

**Comment by DDReaper** [comment]
Should remove ALL use of ??, just to be sure, because Unity.

**Comment by Zod-** [comment]
I would have said don't remove all of them at first, but even when I complete the extension of the resharper plugin to throw warnings for it, not everyone has resharper. Analyzers like that should really be added to the repository directly so that everyone that checks the code out has the same tools, but it's tought with unity.
Maybe if you'd seperate the solution from unity so that you have better control over it.

**Comment by StephenHodgson** [comment]
@DDReaper probably just objects that inherit from `UnityEngine`.  All the others should be fine.

**Comment by DDReaper** [comment]
Given this is Unity and there is one case for not having them.  It's probably safer to remove them all. 
Because, you know, Unity :D @StephenHodgson
