### ISSUE TITLE
Create picking list within assembly process

### ISSUE THREAD

**Issue by Gerco12** [Microsoft/MixedRealityToolkit-Unity#1640]
Hello there,

Since a day I have acquired a Hololens for my study assignment. I am following some tutorials at the moment to get to know the basics, but in the end I have to go further than that.

My goal is to assemble a gearbox with the help of the Hololens, used for training. I eventually want the Hololens to:

1. Scan a QR / barcode on a paper that says which gearbox I am going to assemble.
2. The Hololens recognizes the code and a checklist of components appears.
3. Scan the raster / closet filled with parts
4. Scan the QR/ barcodes beneath every part, so the checklist can check off all parts available
5. If all parts are available, the user can press/say start and the assembling can begin:
6. The raster lights up the first part that has to be taken
7. When its taken, the second part lights up
8. When the second one is taken, a small movie is shown in the glasses how part A and B are meant to attach to each other. (ideal setting, not particularly a must if its to hard)
9. And so on I want the whole assembly to be made with help of the Hololens.

As a rookie, I want to ask help for the steps I have to take. For as far as I know I need software/code to:

- Have a list with all components with corresponding QR/barcode
- Show a checklist onscreen
- Show a movie when a part is taken

Maybe you guys have some helpful tutorials that I must watch or can tell me that I am starting on a mission impossible. Thanks in advance!

Best regards,
Gerco

**Comment by brean** [comment]
Take a look at vuforia for the QR-code detection and tracking: https://library.vuforia.com/articles/Training/Developing-Vuforia-Apps-for-HoloLens
I guess you also need a code on your closet to tell Hololens where that is located (or have your paper sheed in a fixed position relative to the closet)
You can create a checklist using the default unity-ui or use checkboxes from the Interactive [Button demo](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractiveButtonComponents.md) provided by this toolkit.
Instead of a movie I would just show a hologram of the next piece in place (after you detected the first element you can relatively from there show where the second next part has to be placed. For assembly like screws you can have a small animation directly on your hologram).
If you like to show a video anyway take a look at the [Unity Documentation](https://docs.unity3d.com/Manual/VideoPlayer.html).

**Comment by Gerco12** [comment]
Hello Brean, thanks for responding!

I have a lot of trouble starting tutorials with Vuforia. I am trying to follow this list of tutorials: https://www.youtube.com/watch?v=oC9k5Yd4020&list=PL_Nji0JOuXg0tJ-HQ8g0OgEjIxL5RO1R2&index=3 

but when I import the vuforia-unity-6-2-10.package (isn't there a vuforia 7 package somewhere??), I get errors regarding the scripts **vuforiabehaviour**.cs and **defaultinitializationerrorhandler**.cs , saying the associated script can not be loaded. This while I haven't done anything else except installing Unity and Vuforia. I've tried the Vuforia asset via the asset store as well, but this does not include the AR camera. I feel like I can make huge steps with this tutorial if these 'software issues?' don't stop me from starting in the first place. 

My Windows is running 1709, OS 16299.192
I am using Unity 2017.3.0f3 

What am I doing wrong? I was able to follow and run Microsoft tutorials before, the computer and unity must work like required.

**Comment by brean** [comment]
The tutorial is outdated, vuforia is now integrated into Unity, follow the link I posted.

**Comment by Gerco12** [comment]
Thanks. My problem is that with the prescribed tutorials and samples, I never have the AR camera prefab within the packages.. Is this a known problem? I am following the first link but get stuck on this.

**Comment by Gerco12** [comment]
https://www.youtube.com/watch?v=ds02hHOqZGM

Can you see what I am doing wrong? When the tutorial goes to the play scene, I do the same but I can't see anything with my Hololens.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
