### ISSUE TITLE
UX and Input feature areas

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1657]
## Overview
There's a lot of overlap and fuzziness on what belongs where in the UX vs Input feature folders.

I think we should have a discussion to clearly delineate between them and provide a path to organize.

**Comment by Railboy** [comment]
Anything I put into UX is focused more on design than basic functionality. It's definitely a fuzzy line, though.

**Comment by brean** [comment]
I think the description about the [Feature areas](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/README.md#feature-areas) is clear: Input should include all inputs, gaze, voice, motion, ... for me this excludes visual while UX should provide building blocks for common controls to provide user feedback, so the visuals for the components. Of course UX needs Input to work, otherwise it would be just disabled controlls.
So I think cursors (that are currently in Input) belong to UX according to this definition.

**Comment by Railboy** [comment]
@StephenHodgson What are some concrete examples of the overlap you're seeing?

**Comment by StephenHodgson** [comment]
Stuff in input script folder that probably belongs in UX like Cursors and the like. 
I agree with the line that @brean has laid out.
