### ISSUE TITLE
UnityWebRequest and WWW Classes not working on HoloLens

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#1658]
## Overview
`ISNETWORKERROR` always returns true when running a UWP app on 86X architecture.

https://issuetracker.unity3d.com/issues/wsa-isnetworkerror-always-return-true-when-running-an-uwp-app-on-86x-architecture

**Comment by ivan2007** [comment]
WWW completely broken also for X64 UWP app and Release configuration (debug configuration seems ok). No error but the response body is empty.
I temporarily use UnityWebRequest with chunkedTransfer setted to false and checking only error and not isNetworkError because it is always true.
https://forum.unity.com/threads/critical-unity-2017-3-www-with-wwwform-not-working-wrong-network-request-header-body-created.511420/

**Comment by krishnan-unni** [comment]
@StephenHodgson @ivan2007 Adding my test case here if it helps. I am testing with the same configuration Unity 2017.3.0f3 IsNetworkingError and IsHttperror also returns true even when responsecode = 200. Working fine in Unity Editor
WWW also not working in x86 mode in hololens emulator.

**Comment by StephenHodgson** [comment]
was fixed in later editor releases.
