### ISSUE TITLE
When will the next release release be released?

### ISSUE THREAD

**Issue by jerrygg** [Microsoft/MixedRealityToolkit-Unity#1686]
## Mixed Reality Toolkit Release Version
When will the next release versions be released?

**Comment by StephenHodgson** [comment]
We're finishing up the cycle in the coming week or two.

There's been lots of changes and refactoring and asset organization across all the feature areas.

We're also in a holding pattern for getting a stable unity release of 2017 or 2018. We will see.

**Comment by jerrygg** [comment]
Thank you very much !😊

**Comment by firativerson** [comment]
Hi @StephenHodgson  , 
Might be a strange question but I wanna ask your opinion. We are starting to build our product which is roughly gonna take 4 months. Do you think I should wait for the next release or continue with the current one? I am using 17.2.1 and having problems with the new toolkit.  Will the next release be more stable and organized?

**Comment by StephenHodgson** [comment]
Good question.  Because of the fast paced nature of the technology stack we're working with, it's sometimes difficult to answer.  If it's stability you're looking for, then please be sure to contribute back to the project if you find something that's broken, and we'll be sure to address it as quickly as possible.

That being said, there are some big changes coming down the pipeline, like an updated Input Scheme, Namespace refactoring, and more.  So, I'd stick with a current or prev release if you can't afford for these kinds of changes during your project.

**Comment by kyleWillson** [comment]
Any word on when the next release is going to be?

**Comment by StephenHodgson** [comment]
When we merge #1698

**Comment by davidkline-ms** [comment]
Version 2017.4.0.0 releases in May 2018 with monthly releases to follow

Version Next (2018.9.0.0) is scheduled for September 2018

**Comment by davidkline-ms** [comment]
For future reference regarding upcoming releases we are using Project pages to track our roadmap

https://github.com/Microsoft/MixedRealityToolkit-Unity/projects
