### ISSUE TITLE
Is VOIP fully supported between hololens and Immersive, back and fro with UNET sharing ? 

### ISSUE THREAD

**Issue by ALARUNVIGNESH** [Microsoft/MixedRealityToolkit-Unity#1777]
## Overview
VOIP between hololens and Immersive & Immersive to hololens not working bothways!!.

## Expected Behavior
two way VOIP receiving and sending between hololens and immersive & immersive to immersive & Hololens to hololens!!.
## Actual Behavior
Working oneway , voice is sent from one Immersive user  to second Immersive user , Immersive User can receive Voice but cant send voice from Immersive to hololens r to other Immersive !!. <tried with Samsung Odyssey Immersive headset>
## Steps to reproduce
Sending VOIP in bytes through network messages !!. 

## Unity Editor Version
2017.2.1p1
## Mixed Reality Toolkit Release Version
2017.2.1

**Comment by HBJKZLH** [comment]
Socket  workSocket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
workSocket.Connect(point);-->This code untiy build [Universal Windows Platform] error.why?
 int length = workSocket.Receive(buffer);-->This code untiy build [Universal Windows Platform] error.why?
 workSocket.BeginSend(msgbyte, 0, msgbyte.Length, 0, null, null);-->This code untiy build [Universal Windows Platform] error.why?
 workSocket.Close();-->This code untiy build [Universal Windows Platform] error.why?


Thread thread = new Thread(ReciveMsg);-->This code untiy build [Universal Windows Platform] error.why?
thread.IsBackground = true;-->This code untiy build [Universal Windows Platform] error.why?
thread.Start();-->This code untiy build [Universal Windows Platform] error.why?






My code untiy bulid [PC,Mac&Linux Standalone] is successful.

But untiy bulid [Universal Windows Platform] failed.



I feel like [Universal Windows Platform].net is not equal to [PC,Mac&Linux Standalone].net.

Please update [Universal Windows Platform].net.

Let me use the.net socket code Thread code filestream.



------------------ 原始邮件 ------------------
发件人: "ALARUNVIGNESH"<notifications@github.com>;
发送时间: 2018年3月1日(星期四) 中午1:52
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Microsoft/MixedRealityToolkit-Unity] Is VOIP fully supported betweenhololens and Immersive, back and fro with UNET sharing ? (#1777)




Overview
 
VOIP between hololens and Immersive & Immersive to hololens not working bothways!!.
 
Expected Behavior
 
two way VOIP receiving and sending between hololens and immersive & immersive to immersive & Hololens to hololens!!.
 
Actual Behavior
 
Working oneway , voice is sent from one Immersive user  to second Immersive user , Immersive User can receive Voice but cant send voice from Immersive to hololens r to other Immersive !!. 
 
Steps to reproduce
 
Sending VOIP in bytes through network messages !!.
 (Links to sample github project preferred)
 
Unity Editor Version
 
2017.2.1p1
 
Mixed Reality Toolkit Release Version
 
2017.2.1

**Comment by ALARUNVIGNESH** [comment]
For me VOIP working oneside, but not bothways!!.

**Comment by StephenHodgson** [comment]
Are you using the voice chat features in the micstream.dll?

**Comment by HBJKZLH** [comment]
Untiy [Universal Windows Platform] Platform does not support.

The Socket code is written and the Thread code is written and the FileStream code is written, you know what?



I used the network communication section to find that this part of the code could not be transferred to the [Universal Windows Platform].

After I tested Unity 2017.2.0f3 (64-bit) version,Unity 2017.3.1f1 (64-bit) version,Unity 2017.2.1f1 (64-bit) version.



They don't support it.



Do you have any feedback on untiy?









When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the 
socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,




But if I just write in the code.

The Socket client = null;

Thread the Thread = null;

FileStream filedata = null;



This way, the Universal Windows Platform is passed.

I think it should be the flaw in the Platform library of untiy [Universal Windows Platform].


Please help me to feedback this question,








------------------ 原始邮件 ------------------
发件人: "ALARUNVIGNESH"<notifications@github.com>;
发送时间: 2018年3月1日(星期四) 晚上9:42
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "上善若水"<914149295@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [Microsoft/MixedRealityToolkit-Unity] Is VOIP fully supportedbetween hololens and Immersive, back and fro with UNET sharing ? (#1777)




For me VOIP working oneside, but not bothways!!.

**Comment by ALARUNVIGNESH** [comment]
No , Im not using Micstream.dll, I'm sending VOIP in bytes array through network messages!!.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
