### ISSUE TITLE
SpeechInputSource not working

### ISSUE THREAD

**Issue by kvvishwa** [Microsoft/MixedRealityToolkit-Unity#1779]
## Overview
I am trying to use SpeechInputSource for Voice Commands but with no success, I even tried it with Sample Scene available in the Toolkit examples.

I am not even getting an error. My Mic works well , Unity version is 2017.3.1p1. 

Can any one suggest what could be the issue?

## Steps to reproduce
_(Links to sample github project preferred)_

**Comment by HBJKZLH** [comment]
Untiy [Universal Windows Platform] Platform does not support.

The Socket code is written and the Thread code is written and the FileStream code is written, you know what?



I used the network communication section to find that this part of the code could not be transferred to the [Universal Windows Platform].

After I tested Unity 2017.2.0f3 (64-bit) version,Unity 2017.3.1f1 (64-bit) version,Unity 2017.2.1f1 (64-bit) version.



They don't support it.



Do you have any feedback on untiy?









When I wrote socket and IO and Thread related code in the program, untiy packaging times was wrong,
The socket.Connect function is not supported.
The socket.Receive function is not supported, and the 
socket.Send function is not supported.
The filestream.close function is not supported,
New Thread(recv) is not supported,
Does not support Thread. IsBackground,
Does not support Thread. To Start,




But if I just write in the code.

The Socket client = null;

Thread the Thread = null;

FileStream filedata = null;



This way, the Universal Windows Platform is passed.

I think it should be the flaw in the Platform library of untiy [Universal Windows Platform].


Please help me to feedback this question,








------------------ 原始邮件 ------------------
发件人: "kvvishwa"<notifications@github.com>;
发送时间: 2018年3月2日(星期五) 上午10:15
收件人: "Microsoft/MixedRealityToolkit-Unity"<MixedRealityToolkit-Unity@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Microsoft/MixedRealityToolkit-Unity] SpeechInputSource not working(#1779)




Overview
 
I am trying to use SpeechInputSource for Voice Commands but with no success, I even tried it with Sample Scene available in the Toolkit examples.
 
I am not even getting an error. My Mic works well , Unity version is 2017.3.1p1.
 
Can any one suggest what could be the issue?
 
Expected Behavior
 
Actual Behavior
 
Steps to reproduce
 
(Links to sample github project preferred)
 
Unity Editor Version
 
Mixed Reality Toolkit Release Version

**Comment by kvvishwa** [comment]
Hi Thanks for your Reply and time.

I got that working with SpeechInput Source and SpeechInput Handler

The issue was I did not had the IsGlobalListener selected in the SpeechInput Handler.
