### ISSUE TITLE
Cannot test whether grip position can be obtained from a WSA hand

### ISSUE THREAD

**Issue by PJBowron** [Microsoft/MixedRealityToolkit-Unity#1824]
## Overview
Forgive me if this covered elsewhere: it no longer seems possible to 'properly' test **if a position can be obtained** from a WSA 'hand' input source (via InteractionInputSource). Browsing through the current code, it appears that though a hand supplies a position through its 'grip' ability, and this gets reflected up through the SourceCapabilities, **asking for the capability** fails because GetSupportedInputInfo doesn't consider grip info (position or rotation) at all.

## Expected Behavior
Asking **for 'Position'** support will succeed for an InteractionInputSource with an underlying WSA hand source

## Actual Behavior
**The only supported info from a hand is 'Selected', IIRC.**

## Repro
Set up a default scene including the InputManager with an InteractionInputSource.
Add a script that implements a Handler interface (e.g. IInputClickHandler)
In the Interface delegate, ask the InputEventData if its InputSource supports the SupportedInputInfo.Position info

## Mixed Reality Toolkit Release Version
Local version is some flavour of 2017.2, but current code as browsed on GitHub looks the same

**Comment by StephenHodgson** [comment]
I'm not sure the API even supports grip for hands, but I'll double check.

Do you have repro steps for me to test this?

**Comment by PJBowron** [comment]
I realise I've misworded this somewhat, but I think there's still an issue here somewhere... I'm about to get off a train but I'll update the issue asap with something more coherent :)

**Comment by PJBowron** [comment]
@StephenHodgson Regarding the question of API support for Grip: WSA.Input does, via InteractionSourceState.sourcePose, and although the toolkit exposes this via TryGetGripPosition, you just can't test for support with GetSupportedInputInfo.

I'm happy to update the code to address this.

**Comment by StephenHodgson** [comment]
> I'm happy to update the code to address this.

Yes please :)

**Comment by keveleigh** [comment]
Ahh, good catch! Yep, the hand's positional data is routed through the "grip" position, I'd think because that also aligns with where the hand would be placed on a motion controller. GetSupportedInputInfo should definitely distinguish between Pointer and Grip position and rotation support, like you've already proposed. Thanks!

Your mention of Select being supported is interesting too. It looks like that data only comes through `state.anyPressed`, while currently the Toolkit's input system only cares about `state.selectPressed`, where I didn't see any hand data come through from my tests just now.
We could probably update [`GetSelect`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs#L114) to take into account if the source is a hand, then to check `state.anyPressed` instead of `state.selectPressed`.

**Comment by PJBowron** [comment]
I've just put up an initial drop of my changes -
@keveleigh I didn't go near the `select` issue yet as I wasn't entirely clear on it :)  But maybe it would warrant its own PR anyway.

**Comment by timGerken** [comment]
via #1870

**Comment by StephenHodgson** [comment]
Do we also need to fix this in the master branch?

**Comment by timGerken** [comment]
@StephenHodgson  good question.
@PJBowron ?

**Comment by timGerken** [comment]
@PJBowron I think, if the fix is righteous, the right thing to do is cherry-pick it from the Dev_Working_Branch into Patch4_Dev. That branch will merge into master "real soon now".

**Comment by PJBowron** [comment]
Apologies for letting this go stale; @davidkline-ms is it too late for me to cherry-pick this for Patch4_Dev? I'm assuming you're done with that, now that 2017.2.1.4-rc2 is out?

**Comment by davidkline-ms** [comment]
@PJBowron,

2017.2.1.4 is scheduled to be released in the next couple of days.  Please feel free to target your fix to the may18_dev branch.

Thanks!
David

**Comment by PJBowron** [comment]
@davidkline-ms 
Finally gotten around to resubmitting new PR: #2050

**Comment by davidkline-ms** [comment]
This was released in the 2017.4.0.0 release candidate
