### ISSUE TITLE
[master] update unity version to 2017.2.1p2

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/MixedRealityToolkit-Unity#1874]
Update the toolkit's unity version to match the recommendation on https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools

**Comment by StephenHodgson** [comment]
We agreed that we would only move the project to full releases of Unity, and not patches.

Although, I do like the idea that we should keep in line with the dev docs.

**Comment by davidkline-ms** [comment]
Alignment with the dev docs is 100% the goal. Customers that install recommended tools should not have to see the "the versions don't match" dialog. :)

**Comment by keveleigh** [comment]
Related to #1628.

> not patches

We shouldn't arbitrarily move to the latest patch, but Unity has put many MR-specific fixes into patches, often making them the recommended version.

Our current version (2017.2.1f1) was never an officially recommended version for MR development, due to bug fixes that never made it in out of the MRTP builds (motion controllers not being detected when playing from the editor, among others). These bug fixes *did* make p2.

**Comment by davidkline-ms** [comment]
Definitely not advocating to updating for every patch that is released. Only to match the recommended guidance on the Windows Mixed Reality documentation.
