### ISSUE TITLE
Spatial Understanding Performance

### ISSUE THREAD

**Issue by teichgraf** [Microsoft/MixedRealityToolkit-Unity#194]
Thanks for this great contribution! :)

I did some quick tests. 

During scan the framerate looks good at 60 fps but CPU is maxing out. No real surprise and totally fine considering the processing it runs.

Post scan I get 30-40 fps when looking at certain parts. The SpatialUnderstandingSurfaceShader does quite some stuff and even use geom surface shader instructions. I'd recommend making the shader a bit more lightweight or maybe use a much simpler one as default to avoid framerate drops.

**Comment by NeerajW** [comment]
Thanks Rene. I also certainly see the FPS between 30-35 during scan phase. Once scan is done, I bump up to about 45 but still not the best.

**Comment by izatar** [comment]
I played around with this shader a bit.  It did see that the geometry shader is causing a big fps drop especially when the scan is finalized.  But I think that the geometry shader is necessary because the mesh has no normals or UVs.  I am no expert in this area, but I think that if the mesh had more info in it the shader wouldnt have to work so hard.
Also, I see that the fragment shader uses an exponential, which I recall is supposed to be a no-no in shaders because it is slow.   This is a trival problem compared to the geometry shader though.

**Comment by HodgsonSDAS** [comment]
@teichgraf have you seen any substantial improvements?

There's been quite a bit of work to the spatial understanding libraries over the last few weeks.

**Comment by jessemcculloch** [comment]
@teichgraf - We are trying to close out some issues that have been hanging around for a long time.  Can you confirm if this is still an issue?
