### ISSUE TITLE
Input Manager can cause NullReferenceException if EventSystem gets initialized after InputManager

### ISSUE THREAD

**Issue by arctop-sk** [Microsoft/MixedRealityToolkit-Unity#2312]
## Overview
In InputManager.cs, Awake() method calls InitializeEventDatas(), which relies on EventSystem.Current being available, and uses those datas throughout the lifetime of the InputManager.

Depending on how the systems are originated in the hierarchy, it is possible that EventSystem.Current returns null, which causes NullReferenceException to occur on events inside InputManager.

This is easily resolved by moving initialization code into the Start() method.

In general, initialization that relies on other systems/classes should never occur on Awake(), as order of calls is never guaranteed.

**Comment by StephenHodgson** [comment]
It's the same for all Singletons. My advice is to update the script Excecution order. We won't be moving the initialization into start, as it won't guarantee a fix.

**Comment by arctop-sk** [comment]
I was raising the issue as it goes against the recommended Unity initialization guidelines.  I have it fixed locally. I'm glad that you are moving away from Singletons in future versions, there are lots of issues with those in Unity as opposed to normal singletons.

**Comment by StephenHodgson** [comment]
> it goes against the recommended Unity initialization guidelines.

Not sure which ones you mean. Care to explain a bit more?

Yeah I've never been a fan of Singletons in Unity because of the nondeterministic nature of how events are called on GameObjects there's no real way to control how things like this.  MRTK vNEXT features a single entry point into the core logic that has a lot more control over how the internals are setup and how initialization occurs.

**Comment by StephenHodgson** [comment]
> Depending on how the systems are originated in the hierarchy, it is possible that EventSystem.

If this is the case, then simply moving the input manager prefab to the top should in theory fix the issue, correct?

**Comment by arctop-sk** [comment]
> Not sure which ones you mean. Care to explain a bit more?

Unity recommends that if you want to initialize data in a component/system that has a dependency on another component/system being available that you do so at start and not in Awake()/OnEnable(), exactly from these reasons, where order of execution in unknown and not guaranteed. Awake()/OnEnable() should be used to initialize only non depended internals.

I can't point you to the resource, but that is something I learned a very very long time ago ;)

> Depending on how the systems are originated in the hierarchy, it is possible that EventSystem.

Actually exactly the opposite, you need the EventSystem to be initialized prior to InputManager. And relaying on hierarchy order is just bad practice.

**Comment by arctop-sk** [comment]
I agree this is an issue. In my projects I have moved away from singletons completely, and relay a lot more on assignment of dependencies in the inspector, which eliminates a lot of GetComponent calls as well, even made a drawer to automate the process, https://github.com/shkalash/InjectComponentAttribute

I also use ScriptableObjects way more which helps as well. 

I’m not using the menu as I have a lighter version of the prefabs for my own projects. For my use cases, Initialzing in Start() solves the issue. 

I’m happy that vNext is moving away from Singletons. I understand the difficulty in providing a catch all solution. Ultimately I wanted to raise this issue for visibility. A lazy initializition might also fit here, but again, hard to cover all cases. 

Appreciate the responses, I’ll close the issue now.

**Comment by StephenHodgson** [comment]
No worries!  I'm glad you brought the discussion up so other people could get visibility on this as well.  Discussions like this help keep a good record of why certain decisions were made and helps others understand the direction the project is going.

Hopefully we'll get vNEXT Beta ready soon so that we can move on to bigger and better things!

We've def took heavily to the ScriptableObjects in vNEXT.  Take a look at our implementation on that branch and provide feedback. I'd like to hear your thoughts.

**Comment by arctop-sk** [comment]
> Take a look at our implementation on that branch and provide feedback

Will do, when things calm down a bit ;)
