### ISSUE TITLE
How to deploy a IL2CPP Unity 2018.2 build ?

### ISSUE THREAD

**Issue by ThomasAstrakhan** [Microsoft/MixedRealityToolkit-Unity#2419]
## Overview

I did a build with Unity 2018.2 with IL2CPP (because it says that .Net is deprecated)

I don't have the "device" button in the "Start" button in Visual Studio 2017

![image](https://user-images.githubusercontent.com/39410322/42441162-e7408c9e-8367-11e8-9e3a-d5652df440f7.png)

## Expected Behavior

Have the "Device" button to deploy on the hololens

## Actual Behavior

There is only a "Start"

## Unity Editor Version

2018.2.0b11

## Mixed Reality Toolkit Release Version

May 2018

**Comment by isurfraz** [comment]
Do it via the build menu? This is not an issue with this repo, but rather an issue with usage of Visual Studio, close the issue.

**Comment by ThomasAstrakhan** [comment]
@isurfraz how can I deploy a project in the build menu direct to the hololens ?? There is of course a Deploy Button but it installs the App on my computer, not on the hololens.

**Comment by isurfraz** [comment]
@ThomasAstrakhan this is all covered in the basics of the hololens tutorial: https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101

Further more, building and deploying from visual studio is one of the most basic skills you use when developing apps and it appears you have not done any tutorials if you do not know this yet. I recommend starting with more basic tutorials before starting on hololens development.

**Comment by ThomasAstrakhan** [comment]
@isurfraz I already build many hololens app with Unity 2018.1.0 with .Net

and the tutorial says "[click the dropdown and chose Device](https://youtu.be/PmtZGjYFroY?t=261)" which work when building with .net but not with IL2CPP

**Comment by isurfraz** [comment]
@ThomasAstrakhan Could you at least **read** the link I posted before commenting? 

From the first couple of pages:

"Using the top toolbar in Visual Studio, change the target from Debug to Release and from ARM to X86.
Click on the arrow next to the Device button, and select Remote Machine to deploy over Wi-Fi.
Set the Address to the name or IP address of your HoloLens. If you do not know your device IP address, look in Settings > Network & Internet > Advanced Options or ask Cortana "Hey Cortana, What's my IP address?"
If the HoloLens is attached over USB, you may instead select Device to deploy over USB.
Leave the Authentication Mode set to Universal.
Click Select
Click Debug > Start Without debugging or press Ctrl + F5. If this is the first time deploying to your device, you will need to pair it with Visual Studio.
The Origami project will now build, deploy to your HoloLens, and then run.
Put on your HoloLens and look around to see your new holograms."

If you had gone through any of the tutorials you would have worked this out. I really dont understand why one would come and file an issue on here without attempting even the basic tutorials. 

I hope this has helped you, but either way your issue is not that the software does not work properly but that you do not know how to use visual studio properly, so I recommend closing this issue so it does not complicate things for the developers, and instead invest some time in some basic visual studio building + deploying tutorials. 

I recommend starting with: https://msdn.microsoft.com/en-us/library/cyz1h6zd.aspx

If you have further issues regarding this, it would be better to post them on unity forums, stack overflow or something similar rather than filing a bug report immediatly.

**Comment by isurfraz** [comment]
@ThomasAstrakhan You can also do Build > Build Solution and thenBuild > Deploy solution. this will build with the chosen settings. deploy will deploy the build to the connected device by cable or wifi depending on what is selected.

You can go to debug > options at the bottom and then select the second option "debugging", on there there will be a field "machine name", enter your IP address in there and select remote machine and it will set it to go over wifi.

Good luck, If this is not clear enough then I am sorry but you are in need of a full beginners visual studio tutorial and this is not the place for it.

**Comment by ThomasAstrakhan** [comment]
Thank you.
I can't do this :

> Using the top toolbar in Visual Studio, change the target from Debug to Release and from ARM to X86.
> Click on the arrow next to the Device button, and select Remote Machine to deploy over Wi-Fi.

Because if you check my screenshot, there is no arrow next to de device button.

But I will try this :

> You can go to debug > options at the bottom and then select the second option "debugging", on there there will be a field "machine name", enter your IP address in there and select remote machine and it will set it to go over wifi.

**Comment by keveleigh** [comment]
I'm unable to repro this in the latest 2018.2. Can you try deleting your built solution and rebuilding from scratch?

Built IL2CPP in Unity 2018.2.0f2
![image](https://user-images.githubusercontent.com/3580640/42606311-bff3f092-8531-11e8-888d-51c94deb8c6b.png)

**Comment by StephenHodgson** [comment]
Not related to the MRTK, going to close this issue. You guys may carry on and discuss as needed.

**Comment by MRCalderon3D** [comment]
Maybe you are trying to run the wrong project, change the default project
in the Solution Explorer.

**Comment by StephenHodgson** [comment]
You could also be missing components in visual studio, (although, vs is pretty good about installing missing stuff)

**Comment by dbr4389** [comment]
Sorry for the lack of information i was giving. But I found a workaround.

When I build using IL2CPP and use **Remote Connection** there is no popup where I can put in the ip-address from the hololens. 
![2018-10-12_11-45-32](https://user-images.githubusercontent.com/1933794/46862115-786edf80-ce14-11e8-80a9-1cefd777fb8d.gif)

When I build using .NET and click on **Remote Connection** there is this popup to put in the ip.
![2018-10-12_11-49-05](https://user-images.githubusercontent.com/1933794/46862293-d56a9580-ce14-11e8-82a7-563f27b4a7ae.gif)

I've always used .NET with remote connection to build but now it's being deprecated and I wanted to switch to IL2CPP.

the workaround is very easy I found out you can also connect your hololens to the pc with a wire and switch to **Device**.

**Comment by StephenHodgson** [comment]
You should still be able to open the project properties and manually add the remote machine address. Likely this is a bug with vs.

**Comment by MasayaTodoroki** [comment]
Hi all,
did anyone find a solution to OP, i'm trying to deploy over USB but device is not showing, i've changed it to release and x86 but these are my only options

![image](https://user-images.githubusercontent.com/32248662/46984867-082dca00-d144-11e8-847a-db9e24d957e0.png)

**Comment by IzzyGomezThree** [comment]
@ThomasAstrakhan Did you ever resolve the issue where you couldn't find the "device" button in the "Start" button in Visual Studio 2017?

I am following the Microsoft Hololens Academy tutorials, and I am running into the same issue as you.

Thank you in advance for your help!

**Comment by ThomasAstrakhan** [comment]
@IzzyGomezThree did you try the @robinerd solution ?

**Comment by B-e-n-j-a-m-i-n-S-a-v-a-g-e** [comment]
Could it be that you're running the Visual Studio studio in the main directory and not the one in the actual build folder? 

After building in Unity, when the window pops up, be sure to go into the actual folder (the one you named upon build) and run the Visual Studio solution located there.

**Comment by amit7010** [comment]
Hi
I'm getting this error while deploying. It's building sucessfully but fails to deploy.
![image](https://user-images.githubusercontent.com/22027941/58798804-37387380-8621-11e9-99b8-2cf9e269a101.png)


I'm using Visual Studio 2017, unity 2018.4
