### ISSUE TITLE
vNext Task: Core networking scaffolding

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#2722]
# Overview
Implementation of interfaces, types, classes that make up the networking abstraction (#2721).

# Requirements
* Interfaces
* Enumerations
* Class skeletons

# Acceptance Criteria
- [ ] Create all defined
    - [ ] Interfaces
    - [ ] Enumerations
    - [ ] Classes (event data, etc)
- [ ] Baseline / example implementation based on one or more of
    - [ ] Existing HoloToolkit functionality (ex: sharing with unet)
    - [ ] Community sharing and communication systems

**Comment by IsaacSurfraz** [comment]
is this actually going to be in the release version? I know UNET is unsupported but mirror https://github.com/vis2k/Mirror is a 1:1 working implementation of UNET that is supported, allows in place updates from UNET to mirror within 5 mins and allows users **who have already created architecture using the sharing with unet example to continue functioning**. It worries me that the sharing with unet is seemingly abandoned despite there being clear alternatives, and wish your team had signposted that it would be removed very very early on (such as may/june last year when many of us were asking questions about it).

We have managed to update the HTK to use mirror and its flawless (actually performs better than UNET, and because its code is accessible we have been able to update networktransform to use localpositon meaning we can use all the built in components for networking) and having this in MRTK will provide an update path for people that will otherwise be stuck on HTK and therefore stuck being **unable to purchase and update to HoloLens 2 headsets which I am sure is something you dont want at Microsoft**

**Comment by Yoyozilla** [comment]
Sharing will be a standalone component in a separate repo. Please join the public sharing weekly shiproom for details :)
