### ISSUE TITLE
vNEXT: WMR Controller raises duplicate pointer events.

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2738]
Overview
---
Windows Mixed Reality devices raise duplicate pointer up/down/clicked events on HoloLens.

Need to verify on immersive headset.

**Comment by keveleigh** [comment]
This is probably because the GazePointer doesn't filter for a specific action like the other pointers do. Since it'll likely be the only pointer in the scene when it's active, I let all actions go across it, and then the filtering would happen on the handler side. I'm happy to discuss that decision and figure out if it was the right one.

In this case, the two pointer events are from `TriggerTouch` (when select pressed amount > 0) and `Select`.

This is somewhat related to our conversation at the Summit about the pointer events and whether we need them.

**Comment by StephenHodgson** [comment]
I removed all the raise pointer events from any class that's outside the device managers

**Comment by keveleigh** [comment]
In your PR? I'm slightly confused here. Is this issue opened on a PR or mrtk_development? The area in the issue to denote that is missing.

**Comment by StephenHodgson** [comment]
Closing this as it's not relevant to dev atm.

**Comment by StephenHodgson** [comment]
> In this case, the two pointer events are from TriggerTouch (when select pressed amount > 0) and Select.

You're correct. Thanks!
