### ISSUE TITLE
TwoHandsManipulation acts weird when One Hand Movement disabled.

### ISSUE THREAD

**Issue by rafek** [Microsoft/MixedRealityToolkit-Unity#2797]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
HoloToolkit

**Describe the bug**
Per my discovery I shared on Slack. If it hasn't been brought yet (that would surprise me as it's easy to reproduce) I think  there's a bug in TwoHand manipulation script. It happens when one disables One Hand Movement for the script, leaving the object being only manipulatable by two hands. Following is the video I've just recorded:

https://www.dropbox.com/s/oi1q7jy3u7f4idr/two_hands_manipulation_bug.mp4?dl=0

**To Reproduce**
1. Run the example from MRTH (Two Hands Manipulation scene)
2. Disable "One Hand Movement" for every game object
3. Play with them for a while..

**Expected behavior**
Expected is two hands manipulation working properly over time.

**Actual behavior**
Two hands manipulation is broken after a while.

**Additional context**
In the referenced video, problem starts occurring at 1:07.

**Comment by JemisaR** [comment]
I've encountered the same bug and I really wanted this to work, so I fixed it myself. When I troubleshooted the bug, I noticed the issue wasn't with playing around with the game objects. It happened when you tapped and held your hand (both or one) and then moved your gaze away or into another game object.

This should trigger OnSourceLost() method, but it never did as the GameObject wasn't added to the InputManager when One Hand Movement was disabled. One Hand Movement relied completely on OnInputUp() to work in the older version.

Which in turn caused one extra hand location to stay in memory, which in turn allowed you to do Two Hand Manipulations with only one hand (as the application thought there was two of them present). And if you did this with two hands, then the application thought you had three hands active. Because the GameObject was added to the InputManager when two hands were used, the count never went higher than three.

So I implemented a way to add the GameObject to InputManager when One Hand Movement is disabled. That was the simplest way fix this (at least to me).

I have tested the code mainly with Scale manipulation enabled and One Hand Movement disabled, as that is the scenario I wanted it to work in. Thus, I am not sure if I have broken something when it comes to other modes.

I uploaded my version as a public gist [TwoHandManipulatable](https://gist.github.com/JemisaR/80178d6f120fa01b2d1b462ac32b3bb8), so it can just be copied and pasted over the old code.

### What I added/edited

- Two additional methods at the end of file: CheckIfInputHandlerIsRequired and CheckIfInputHanderShouldBeRemoved.
- Modified methods OnManipulationStarted and OnManipulationEnded to not add anything to InputManager when One Hand Movement is disabled.
- Modified InvokeStateUpdateFunctions() =>  CheckIfInputHandlerIsRequired() is called when ManipulationMode is None (Line 327 in my version).
- Modified methods OnInputUp and OnSourceLost to call CheckIfInputHanderShouldBeRemoved() at the end.
- I left the Debug.Logs that I used to debug my code, however they are commented out so you don't have to do it yourself.
- There is a private bool variable addedToInputManager to determine if the actions inside CheckIfInputHandlerIsRequired() or CheckIfInputHanderShouldBeRemoved() should be called.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
