### ISSUE TITLE
Focus Provider not returning correct focused object for event

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#2918]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Describe the bug**
When we handle events in the `MixedRealityInputManager` we don't get the focused object for our event properly when the pointer falls back to gaze.

This affects any input source that does not assign pointers when created.

**Expected behavior**
An event handled with an input source that does not have pointers, should use the gaze pointer and its focused object to handle the event

**Actual behavior**
No focused object is returned nor used, so the gaze input fails.

**Comment by keveleigh** [comment]
I believe the issue largely lies here: https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs#L288.

The gaze pointer has its own input source and this will never match the input source of the event, so it's never returned by this method and thus the focused object is never returned.

This method also has an issue if we have multiple pointers with the same input source, since it'll just return the pointer that shows up first matching the ID instead of one specifically designated for focus / the type of event (like pointing vs teleport).

It seems like, since each input source knows about its pointers, there's probably a better way to figure out the correct pointer / focused object instead of needing some other script to iterate through all registered pointers from all sources.

I was pretty sure there was a different issue about this recently (and had been thinking about how to best fix it), but I can't seem to find it anymore.

**Comment by StephenHodgson** [comment]
I'm thinking we should return all the pointers and their focused objects, but I'm not sure how to do it without incurring any allocations.
