### ISSUE TITLE
Add a 0-1.0 Transparency to MRTK Standard Shader for ease of use.

### ISSUE THREAD

**Issue by larsonmattr** [Microsoft/MixedRealityToolkit-Unity#2969]
**Does this affect the legacy HoloToolkit (master) or the Mixed Reality Toolkit (mrtk_release)?**
Mixed Reality Toolkit

**Is your feature request related to a problem? Please describe.**
It's a common use case to want to make a partially transparent material, but to do so with the MRTK Standard Shader requires us to use a texture that has an alpha channel set to a transparency of 0-1.0. This requires a developer to go to an image editor to change the percent transparency of an object and to import a texture just for changing an alpha %.

**Describe the solution you'd like**
It would be very much easier if there was an "Transparency" setting from 0-1.0 taking a float value that is a publicly modifiable value for the MRTK Standard Shader, changeable via the Inspector for a Material that uses this shader.

**Describe alternatives you've considered**
Currently, I am creating small white textures of 256x256, etc with an alpha value via Gimp, then importing these into Unity, then setting this in the Material. It's a pain.

**Additional context**
None

**Comment by Cameron-Micka** [comment]
Hi @larsonmattr thank you for filing this issue. Does changing the alpha value of the color box (to the right of the albedo property) solve your issue? (Also make sure your rendering mode is set to one of the transparent ones.)

**Comment by larsonmattr** [comment]
@Cameron-Micka : thanks! The alpha value in the color selector does change the transparency alpha, when the Rendering Mode is transparent. I may have tried this but was still Rendering Mode Opaque or just missed it.

**Comment by Cameron-Micka** [comment]
Awesome! I'm glad to hear that worked for you.

**Comment by dpurgin** [comment]
The problem is though if you want to update opacity dynamically (for example, depending on object's position). Changing material color didn't work for me for some reason. Although the Unity object inspector shows that the material changes in Play mode, the "Albedo" remains the same

**Comment by Cameron-Micka** [comment]
Hi @dpurgin! The process you described should work. Can you check to make sure your rendering mode is not Opaque (something like Transparent would work best for your scenario):

![image](https://user-images.githubusercontent.com/13305729/58818613-2e28b180-85e3-11e9-8f9a-874cd7bce6b4.png)

**Comment by dpurgin** [comment]
Hey @Cameron-Micka, thanks a lot for your reply! I couldn't check it out earlier because I've just got back to that project recently. It appears that my shader has the same settings as yours: 

![image](https://user-images.githubusercontent.com/8401313/60293182-01846300-991f-11e9-8e3a-bf9e6cb4f067.png)

It does work in Editor if setting the alpha value with the picker in Properties but as soon as I start the scene in the "Game" Mode and set the opacity programmatically, my objects remain opaque. 

I'm not an expert in shader programming but I've tried to look into the shader program and it seems that the alpha channel setting is there in the beginning but is somehow gone by the end of the program. 

I ended up cloning the existing shader and added my own Alpha property, so that it overrides anything that is computed by the shader in the end. 

[MyButtonShader.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3336305/MyButtonShader.zip)

**Comment by Cameron-Micka** [comment]
@dpurgin Hmm, that sounds like some other script may be overriding the values you are settings. You mentined the material is on a button, by chance is there an Interactable script on your button? The Interactable class will often override material values.

If you have a small repo project I can check that out too.
