### ISSUE TITLE
controller visualization for openvr

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#3332]
## Overview
Currently, the only mechanism to visualize a specific controller model is for that model to be baked into the application as an obj, fbx, etc. and referenced in the appropriate profile.

We should investigate / implement a means of acquiring the appropriate models from the OpenVR runtime.

**Comment by Yoyozilla** [comment]
Is this not done?

**Comment by keveleigh** [comment]
@yoyozilla It's not

**Comment by Alexees** [comment]
Is this even true? The WindowsMixedRealityController is constructing its representation in code:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ac2b8108f85aaef32b7f1d6022c1af1d19b154b2/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs#L259

**Comment by Le0nLyn** [comment]
I believe this feature is still not done on v2.0.0 from my testing, but I have a more specific scenario which may have a workaround?
I'm working with a WMR headset in an OpenVR environment because some of my libraries cannot be built to UWP. Is there a way to get the old MotionControllerVisualizer script working in v2.0.0 to visualize my WMR controllers in editor and build?

**Comment by keveleigh** [comment]
@Le0nLyn Using OpenVR, it's unfortunately not as easy as importing the old MotionControllerVisualizer script. We'll need to use some of the [OpenVR headers](https://github.com/ValveSoftware/openvr/blob/master/headers/openvr_api.cs) to access specific APIs
