### ISSUE TITLE
It's unclear how to setup an MRTK project from the github landing page

### ISSUE THREAD

**Issue by chrisfromwork** [microsoft/MixedRealityToolkit-Unity#3336]
In my opinion, the MRTK landing page doesn't contain enough information to understand how to setup a new MRTK project.

1) It's not obvious what purpose 'Building the Artifacts" fulfills. Are these steps required? What do they achieve?
2) How is the MRTK added to a project? Are users expected to just include/import the default assets folder? Should the MRTK be useable after running through the 'Building the Artifacts' step?
3) What examples currently exist for the MRTK? Stating that examples will/do exist somewhere in a development branch without a direct link doesn't build confidence/may generate frustration for new users.

**Comment by genereddick** [comment]
I'm just getting trying to get up to speed on the vNext branch and I would like to second this concern. I thought it is best to record it now while I am in a minor state of confusion transitioning to the new branch and the issues are fresh. 

In addition to @chrisfromwork 's issues, I stumbled on the following:

1. What is the expected behavior when running in the Unity editor. When running the MRTK release branch in the editor it works with mouse, keyboard, etc. but in vNext I was only able to get controller input when in Holographic Emulation mode. Is Holographic Emulation mode (or deploying to a device required)? 

2. No mouse controller input, even in Holographic Emulation mode. Using the mouse was a big part of testing minor changes. It would be a shame to lose it, though I'm still uncertain if this is by design or a configuration issue on my part. Has the mouse behavior from the previous version been removed?

3. While there are a lot of words around the config files, a few examples of how you might make changes to achieve specific goals would be useful, as well as where and how the files hook into the code. While I think this system is great, it feels a bit opaque in where and how it interacts with the code.

**Comment by ManasviSrivastava** [comment]
Hello,

I have a few queries regarding UWP app development for HoloLens. Below are the questions:

1. Does MRTK default config profile support HoloLens v1?
2. In Example demos, the interactions (Gesture, Air-Tap, Gaze) in the scenes are not working with HoloLens v1. 
3. Are there any other profile settings required to make them work?
4. How can we map input actions like gaze and hand gestures for HoloLens v1?
5. Can we have more in-depth configuration guides for each of the features?
6. Is there any link available for detailed API documentation?

Can anyone please provide the assistance in this regard?

Thanks!
