### ISSUE TITLE
[Question] TrackedPoseDriver support?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3474]
I found this blog post and since it promises a fair amount of cross platform work on Unity's side, I was wondering if vNext would make use of the components or run its own solution completely?

https://blogs.unity3d.com/2018/11/22/multi-platform-vr-features-in-2018-3/?_ga=2.50446189.535792211.1550582451-1531890405.1524821964

**Comment by SimonDarksideJ** [comment]
VNext provides an alternative to the Unity features (such as ARFoundation) and provides more capabilities that that which are built in to Unity.
Unity's "TrackedPoseDriver" is akin to the vNext Controller pose synchroniser, although we implement in code instead of a prefab or new component and get the data directly from the controller.

In other words, we already do :D 

If you're happy with this answer, please close the query but happy to chat further

**Comment by Alexees** [comment]
That sounds interesting. Thanks for the quick reply.
