### ISSUE TITLE
AppBar always active when object is inactive.

### ISSUE THREAD

**Issue by Mustaval** [microsoft/MixedRealityToolkit-Unity#3523]
I'm having an issue with AppBar being active while the gameobject ot is attached to is inactive within the hololens app.  I have messed with display types on the AppBar prefab but just unsure how to resolve this issue, I'm sure it's simple but can please guide me in the right direction.

## Expected Behavioe
Whenever object is set to inactive I would like the appbar to disappear with the hologram.

## Actual Behavior
Appbar remains on screen win the gameobject is set to inactive.  I have a screen set up with back buttons to go from one screen to another and the appbar remains on the screen going between screens.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.2.18

**Comment by PJBowron** [comment]
It's been about 9 months since I was looking into AppBar & BoundingBox, but if I remember correctly the lifecycle management of the current version isn't really set up for doing any programmatically controlled re-entrancy, re-use or dynamic management of the appbar.

It's staying active because it's instantiated outside of the target object's hierarchy, right? For now, you might need to modify AppBar and/or BoundingBoxRig to either instantiate AppBar under your target object, or to provide you with a handle to the instantiated AppBar so that you can activate/deactivate it yourself.

**Comment by wiwei** [comment]
Closing out an old issue - I think that in this particular case it seems like what you want to accomplish could just be done by what @PJBowron mentioned a long time back (i.e. just nest the AppBar under some container game object that contains both the target object and the app bar).
