### ISSUE TITLE
ManipulationHandler is completely broken

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#3542]
## Overview
Checking out the ManipulationExample scene I found that the manipulations are unusable with the Mixed Reality Motion Controllers:

- Selecting any of the Objects teleports them to somewhere near of the actual gaze position instead of keeping it in place.

- Moving them around does not behave like you would expect in the least (just try it and you'll see)

- Manipulating them with two controllers involves head rotation too. Just holding still and turning the head rotates the object. This should be handled by the hands only.

## Expected Behavior
Manipulation just works

## Actual Behavior
Manipulation does not work very good

## Steps to reproduce
- Open the ManipulationExample scene
- Play around with the objects

## Unity Editor Version
2018.3.6f1

## Mixed Reality Toolkit Release Version
mrtk_development

**Comment by julenka** [comment]
This should be improved in the latest MRTK_development branch, though some specific issues may still exist. Closing this so that we can re-open bugs with more specific issues. Alexees, if you run into problems with the latest ManipulationHandler, please file a new issue, one issue per behavior problem. It will make it much easier to fix if we break the problem into smaller sub-problems.
