### ISSUE TITLE
Iphone doesn't show the ArUco Marker

### ISSUE THREAD

**Issue by pacearthur** [microsoft/MixedRealityToolkit-Unity#3578]
## Overview
Simply attempting to run spectator view example scene and link the iPad to the hololens.
## Expected Behavior
Iphone show ArUco marker and link to the hololens
## Actual Behavior
Iphone doesn't show the marker, there is just the text line "Show to the hololens" but nothing appears above it.
## Steps to reproduce
Following the instructions from spectator preview setup tutorial
https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view

## Unity Editor Version
Using version 2017.4.3 of unity to build iOS and UWP Builds.
## Mixed Reality Toolkit Release Version
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases/tag/2017.4.3.0

**Comment by chrisfromwork** [comment]
Hello @pacearthur 

Based on your steps to reproduce, it sounds like you are using the HoloToolkit Spectator View Preview code compared to the new Spectator View refactor code?

If text is showing stating that to show the iPhone to the HoloLens, it sounds like the iPhone is correctly transitioning to the orthographic unity camera for displaying the ArUco visual. Some things that come to mind to check are the following:

1) Right now the ArUco visual is scaled based on screen dpis in order to display the visual with a specific physical size. It looks like a hack already exists to obtain iPhone screen dpis. It may be that the IPad's dpi is getting reported incorrectly in Unity. To determine this, you should be able to break/or log values in the following script (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/Scale3DMarker.cs). Then see if the reported dpi matches your specific iPad version/hardware.

2) Something may be going wrong with marker generation. Most of the marker generation logic should be contained in https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/MarkerGeneration3D/SpectatorViewMarkerGenerator3D.cs. It may be worth assessing whether or not the transition to visible completes correctly here. I think if the shader wasn't getting deployed correctly you would see a pink/purple game object in the scene. But immediately setting _TransitionCompletion to 1 in marker generation (https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/91107545a518aa543fd43376daa9ad420fa03fb9/Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/MarkerGeneration3D/SpectatorViewMarkerGenerator3D.cs#L63) should rule out any transition issues.

**Comment by sebrk** [comment]
Hi @chrisfromwork, I wanted to test the Spectator View but I have similar but different issues which make me wonder if I better hold off because of the in-between state of everything. So far I have tried out feature/SpectatorView branch and the htk-release branch but both have their set of issues. The feature/SpectatorView branch did compile but devices seem not to locate each other properly (testing the example scene).

Could you point me to a known "working" commit or simply tell me what to expect at this point in time? Would love to test this.

**Comment by Yoyozilla** [comment]
Please reopen your issue in our new spectator view GitHub Repo:
https://github.com/Microsoft/MixedReality-spectatorview
