### ISSUE TITLE
WMR Controller Model and Shader no longer included?

### ISSUE THREAD

**Issue by kaedenjames** [microsoft/MixedRealityToolkit-Unity#3595]
## Overview
The newer versions of MRTK-vNext (v2.0.0 Beta 2), don't seem to contain the ability to load the native Controller meshes & shaders. Is there anyway to get these implemented like older versions, or is this something that will be added in the -near- future? The MixedRealityConfigurationGuide states:

> The MRTK does not currently support native SDK's controller models as Unity does not yet provide the capability to load / render gLTF models, which is the default type of models provided by most SDKs. This will be enhanced when this is available.

However, previous versions of the HoloToolKit seemed to have this implemented? I can understand why controllers for Oculus and OpenVR haven't been implemented yet, but why not the WMR ones. Is there anyway to add the older methods into a project running V2.0.0 Beta 2?

## Unity Editor Version
2018.3.7f1
## Mixed Reality Toolkit Release Version
2.0.0 Beta 2

**Comment by chrisfromwork** [comment]
Hello,

We are planning on adding back this functionality. It was originally removed because the underlying gltf loader had a dependency on a newtonsoft json.net library. This dependency often caused version conflicts with different contributors' projects. The first wave of changes is currently in review. It adds a new gltf loader based on Unity's json serializer. A second review should appear shortly to hook back up the wmr controller model loading.

GLTF loader pull request:
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3548

**Comment by keveleigh** [comment]
Was added for WMR in #3673. Please let us know if you see any issues!
