### ISSUE TITLE
AssemblyQualifiedName addition breaks existing local themes

### ISSUE THREAD

**Issue by genereddick** [Microsoft/MixedRealityToolkit-Unity#3672]
## Overview
This change:
https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/99ec5a139b404aba7c24ee545d99b9b4465ab5cc

Which adds an AssemblyQualifiedName field to default Interactable themes in MixedReality.SDK.Features.UX.Interactable.Themes breaks any currently configured local copies of themes.

Not a problem to fix, as it just requires the addition of 

AssemblyQualifiedName: [matching assembly name here]

In actual code this looks something like adding:
    AssemblyQualifiedName: Microsoft.MixedReality.Toolkit.SDK.UX.Interactable.Themes.InteractableAnimatorTheme,
      Microsoft.MixedReality.Toolkit.SDK

to your existing theme files, such as:

    Name: 
    Settings:
    - Name: ScaleOffsetColorTheme
     AssemblyQualifiedName: [assembly name]
     Properties:
     - Name: Scale
     ....

You need to get the correct Assembly name from the original theme source file (this is the MSFT assembly name unless you have also cloned the cs script associated with it).

Just filing this in case anyone else hits this issue.

## Expected Behavior
NA

## Actual Behavior
NA

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.9f1

## Mixed Reality Toolkit Release Version
vNext latest

**Comment by genereddick** [comment]
Hmm, still some issues. I'll fix and resubmit

**Comment by wiwei** [comment]
Thanks for bringing this up - in the original PR that introduced this, I called out that this is something that existing custom themes would have to deal with:

https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3630

FWIW when the change was made, it was clear that it wasn't going to be the end-all solution to the problem here (i.e. ideally we could actually make use of DI or other pattern to avoid having to do manual assembly name enumeration to get a list of class names)

As part of doing vNext, the team is introducing a number of breaking changes, and this is one of them. 

This all being said, if you're seeing issues with the assets and unity files that are checked in (i.e. they didn't update the assembly names) let me us know and we will get those patched up.

I think that we can commit to the long term proper fix being one which doesn't require you to change any of your theme files (that you just happened to change to account for this commit)

**Comment by genereddick** [comment]
@wiwei thanks, I expect it won't hit a lot of people and an easy fix in any case, once you know where to look.
