### ISSUE TITLE
Spatial awareness works in Remote, doesn't on deploy

### ISSUE THREAD

**Issue by shamsfk** [microsoft/MixedRealityToolkit-Unity#3729]
## Overview
New project, Remote from Unity works perfect, the project builds and deploys, but deployed app fails to use spatial awareness.

What could I be doing wrong?
## Expected Behavior
Spatial awareness should work
## Actual Behavior
It doesn't
## Steps to reproduce
Create a new Scene, import MRTK, import Examples, open spatial awareness demo, optionally add a rigid body cube, launch remote to see it working, build the project, deploy with VS2017, see it not working and cube falling to the abyss.

## Unity Editor Version
2018.3.10f1
## Mixed Reality Toolkit Release Version
2.0 Beta 2

**Comment by Alexees** [comment]
@shamsfk define not working. The appearance of the first walls can take a couple of seconds depending on how fast the Hololens identifies it's surroundings. A cube could very well fall through the floor because of that. Waiting a little should show triangularized surfaces by default.
I'd wait with any physics until the lens has spawned at least a couple of surfaces. I'm not sure if there's a callback like "managed to spawn all surfraces I'm aware of exist"

**Comment by davidkline-ms** [comment]
This issue does not repro on HoloLens or HoloLens 2 when i run the spatial awareness demo scene.

Tested:
Unity 2018.4.7
MRTK 2.0.0

If you continue to see this issue on 2.0.0 (or later), please reopen the issue and include specific Unity, MRTK and Operating System version info.

Thanks!
