### ISSUE TITLE
SpectatorView not rendering AR Camera after export with Android Studio

### ISSUE THREAD

**Issue by Avalin** [Microsoft/MixedRealityToolkit-Unity#3762]
## Overview
Exporting MRTK project (with SpectatorView) does not work when exported to Android Studio  and built/run from this.

## Expected Behavior
That the exported project file will built and work as it would when you just build an APK directly from Unity.

## Actual Behavior
App renders a black background and a still picture (2D) of some elements from the app. 
See picture ![SpectatorViewIssue](https://user-images.githubusercontent.com/15669154/55405263-f73e0d00-5559-11e9-8627-0cc66dcbc850.jpg)

## Steps to reproduce
Create project with MRTK and implement spectator view.
Building Android APK will work fine, when exported to Android Studio there will be above illustrated problem. Assuming it might be a problem rendering the camera? 

## Attempted solutions/workarounds
We tried turning the phone on and off again, as we've been suggested that previously. 
Also tried fiddling with the player settings in different combinations, it has previously -by random chance- seemingly worked after the same problem, but even reverting to previous collab version where it _used_ to work, we've run into the same problems. This has been tested on multiple devices:

Samsung Galaxy A5 2017
Samsung Galaxy S8  (Api 28)

Where same problem is prevalent.

## Unity Editor Version
2018.3.10.f

## Mixed Reality Toolkit Release Version
MRTK v2 Beta

**Comment by chrisfromwork** [comment]
@Avalin what commit are you working from? Also, is there a MixedRealityToolkit and MixedRealityPlayspace game object in your scene?

**Comment by stela7** [comment]
Here's the complete step-by-step procedure we did to acquire this problem:

- Downloaded the foundation unitypackage found [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases) for MRTK V2 
- Cloned the latest MRTK-Project found [here](https://github.com/Microsoft/MixedRealityToolkit)
- Checkout this commit from the feature/spectatorView branch: "ffd18248f64d915ef800b6c62830fd22f6a3b8e5" found [here](https://github.com/Microsoft/MixedRealityToolkit/tree/feature/spectatorView)
- Built the MRTK-project, and copied the binaries to our new project into the Assets/Plugins/WSA/x86 folder
- MixedRealityToolkit and MixedRealityPlayspace are added to the scene with all the profiles that are seemingly required
(**Sidenote**: In earlier releases, pressing configure simply added a new MainCamera with the MixedRealityPlayspace. In the current version, it gives an error message when there's no camera already in the scene. I think it would be easier from a user-perspective if the configure just instantiated the camera as it did previously when there's not already a MainCamera in the scene, instead of throwing an error. But still use the existing MainCamera but only if it already exists)
- "Spectator View - HoloLens" is added to the scene, switched to Android through the PlatformSwitcher
- GameObjects needed to be rendered are added to a SceneHierarchy object, which has a "SceneRoot" tag.
- We added a line of code to the Start function in the "SpectatorView.cs" that goes: 
`SceneRoot = GameObject.FindGameObjectWithTag("SceneRoot");`
- Exported this scene to Android Studio
- Built it on aforementioned phones

We tried unplugging them from Android Studio, restarting the device(s), but it still does not seem to render anything but a 2D view - we just tried with a completely fresh project, and there's currently just a still picture of the skybox as seen in below picture:
![Screenshot_20190403-150827_Waterworks 2019](https://user-images.githubusercontent.com/26737314/55482319-8ca5d380-5624-11e9-9e2a-89f7e2457086.jpg)

**Comment by Avalin** [comment]
Here's the complete step-by-step procedure we did to acquire this problem:

- Downloaded the foundation unitypackage found [here](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases) for MRTK V2 
- Cloned the latest MRTK-Project found [here](https://github.com/Microsoft/MixedRealityToolkit)
- Checkout this commit from the feature/spectatorView branch: "ffd18248f64d915ef800b6c62830fd22f6a3b8e5" found [here](https://github.com/Microsoft/MixedRealityToolkit/tree/feature/spectatorView)
- Built the MRTK-project, and copied the binaries to our new project into the Assets/Plugins/WSA/x86 folder
- MixedRealityToolkit and MixedRealityPlayspace are added to the scene with all the profiles that are seemingly required
(**Sidenote**: In earlier releases, pressing configure simply added a new MainCamera with the MixedRealityPlayspace. In the current version, it gives an error message when there's no camera already in the scene. I think it would be easier from a user-perspective if the configure just instantiated the camera as it did previously when there's not already a MainCamera in the scene, instead of throwing an error. But still use the existing MainCamera but only if it already exists)
- "Spectator View - HoloLens" is added to the scene, switched to Android through the PlatformSwitcher
- GameObjects needed to be rendered are added to a SceneHierarchy object, which has a "SceneRoot" tag.
- We added a line of code to the Start function in the "SpectatorView.cs" that goes: 
`SceneRoot = GameObject.FindGameObjectWithTag("SceneRoot");`
- Exported this scene to Android Studio
- Built it on aforementioned phones

We tried unplugging them from Android Studio, restarting the device(s), but it still does not seem to render anything but a 2D view - we just tried with a completely fresh project, and there's currently just a still picture of the skybox as seen in below picture:
![Screenshot_20190403-150827_Waterworks 2019](https://user-images.githubusercontent.com/26737314/55482319-8ca5d380-5624-11e9-9e2a-89f7e2457086.jpg)

**Comment by Yoyozilla** [comment]
should be fixed by Moves camera management into core CameraService #4047.

Please reopen if you hit this issue again
