### ISSUE TITLE
Proposal: Simplify input system interface by removing method versions without handedness

### ISSUE THREAD

**Issue by luis-valverde-ms** [Microsoft/MixedRealityToolkit-Unity#3791]
We currently have two versions for most methods for raising events in IMixedRealityEventSystem, one that receives handedness and one that doesn't. Example:

```
void RaiseOnInputDown(IMixedRealityInputSource source, MixedRealityInputAction inputAction);
void RaiseOnInputDown(IMixedRealityInputSource source, Handedness handedness, MixedRealityInputAction inputAction);
```
I propose removing the version that receives no handedness and change current calls to pass Handedness::None instead.

**Comment by davidkline-ms** [comment]
If this is taken post RC1, we _must_ maintain the non-handedness events as pass-through to the handedness events and mark them as obsolete.

we are at the no breaking changes point.

**Comment by wiwei** [comment]
This sounds like a good thing to do, but I do not believe that this would stop the train. I think that the reality is that there will always be a stream of things we want to improve, but at some point we need to snap to a release in order to get some degree of feedback on that snap (and then obviously iterate on that additional feedback).

To cite a crazy alternative, it's possible that we could ship with this as-is and then customers will tell us that they love the simpler version and really don't care about handedness (which sounds kinda odd to me but hey who knows).

**Comment by wiwei** [comment]
This has been done, closing this out.
