### ISSUE TITLE
When operating Hand Tracking simulation on unity debug,the hand rotate on an axis formed by fingertip.

### ISSUE THREAD

**Issue by TakahiroMiyaura** [Microsoft/MixedRealityToolkit-Unity#3879]
## Overview

When operating Hand Tracking(simulation) on unity debug,the hand rotate on  an axis formed by fingertip.
I propose that the hand rotate on an axis formed by the wrist.
I think that this is easier to use because this is a motion near a human motion.

## Expected Behavior

When operating Hand Tracking simulation on unity debug,the hand rotate on  an axis formed by the wrist.

## Actual Behavior

When operating Hand Tracking simulation on unity debug,the hand rotate on  an axis formed by fingertip.

## Steps to reproduce

1. Open Unity project "MixedRealityToolkit-Unity"
1. Open scene "HandInteractionExamples"
1. Start debug on Unity editor.
1. Operate by Hand Tracking(e.q shift+r,shift+f etc...)

## Unity Editor Version

Unity 2018.3.9f1

## Mixed Reality Toolkit Release Version

Mixed Reality Toolkit 2.0.0-RC1

**Comment by lukastoenneMS** [comment]
IIRC the reason for pivoting on the index finger tip rather than the wrist was that, when using the wrist, it's kind of hard to guess where the actual interaction point is. For testing interactions that can be more important than accurately reproducing human anatomy.

That being said, i would be happy to re-evaluate both variants and see which one works best. I can add a secondary gesture for "SteadyWristPinch" for that purpose.

**Comment by lukastoenneMS** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3916

**Comment by lukastoenneMS** [comment]
Alternative hand sim gesture "PinchSteadyWrist" is now in mrtk_development.
