### ISSUE TITLE
InputSimulationProfile should support pad controller 2nd joystick by default 

### ISSUE THREAD

**Issue by gilbdev** [Microsoft/MixedRealityToolkit-Unity#3892]
## Overview
Currently, when launching a demo with a pad controller in the editor, we can't control cameras

## Expected Behavior
by default for the **DefaultMixedRealityInputSimulationProfile** LookHorizontal and LookVertical should be mapped in respectively 4th Axis and 5th Axis (Invert) in the Input project settings.
If the MRTK can change Input Settings by adding those 2 mappings, it would be great.

## Actual Behavior
LookHorizontal and LookVertical are defined in the DefaultMixedRealityInputSimulationProfile but not in the Input Project Settings.

## Workaround (for those that want it to work as expected)
- Edit > Project Settings... > Input
- Add 2 Axes 
  * LookHorizontal mapped to Joystick Axis, 4th axis
  * LookVertical mapped to Invert, Joystick Axis, 5th axis

## Steps to reproduce
Launch a demo scene, try moving the camera view with a controller right joystick
camera view does not change, needs to use mouse right click + move mouse
 (left joystick for moves works fine)

## Unity Editor Version
2018.3.11f1

## Mixed Reality Toolkit Release Version
v2.0.0-RC1

**Comment by chrisfromwork** [comment]
Hello,

@gilbdev is it possible to get more information on this pad controller? Is it a specific physical device?

**Comment by gilbdev** [comment]
Oh, sorry, i thought i had it specified ...
It's a standard official xboxone controller.

**Comment by StephenHodgson** [comment]
The `DefaultMixedRealityInputSimulationProfile` should be updated to properly utilize InputActions instead of hard coded axis strings

**Comment by lukastoenneMS** [comment]
> 
> 
> The `DefaultMixedRealityInputSimulationProfile` should be updated to properly utilize InputActions instead of hard coded axis strings

I've been looking at input actions and it using them for controlling camera and hand simulation in the editor does not seem feasible:

- We would need to add **a lot** of new actions to the input actions profile:
  * Camera rotation: 2
  * Camera movement: 2
  * Toggle hands: 2 (left/right)
  * Control hands: 2
  * Rotate hands: 3
- The input sim service is an editor-only data provider. The actions profile is a core profile that would have to include the actions nevertheless.
- With each action added the risk of breaking changes increases due to the way action IDs are just indices in the profile. This should be improved in any case, but it makes me want to stay away from input actions in the meantime.
- Using input actions means the service would have to become or create a `InputSystemGlobalListener`

I'd rather keep the input sim service as-is until the input actions system can be reworked somewhat.

**Comment by StephenHodgson** [comment]
That's the whole point of the input actions is to facilitate this sort of thing.

If you're having to add a ton of additional actions it might be beneficial to understand the kinds of data you're trying to convey to the system. Do you _really_ need that many? Should some of that logic be better organized to be closer to the data that it needs? Maybe creating a new data type / axis constraint to convey the hand data?

> Using input actions means the service would have to become or create a `InputSystemGlobalListener`

And what's wrong with that? If that's a problem, why aren't you just sending the messages directly to the game object?

> The input sim service is an editor-only data provider. The actions profile is a core profile that would have to include the actions nevertheless.

I don't understand the problem here. Might need more clarification.

> With each action added the risk of breaking changes increases due to the way action IDs are just indices in the profile. This should be improved in any case, but it makes me want to stay away from input actions in the meantime.

That's unrelated to the task at hand, but I agree, maybe that could be improved upon. index id was chosen for performance reasons.  One thing to note is that the input action profiles are one of the few profiles we didn't intend to be able to be changed at runtime for that specific reason.

It's the controller mapping that should be swappable and really where the magic happens in relation to what you're trying to accomplish.

**Comment by lukastoenneMS** [comment]
I've pushed a fix for the original issue of gamepad joystick axes for camera rotation.

I'd like to leave the question of using InputActions for input simulation for another time.
