### ISSUE TITLE
[Question] Where is the MRTK v2 RC1 branch?

### ISSUE THREAD

**Issue by Alexees** [Microsoft/MixedRealityToolkit-Unity#3902]
I like to stay up to date or be able to fork the repo to help with fixing bugs I find during development.
Where is the RC1 branch, I only found the archive download section.

**Comment by wiwei** [comment]
We're currently in the process of drafting up a more formal set of guidelines for how development is done, and part of this will involve restructuring our branches.

For RC1 we have a branch:
https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/prerelease/2019_rc1

However I wouldn't necessarily expect that binaries/packages will get rebuilt if changes go into that branch. It's primarily if we wanted to fix something and people are consuming the code directly (rather than downloading the packages).

For contributions going forward, it would be best to stick to mrtk_development.

But again, stay tuned for more updates on the other stuff....

**Comment by Alexees** [comment]
@wiwei sorry to post on a closed thread, but my remotes do no list that and according to the clone link it's the same as any other. There's a couple more branches I do not see. How do I make them visible? I'm using Sourcetree, is that a problem? I only see the features subdirectory

**Comment by Alexees** [comment]
Ok, nevermind, I did not configure the upstream correctly
