### ISSUE TITLE
Main Camera is changing Clear Flags during runtime

### ISSUE THREAD

**Issue by DaRockJaeger** [Microsoft/MixedRealityToolkit-Unity#3948]
## Overview
When I change the Clear Flags of the Main Camera to Solid Color, and press Play in Unity, the Main Camera set Clear Flags on "Skybox" again.

## Expected Behavior
MainCamera should keep Clear Flags on "Solid Color" during runtime

## Actual Behavior
Main Camera sets Clear Flags to Skybox during runtime

## Steps to reproduce
1. Insert Main Camera using Mixed-Reality-Toolkit -> Add to Scene and Configure
2. Set Main Camerea's Clear Flags from Skybox to Solid Color
3. Press Play in Unity, and check Main Camera's Clear Flags.
## Unity Editor Version
Unity 2018.3.12f1

## Mixed Reality Toolkit Release Version
2.0.0 RC1

**Comment by DaRockJaeger** [comment]
With Main Camera, I mean the Camera that is created when using in menu:
 Mixed-Reality-Toolkit -> Add to Scene and Configure

**Comment by gilbdev** [comment]
You need to edit the Camera Profile Settings instead of directly setting up the Camera.
 
- edit the MixedRealityToolkit
- access the Caemra Settings from here (you can clone the Camera Profile if you want to change it)

i guess it's done this way to be able to make the same application for different device (both AR with transparent display, and VR with Opaque ones)

**Comment by davidkline-ms** [comment]
> i guess it's done this way to be able to make the same application for different device (both AR with transparent display, and VR with Opaque ones)

Correct.

**Comment by wiwei** [comment]
Closing down this question, as it looks like it has been addressed.
