### ISSUE TITLE
No formal parameter for scope in Unity 2019.2.0a11 with DOTS

### ISSUE THREAD

**Issue by quakeulf** [Microsoft/MixedRealityToolkit-Unity#3951]
## Overview
When inporting the latest MRTK-release from here:
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases

...the sole console puts out this:

Assets\MixedRealityToolkit\Inspectors\MixedRealityPreferences.cs(70,32): error CS7036: There is no argument given that corresponds to the required formal parameter 'scopes' of 'SettingsProvider.SettingsProvider(string, SettingsScope, IEnumerable<string>)'

## Expected Behavior
This should just work. No issues at all.

## Actual Behavior
Can't do anything because this is a compiler error.

## Steps to reproduce
0. Install Unity 2019.2.0a11.

1. Import:
https://github.com/Microsoft/MixedRealityToolkit-Unity/releases

2. Import:
https://github.com/Unity-Technologies/EntityComponentSystemSamples

## Unity Editor Version
Unity 2019.2.0a11

## Mixed Reality Toolkit Release Version
MRTK v2 RC1

**Comment by quakeulf** [comment]
This can be fixed by making:
            **var provider = new SettingsProvider("Project/MRTK")**

Into:
            **var provider = new SettingsProvider("Project/MRTK", SettingsScope.Project)**

**Comment by StephenHodgson** [comment]
Actually I think using the `SettingsScope.User` makes more sense for the mrtk settings to show up in preferences window.

**Comment by quakeulf** [comment]
Could this be added to the code in the repository?

**Comment by wiwei** [comment]
This is an action item on us where we're working through the best model of supporting 2019.1. Even though our docs say that we support 2018.3.x+, in reality we've been focused entirely on the current stable version of unity (i.e. 2018.3.x, not 2019.x).

There's also figuring out ARM64 support and other ramifications of 2019 that we're looking at holistically.

In this particular case going with SettingsScope.Project I believe keeps it in the old place it was at due to how defaults worked with 2018:

https://github.com/Unity-Technologies/UnityCsReference/blob/2018.3/Editor/Mono/Settings/SettingsProvider.cs

Going with .User would change it up for current users (i.e. disrupt their flow based on their current experiences).

In general this change seems safe to me.

**Comment by StephenHodgson** [comment]
> Going with .User would change it up for current users (i.e. disrupt their flow based on their current experiences).

Considering when I first wrote it it was in preferences, I thing that it's already been disrupted.
