### ISSUE TITLE
Uniy LTS crash with MRTK

### ISSUE THREAD

**Issue by KeurKeur** [Microsoft/MixedRealityToolkit-Unity#3960]
## Overview
Hello hello, I wanted to try the MRTK for a project and I have to use a LTS version of Unity but unity crash (I mean the application quit and an unity bug reporter window appear).

## Expected Behavior
Unity not crash.

## Actual Behavior
Unity crash and bug reporter window appear.

## Steps to reproduce
_(Links to sample github project preferred)_
Right click, import package, custom package

## Unity Editor Version
Unity 2017.4.25f1 LTS.

## Mixed Reality Toolkit Release Version
Microsoft Mixed Reality Toolkit v2.0.0 RC1

Thank you, I hope it will be fix for a LTS version.

**Comment by wiwei** [comment]
Thanks for filing an issue!

MRTK V2 requires Unity 2018.3.x (which I think will become the LTS "soonish" following Unity's LTS roadmap here:

https://blogs.unity3d.com/2018/04/09/new-plans-for-unity-releases-introducing-the-tech-and-long-term-support-lts-streams/)

You'll need to upgrade to the latest 2018 Unity in order to use this.
