### ISSUE TITLE
Motion Controller button assignment changed in new MRTK version

### ISSUE THREAD

**Issue by frangagn** [microsoft/MixedRealityToolkit-Unity#3994]
## Describe the problem

Working with past version of the MRTK and used this guide (https://docs.microsoft.com/en-us/windows/mixed-reality/gestures-and-motion-controllers-in-unity) to determine with buttons and axies to track for my user interface. All of a sudden, after installing Unity 2019.1.0f2 and latest commit of MRTK ( 9c57fbb ) the button assignment do not work the same.

## Describe the solution you'd like

Either change the button assignment to the original documented version, or provide documentation on what the new assignment are.

In the mean time, a time saver for developers would be to know which button changed where instead of forcing us to search blindly for it.

**Comment by frangagn** [comment]
For the record, and for those looking for them:

left Grab button is still 4
left Touchpad Pressed is now button 8
left Stick pressed is now button 18
left Trigger pressed is button 14
left Menu pressed is button 6

**Comment by keveleigh** [comment]
I'm not sure I understand the ask here. You shouldn't need to know about the specific axis mappings, as they're mapped behind the scenes to MRTK input actions.

Do the changed assignments cause the buttons / controller to behave incorrectly?

**Comment by keveleigh** [comment]
As far as the mappings you linked above: those mappings are specific to WMR controllers running on Windows Mixed Reality. In the MRTK, we use the `InteractionManager` APIs instead of those input axes.

If you're using WMR controllers on OpenVR (which is the only place we map WMR controllers to input axes in the MRTK), you'll want to look at the far right column on this page: https://docs.unity3d.com/Manual/xr_input.html.

It's a slightly different mapping between WMR and OpenVR. Both are present in that chart, if you want to compare (`WMR` vs `OpenVR (WMR)`)

Note: I just noticed that touchpad click, touchpad touch, and joystick click are incorrect for `WMR` in the table I linked (`OpenVR (WMR)` is correct). They are correct in the one you linked, and I've filed feedback to get it corrected.

**Comment by frangagn** [comment]
I wish to follow the proper MRTK way of interacting, however I can<t find anything on the InteractionManager and the documentation is really unclear. And believe me, I'm not a newbie, with over 30 years of programming all kinds of things in over 15 programming languages and having read mountains of computer and system documentation....

I'm not trying to make excuses. Just that the only clear example I have found through hours of searching was from that Microsoft doc linked above, which I realize is one year old, so this is what I've used to code.... So I guess my ask in this case is to make the documentation clearer. 

Thanks however for your answers!

**Comment by keveleigh** [comment]
Closing, as the Windows docs linked above are specifically for running on Windows MR, while the axis updates made in MRTK were for OpenVR, which has different mappings (linked in the XR Input doc above, which has a table comparing the WMR and OpenVR mappings).
