### ISSUE TITLE
Error on import MRTK RC1

### ISSUE THREAD

**Issue by Yoyozilla** [Microsoft/MixedRealityToolkit-Unity#4036]
![image](https://user-images.githubusercontent.com/40645158/56443277-c1628d80-62a8-11e9-8a37-8a78d60b149f.png)

- Unity Version [e.g. 2018.3.9]
- MRTK Version [RC1]

**Comment by Yoyozilla** [comment]
I realized that when you start a new unity project, and then import MRTK, you are default in the sample scene. If i start a new scene, and re-import MRTK, it fixes the issue

**Comment by julenka** [comment]
Hi Yoyo, thanks for filing an issue! I'm actually unclear on what the bug is here. Could you please provide a more detail about how somebody else could reproduce the issue, and what the issue is? A good way to describe an issue is by stating expected and actual behavior, or if you see an error, you can just give the repro steps somebody would need to hit to get to that error, and the paste the error that you see.
