### ISSUE TITLE
InputSimulationProfile does not exist...

### ISSUE THREAD

**Issue by hdaUwe** [Microsoft/MixedRealityToolkit-Unity#4079]
## Describe the problem
I'm using the release candidate downloaded directly from git. The documentation say there should be something like a InputSimulationProfile, to controll the app in the Unity Editor (working for HoloLens 1). Well, it's not there. This worked perfectly in the HLTK and really should be enabled by default. 

## Describe the solution you'd like
This whole profile editing and adding stuff is a little much in my opinion. Most of that stuff could be just set with a toggle on/off. I would love  to just toggle a thingy that disables all the stuff I don't need when using the HL1...

## Describe alternatives you've considered

I coded the camera controlls myself, but no way to grab or even click something the Holo-way

**Comment by SimonDarksideJ** [comment]
The issue above seems to be more with what the framework does when the simulation is NOT available, which is what should be fixed. NOT putting it everywhere as it breaks the abstraction.

To resolve this @davidkline-ms , we should be fixing why we are getting an error when it's on device (aka simulation not needed) rather than pushing simulation everywhere.
