### ISSUE TITLE
Create a EditorConfig with project code style

### ISSUE THREAD

**Issue by aalmada** [Microsoft/MixedRealityToolkit-Unity#409]
This would save a lot of reviewer's time. Right @HodgsonSDAS? ;)
https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/

**Comment by HodgsonSDAS** [comment]
very true.  But I think everyone would have to have vs 2017, correct?

**Comment by aalmada** [comment]
I still have to test how it behaves with Unity-generated projects and if it can be optional for others.
My VS 2017 at work doesn't want to update itself.

**Comment by HodgsonSDAS** [comment]
Yeah, we're currently on 2015.

**Comment by Zod-** [comment]
@StephenHodgson are the repository settings for ReSharper compatible between 2015 and 2017? I've [created](https://github.com/Zod-/MixedRealityToolkit-Unity/blob/ReSharper-Settings/MixedRealityToolkit-Unity.sln.DotSettings) a basic config file with some of the conventions, ignored the auto-generated SDK folder and a few abbrevations. Could you give it a try with that file? Then we could add it to the repo so that everyone has the ReSharper settings.

**Comment by StephenHodgson** [comment]
I've got no clue.

**Comment by davidkline-ms** [comment]
We should investigate automating the code style checks. Consider looking into resharper / stylecop rules that we could publish.

**Comment by Jarodshow** [comment]
[CodeMaid](http://www.codemaid.net) maybe?

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
