### ISSUE TITLE
Everything made with the 'old' Mixed Reality Toolkit Standard Shader breaks

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#4137]
## Describe the bug

Everything made with the 'old' Mixed Reality Toolkit Standard Shader breaks and becomes purple

## To reproduce

Import something created with the old shader - after replacing the HTK by the MRTK it says "Hidden/InternalErrorShader" at the material dropdown

## Expected behavior

Every object should keep it's own color/shader/material

## Screenshots

![image](https://user-images.githubusercontent.com/4129183/57023444-5b73ef80-6c32-11e9-95cc-f6b9bff03ad5.png)
![image](https://user-images.githubusercontent.com/4129183/57023481-70e91980-6c32-11e9-974f-21a54624bb64.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.11f1
- MRTK Version v2.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive

**Comment by genereddick** [comment]
I think this is by design, as they allow for you to run the old HoloToolkit and the new MRTK side by side. The advantage is that it gives you the ability to migrate one object or reference at a time. However, if you simply remove the HTK (as I did) you will end up with a lot broken.

The new MRTK standard shader has a new name, so either include the HoloToolkit to avoid the broken references and/or go through and manually update all the shaders.

You will find fonts and some other items have also slightly changed to allow for them to exist side by side.
