### ISSUE TITLE
RC2 Notes

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4184]
This issue tracks release notes, migration guides, and other things of interest to mention in the RC2 release.

**Comment by wiwei** [comment]
Calling out that we should highlight https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4103 which makes it easier to do an HTK -> MRTK upgrade

**Comment by wiwei** [comment]
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4211

Hand input recording functionality. Note that because this is actually renaming a class this is technically a breaking change.

**Comment by julenka** [comment]
#4532 includes two interesting changes for RC2

### Introduce the Experimental Attribute
This change includes a new [Experimental] attribute you can attach to a class to denote that the component is experimental. Experimental means a promising idea that we have not yet graduated to a full feature. The component subject to change and not subject to same testing and validations. 

### Experimental Hand-Attached menu
First experimental feature: a hand-attached menu. Please see #4532 for a description.

**Comment by julenka** [comment]
Recommendation to add the following into the RC2 Release

# Experimental UI UX Features
Some features the MRTK team works on appear to have a lot of initial value even if we haven’t fully fleshed out the details. For these types of features, we want the community to get a chance to see them early. Because they are early in the cycle, we label them as experimental to indicate that they are still evolving, and subject to change over time.

Please read the following page for more details: https://github.com/microsoft/MixedRealityToolkit-Unity/wiki/Experimental-UI-UX-Features

**Comment by cre8ivepark** [comment]
For UX controls, Slider is newly added after RC1 release.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/prerelease/2.0.0.rc2_stabilization/Documentation/README_Sliders.md
