### ISSUE TITLE
Inconsistency in eye tracking properties

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4195]
## Describe the bug

When viewing GazeProvider in the Unity inspector there is a option labeled "Prefer Eye Tracking". However, in the [GazeProvider](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs) code this field is exposed as the property **UseEyeTracking**. These are inconsistent.

MRTK will fall back from eye tracking to head tracking if:

- The application is missing permissions (see #4194)
- The user did not approve permissions
- The device is not calibrated for the user

Since MRTK will silently fall back to head tracking in these situations, the property should be renamed to **PreferEyeTracking** to match the inspector.

## Additional context

I'm aware this is a breaking change and I am labeling this issue as such. However, it's unlikely many developers are currently setting this property in code and I believe consistency with the inspector and clarity around what the property actually does justify the breaking change.

**Comment by wiwei** [comment]
Got around to looking at this one - as mentioned above, this is a breaking change, not just because it's a public property on GazeProvider.cs, but also because it's a public property on the interface IMixedRealityEyeGazeProvider.cs

Given that the value is primarily in consistency (and yes, prefer definitely a more correct term to use), it's somewhat difficult to argue the value vs break proposition here. The chance here is super low, but we could also make this consistent just by naming the underlying property useEyeTracking (and give it a better tooltip).

I'm probably going to go with that safer option here.

**Comment by wiwei** [comment]
Removed the breaking change label, because we took a non-breaking route here.
