### ISSUE TITLE
Grabbable objects have offset

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4217]
## Describe the bug

If there are several grabbable objects next to each other and you try to grab one of them you'll notice the grab will happen with an offset and might grab an object next to the one you actually wanted to interact with

## To reproduce

place several grabbable objects very close to each other in a scene and try to grab them with your hand on Hololens 2. Observe that you will grab an object that is next to your hand instead the one that is actually intersecting with the hand.

We tried this with mesh and box collider. The problem is more visible with mesh collider but still happens with box collider

## Expected behavior

When interacting with a grabbable object only the object that is touched should be grabbed. 

## Your Setup (please complete the following information)

- MRTK Version v2 RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by carmines** [comment]
issue also occurs with capsule collider

**Comment by Yoyozilla** [comment]
@julenka 
could you look at this as part of your grabbable investigation?

**Comment by julenka** [comment]
Hi Yoyo, which grabbable investigation are you talking about? I think you might be confusing me with Berni? Right now I'm working on Interactable mostly...

**Comment by thalbern** [comment]
I'm aware of the issue - it's in progress and will continue on it after rc2 is out :)

**Comment by Yoyozilla** [comment]
@thalbern  do you think this is a GA blocker?

**Comment by thalbern** [comment]
@Yoyozilla Yes I would consider this GA blocker

**Comment by googlan** [comment]
Following up on this one. I think it appeared due to initial misunderstanding how grab behavior was intended to work combined with a mistake in scene setup.
First of all, grab behavior works as follows:
* When grab is activated, all objects within certain radius from the pointer are accumulated for "potential grab". Radius is defined in `SpherePointer` options. 
* Among all these object `FocusProvider` chooses the one closest to pointer position (center of the sphere). This object is grabbed.
To determine closest object Unity method `Collider.ClosestPoint` is used, which has a restriction on collider type - must be Box, Capsule, Sphere or convex Mesh. If a collider type is different, `ClosestPoint` will emit a warning and return 0.

Now, back to the original issue:
* Initial sphere radius for grab is quite significant. It is chosen so big because "mathematically precise" grab (when you need to touch an object when grabbing it) actually doesn't feel great when trying to grab small objects (hand tracking isn't perfect). This means that you can grab objects, while not touching them. This is expected behavior for box and capsule (and other) colliders, which have been mentioned in the original report. This might have been interpreted as grabbing objects with an offset.
* If one tries to use `MeshCollider` without convex on an object with `NearInteractionGrabbable` behavior, distance to the closest object will always be calculated as 0, so `FocusProvider` will select a random object within pointer sphere radius. Basically user won't have control over object selection within the grab radius.

Restriction for collider types is enforced by Unity, so the only thing Mrtk can do here is to make an error in scene setup more visible. #5211 does that.

@carmines and @thalbern for visibility.
