### ISSUE TITLE
Poke pointer shouldn't iterate over all NearTouchInteractables every frame and use interface rather than static list

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4218]
## Describe the bug

Currently we're iterating over all NearTouchInteractables that are registered to a static instance list every frame in the poke pointer which is a performance issue and will miss any interactable that isn't registering itself to that list.

Proposal:

Can we do a raycast to figure out which objects we're actually pointing to and then check for an interface instead of keeping that list around?

## To reproduce

see code

## Your Setup (please complete the following information)

- MRTK Version v2 RC1

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
@julenka Do you know why we didn't do a sphere raycast when this was originally written?

It seems like at the very least we should make it so that we don't re-allocate another read only array on each iteration (i.e. the AsReadOnly)

**Comment by julenka** [comment]
Robert Ferrese wrote the original code, we should ask him. Here is a reason I think we might have wanted to keep a list of items instead of doing a ray cass in the scene. Let's say you have the following setup:

![image](https://user-images.githubusercontent.com/168492/57426382-d5c4e680-71d3-11e9-9fb6-3f4d3558c301.png)

In this case, if I cast a ray from the finger and take the closest hit, the ray would hit the grabbable box first, not the touchable collider. A similar thing would happen if you did sphere cast and just picked closest.

Note that we could instead use [Physics.RaycastAll](https://docs.unity3d.com/ScriptReference/Physics.RaycastAll.html)  to get all hits along a ray, then find the closest object that has a NearInteractionTouchable. Note that while this works for surfaces, it may not work if you approach a touchable volume from the side (something I believe Niall is working on ). Instead, using [Physics.SphereCastAll](https://docs.unity3d.com/ScriptReference/Physics.SphereCastAll.html) and finding the closest NearInteractionTouchable could work.

I think it's a reasonable issue to fix. Note also another issue with touch dispatch that we have, #4174.

**Comment by lukastoenneMS** [comment]
A major problem seems to be that NearInteractionTouchable doesn't necessarily use a collider. Easiest/Cleanest solution would be to require collidables for touchables now, but that is a significant breaking change.

Another issue i'm worried about is the way we don't take layers/layer masks into account at all right now. With collidables we'd want to expose the pointer layer mask as well, so users know what touchables the pointer will interact with. Could be quite confusing, but also a feature (additional filtering and bulk en/disabling touchables by changing layers).

I also don't see PokePointer caring about focus at all right now (not familiar with the code though). It looks like focus is a completely separate system.

Ideally i would want the PokePointer OnSceneQuery to work something like this:
1. Do a [OverlapSphere](https://docs.unity3d.com/ScriptReference/Physics.OverlapSphere.html) query to get all potential touchables in the max. radius. Use the `PrioritizedLayerMasksOverride` of PokePointer for that query [_Note: the custom PokePointer inspector currently doesn't show the layer mask property_]
2. Loop over returned colliders and filter for GameObjects with NearInteractionTouchables. [_Do we need to include parents in this, i.e. NearInteractionTouchables would work with child object colliders?_]
3. Use the existing distance function as a near-phase test to find the closes touchable.

**Comment by julenka** [comment]
Thank you for the thoughtful suggestions Lukas! These sound like great ideas. for 2) currently we say only colliders containing nearinteractiontouchable gameobject are touchable so I would say don't include parents for now.

If you free up and help we would love to have some help here :-)

**Comment by lukastoenneMS** [comment]
The problem i'm facing right now is that in order to do an overlap test i need to know some maximum distance for the interaction. Currently the maximum distance is defined for each individual touchable by [BaseNearInteractionTouchable.DistFront](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/5b3cf75b554df874584c3e95d99e32ddcd2d3da3/Assets/MixedRealityToolkit.Services/InputSystem/BaseNearInteractionTouchable.cs#L59), so i cannot use a single distance that works for all touchables. Here is how the PokePointer uses the property for the distance check:
[https://github.com/microsoft/MixedRealityToolkit-Unity/blob[/5b3cf75b554df874584c3e95d99e32ddcd2d3da3/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs#L59
](/5b3cf75b554df874584c3e95d99e32ddcd2d3da3/Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs#L59)

I have two possible solutions in mind:
- Move the distance setting from individual touchables to the PokePointer.
  Touch distance becomes a tool setting rather than a property of interactables.
- Use a trigger collider on each touchable with the individual distance as radius, then test which triggers the PokePointer intersects with.

I would prefer solution 1, since it's easier to implement and less error prone and probably more efficient too. However, it's a another breaking change, so i'd like to know if anyone has an opinion on this.

**Comment by MenelvagorMilsom** [comment]
> Move the distance setting from individual touchables to the PokePointer.
> Touch distance becomes a tool setting rather than a property of interactables.

This is the way that this used to be done. It was changed in #4263.

Julia requested in [this comment](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4263#issuecomment-491486787) that tolerance distances be configurable per touchable. However, if you're only planning on moving distFront back to the PokePointer, I imagine this will be fine. It's currently not exposed in the inspector as we were unsure whether users need to configure it per touchable.

**Comment by lukastoenneMS** [comment]
Thanks @MenelvagorMilsom. Quoting @julenka from #4263:

> I think the tolerances for surfaces should be configurable per-surface, not globally in the poke pointer like it is now. Reason is some things such as Unity UI may want to have a very large back tolerance, because we have observed people stick finger far behind surface when scrolling.

That should still be fine, since we only need the "distFront" for the activation query.

I would also suggest we rename these two distance properties to indicate their usage (and abstract away from planar geometry a bit):
* _distFront_ -> `activationDistance` : The distance at which the PokePointer will start interacting with the touchable. This will be a PokePointer property.
* _distBack_ -> `pokeDistance` : The distance at which the active touchable will raise the PokeDown event. This will be a NearInteractionTouchable property.
