### ISSUE TITLE
Make start interaction plane on pressable button configurable

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4219]
## Describe the problem

currently the point for that plane is the pivot of the movable button part. you can only modify it by putting a parent gameobject to that movable part and moving the pivot throught this hack 

## Describe the solution you'd like

Make the start interaction plane configurable through the debug manipulators (independent from the movable button part)

## Additional context

feature is already implemented in a draft PR from @danielhofmann-ms

**Comment by wiwei** [comment]
I believe this issue was fixed by @thalbern in #4144 (due to the comment left:

_Yes there's at least 2 tickets that are fixed with this PR (#4219, #4216) - but I just wanted to open this as a draft for having a discussion about it. If possible I'd like to avoid having the migration step (if we have to keep it in it should be moved out of the class)._

**Comment by thalbern** [comment]
not fixed! i was asked to close the draft PR - there's a comment in there that says there's going to be a second PR with the actual fix - the draft was just for discussing the fixes
