### ISSUE TITLE
Simplify enabling/disabling eye tracking feature support with MRTK

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#4245]
## Describe the problem

The user has to go to three different components to enable Eye tracking support from MRTK in their app (not counting the need to also enable the capability in every VS build). 

## Describe the solution you'd like

Turning on the feature should be consolidated to one checkbox or at the very least one section for the user to control. 

## Describe alternatives you've considered

It would be awesome if this was just a package to install and by installing, you are auto-enabling the feature support

**Comment by Yoyozilla** [comment]
Active thread discussing the right approach. We should fix this soon to reduce confusion

**Comment by wiwei** [comment]
@Yoyozilla do you have any new information from that thread? Ideally we could have that conversation on this issue.

**Comment by Yoyozilla** [comment]
Added Will and Luis to the thread to discuss

**Comment by Yoyozilla** [comment]
yoyo to follow up on if the fixes we already did are good enough for GA 
Also needs to get the Unity bug number

**Comment by wiwei** [comment]
So this one was interesting - a few things have changed since this was originally filed, and now we're in a slightly better world because of:

1) We have a default HL2 profile, which has the profile changes there by default. 
2) Made the "use eye tracking" toggle on by default.

Note that the gaze capability is still kinda weird - it's still only something that exists in VS, despite having a coming soon status in Unity. That being said, we also added an update to the MRTK build tooling to add the manifest capability in automatically afterward, so that should help.
