### ISSUE TITLE
MRTK buttons activate on release, not press. Not reliable to hit

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4259]
MRTK buttons default behavior in the "PressableButton" prefab s to activate on release instead of on press. But this is difficult to actually trigger because the user needs to carefully 'unpress' the button in order to activate the button. If the user exits the collision region without 'unpressing' the button, the button activation state will cancel.

I think the simplest way to fix this is to make the buttons activate on press, not on release, by default.

**Comment by chbecker-ms** [comment]
Comment from Sophie:

Please also think of whether it makes sense aligning with the button behavior from the Shell keyboard which activates on touch. It's especially confusing in the HandsInteraction sample app, where we have both the native Shell keyboard behavior and the custom MRTK buttons.

**Comment by chbecker-ms** [comment]
Ported from internal database.

**Comment by wiwei** [comment]
@julenka, do you have any thoughts on this regarding the parity or suggested fix?

**Comment by julenka** [comment]
I think for now it's better to err on making the controls easy to interact with, even though technically many buttons in the shell now activate on release (though you can activate them by pressing entirely through the button). Actually I just completed a PR a week ago to make buttons activate on press by default, so this bug is already completed :-)
