### ISSUE TITLE
NuGet + IL2CPP + UWP Doesn't work for Hands (SystemType reference is broken)

### ISSUE THREAD

**Issue by chbecker-ms** [microsoft/MixedRealityToolkit-Unity#4265]
Take latest NuGet packages, build IL2CPP for UWP, and the hands won't work.

The log has the following (it appears getting the type from the serialized reference is broken).

Failed to properly initialize the MixedRealityToolkit
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)​
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])​
UnityEngine.Logger:Log(LogType, Object)​
UnityEngine.Debug:LogError(Object)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()​
 ​
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)​
​
Unable to register a service with a null concrete type.​
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)​
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])​
UnityEngine.Logger:Log(LogType, Object)​
UnityEngine.Debug:LogError(Object)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterDataProvider(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Enable()​
Microsoft.MixedReality.Toolkit.<>c:<EnableAllServices>b__63_0(IMixedRealityService)​
System.Action`1:Invoke(T)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(Action`1)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:EnableAllServices()​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnEnable()​
 ​
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)​
​
Unable to register a service with a null concrete type.​
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)​
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])​
UnityEngine.Logger:Log(LogType, Object)​
UnityEngine.Debug:LogError(Object)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterDataProvider(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Enable()​
Microsoft.MixedReality.Toolkit.<>c:<EnableAllServices>b__63_0(IMixedRealityService)​
System.Action`1:Invoke(T)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(Action`1)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:EnableAllServices()​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnEnable()​
 ​
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)​
​
Unable to register a service with a null concrete type.​
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)​
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])​
UnityEngine.Logger:Log(LogType, Object)​
UnityEngine.Debug:LogError(Object)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterService(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterDataProvider(Type, SupportedPlatforms, Object[])​
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Enable()​
Microsoft.MixedReality.Toolkit.<>c:<EnableAllServices>b__63_0(IMixedRealityService)​
System.Action`1:Invoke(T)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServices(Action`1)​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:EnableAllServices()​
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:OnEnable()​
 ​
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)​
​
Diagnostics system is disabled. To run this demo, it needs to be enabled. Check your configuration settings.​
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)​
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])​
UnityEngine.Logger:Log(LogType, Object)​
UnityEngine.Debug:LogWarning(Object)​
Microsoft.MixedReality.Toolkit.Examples.Demos.EyeTracking.Logging.<PopulateHeatmap>d__43:.ctor(Int32)​
System.Threading.Tasks.AsyncInfoToTaskBridge`1:CompleteFromAsyncOperationWithProgress(IAsyncOperationWithProgress`2, AsyncStatus)​
Microsoft.MixedReality.Toolkit.Examples.Demos.DiagnosticsDemoControls:Start()​
 ​
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

**Comment by chbecker-ms** [comment]
Ported from internal database

**Comment by wiwei** [comment]
This is similar to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4340, in that without this fix or that issue fixed, you can't have NuGet + articulated hands.

Just a note that these two are related, and that we need to get at least one of them working soon.

**Comment by andreiborodin** [comment]
Well, I think we will need both of them working. As some apps rely on .NET others in IL2CPP.

**Comment by andreiborodin** [comment]
The first issue is fixed by including a **link.xml** file as part of NuGet to prevent bytecode stripping from the MRTK assemblies. We are still left with hands not working, and the following two logs:
analog\input\mirage\publicapi\ismdevicemanager.cpp(518)\Windows.Mirage.dll!70058673: (caller: 70054B9F) ReturnHr(3) tid(1950) 80070490 Element not found.
analog\input\mirage\publicapi\spatialinteractionsourceproperties.cpp(549)\Windows.Mirage.dll!70054CCF: (caller: 70056307) ReturnHr(4) tid(1950) 80070490 Element not found.

**Comment by andreiborodin** [comment]
So, one of the issues I suppose is that Il2CPP strips the ByteCode from MRTK binaries, however, the second issue, is that the serialized field is actually null.

**Comment by wiwei** [comment]
Okay, I took a look at this today, and also thanks to @andreiborodin for the pointer on the bytecode stripping stuff.

The gist of it is is that yeah, when Unity is building the project, it strips away a lot of MRTK code because it thinks things like:

the input system
The windows mixed reality provider
OpenVR provider
The diagnostic system

(The list goes on)

It thinks that they aren't used, because it's actually really hard for it to know that it is used.

Note that these components ARE used, and they are specified in the MRTK profiles (i.e. the type of input system we init is stored in the input profile). These aren't stored as a serialized guid/asset - they're stored as basically plain text (well, not really, they're stored as SystemType objects, which are a way that we workaround having a friendly dropdown to show an array of types vs. still being able to serialize them for real).

If you take a look at:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/f3a97916629a965c9fc45e85290c453ebc9b45f3/Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityToolkitConfigurationProfile.asset#L29

Notice how the type is stored as basically a flat name + assembly. Unity isn't designed to reason over these connections, so it sees that "oh hey, the boundary system class isn't used" and then optimizes them out.

This appears in multiple scenarios - when using pre-compiled binaries (has nothing to do with nuget) or when you're using code that's in a UPM (even as sources). 

You can see when you build the IL2cpp project (certain .cpp files will just be missing - i.e. you won't see the windows mixed reality one or the boundary system one).

In the longer term I think that we'll want to provide some tooling here to build a custom link.xml that will be the minimal set of things required to make the player build run - in the interim what I'll do is just add a link.xml to the respective folders to ensure that general set of things that are required (i.e. base services and such) are handled.

If you can't wait, you can also just copy the following text into a link.xml file in the root Assets/ folder of your project:
```
<linker>
  <assembly fullname="Microsoft.MixedReality.Toolkit" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.WindowsVoiceInput" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Providers.OpenVR" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.SDK" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.InputSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.BoundarySystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.CameraSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.DiagnosticsSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.SceneSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.SpatialAwarenessSystem" preserve="all"/>
  <assembly fullname="Microsoft.MixedReality.Toolkit.Services.TeleportSystem" preserve="all"/>
</linker>
```

**Comment by wiwei** [comment]
Alrighty, should be good now.

I just took the latest nuget packages for a spin and hands work when deployed to device using the IL2CPP backend.
