### ISSUE TITLE
MRTK branch like Windows Insider Preview

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4303]
## Describe the problem

The MRTK seems to be considered stable enough and is used by a lot of companies already, that it's hard to get breaking changes in that can improve the MRTK faster.

I can only speak for myself, but I have been contributing to the current MRTK for at least 2 months now, at work, and it's still not in a state where we can use it. I have no idea how others do actually.

## Describe the solution you'd like

I'm proposing an additional branch, like the Windows Insider Preview program for Windows, where things are highly unstable, but therefore flexible and very dynamic.
I would be very happy to fix MY code if something breaks when I choose to pull in an newer version of the toolkit, but since not even the development branch, which I thought was just that, a changing thing that once got stable, shipped with some kind of upgrade guide, like Unity does all the time (yes, even there not everything gets automated, you do need to to things manually if you want to go to the next full version).

## Additional context

We already have software running on a very old MRKT from over 1,5 years ago and want to upgrade. We then used Windows Desktop, UWP Portal and Hololens and Oculus Go. Besides the Toolkit being open for device extensions, it's not even ready to take them and changes to it are prohibited (#4240) since they break it.... well

**Comment by wiwei** [comment]
This is a discussion that we've had amongst the team a number of times, and at this time all of our engineering focus and time is being spent on stabilizing a number of issues that have been reported by customers who are starting to onboard to MRTK.

It's difficult for us to try to split engineering work between future and current right now, since we're so focused on a number of different stabilization fronts (consider that we have >30 issues that we want to drive down in <2 weeks https://github.com/microsoft/MixedRealityToolkit-Unity/issues?q=is%3Aissue+is%3Aopen+label%3AUrgency-Soon)

I think the most transparent I can be (and others please chime in with their opinions) is that we'll be operating in this single-branch until we have V2 fully out, at which point we will be open to breaking changes by default. @davidkline-ms

**Comment by Alexees** [comment]
Still a thing?

**Comment by polar-kev** [comment]
We don't want to break existing customers with preview builds but getting previews out to people is certainly something we want to do.

**Comment by polar-kev** [comment]
We need to investigate with the Feature Tool how to surface this correctly.

**Comment by keveleigh** [comment]
We're now shipping previews out of the main branch every couple weeks! @davidkline-ms may have more concrete information on the plan.
