### ISSUE TITLE
MouseController requires InputProfile but does not force it

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#4306]
## Describe the bug

Among others the MixedRealityInputSystemProfile provides the UnityMouseDeviceManager. It's one of a few that actually require a DeviceManagerProfile, otherwise a constant call to MixedRealityToolkit's GetService throws an error that it does not exist.

## To reproduce

1. Add a UnityMouseDeviceManager to an InputSystemProfile you use in a scene
2. Run the scene

## Expected behavior

Either default values prevent the error from appearing and allow the mouse to be used without a profile, or, like the MRTK itself shows a popup which profile to use, the controller should do that as well.

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/57613559-7b32de00-7577-11e9-96f2-ed1c8ce9a023.png)

## Your Setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version v2.0 mrtk_development as of now

## Target Platform (please complete the following information)

- Windows Editor

**Comment by wiwei** [comment]
There's been other feedback around these profile things as well - i.e. it really should be restrictive to just the mouse one (or maybe have some way of marking a profile as required in the data provider attribute so that it's clear that something is needed).

I think for this one it might just be a matter of providing the default profile in the attribute, though I haven't actually looked deeply enough into this to know.

**Comment by keveleigh** [comment]
Fixed via #6132. Thanks @alexees!
