### ISSUE TITLE
BoundingBox script doesn't work  when ManipulationHandler component is also added to the same gameobject

### ISSUE THREAD

**Issue by ritijain** [microsoft/MixedRealityToolkit-Unity#4393]
## Describe the bug

I attempted leveraging the Bounding Box + ManipulationHandler capabilities. Turns out BoundingBox doesn’t work reliably when ManipulationHandler is also active in the same hierarchy. 

## To reproduce

1. Create an object in the MRTK enabled scene
2. Add the ManipulationHandler script to the gameobject.
3. Add the BoundingBox script to the gameobject. (script order is important)
4. Hit play in unity editor
5. try to use the bounding box handles. - Nothing happens.

## Expected behavior
Bounding Box works as expected and allows rotation and scale operations based on handles.

## Screenshots

![image](https://user-images.githubusercontent.com/17660747/57820466-c698e800-7741-11e9-8245-cb8d67a8ecd5.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.3.10f1]
- MRTK Version [e.g. v2.0 - RC1-Refresh]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- UnityEditor

## Additional context
I tracked down the reason to the pointer event that BoundingBox receives has been marked “used” by manipulation handler sometimes.

**Comment by wiwei** [comment]
@julenka @cre8ivepark what's the intent here? Was this ever designed to be supported, or should we have a more formal system by which there can only be a single component of type "manipulator" or something

**Comment by julenka** [comment]
Yes, bounding box and manipulation handler should work together -- design is for you to be able to manipulate by grabbing the box itself (manipulationhandler), or by using affordances on corners/edges (boundingbox)

**Comment by cre8ivepark** [comment]
Currently, it only works when the Bounding Box is above the Manipulation Handler in the inspector.
Our examples in the HandInteractionExample scene has this order. Need to support both features regardless of the script order.

![2019-05-15 18_28_01-Me - DongYoon Park@microsoft com - Outlook](https://user-images.githubusercontent.com/13754172/58051146-49d18980-7b06-11e9-88a7-7b3bf54293c2.png)

**Comment by julenka** [comment]
Revisting this, I realize this is actually by design. Bounding Box should be above manipulation handler so that it can handle events before manipultion handler gets this. If we allowed both manipulation handler and bounding box to handle events, the object with both move from manipulation handler and scale.

If manipulation handler is above bounding box in component list, then it will get the events first. Then, any time you grab corners manipulationhandler gets ownership of the grab interaction. This is because the bounding box for the manipulation handler actually overlaps the rotate and scale affordances. We could work around this by introducing quite a bit more complexity in the bounding box colliders, but this would be at the cost of perf (more bounding boxes to query, also more complex assets). 

So, the behavior is as expected, and the fix / workaround is to ensure that the bounding box is above the manipulation handler.

One thing we could do is to have some validation to check that if bounding box is on component, that manipulation handler is always below bounding box. I wonder if it would be appropriate to put this in the inspector.

**Comment by ritijain** [comment]
@julenka i think there should be a validation for the bounding box script to be above the manipulation handler script (potentially an OnValidate() ? ). this is especially important since the MRTK documentaion explicitly calls out the manipulationHelper+boundingbox combination use case.
 https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_BoundingBox.html

**Comment by julenka** [comment]
I created #4546 to track the fix you suggested @ritijain

**Comment by julenka** [comment]
Actually fixed this properly by #5162 so removing by design tag. We found a better way.
