### ISSUE TITLE
Runtime error when build mixed reality project with unity and visual studio

### ISSUE THREAD

**Issue by lionrig** [microsoft/MixedRealityToolkit-Unity#4400]
## Overview
When we have built the solution, a runtime error appears in one eye on a corner.  Is imposible to read and we are tested in debug, release, master... and the error persist. In editor mode on Unity, the error dont appear. The experience is the same but is a little annoying. Any solution ?

## Expected Behavior
No runtime error
## Actual Behavior
Runtime error
## Steps to reproduce
Create project on Unity 2019
Build for Windows Universal Platform on VR
Open the solution in Visual Studio 2017
Compile and play or compile and make a appx

## Unity Editor Version
2019.1.0f2
## Mixed Reality Toolkit Release Version
v2.0.0-RC1

**Comment by wiwei** [comment]
A couple of things here:

1) Can you try to see if you still have this issue on RC1 refresh (release or master, debug actually has an issue with some InteractionManager code).
2) Can you provide more details on what this runtime error is (i.e. can you tether the device to a debugger and look at the output, or otherwise do some logging to file to capture what it is)?

Please reopen this with more details.
