### ISSUE TITLE
Getting started docs don't mention recommended build settings.

### ISSUE THREAD

**Issue by Samvid95** [microsoft/MixedRealityToolkit-Unity#4406]
I am trying to build a simple scene for Hololens v1 using MRTK v2. After solving a few problems I am facing the deployment issue on the side of Visual Studio. I am getting the error saying, "DEP3321: To deploy this application, your deployment target should be running Windows Universal Runtime version 10.0.18362.0 or higher. You currently are running version 10.0.17763.502. Please update your OS, or change your deployment target to a device with the appropriate version."

I am not familiar on how to update the OS on the Hololens to make it to the version required by the MRTKv2.

**Comment by wiwei** [comment]
It's possible that the minimum platform version you have in your build settings within Unity were set to 18362 instead of 17763:

![image](https://user-images.githubusercontent.com/5840182/57871047-562fac80-77bd-11e9-859f-bc86c45911dc.png)

Usually we'll have the lowest possible selected (so that it's possible to deploy the app to almost anything)

Looking through our getting started guide, we don't have any mention of this recommendation, so I'll keep this issue open to track adding that note.

**Comment by Samvid95** [comment]
Hahaha. Yess it was the minimum platform version that was confusing me. Thank you.
