### ISSUE TITLE
[MRTK] Cloning items and saving prefabs periodically causes file lock errors to pop up in Unity. 

### ISSUE THREAD

**Issue by andreiborodin** [microsoft/MixedRealityToolkit-Unity#4420]
## Overview
When cloning items, or saving prefabs, periodically an error stating "Saving from <TempPath>\RandomUnrelated.pfb to <LibraryPath>\RandomUnrelated.pfb failed". This is more easily reproable when cloning profiles based on the default profile (though I also suspect that this is enabled even further by having a project where a lot of editor script modifying files are running). It seems to be related to the nature of the editor scripts running in background that modify prefabs periodically and saves them.

## Expected Behavior
No Errors.

## Actual Behavior
File lock error preventing a copy, requiring a reimport of the AsmDef associated with this dll/pfb.

## Steps to reproduce
_(Links to sample github project preferred)_

## Unity Editor Version
2018.3.11f1

## Mixed Reality Toolkit Release Version
2.0.0-*

**Comment by wiwei** [comment]
Reference 21413012

**Comment by andreiborodin** [comment]
My repro:
I was waiting on editor to finish compiling so that I could immediately kick off a UWP compile, and that is when it repro'ed for me, after the UWP compiled.

**Comment by wiwei** [comment]
So it looks like a number of folks hit this internally on the team (and on other teams that were using MRTK on domain joined machines with certain policies set).

The team in charge of setting those policies is looking into this, but from the MRTK perspective it looks like the best way to work around this is to try to re-import (if the issue is from reimport) or trigger a rebuild (changing some code, etc). From the data we're seeing it looks like this isn't MRTK specific either.
