### ISSUE TITLE
Eye targeting not working with near hand pointers enabled anymore

### ISSUE THREAD

**Issue by sostel** [microsoft/MixedRealityToolkit-Unity#4431]
# Describe the bug

Hand focus breaks BaseEyeFocusHandler in Unity Editor (did not test on device).

**Edit**: I noticed that after I remove all of the "Articulated Hand" pointers, namely PokePointer and GrabPointer, the expected behavior would work again: Look at a target and use airtap to select it. I had already removed the DefaultPointer (causing the hand ray to show up) a while ago, because it interferred with eye targeting as soon as a hand would be detected. However, so far, it was still possible to use "Look & tap" for far and poke and grab for near interactions. This is not possible anymore.

## To reproduce

1. Load EyeTrackingDemo-00-RootScene
2. Hit play
3. Move eye cursor over a gem by pressing right mouse button and moving mouse. The gem should start rotating.
4. Press Space to show hands. The rotation stops. An airtap does not cause the gem to be selected.
5. Release Space to hide hands. Eye targeting via BaseEyeFocusHandler remains broken. 

## Expected behavior

Look at a gem and select it via airtap.

## Your Setup (please complete the following information)

- Unity Version [e.g. 2018.4.0f1]
- MRTK Version [e.g. last updated 05/16/19 - 1:43 PM]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

Current Input Profile setting that seems to work for "look & tap": 
![image](https://user-images.githubusercontent.com/32180789/57889796-92c5cd00-77ea-11e9-8059-6344f7ee0c66.png)

**Comment by wiwei** [comment]
Okay, figured out what's going on here - after this PR went in:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4270

It looks like this was also causing the new-eye-tracking-style-gaze-provider to also get disabled once hands were in the picture, and you had to say "select" in order to bring them back.

It looks like the intent here is for eye gaze scenarios, we want to go back to what it was before (i.e. if any far interactions active, disable eye gaze, near interactions don't really matter)
