### ISSUE TITLE
Bounding box scaling varies based on whether the box is directly on the target/collider or parented to it

### ISSUE THREAD

**Issue by djohnsomsft** [microsoft/MixedRealityToolkit-Unity#4434]
The scaling of the bounding box is inconsistent depending on whether it is applied directly to the target or to a parent of the target. While the scaling starts out the same, if the bounding box is on the target, the handles will shrink to be unusably small.

This example shows a set of two of the same model:
The left one has no target and the overridden BoxCollider on the same object as the BoundingBox
The right one has the BoundingBox on a parent with a disabled BoxCollider, and the overridden BoxCollider + Target referencing the child.

![boundingboxes0](https://user-images.githubusercontent.com/27969160/57886136-635e9280-77e1-11e9-90de-55f2f9acbbb8.PNG)

You can see they both start out the same:

![boundingboxes1](https://user-images.githubusercontent.com/27969160/57886237-9a34a880-77e1-11e9-8ad7-5323f19034fb.PNG)

However, upon scaling down, the handles for the unparented one also scale down to become tiny. The parented one maintains handle sizes consistent with the set handle size in the editor properties and remain usable.

![boundingboxes2](https://user-images.githubusercontent.com/27969160/57886306-c4866600-77e1-11e9-88d2-c66fa2a3099b.PNG)

Expected behavior is that either the developer controls this (fixed vs scaling size), potentially able to change the fixed size programmatically if the model gets too small.

**Comment by julenka** [comment]
Okay, I understand why this is happening. 

In first case (no parent), the bounding box is scaling SampleLargeModelBounded, which is also scaling rigRoot. BoundingBox has no code to ensure that after scaling some parent transform, the affordances maintain size.

![image](https://user-images.githubusercontent.com/168492/60148208-fbf31580-9784-11e9-9614-98ebf0281648.png)


In the second case, the scale of SampleParentBounds always remains at Vector3.one, because the child object "Collection 2" is getting scaled.

![image](https://user-images.githubusercontent.com/168492/60148237-204ef200-9785-11e9-9b21-ca1dda41d532.png)

**Comment by julenka** [comment]
merged
