### ISSUE TITLE
[Proposal] Reduce the number of core assemblies

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#4453]
## Describe the problem
We have received customer feedback that the number of MRTK core assemblies is overwhelming (in VS, etc). They have requested that we combine them into a single core assembly and a single core-editor assembly.

This _may_ also have the desired effect of reducing the number of instances of Unity reporting a failed dll copy on project (re)load.

## Describe the solution you'd like

Ultimate goal is to reduce the core assembies to the following:
- Microsoft.MixedReality.Toolkit
- Microsoft.MixedReality.Toolkit.Editor

This would eliminate:
- Microsoft.MixedReality.Toolkit.Core.Build
- Microsoft.MixedReality.Toolkit.Core.Definitions.Utilities.Editor
- Microsoft.MixedReality.Toolkit.Core.Extensions.EditorClassExtensions
- Microsoft.MixedReality.Toolkit.Core.Inspectors.ServiceInspectors
- Microsoft.MixedReality.Toolkit.Core.Inspectors
- Microsoft.MixedReality.Toolkit.Core.Utilities.Async
- Microsoft.MixedReality.Toolkit.Core.Utilities.Editor 
- Microsoft.MixedReality.Toolkit.Player
- Microsoft.MixedReality.Toolkit.Utilities.Gltf
- Microsoft.MixedReality.Toolkit.Utilities.Gltf.Importers

**Comment by provencher** [comment]
I think Examples should be in a separate assembly, but all be grouped together.

Specific supported platforms should also be their own assemblies, so that when the package manager solution goes live, you can only bring in the examples you want.

**Comment by provencher** [comment]
Personally, the way that @StephenHodgson setup the XRTK makes the most sense to me.
https://github.com/XRTK

**Comment by davidkline-ms** [comment]
@provencher, there are currently no plans to bundle the services or platforms. Examples are something that needs to be further thought out

**Comment by Railboy** [comment]
I like the simplicity but this might be case where devs don't realize what they'd be giving up.

Assemblies keep editor compile times down when editing scripts in large projects. Maybe we can measure the impact? I recall it being pretty miserable before they were introduced.

They're also free best-practice enforcement. They make it impossible to write the kind of spaghetti that made the HTK hard to consume.

**Comment by provencher** [comment]
I remember speaking to @andreiborodin about how all these assemblies would eventually simply be imported via nuget or some other package management system. 

For people actively changing the MRTK, as @Railboy points out, keeping these separate assemblies improves editing performance. 

For folks simply consuming the MRTK, who are the ones largely making this complaint, package delivery would solve this issue.

For folks like me, who keep a custom version of the MRTK in my projects, hosted on my own git submodule, it'd be nice to be able to build out these assemblies as DLLs myself, to to avoid having project files for parts of the MRTK I don't have modifications for. 

Give how the MRTK already bogs down the editor, if removing the assemblies will bog it down further, I remove all support from the simplification.

**Comment by wiwei** [comment]
I think that it would be important here to understand what we're giving up (as @Railboy mentions) - it seems like to understand the impact of the change here we should do the due diligence of doing some basic benchmarks, so that we can understand the tradeoff of:

Pros:
Simpler binary story
Better navigate-ability in VS

Cons:
X% slower?

If on average we're losing single digit times or low double digits, maybe this is alright, but if we're seeing 100% increases in build times because Unity has to rebuilt at a much higher scope each time, we might want to consider something else (i.e. doing a build preprocessing step of removing asmdefs when creating the release unitypackage/UPMs)

**Comment by Ecnassianer** [comment]
To @wiwei 's point, I bet that there's some subset of asmdefs that make very little difference in compile times, even if we see huge gains from others. For instance, is splitting Inspectors from Service Inspectors really giving us a huge benefit? We could likely reduce the total number of asmdefs without going back to not using them at all.

**Comment by provencher** [comment]
Thinking about this more - As long as all the MRTK code is behind a separate assembly than a user's project code, there is no slowdown on recompile for the user.

The only folks that gain from having many assemblies are the MRTK developers.

**Comment by wiwei** [comment]
Plus-1-ing this, with a few other comments:

We have to separate out the fact that there are two different consumers of this:
1) There are the contributors of the MRTK - these people actually benefit from having these asmdefs with reduced build times.
2) There are the consumers of the MRTK - these people don't benefit from this (because they're likely not changing the MRTK as often as their own code) but are getting massive VS bloat because of this.

I don't want to regress #1 soley to make #2 better, but also I don't want to make #2 suffer just because of #1. 

There should be some way to do a prebuild step (i.e. in our CI pipelines) that can clean things up such that we get the best of both world.

**Comment by davidkline-ms** [comment]
> We could likely reduce the total number of asmdefs without going back to not using them at all.

@Ecnassianer, agreed. There will still be asmdefs for each provider, service, etc. The proposed change is to limit the "Core" assembly count.

**Comment by davidkline-ms** [comment]
Looks like this may involve moving code in the source tree. Editor code is spread across multiple folders that are not in the same hierarchy, With the way that asmdef files work in Unity, code needs to share the same parent to be contained within the same assembly.

Proposal:
- Create MixedRealityToolkit\Editor folder
- Move editor code from the following into the new Editor folder
    - Definitions\Utilities\Editor
    - Extensions\EditorClassExtensions
    - Inspectors
    - Utilities\BuildAndDeploy
    - Utilities\Editor

**Comment by davidkline-ms** [comment]
GLTF is a large component. At this time, it seems to make sense to keep it as a separate assembly.

Thoughts?

**Comment by davidkline-ms** [comment]
Removing from GA Blocker as there is debate to the performance value gained with this change. Moving to investigate.

**Comment by davidkline-ms** [comment]
Closing as this proposal requires some significant changes to how code is laid out to avoid circular assembly references.
