### ISSUE TITLE
Type or Namespace not found errors in 2 script

### ISSUE THREAD

**Issue by Kulanei** [microsoft/MixedRealityToolkit-Unity#4537]
## Describe the bug

Got 4 error about namepsace not found (see screenshots)

## To reproduce

1. Updated a project by updating to the last ver of the mixed reality toolkit (v2.0.0 RC1 Refresh)
2. See error

## Expected behavior

No Namespace error, would allow me to compile my project in unity

## Screenshots

https://imgur.com/a/bWTS2tL

## Your Setup (please complete the following information)

- Unity Version [2019.1.3f1]
- MRTK Version [v2.0.0 RC1 Refresh]

## Target Platform (please complete the following information)

- HoloLens

## Additional context

Doing an internship, teacher asked me to reopen a project made with Unity 2017.4.24f1 so i could update it to last unity and Toolkit version. Might end up modifying it and with this problem i can't really work :/

**Comment by KrasnovPavel** [comment]
I have the same problem but with other file.
![image](https://user-images.githubusercontent.com/5003831/58262117-4c401780-7d82-11e9-9cb1-876a4ba5ea06.png)
I've made search in project for those classes but didn't find their implementation at all.
- Unity Version [2018.3.7f1]
- MRTK Version [v2.0.0 RC1 Refresh]

**Comment by julenka** [comment]
Hi, please see the answer in the following thread: https://stackoverflow.com/questions/55544730/cannot-build-with-mrtk-v2-0-0-rc1

**Comment by ALaurain** [comment]
@julenka I think the question @Kulanei  asked is slightly different than the one KrasnovPavel asked/you linked an answer to. Kulanei I had these exact same error appear for me when migrating a project from Unity 2018.2 to 2018.3 going from the HoloToolkit to the new MixedRealityToolkit v2. I tried every suggestion in every forum before I found an answer on my own.

After some investigation I believe  Unity is importing the files incorrectly causing a namespace issue. I was able to find the file definition for the ToolTip type and the other types Unity is complaining about in the errors, but for some reason Unity can't just create a reference to these files like it is supposed to. My assumption is that it has something to do with the execution order within Unity, or something along those lines. Because I am able to reference MixedRealityToolkit scripts from within the HoloToolkit namespace, but not the other way around.

I realized that when importing the new MixedRealityToolkit v2, Unity was simply updating some files, rather than creating the files in the new location they are supposed in. View my attached screenshot to get a list of files Unity is simply updating, rather than deleting and recreating in the proper location
![UnityImport](https://user-images.githubusercontent.com/7387611/58652075-bf94dc80-82e0-11e9-8cac-32a549304d2c.png)

So to fix my errors, I re-pulled my project fresh from SVN to get it in a working state. Deleted the files circled in my screenshot **BEFORE** importing the MixedRealityToolkit. After deleting the files, I imported the new toolkit, and it created these files in their proper location instead of updating the old versions. I was then able to create a reference to the Tooltip type (and the others) through visual studio no problem.

Be warned  that you will have to go in and manually fix some errors in these new files since some namespaces changed between versions. Unity will tell you where, and it isn't that bad. It is all pretty intuitive changes with some guessing work. However, I never plan on using Tooltips and some of these extra features, so even if my changes aren't perfect I was able to compile without errors. 

I hope this helps! (It made me feel slightly less insane that someone else was having the same issues as me)

**Comment by julenka** [comment]
Thanks for the workaround @ALaurain, super helpful to undrestand. Yes you are correct it is a different issue. It looks like old HTK and MRTK v2 have some assets with the same GUIds. Actually @keveleigh has fixed this by #4103. This fix will be available in RC2 release which should be coming out soon. Pleas see #4184 for the RC2 notes.
