### ISSUE TITLE
How to enable real time shadows on the Mixed Reality Standard Shader?

### ISSUE THREAD

**Issue by StephenHodgson** [microsoft/MixedRealityToolkit-Unity#4617]
## Describe the Issue

@Cameron-Micka How do we enable real time shadows on the Mixed Reality Standard Shader?

## Feature Area

I'm unable to figure this out and it would be nice to be able to enable this feature.
I'm understand this was done intentionally as a optimization, but would like to be able to use dynamic lights with this shader and all the awesome features that come with it.

**Comment by StephenHodgson** [comment]
MRTK Standard shader on a cube and plane without shows and a default directional light
![image](https://user-images.githubusercontent.com/13334553/58581430-622b5d80-8204-11e9-914b-cabd5fa7f004.png)

**Comment by StephenHodgson** [comment]
Unity Standard Shader
![image](https://user-images.githubusercontent.com/13334553/58581505-9010a200-8204-11e9-9662-3bfe30105966.png)

**Comment by StephenHodgson** [comment]
I noticed that this works fine for baked lighting but real time shadows are out of the question.

**Comment by davidkline-ms** [comment]
For Holographic / AR scenarios, real-time shadows are often too expensive.

From the Windows Mixed Reality [documentation](https://docs.microsoft.com/en-us/windows/mixed-reality/color%2c-light-and-materials):
- Avoid dynamic lighting – Holograms that are uniformly lit in holographic experiences are the most efficient. Using advanced, dynamic lighting will likely exceed the capabilities of mobile shaders.

VR-only scenarios on high powered GPUs may be able to leverage the dynamic lighting support of Unity's standard shader.

**Comment by StephenHodgson** [comment]
@davidkline-ms I know full well why it's done this way.

But I really like all the features of the mixed reality standard shader and I don't think it's too much to ask for the dynamic lighting support in VR scenarios.

**Comment by Cameron-Micka** [comment]
Hi @StephenHodgson you are correct that the MRTK/Standard shader doesn't support dynamic shadows (something I omitted since mobile VR, and even some VR PCs, have trouble supporting them). But, it shouldn't be too hard to add. This [blog post](https://alastaira.wordpress.com/2014/12/30/adding-shadows-to-a-unity-vertexfragment-shader-in-7-easy-steps/) shows the handful of macros and methods to implement to add dynamic shadowing. 

That being said, I'm not sure if those steps match what is necessary for the LWRP or single pass instanced rendering? Something to test!

I'm not sure what your use case is, but some other things to try if you can't utilize static lighting and you find dynamic shadows are too expensive are [shadow projectors](https://docs.unity3d.com/Manual/class-Projector.html)  (also know as "blob shadows") or if you want to get fancy, [capsule shadows](https://forum.unity.com/threads/capsule-shadow-dynamic-object-soft-shadow-fake-indirect.478096/) (which were made famous by the Last of Us, UE4 has support for them out of the box).

**Comment by StephenHodgson** [comment]
Super useful thanks.

Really the use case is dynamically loaded 3d models at runtime that don't have light information baked into them AOT.

That capsule shadow feature looks pretty useful!

I think the real winner is the LWRP in the long term but I know that's probably some time off before being fully availible and out of beta. (Is it true it still has problems on UWP, or did those get resolved?)

**Comment by Cameron-Micka** [comment]
Thank you for the kind words! Ah okay, yeah dynamic + static lighting is a tough hurdle.

Luckily the LWRP pipeline is out of beta in 2019.x, so once the MRTK jumps to 2019 we can provide better support. Until then we have an [upgrade path](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4311).

**Comment by Cameron-Micka** [comment]
Another option for dynamic content is you could fire off a background process that computes ambient occlusion for meshes and bakes the result into the vertex colors of the mesh (I'm not sure how quick this would be at runtime, but certainly faster than traditional lightmaps). You can get nice results like this: https://forum.unity.com/threads/vertexdirt-per-vertex-ambient-occlusion-baking.267826/ Not quite "shadows" but adds nice contrast.
