### ISSUE TITLE
Azure pipeline does not generate UPM-Compliant packages in releases

### ISSUE THREAD

**Issue by ei2kpi-ptc** [microsoft/MixedRealityToolkit-Unity#4652]
## Describe the problem

This is an extension of PR #4616 and issue #4403 to actually generate the UPM-compliant .zip packages as part of a release

## Describe the solution you'd like

See [this comment](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4616#issuecomment-497275082) for steps to add to the Azure Pipeline

**Comment by ei2kpi-ptc** [comment]
@MenelvagorMilsom Can you provide a little more guidance on how to get the Azure pipelines packaging up the UPM packages?

Here is what needs to happen:
- Each of the folders (MRTK, MRTK.Services, MRTK.Providers, MRTK.SDK and MRTK.Examples) need to be zipped up into individual archives
- The archives have to be named com.mixedreality.toolkit, com.mixedreality.toolkit.providers etc.
- These archives need to be made available as artifacts on each of the releases.

**Comment by MenelvagorMilsom** [comment]
1. **ci.yaml** is run whenever changes are made to the mrtk_development branch.
**pr.yaml** is run when a member of the MRTK team requests PR validation. You'll see comments with `/run azp mrtk_PR`, which trigger this pipeline.
**ci-release.yaml** is run on a private Microsoft ADO project. This pipeline is not public facing and only Microsoft employees can queue and check results. This pipeline is triggered manually in order to generate artifacts for our release.
2. I'm not sure I fully understand this question, let me know if I misunderstood. We don't use the .yml editor in ADO. So far we've been editing all of our .yml pipeline definitions through a text editor. The schema is generally pretty well defined. We just check these into git as normal then.

**Comment by Yoyozilla** [comment]
coming shortly after GA!

**Comment by keveleigh** [comment]
This was added in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8232! Each CI run now publishes UPM-compliant packages in the artifacts. For example: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=13054&view=artifacts&type=publishedArtifacts
