### ISSUE TITLE
No information regarding SpatialAwareness mesh retrieval

### ISSUE THREAD

**Issue by Wolfoso** [microsoft/MixedRealityToolkit-Unity#4718]
## Issue Description
I want to retrieve the mesh generated by the Spatial Awareness System and do operations on it in other to generate more data (like getting floor, walls, etc) but I had no idea how to do that. I was only able to do this thanks to @wiwei , who showed me the method below to gain all observers (each observer having its meshes collection).
`MixedRealityToolkit.SpatialAwarenessSystem.GetObservers<IMixedRealitySpatialAwarenessMeshObserver>()`

It appears the base interface _IMixedRealitySpatialAwarenessObserver_ does not provide access to the meshes.

## Feature Area
It would be nice to access the whole mesh/all meshes used for the Spatial Mapping more easily, without having to go through multiple lists of lists. Even better if there were tools to easily process information out of these meshes.

## Existing Doc Link
Missing documentation regarding this.

**Comment by jbienzms** [comment]
Here is more detail about the issue:

The only way to get the meshes is through the **IMixedRealitySpatialAwarenessMeshObserver** interface. Specifically the **IMixedRealitySpatialAwarenessMeshObserver.Meshes** property.

But the path customers will follow to access the service is **MixedRealityToolkit.SpatialAwarenessSystem.GetObservers()** and that method returns a list of objects of type **IMixedRealitySpatialAwarenessObserver**. 

The **IMixedRealitySpatialAwarenessObserver** interface does not have a **.Meshes** property. Only **IMixedRealitySpatialAwarenessMeshObserver** does. It’s unclear to me why any spatial awareness observer would not provide meshes. Therefore it’s unclear to me why **IMixedRealitySpatialAwarenessObserver** does not have a .Meshes property. If this was accidentally omitted, it should be added. If there is a real reason for this omission then documentation should be updated to describe how to enumerate and query the meshes.

FYI, this does seem to be a common theme of confusion for developers. There are many service provider interfaces in the MRTK. We start with the most generic interfaces exposed at the **MixedRealityToolkit** object, then require developers to cast these basic interfaces in order to access commonly needed functionality. Unfortunately, because these casts are not documented, developers do not know how to access the information they need. This issue with accessing spatial observer meshes is another example of the problem I tried to call out [here](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4882#issuecomment-503068968).

**Comment by davidkline-ms** [comment]
I own documenting this (ETA: week of 7/8). 

The overall rationale behind this architecture is that there will be multiple types of spatial observers. Once MRTK support is expanded to phone AR, there will be observers that will natively deliver planes.

If the spatial awareness system directly exposed meshes today, it would need to directly expose planes "tomorrow". That would constitute a breaking change to the **IMixedRealitySpatialAwarenessSystem** interface. 

The implementation of casting the interface to an instance of **IMixedRealityDataProviderAccess** provides a cross system pattern for accessing data providers (note: observers are data providers and the existing GetObservers methods have been deprecated).

**Comment by wiwei** [comment]
I've added information about how to do this to the MRTK docs themselves:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/UsageGuide.html
