### ISSUE TITLE
Controller representation for WMR missing

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4748]
## Describe the bug

Controller representations for WMR in editor play mode (coordinate systems) not visible until you press the start button for the first time (possible regression of PR 3638) 

## To reproduce

Start HandInteractionExample Scene with WMR and observe that no controllers are rendered
Press start button to open MR menu - controllers appear
Press start menu button again to close menu - controllers will still be visible

## Expected behavior
Controllers should be visible on start of the application without having to enter the wmr start menu

## Your Setup (please complete the following information)
MRTK RC2 build call issue
Unity 2018.4 

## Target Platform (please complete the following information)

- WMR immersive

**Comment by thalbern** [comment]
can confirm - regression of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/3638

**Comment by wiwei** [comment]
As a workaround, we could probably just use the WaitUntil functionality to wait until the second frame before doing the rest of the initialization - as I understand this, it looks like it never actually gets around to running the source detected function unless there's an interaction loss->gain transition (i.e. bringing up the WMR menu)

I don't fully understand in the original code change why the force-reconciliation of source state was completely axed out (rather than just delayed) but yeah we should probably try that out.

**Comment by thalbern** [comment]
simply delaying the execution won't help - the input detected event will still be sent in the first frame and register the old (from previous session) controllers. You can keep the "skip frame 1" hack in the event handler and delay the controller register from the Enable() method but that's even more hacky :/ - I just posted a PR where I'm cleaning up "ghost" controllers in the InteractionManager source state query. that seems a bit cleaner, but also not the best solution. defo a bug in the interaction manager

**Comment by thalbern** [comment]
fixed in #4799
