### ISSUE TITLE
Pressable Button prefab events not firing in Unity Editor

### ISSUE THREAD

**Issue by mirzasohailbaig** [microsoft/MixedRealityToolkit-Unity#4757]
## Describe the bug
The PressableButton prefab doesn't trigger any of the events in the Unity Editor, specifically  **TouchBegins()**,**TouchEnd()**,**ButtonPressed()**, **ButtonReleased()**
## To reproduce

1. Load the **PressableButtonExample** scene in the editor.
2. Press **play** in the scene. 
3. use the near interaction (by holding space bar and left clicking) to click on the button using the hand 
4. Notice no audio plays for the **ButtonPressed()** event, this behavior is the same for any of the other events listed above.

## Expected behavior

When the button is pressed via the near interaction, the events should get triggered in Unity Editor, although this works fine on HoloLens. 

## Your Setup
- Unity Version 2018.4.1f1
- MRTK Version v2 RC1 Refresh

## Target Platform

- HoloLens 
- Unity Editor (Doesn't work)

**Comment by wiwei** [comment]
@mirzamazharalibeg sorry for the delay here - there have been a number of pressable button fixes that have gone into mrtk_development since RC1 refresh. I just gave this another spin on latest mrtk_development and I"m able to hear the sound and see the interaction for the near interaction buttons on the far left of the scene (i.e. the third button from the left)

Please reopen if you're still seeing this on latest and @wiwei ping me!
