### ISSUE TITLE
Adding tile direction aka "anchor" aka "alignment" support to GridObjectCollection

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#4777]
The current GridObjectCollection will tile the objects with the parent object in the center of the collection - this great if you have a collection that you want to appear in the middle of something, but if you have a UI where you have a grid of buttons, which you want to appear going from the top left of a place and then growing toward the bottom right, this makes things difficult (i.e. you need to duplicate the layout logic to figure out where the buttons will be, and then move the parent object to JUST the right location).

This is trivially "workaroundable" by just setting the xOffset and yOffset starting values to zero, but it would probably be helpful to have an option on the object collections to provide a "which direction will they grow from"

* [x] Add a single field "anchor" with the following values: "Upper Left", "Upper Center",...,"Middle Left",..."Bottom Left",...,"Bottom Right". This matches what Unity has for Text Meshes: 
![image](https://user-images.githubusercontent.com/168492/67997253-a4702500-fc10-11e9-9d86-a5996eca377d.png)

* [x] Update "Rows" to be "Rows or Columns", since if the layout is "Columns then rows", then the layout actually uses the "Rows" field to determine the maximum number of columns to use, not rows :-)

**Comment by radicalad** [comment]
I'd recommend we make a net new `GridObjectCollection` (different name just not sure what) with a different set of Layout logic. Much like how` ScatterObjectCollection` is now a separate control. If you have a good name suggestion, I can add it to my PR for #4724 - I rewrote the Layout method for `ScrollingObjectCollection` because moving `GridObjectCollection` was a nightmare (for the same reason).

**Comment by julenka** [comment]
@wiwei  can you explain where this "trivial" xOffset and yOffset value is? I can't find it. Maybe it's not so trivial?

**Comment by julenka** [comment]
@radicalad, I think we can actually do this without needing to rewrite or GridObjectCollection, or create a new class. While I like the idea of starting from a clean slate, re-using GridObjectCollection has a few advantages:

1) People using GridObjectCollection will benefit without needing to redo their assets
2) People will be able to more easily switch layouts
3) The name "GridObjectCollection" feels like the best name for what this does :-( I can't think of a better name, and "GridObjectCollection2" is something we are trying to avoid.

**Comment by julenka** [comment]
How about the following spec:

* [ ] When the "Surface Type" is "Plane" we have a section called "grid alignment", with the following options:

Vertical Alignment:
- Can be "Top, Middle, or Bottom"

Horizontal Alignmetn:
- Can be "Left, Center, or Right"


* [ ] Update "Rows" to be "Rows or Columns", since if the layout is "Columns then rows", then the layout actually uses the "Rows" field to determine the maximum number of columns to use, not rows :-)

**Comment by julenka** [comment]
@radicalad I've got the "anchor" field working in GridObjectCollection without needing to rewrite it, the code change was actually fairly minimal. I don't think we need to rewrite GridObjectCollection.
