### ISSUE TITLE
Performance issues rendering complex 3d objects with transparency

### ISSUE THREAD

**Issue by marcelomejiacobo** [microsoft/MixedRealityToolkit-Unity#4867]
## Describe the bug

Trying to render complex 3D models with transparency generate performance issues.

## To reproduce

1. Load 3D complex objects and assign a texture with transparency. 

## Expected behavior

Low frames per second 

## Your Setup (please complete the following information)

HoloLens 2
- Unity Version [e.g. 2018.3.11f1]
- MRTK Version [e.g. v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

Trying to improve performance with integrated unity solution for camera render.

**Comment by Cameron-Micka** [comment]
Hi Marcelo! Unfortunately this isn’t a issue unique to the MRTK. Rendering complex transparent models with transparency is a common problem both in terms of visual accuracy and performance.

On the performance side of things, when a material is marked as transparent it’s render state is traditionally set to disable back face culling and depth testing to look “visually correct.” Rendering engines do this because the user usually wants to see geometry on the far side of the mesh viewed though the near side of the mesh. Think about holding up a wine glass, you can still see the glass on the back side though the side of the glass nearest to you. When disabling back face culling and depth testing you also disable two important mechanisms that the GPU uses to reject geometry which would not normally be seen on opaque objects. When the GPU can’t reject the triangles not normally seen on opaque objects, the GPU ends up having to render more triangles that overlap, which means more time is spent rendering your object. This problem is normally referred to as “overdraw.”

You may say “_hey, on my desktop PC I can render transparent objects just fine and don’t see a big overdraw issue?_” Another issues with rendering transparent objects on HoloLens (and other mobile devices) is most mobile/handheld devices use [tile based rendering](https://en.m.wikipedia.org/wiki/Tiled_rendering) to reduce memory bandwidth requirements. The problem with tile based renders is that they can exacerbate overdraw issues when triangles straddle a tile boundary and can’t be rejected early by back face culling and depth testing. Many platforms which use tiled rendering warn the user to avoid transparency whenever possible.

Now onto the question of “_how can I solve this issue?_” This is a tough question. Can your design allow the use of less transparent objects? In other words, can you have just one part of the model be transparent while the rest is opaque and toggle on/off transparent parts as focus changes? You can also try reducing the complexity of your mesh by running it though geometry decimation processes like [Simplygon](https://www.simplygon.com/). Or, can you enable back facing culling and/or depth testing on your transparent material and still get the desired visual look? (This is often not the case, but you can experiment with this by selecting you MRTK/Standard material in Unity, selecting “Custom” for the Rendering Mode, then "On" for Depth Write, and “Back” for the Cull Mode.)

I'm going to close this issue for now since it isn't a bug with the MRTK, but please don't hesitate to ask for more information.
