### ISSUE TITLE
Analyze MRTK memory usage

### ISSUE THREAD

**Issue by Yoyozilla** [microsoft/MixedRealityToolkit-Unity#4902]
MRTK onscreen profiler reports ~285 MB of memory used running the HandInteractionExamples scene on a Master build in HoloLens 2. An empty scene with MRTK uses around 270 MB. This is running from sources with caff836f8124283df53eae84baa70fafd87be5e4.

Quoting @davidkline-ms :

> By default, configuring an empty scene with the MixedRealityToolkit object starts ALL systems. We need to do some profiling to find out how much each system consumes and provide guidance / optimize the footprints.

**Comment by luis-valverde-ms** [comment]
Disabling the boundary system seems to reduce memory use a bit over 15 MB.

**Comment by googlan** [comment]
So, this turned out to be a bit vague issue. This is what I found out.
I used memory profiler package, which can be added into the project as described here:
https://docs.unity3d.com/Packages/com.unity.memoryprofiler@0.1/manual/index.html
There are other ones, which can be found in docs and on forums, but that's the only one, which reliably worked.
I compared memory snapshots for an empty scene in play mode and same empty scene with Mrtk added to it:
* First snapshot taken immediately after starting play mode. 
* Second snapshot taken after adding Mrtk to the scene while in play mode (so Mrtk is added and started immediately). Onscreen diagnostics bar has been disabled for this (diagnostics system was enabled, just no visuals).

I attempted comparing 2 different scenes, but the address space (especially for managed objects) between 2 play mode runs changes so much, that it becomes very hard to compare snapshots.

Numbers:
* "Baseline" for an empty scene -- 239 Mb.
* After adding Mrtk -- 321 Mb -- difference ~81.6 Mb.

From these 81.6 Mb:
* 73.7 Mb -- Shadow Map and Screenspace shadowmap render textures. 
These are initialized by Unity itself reliably when adding Mrtk and teared down when removing Mrtk. Some of Unity features, which Mrtk uses, must trigger this initialization, but I don't know exactly what. This allocation is, however, is not controlled by Mrtk.
* 6.8 Mb -- 2 Mrtk logos.
* 0.7 Mb -- other native allocations (predominantly icon textures).
* 380 Kb -- all managed allocations, including mrtk entities, services and preallocated data.

Of course, this is a snapshot of empty scene without any assets, but I believe from just these numbers we can make an assumption that Mrtk memory consumption doesn't come close to memory, taken by assets in the scene and Unity itself.
I'm closing this issue, as no action is required.

**Comment by Railboy** [comment]
>73.7 Mb -- Shadow Map and Screenspace shadowmap render textures.
>Some of Unity features, which Mrtk uses, must trigger this initialization, but I don't know exactly what. 

@googlan These will be created when you have:
 - A renderer with shadows enabled in the scene
 - A light with shadows enabled in the scene
 - Shadows enabled in your graphics / detail settings

Change any one of these and those textures get dumped.

**Comment by googlan** [comment]
Is it specific to the scene, or determined dynamically during scene life time?

**Comment by Railboy** [comment]
Scene life time. If you take snapshots over time you should see those textures getting created / dumped as those elements are added / removed.
