### ISSUE TITLE
ManipulationHandler uses incorrect origin when object origin is far from the object.

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedRealityToolkit-Unity#4910]
## Describe the bug

When manipulating an object using a ManipulationHandler and Solver it does not transform around the pointer position or the average of the two grab points. It appears to use the object origin, which in some cases will be a long way from the mesh or collider.

## To reproduce

1. Import MRTK
2. Import a mesh which does not have the origin in the center of the object. This would be the default when exporting as .obj or similar from a CAD platform. For example a cube from (10,10,10) to (11,11,11).
3. Attach a convex MeshCollider
4. Attach a ManipulationHandler
5. Manipulate the object and observe that it behaves unexpectedly (scales around a point a long way away, or moves in fast unexpected movements)

## Expected behavior

(5) The object would be transformed relative to the touch points, or have an option to use mesh origin or bounding box center.

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version v2.0.0 RC2.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

## Additional context

Reproduced for Julia at Hack Week.

**Comment by MenelvagorMilsom** [comment]
@camnewnham @julenka I've been working on fixes for this for a couple of days and I have a few concerns. Myself and @thalbern have been chatting about this.

1. We don't really want to add new features with GA coming up. Giving the option to switch between object origin and mesh origin isn't something we can't add right now. Even if we could, there would still be other issues (see point 3).
1. Given that we can't add this feature right now, we could at least fix it in cases where we do provide options. For example, using the `RotateAboutGrabPoint` option should fix this issue for rotation. However, it doesn't work for far interaction; the object still rotates around the origin. We can fix this (I have it working), but it's not a clean fix. Also, because things are still broken for translate and scale, manipulation overall still feels broken. I feel like this fix needs to be all or nothing for manipulation of these objects to actually feel correct.
1. With the way `ManipulationHandler` is currently set up, the changes required here are quite fundamental to the way we do manipulation. To get some things working I've added a bunch of hacky changes to some fundamental manipulation logic. They don't seem like safe changes so close to GA. The right changes would require an overhaul of a good portion of our manipulation code.

The problem is that `ManipulationHandler` is in a far from ideal state right now, and I'm not sure that we should hack further changes into it without overhauling completely. @julenka @thalbern I should be working on this still tomorrow, and I'll have a PR ready, but we should discuss if the changes are right for GA.

**Comment by julenka** [comment]
In near mode we could scale / rotate about the center of the hands, have you tried this approach?

**Comment by julenka** [comment]
For far interaction, for scaling and rotation perhaps we could have the component optionally specify the "scale rotation origin" -- a transform that we would scale and rotate about. Then for complex meshes people could in a prefab specify the actual origin to scale / rotate around. Would that work?

**Comment by camnewnham** [comment]
This issue primarily presents itself in models loaded at runtime, where the user will likely be providing geometry from an external source (i.e. a CAD platform, where geometry is defined relative to a different coordinate system). 
If the origin can be specified this would help, as procedurally generate it and specify it using either a vertex average or bounding box center. I'd rather this was built in though, to avoid having an extra transform in the hierarchy for every object just to record the center.

**Comment by MenelvagorMilsom** [comment]
So I'm not sure I was clear enough in my previous comment.

> In near mode we could scale / rotate about the center of the hands, have you tried this approach?

I have tried this, and got it working for one handed near interaction providing you're not using the `RotateAboutObjectCenter` option for near interaction. Getting it working for one handed near interaction was a very small change. However it didn't work for one handed far, or for two handed near or far. This is because one handed near interaction uses completely different move logic from the other types of interaction:

&#xfeff; | Near | Far
--- | --- | ---
**One Handed** | [ManipulationHandler](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae866a7b90660cb51bd0890780645f1fd78529e9/Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs#L621) | [TwoHandMoveLogic](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae866a7b90660cb51bd0890780645f1fd78529e9/Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs#L65)
**Two Handed** | [TwoHandMoveLogic](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae866a7b90660cb51bd0890780645f1fd78529e9/Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs#L65) | [TwoHandMoveLogic](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ae866a7b90660cb51bd0890780645f1fd78529e9/Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs#L65)

The problem is that when we apply rotation/scale in unity, it is always around the object origin. To counteract this we need to apply some offset translation in order to give the impression of rotating/scaling around a pivot point. We can do that easily in the one handed near interaction, but getting this offset translation to work with `TwoHandedMoveLogic` would require completely changing the way that class is set up.

So I did that. I made it pivot around the grab point for the four interaction types. I have it correcting properly for rotate and scale. I even made `TwoHandedMoveLogic` work for one handed near interaction too. It still looks a bit funny because of lerping, but the object you're manipulating always ends up where you're expecting it. 

So it's possible to get this working. But I still have concerns:

1. How do we expose this new behaviour to people? Do we add even more inspector options for `ManipulationHandler`? The amount of options, and how they interact, is already confusing enough as it is. Do we automatically use the grab point as a pivot for most interactions? What does that mean for options like `oneHandRotationModeNear` and `oneHandRotationModeFar`?
1. I'm not sure we want to change the fundamentals of `ManipulationHandler` translation so close to GA. The cleanest way to make these changes would require an overhaul of `ManipulationHandler`. Because we can't overhaul `ManipulationHandler` right now, my changes are hacky and forced.

@julenka @thalbern I'm not convinced that we should make this change now, when there are a number of workarounds inside and outside Unity ([including using Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/how-to-modify-the-pivot-point-of-a-3-d-model?view=vs-2019)). We should definitely give people this option in the future, but it should come alongside a `ManipulationHandler` overhaul, rather than hacking in a dirty fix. Should we reconsider having this issue as a GA blocker?

I'll create a PR this afternoon. Even though I have most things working, the changes aren't quite ready, and some tests are failing. However I'll create a PR so we can talk though some of the changes.

**Comment by julenka** [comment]
I agree given how close we are to GA we don't have time to overhaul manipulationhandler. If it's possible I do want to get this behavior fix in, though, since it does impact quite a few people. In the end, even if the code is hacky, if the behavior is correct then for the end user that's better than beautiful code that's not correct :-) Though of course beautiful code that's correct is best

> How do we expose this new behaviour to people? Do we add even more inspector options for ManipulationHandler? The amount of options, and how they interact, is already confusing enough as it is. Do we automatically use the grab point as a pivot for most interactions? What does that mean for options like oneHandRotationModeNear and oneHandRotationModeFar?

I would avoid adding more options. How about this:
* For near interaction we could modify scaling to scale about objects center.
* For far interaction we could modify scaling to scale about the average of the pointer endpoints
Incidentally I believe this is what the shell does.

For far interaction on HoloLens 2, I think grabbing the two pointer endpoints will also work, because the two cursor endpoints for the GGV Pointer will just be the gaze cursor position, so scaling will happen around the gaze cursor.

I actually just tested and realized that this is the behavior that the shell has. Sorry for not mentioning this earlier for the far interaction!

**Comment by MenelvagorMilsom** [comment]
> I would avoid adding more options. How about this:
> 
> * For near interaction we could modify scaling to scale about objects center.
> * For far interaction we could modify scaling to scale about the average of the pointer endpoints
>   Incidentally I believe this is what the shell does.

Ok, that's kind of the behaviour I was thinking of so I have a PR (#5379) that is a good portion of the way there. There are definitely a couple of things that still need fixing. We can discuss in there. However, I won't have time to continue working on this this evening. I'll fix those issues on Monday and we can discuss further. Thanks!

**Comment by Yoyozilla** [comment]
fixed
