### ISSUE TITLE
Sharing Stage Discovery Client fails to find systems to connect to

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#493]
When setting `AutoDiscoverServer == true` the Discovery Client fails to find server.

Repro Steps:

1. Open Sharing test scene.
2. Set `AutoDiscoverServer` to true on the sharing prefab.
3. Start `SharingService` from editor.
4. Observe that the client never connects.

**Comment by NeerajW** [comment]
@alexdrenea any thoughts here?

**Comment by DrNeuroSurg** [comment]
Any news here ?

**Comment by HodgsonSDAS** [comment]
I think part of the issue is embedded into the sharing service binaries that come from the main [HoloToolkit](https://github.com/Microsoft/HoloToolkit) (which is written in C++).

I've been doing a lot of work trying to make sure everything is working again with the test scenes.
Unfortunately I haven't gotten this to work.

**Comment by yacuzo** [comment]
I use the Holotoolkit library directly for sharing (not the scripts in this repo), and i have the same problem, so I made an issue at the Holotoolkit repo: https://github.com/Microsoft/HoloToolkit/issues/70.

**Comment by StephenHodgson** [comment]
https://github.com/Microsoft/HoloToolkit/pull/106

**Comment by davidkline-ms** [comment]
Should be fixed by #1670.
