### ISSUE TITLE
Error message spam when hitting play and switching tabs in the inspector of the MRTK gameobject

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#4944]
## Describe the bug

There's a constant error spam in the console whenever you hit play in unity and then switch the tabs in the property inspector of the MRTK gameobject

![image](https://user-images.githubusercontent.com/36998103/59694288-ab117900-91e8-11e9-9ba5-b7d1029f92a2.png)

## To reproduce

Create a new project
add the MRTK gameobject / playspace through the menu
hit play
select the mrtk gameobject
in the inspector click eg on the Teleport tab
![image](https://user-images.githubusercontent.com/36998103/59694367-cf6d5580-91e8-11e9-9ae8-8c108e587474.png)

## Your Setup (please complete the following information)

- Unity Version 2018.4
- MRTK Version v2.0 RC2.1

## Target Platform (please complete the following information)

- Unity

**Comment by Railboy** [comment]
This is caused by tab switching triggering a 'changed' event in the toolkit inspector, which tears down services. (The idea is if any profile has changed in any way we can't guarantee that service states will reflect the new profile data, so we tear everything down and start over.)

So we can break this down into two issues:
- Changing an inspector tab shouldn't trigger 'changed' in the inspector
- Tearing down services in play mode shouldn't cause errors

Related: #3945

**Comment by Troy-Ferrell** [comment]
@Railboy I agree, let's say issue #1 will be solved by PR = #4991

And leave issue #2 as tracked by #3945
