### ISSUE TITLE
Spatial Awareness not Enabled by Default

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#4945]
## Describe the bug

In all Spatial Mapping Profiles _including_ the one referenced by **DefaultHoloLens2ConfigurationProfile**, Spatial Awareness is not enabled by default.

![image](https://user-images.githubusercontent.com/5230670/59695117-fa0bde00-91e9-11e9-8e33-e7069c963ffd.png)

This easily leads to confusion when the app is run for the first time and no spatial map is generated.

## To reproduce

1. Create a new project
2. Import MRTK
3. Select **DefaultHoloLens2ConfigurationProfile**
4. Deploy the app
5. Run the app

## Expected behavior

The spatial mesh should appear by default. However, no spatial mesh appears.

## Your Setup (please complete the following information)

- Unity Version: 2018.4.2f1
- MRTK Version: mrtk_development (as of 2019-06-18)

## Target Platform (please complete the following information)

- HoloLens 2

## Additional context

I believe this should at least be turned on by default when selecting **DefaultHoloLens2ConfigurationProfile**. If we do not believe all HoloLens 2 applications will want spatial mapping, this is another vote for why we need #4005.

**Comment by Troy-Ferrell** [comment]
@jbienzms , Spatial awareness was disabled actually because of customer feedback. Many customer kept turning it off right away. Rendering the spatial mesh can be annoying but in particular, it impacts performance. Furthermore, the apps that do want spatial mapping also generally don't want it at startup but at a later point in the app design such as placement or alignment.

We could set the observer to "Manual Start" instead of "Auto start" but then that would be even more hidden for developers who do want spatial awareness but do not understand why it is not on when the tickbox is enabled. The top tickbox is at least the first thing one sees and disabled clearly means no system will be running. 

There is a spatial awareness doc section but it could be updated/cleaned up a bit I'd say:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.html

**Comment by jbienzms** [comment]
Wow, I truly find this fascinating. I think this may be a case of only hearing feedback from those affected. With it enabled by default we only hear feedback from those who don't want it on at all or those who want to manually enable it at a specific point in time. With it disabled by default we only hear feedback from those who just expected it to work right out of the box.

Without having any telemetry about how many have it on at the start of the application vs how many don't use it or defer enabling it, I really don't know which is the right default value. I guess documentation can help here, but I agree this could be called out a bit more prominently in the documentation. Big bold letters, highlight, or something. Unfortunately, many times the docs are only consulted once something doesn't work as epected, but at least the reason could be documented along with potentially some guidance about why it's not enabled by default.

**Comment by wiwei** [comment]
Yep, thanks for posting this @Troy-Ferrell

I can add a note to here for why:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Profiles/Profiles.html#hololens-2-profile
