### ISSUE TITLE
Hand mesh is too small

### ISSUE THREAD

**Issue by raguenon** [microsoft/MixedRealityToolkit-Unity#5008]
## Describe the bug

With some people, the hand mesh detected by the Hololens 2 is too small. Thus, some gesture and interactions are more difficult to perform (for exemple, the wrist button to access to the main menu appears inside the wrist, making it difficult to reach).

Note: This bug only appears on certain hands. In most cases, the mesh is well dimensioned.

## To reproduce

1. Start the Hololens
2. Look at left wrist
3. Try to interact with the main menu button

## Expected behavior

The button appears on the skin, being accessible by touch.

## Screenshots

Using MRC screenshot tools, RA holograms are not well aligned with the video background, thus, it is impossible to take a screenshot of this problem.

## Your Setup (please complete the following information)

- Unity Version 2018.4.2f1
- MRTK Version 2.0.0-RC2

## Target Platform (please complete the following information)

- HoloLens 2

**Comment by wiwei** [comment]
I *think* that what you're running into here is a HL2 operating system issue itself (i.e. from looking at the description above this doesn't seem to have anything to do with the MRTK.)

There's a couple of ways forward here:

1) You could file an issue using device portal (there's a way to file bugs using that, and you can use your desktop keyboard for typing).
2) You can file an issue through the feedback app on the HL2 itself.

I can follow up with the folks who know more about hand tracking on the OS side, though I'll close this issue out because it's not related to the MRTK
