### ISSUE TITLE
Add API on FocusProvider to override the focus point for a given pointer

### ISSUE THREAD

**Issue by kircher1** [microsoft/MixedRealityToolkit-Unity#5015]
## Describe the problem

If a pointer is locked to a target, the point is maintained in the targeted object's local space. This allows for dragging/rotating/scaling objects via their transform.

If however the object being targeted needs to update it's content in way that is not tied to the transform, then the pointer is not adjusted:

![Before](https://user-images.githubusercontent.com/20366429/59947910-602f7580-9423-11e9-9239-b78350710005.gif)

Here, panning the map does not mean translating the game object's transform. It means translating a lat-long center property. The focus provider has no context of this, i.e. the local space point is not changing, so while the map translates, the focus point remains fixed instead of tracking along with the map.

## Describe the solution you'd like

By adding an API on FocusProvider to set a focus point for a given pointer, the correct behavior can be achieved:

![After](https://user-images.githubusercontent.com/20366429/59947911-602f7580-9423-11e9-980d-cd8f9ceb5739.gif)

 This API could be pulled into the IFocusProvider interface, but that may be more of a breaking change. Even having this API on the default implementation would be helpful.

## Describe alternatives you've considered

I think it would be possible to achieve this behavior in a very roundabout way with the current system, using invisible colliders and carefully timing when the pointer is locked. That solution seems more complicated and prone to script ordering issues though, so having a direct API to set the focus point would be ideal.

**Comment by kircher1** [comment]
Possible fix provided by [this draft PR](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5016/files).

**Comment by naostranMS** [comment]
I like this, and similar ideas have been bouncing around in my head for a while.

A similar use case that might be worth considering: in our VR app, we "drag" assets out of the menu for placement. That means we get input down (and focus lock) on a piece of UI, spawn an asset, and then want to attach the pointer to the 3d model once it is spawned. I currently implement this with a custom cursor class that has an attach-to-object capability, but I think it could also be solved in a similar way to this by allowing a little more control over focus lock. E.g. In keeping with your draft PR, maybe there could also be a TrySetFocus that takes a GameObject and position and sets it up to track in the same way the auto-focus-lock does.

A couple of other possibilities I've considered:
1. IMixedRealityPointer could have a FocusModifier (similar to its CursorModifier - perhaps they could even be combined*) - it could potentially be set automatically by the focus target (again like CursorModifier) or could allow external users to set it
2. When FocusProvider updates focus-lock, it could use the pointer's Result.Details instead of it's own PointerData.Details - that would allow the pointer to modify its version of the FocusDetails, and have the FocusProvider respect and maintain the changes (e.g. in my use case above, if I were to change the target and local point/normal then I would expect FocusProvider to keep updating the point/normal to track the new target). This would probably mean most things should stop using TryGetFocusDetails as that wouldn't have the pointer's overrides (or the pointer would have to update the FocusProvider's pointer details when overridden) - but I also think the distinction between the different ways of getting a pointer's focus details is kind of murky currently and maybe should be clarified a bit.

I would prefer the functionality being on the pointer (or its target) rather than having to interact with FocusProvider, but I don't feel strongly about that. But if we do go with the latter, I'd definitely rather have it in the interface (or *an* interface that the default FocusProvider implements).

\* I actually kind of like the idea of using the same thing for focus lock and cursor modification, as it seems like in general the cursor should always be at the end point of the pointer, so they represent more or less the same thing. On the other hand, in the past I've felt that having the CursorModifier manage itself through focus change events constrained things too much (hence the custom cursor class attach functionality I'm using instead), so maybe it's not ideal for that reason. I also don't have any idea how CursorModifier is being used by others, so I'm not sure if that would entail a breaking change.

**Comment by kircher1** [comment]
These are good points @naostranMS. There may be a better architected solution for this sort of functionality, but so far I like the slimness and un-breakingness of the current change (which now includes a GameObject parameter). 

It would be great to get some more feedback on this from someone working directly in the FocusProvider area. @wiwei, would you help bring this to the right folks' attention?

**Comment by wiwei** [comment]
Super late response on my part - I took a look at the change and it seemed reasonable, though I'd probably want to get @julenka and @keveleigh's opinion on the linked changes:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5016
