### ISSUE TITLE
Add a default MRTK profile for HoloLens 1 Interactions

### ISSUE THREAD

**Issue by DrDecipher** [microsoft/MixedRealityToolkit-Unity#5046]
The original question / bug highlighted a gap in usability/configurability of MRTK for HoloLens 1. By default interactions are set up for HoloLens 2 and there's no easy way to get to a HoloLens 1 friendly MRTK profile. This item tracks adding a config profile that's hololens 1 friendly (for HoloLens 1 interactions). 

This profile should use Gestures input simulation mode instead of articulated hands to simulate how HoloLens 1 works.

# Original Question
Gaze cursor is no longer re-enabled after using the 'Hand' in the latest release and can not be altered manually via the inspector.

1. Press Play( Gaze Cursor will be visible/active highlighting correctly )
2. Hold Down the 'Space Bar' to engage 'Hand'.
3. Release 'Space Bar'
4. Gaze Cursor remains inactive and disabled.
5. Can not be activated in the inspector as something is turning it off per frame.

## Expected behavior
After using either 'Hand', the Gaze cursor should reappear and be active after releasing the space bar.

## Your Setup (please complete the following information)

- Unity Version 
Unity : 2019.1.6f1
- MRTK : MRTK RC2.1

Platforms
- HoloLens
- HoloLens 2

**Comment by wiwei** [comment]
This is by design AFAIK to be consistent with how the shell works (i.e. gaze cursor visible, then hand shows up, you have to say select order to get the cursor to show up again).

@julenka FYI, also to correct me if I'm wrong here.

Is there a specific scenario/use case that you're getting blocked on because of this?

**Comment by DrDecipher** [comment]
We are developing for both the HL1 and the HL2.  When testing we are often checking controls with an air-tap and a hand.  This type of behavior should not be hidden. As great as the MRTK2 is becoming there seem to be little consideration for the fact that many of us will be stuck in 'HL1 land' for the foreseeable future. _How can I reenable gaze it after the hand is used in the editor?_ Any assistance would be appreciated :)

**Comment by wiwei** [comment]
@julenka, Q for you, maybe a question for folks who don't want the default shell behavior that the MRTK is mimicing

**Comment by DrDecipher** [comment]
It would seem the behaviors don't need to be contradictory. I wrote a service simply to 'add back' the ability to use the 'left mouse' with gaze 'air-tap' that triggers the 'Select' event. All I need is the ability to get the gaze cursor back. I would really think this would be a good addition to the UI. H_ow can I re-enable/intercept whatever is forcing the cursor to be disabled?_ Upon release of the space bar I need the cursor back. Thank you again for the quick responses. **I know how much effort you all are putting into the tool kit and it is appreciated!**

**Comment by julenka** [comment]
Hi you can just press the “1” key and it will trigger a simulated “select” voice command, which will bring back the cursor. You can also press “1” to click items with that head cursor.

Sent from phone, please excuse typos.
________________________________

**Comment by DrDecipher** [comment]
That is something I did not know and a great workaround that I can use for now, but this is a bigger issue than is being recognized in this development. Please take the following as constructive and it is directed at the development as a who not you personally:)   Anyone who makes a living developing HoloLens applications needs to be able to use MRTK with the HL1 or we simply will not use MRTK wwhich would be a shame. We have clients, now, that we must test for and support. It is confusiong why the simplest of things to test HL1 apps where removed.  The HL2 has no timeline for release and it's being treated as if we are all developing for it right now.  I'm not proposing backward compatibility for anything in the old tool kit, just a workflow for the HL1 that does not require extra steps. You must understand when we are testing an enterprise application and send it to QA we can not provide extra steps to them, as it is easy to confuse a user error with a bug. Does that make sense? I asue you it's not intended as a rant ;)

**Comment by DrDecipher** [comment]
Thank you for entertaining this thread. I'm trying to get more of our team to use MRTK and the above mentions are a show stopper in production right now. It is possible to get the behavior back? 1: When releasing the spacebar to get the Gaze cursor. 2: Can '1' be remapped to Mouse 0 somehow. This is all we need to adopt MRTK fully.

**Comment by julenka** [comment]
> Anyone who makes a living developing HoloLens applications needs to be able to use MRTK with the HL1 or we simply will not use MRTK wwhich would be a shame. We have clients, now, that we must test for and support. It is confusiong why the simplest of things to test HL1 apps where removed.

There is a way to test HL1 behavior in the editor, although it's a bit hidden. The default hands that are enabled in MRTK are "HoloLens 2 hands" aka "Fully articulated hands". To get behavior that matches HoloLens 1, you will want to change your input simulation profile to use "GGV Hands" aka "HoloLens 1 hands". When you do that, you will see that when you let go of spacebar the gaze cursor will appear again.

## How to change input simulation profile (using MRTK RC2 release)
1) Select MixedRealityToolkit
2) Under Input, hit "Clone" to create a custom input profile
![image](https://user-images.githubusercontent.com/168492/60159612-76815c80-97a8-11e9-92a6-56fb2cb7e611.png)
3) Expand Input Data Providers, then under Input Simulation Service, clone to create custom input simulation profile
![image](https://user-images.githubusercontent.com/168492/60159631-85680f00-97a8-11e9-8b36-dc2524399786.png)
4) Now that you can customize the input simulation service, scroll down until you see "Hand Simulation Mode, and select 'Gestures' instead of "Articulated". 

![image](https://user-images.githubusercontent.com/168492/60159671-a03a8380-97a8-11e9-9bd5-69b58ac73188.png)


This will update the input simulation system so that the type of hands that will be used are HoloLens 1 hands, and then when you drop your hand, you will still see the cursor.

**Comment by julenka** [comment]
@wiwei maybe the action from this issue should be that we should provide a DefaultHoloLens1ConfigurationProfile? I've already started making one.

**Comment by julenka** [comment]
Hopefully this answers your question, hopefully I understood the question correctly. If you want more help with how to set up  MRTK so that you can test HoloLens 1 behavior in the editor, please consider asking a question on stackoverflow to ensure that others can also benefit and also in case somebody else can help answer.

**Comment by DrDecipher** [comment]
### _### **This is wonderful and thank you again for all of this! A HL1 profile would be a great addition to the Kit.**_ and I will decminate the above to our entire team.

**Comment by DrDecipher** [comment]
After a lot of testing we're still stuck so I have posted to Stack Overflow an extended explanation of the need. For anyone who finds this thread head here for more...
https://stackoverflow.com/questions/56821449/hl1-input-for-mrtk-v2-1

**Comment by michel-de-verdelhan** [comment]
Same problem here : We have applications we want to port to the new MRTK in order to run on futur Hololens v2, but we also need to support Hololens V1 for all our clients already using it.

the debugging in the editor is a real pain due to gaze cursor problem and we havn't found any way to simulate it properly.

**Comment by julenka** [comment]
> the debugging in the editor is a real pain due to gaze cursor problem and we havn't found any way to simulate it properly.

Have you found Gestures mode (see instructions above) sufficient? If not, what isn't working for you when you use Gestures mode?

**Comment by DrDecipher** [comment]
The issue is that in gestures mode MRTK2 buttons and UI elements are not triggered by the left mouse (Air-Tap) when using gaze.

Prior to 'Hand' emulation being added gaze and left mouse behaved as an air-tap. After they were added the left mouse no longer acts as an air-tap with the mode set to 'Gestures'. All you can do in Gestures mode is move the camera and see the gaze cursor, but no interaction. I believe it was mentioned that pressing #1 would initiate a 'Select', but there is no way to map this to the left mouse as it was with HL1.

We want the old behavior when set to Gestures. Left mouse = Select/Air-Tap/Press just like when you build to the HL1, but in the editor.

Does that make sense?

**Comment by DrDecipher** [comment]
I did post this to Stack Overflow and Slack as well, but have received no answers. :/ This seems so simple, but I have not found a way to accomplish it with the new emulation.

**Comment by julenka** [comment]
> I did post this to Stack Overflow and Slack as well, but have received no answers. :/ This seems so simple, but I have not found a way to accomplish it with the new emulation.

Hi sorry for not replying yet! We have seen your question and I've been thinking about it. I think I understand what you want but there's no built in way to do this. Trying to build something now.

**Comment by julenka** [comment]
Hi, I posted an answer that I think answers the question you asked. I provided a script that will allow you to simulate input down and up using just a mouse, without needing to bring up a hand. I think this is what you were asking, but not sure. It might help to edit the question down a bit to focus on just one specific question, to help folks better distill the actual question you're asking. Stackoverflow has a great [guide for how to ask good questions](https://stackoverflow.com/help/how-to-ask) that I would recommend reading.

I've also attached a .zip containing both the script that I think will solve your problem as well as a prefab showing how to use the script. Simply drag the prefab onto your scene to get the desired behavior.

[SO Mouse Only Input Simulation.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3429684/SO.Mouse.Only.Input.Simulation.zip)

**Comment by DrDecipher** [comment]
I will have an opportunity to test this in the next couple of days. Thank you for the effort in advance!

**Comment by DrDecipher** [comment]
This is exactly the behavior we have needed. Thank you so much for your effort. This is a little thing that is huge to us :)

**Comment by julenka** [comment]
> This is exactly the behavior we have needed. Thank you so much for your effort. This is a little thing that is huge to us :)

Glad it helped! Would you mind please marking the stackoverflow answer I wrote as the correct answer, and then upvoting, so others can also benefit if they look for the same info in the future?
