### ISSUE TITLE
show error when Build v2.0.0 RC2.1 in Hololens 1

### ISSUE THREAD

**Issue by IfnoLee** [microsoft/MixedRealityToolkit-Unity#5057]
## Describe the bug
require Windows 10 SDK 10.0.18362.0 ,but this SDK cannot run on Hololens 1( Hololens 1 was updated latest：10.0.17763.0)

## To reproduce

1. do not install  Windows 10 SDK 10.0.18362.0
2. open Build Window 

## Screenshots
![image](https://user-images.githubusercontent.com/38685433/60156150-6a37e680-981e-11e9-9fea-e02412634bd0.png)

## Your Setup (please complete the following information)

- Unity Version [2018.4.0f1 LTS]
- MRTK Version [v2.0.0 RC2.1]

## Target Platform (please complete the following information)
- HoloLens

**Comment by MenelvagorMilsom** [comment]
When building for either Hololens1 or Hololens2 you need 10.0.18362.0:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html?q=getting%20started#recommended-build-settings-uwp

**Comment by MenelvagorMilsom** [comment]
We recommend you set you build settings for "Target SDK Version" and "Minimum Platform Version" to what's shown in the picture below.
![image](https://user-images.githubusercontent.com/47415945/60178531-09a7aa00-981c-11e9-8feb-6dc516214d71.png)

**Comment by wiwei** [comment]
Yep, please grab the latest SDK. While there's some work happening that could help with allowing people to stay on an older SDK version, folks should be grabbing the latest and just using that.

If you have some specific reason that you can't move to the latest SDK because of issues you encountered, that would be interesting to know (feel free to reopen with comments on that if that's the case)
