### ISSUE TITLE
Add an outline in the MRTK shader

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#5063]
## Describe the problem

Hello, in many of our projects with have used an outline effect (to higlight objects) like these ones:

https://assetstore.unity.com/packages/vfx/shaders/fullscreen-camera-effects/outline-effect-78608
https://assetstore.unity.com/packages/tools/particles-effects/quick-outline-115488

However passing to MRTK 2 and single pass rendering broke these assets.
We are curently looking for an alternative but because MRTK2 shaders are recommended I am suggesting this feature.

## Describe the solution you'd like

The possibility in one of the MRTK shader to create a colored outline.

## Describe alternatives you've considered

Using an external asset but the shaders are not optimized for HL2 and are not working in Single Pass rendering.

note: the rim light effect does not meet the needs

**Comment by Cameron-Micka** [comment]
Hi @benjamincoven, I think this is a great suggestion for the MRTK shaders! I've built a few one-off prototypes for this type of effect. It has a few asset caveats at the moment. But, I'll see how best I can resolve them and merge them into the MRTK in the future.
 
Here is an example utilizing a modified version of the MRTK/Standard shader:
![Outline](https://user-images.githubusercontent.com/13305729/60206447-6ac58280-9808-11e9-8525-357e236f8139.gif)

**Comment by benjamincoven** [comment]
You are awesome, we would be very happy to test it as early as possible before the next MRTK release.

Also note that we had many problems with the previous outlines that we used in the asset store about the normal of the back faces (same as #4946 ), we are using the new MRTK standard shader of the last week.

**Comment by Cameron-Micka** [comment]
Sounds great, I'll be sure to post back here when I have a pull request for this feature.

**Comment by Cameron-Micka** [comment]
Hi @benjamincoven, a pull request is up for mesh outlines if you want to check it out: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5562

**Comment by benjamincoven** [comment]
Hi, thank you very much for your work.

Unfortunetly I have some issues with my meshes that are one sided. I tried to set the Cull mode to off on the outline material, it's slightly better but not totally smooth.

Also it looks like that the outline is not renderer when there is another object at the back.

Maybe I missed something when configuring my test?

Here some screenshots:

![image](https://user-images.githubusercontent.com/12698212/62771064-9e98f680-ba9c-11e9-9ea3-0a37bb97e02d.png)

![image](https://user-images.githubusercontent.com/12698212/62771085-aa84b880-ba9c-11e9-9db1-e92b41578c78.png)

![image](https://user-images.githubusercontent.com/12698212/62771123-c0927900-ba9c-11e9-8df7-c272a2f0ff1e.png)

**Comment by Cameron-Micka** [comment]
Thank you for testing it out so quickly! 

> Unfortunetly I have some issues with my meshes that are one sided. I tried to set the Cull mode to off on the outline material, it's slightly better but not totally smooth.

Sadly since this technique uses mesh extrusion flat-ish objects (or objects with a small volume compared to their surface area) don't extrude very well and break the effect. I would assume those card parts would extrude a bit better, but I'm not sure. Would you be able to attach those models for me to test out?

> outline is not renderer when there is another object at the back.

That is also true of this effect. One could get around this issue by playing with render queues and the stencil buffer. Maybe I should add that!

**Comment by jakub-wisniewski** [comment]
@Cameron-Micka Are there some other third-party outline assets that work for HoloLens? This one just doesn't work. It works only for simple meshes. I tried most of them including Quick Outline asset from Asset Store. But the performance drop is horrible. It requires anti-aliasing, and when I activate basic anti-aliasing x2 on HoloLens app the fps drops from 45FPS to 30 fps...

**Comment by Cameron-Micka** [comment]
Hey @jakub-wisniewski, I'm not aware of any third-party outline assets (since I've not tried any myself). But most outline methods these days rely on post processing (which is prohibitively expensive on mobile stereo headsets like HoloLens). 

The most popular non-postprocessing based outline method uses "inverted hulls" or "cracked shells" (more info [here](https://bgolus.medium.com/the-quest-for-very-wide-outlines-ba82ed442cd9)) this is what we use in MRTK. In Graphics Tools we've taken this system and extended it to be more flexible (it still has some caveats). I'd encourage you to try it and see if it works for your use cases: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/tree/main/com.microsoft.mrtk.graphicstools.unity/Runtime/MeshOutline

More details in this PR: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/pull/119
![image](https://user-images.githubusercontent.com/13305729/227273702-821f4335-88a0-4f11-9387-28a3c69bef91.png)
