### ISSUE TITLE
[Partner Hack] MRTK Extensibility

### ISSUE THREAD

**Issue by vijang** [microsoft/MixedRealityToolkit-Unity#5084]
Description: Partner feels MRTK v2 is great to get started quickly or for beginner developers. However for experimented dev, that have been around for a while, MRTK can feel restritive :

Too pre-baked features / behaviour
Not extensible / tweakable option or not enough.

This can help drive adoption and improve Developer Experience.

Sometime can be a blocker and force dev to use alternatives.

Partner: XXII
Filed for: @dacoppet  during Paris hack

**Comment by MenelvagorMilsom** [comment]
At the Berlin people are giving similar feedback. There's been a number of issues where people are finding MRTK impossible to extend components or configure them at runtime. Most people are just hacking MRTK components so that they can do what they want.

**Comment by wiwei** [comment]
The team has made some good progress in this area for some of the features (i.e. UX controls, raycasts, etc). 

I think that it's good to hear this general feedback, though I think the meta question I have is, it would be really helpful to have the specific ways in which things aren't extendable - this will help us identify:

1) What we should change and why
2) What the benefit is for changing it.

Without those specifics, we could do exercises where change a bunch of things, but we may not fully understand the value prop (i.e. WHO will benefit from this the most, or at all?)

I'm closing this out not because we fixed this (i.e. we did it, time to go home), but because we need more specifics and for folks who feel this way (they should!) please file specific issues for things that aren't extendable.
