### ISSUE TITLE
Remove InteractionReceiver since it is not being used by anything

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5139]
If InteractionReceiver is supposed to be removed from the Toolkit, stop reading and mark as closed.

## Describe the bug

While trying to find something in common between FocusEventData and BaseInputEventData, I stumbled across the BaseEventData.selectedObject. Searching for every appearance of it revealed that it's not assigned to even once in the whole Toolkit.
This also means that InteractionReceiver simply does not work as it depends on its existence when comparing with it's list of registered receivers.

## Expected behavior

Either InteractionReceiver gets removed or BaseEventData.selectedObject gets set

## Screenshots

![image](https://user-images.githubusercontent.com/32508825/60380943-b9b02980-9a4d-11e9-87cf-9afdc6404a83.png)

**Comment by julenka** [comment]
@killerantz FYI this is related to Interactables. Based on this bug I would guess that InteractionReceiver is not currently working. Perhaps we should consider removing it, since before this bug (found via code analysis), nobody has reported any issues. It makes me think it is not being used.

@killerantz  and @cre8ivepark  do you know of any cases where people are using interactable receiver?

**Comment by killerantz** [comment]
It was proposed at one time that Interactable might extend this class or something similar to handle some of the input logic. I like the idea of having a good code only example of handling input that Interactable could extend, but don't know enough to tell if this is the right class for that yet. I think we fixed a similar issue with Interactable recently as well.

**Comment by julenka** [comment]
> I think we fixed a similar issue with Interactable recently as well.

Could you please provide an issue number?

**Comment by killerantz** [comment]
I was referring to this issue, https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4611, but see that this is quite different. I thought the reference to selectedObject was checking to see if the object had focus, but it's just passing a null value to InteractionReceiver's virtual handler methods.

This class is good for the switchboard approach to handling input.

**Comment by julenka** [comment]
Hi @killerantz, since it is currently broken and we actually haven't seen any bugs, I would guess that very few people are using it, perhaps nobody is using it. If people were using it I would expect to see bugs filed saying "I am trying to use interactionreceiver but it is not working".

@cre8ivepark  and @killerantz  I'm also not seeing any documentation for the class, and it is referenced only once in the repository. 

```
git grep -i interactionreceiver                                                                        Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs:    public abstract class InteractionReceiver : BaseInputHandler,
```

It seems like it's a legacy component from HoloToolkit and I would argue for removing it, since there are already multiple ways to respond to input in MRTK. Please let me know if you object by Thursday EOD. I will create an issue to remove interactionrecevier if I don't hear back.

**Comment by killerantz** [comment]
No objections here.

**Comment by julenka** [comment]
@wiwei for this bug I know you have been wanting to deprecate e.g. PointerClickHandler, but interaction receiver is not used anywhere in the toolkit and also doesn't work currently. So, I would argue it would be better to remove it so people never use it, even if it is marked obsolete (since it doesn't work at all).

**Comment by wiwei** [comment]
I'm removing this, and given that it's broken, I don't think it's worth calling out in the changelog in GA.

For future folks if you're reading this and you WERE using this functionality, please reopen this issue (or a file a new one) with your use case.
