### ISSUE TITLE
[HL1] Cursor should follow the movement for manipulation 

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5183]
## Describe the bug
For GGV input in HoloLens 1, currently, MRTK's pointer/cursor does not follow on tap-and-drag gesture movement (grab point for manipulation/navigation and BB handle) which is confusing.

### Current MRTK behavior:
![MRTK_ContextualCursor0702b](https://user-images.githubusercontent.com/13754172/60564894-4856cc00-9d16-11e9-9145-d0bb85d785c3.gif)
![MRTK_ContextualCursor0702c](https://user-images.githubusercontent.com/13754172/60564896-4856cc00-9d16-11e9-92e4-9d9971450fb2.gif)

### Shell behavior:
Cursor follows the grab point 
![MRTK_ContextualCursorShell](https://user-images.githubusercontent.com/13754172/60565033-c5824100-9d16-11e9-9553-b7fe658f3e21.gif)
movement 

## Target Platform (please complete the following information)
- HoloLens

**Comment by julenka** [comment]
Would be nice to have this for GA but don't think it's required. However, it is a shell parity issue.

**Comment by MenelvagorMilsom** [comment]
It appears as if the reason this behaviour is no longer working for GGV is because `InternalGazePointer.RaisePointerDown` and `InternalGazePointer.RaisePointerUp` never appear to be called. The reason for this can be seen in `GazeProvider.OnInputDown`:
```
public void OnInputDown(InputEventData eventData)
{
    for (int i = 0; i < eventData.InputSource.Pointers.Length; i++)
    {
        if (eventData.InputSource.Pointers[i].PointerId == GazePointer.PointerId)
        {
            gazePointer.RaisePointerDown(eventData.MixedRealityInputAction, eventData.Handedness, eventData.InputSource);
            return;
        }
    }
}
```
Because the hand input sources do not have the `InternalGazePointer` in their pointer list, this condition does not pass when pinching.

As a result, `IsFocusLocked` is never being set to true, and the cursors position is never being updated as the focus object moves. 

I've hacked a proof of concept fix for this using reflection, and it seems to work well. I'll see if there's a proper way to ensure that these functions are being called.
