### ISSUE TITLE
Can't switch MRTK profile at runtime

### ISSUE THREAD

**Issue by fcagnetta** [microsoft/MixedRealityToolkit-Unity#5185]
## The bug
Scenario: single Unity project for multi-platform application. You cannot change the MRTK profile at runtime. For example, if you want to run something like: 

`if(MixedRealityToolkit.Instance.ActiveProfile != SomeProfile)
{
      MixedRealityToolkit.Instance.ActiveProfile = SomeProfile;
}`

It's ineffective. Am I wrong with these lines of code?

## Expected behavior
Dynamically change the MRTK profile at runtime.

##  Setup

- Unity Version: 2018.3.12f1
- MRTK 2.0.0 RC1

## Target Platform 
UWP:
- Desktop
- HoloLens
- HoloLens 2
- WMR immersive

**Comment by wiwei** [comment]
Huh, TIL

**Comment by wiwei** [comment]
Got a fix for this, will get this in soon.

I prioritized this because we shouldn't have things fundamentally broken on different locales

**Comment by Alexees** [comment]
Julia said it was like this up until now:
https://stackoverflow.com/questions/55945943/how-do-i-setup-a-single-application-for-cross-platform-deployment-using-mrtk/55946675#55946675

When do you think the change will be ready?

**Comment by wiwei** [comment]
Ahhh looking back at my own comments, these were not intended for this issue - this was supposed to be for the one around CSV parsing/writing (for the eye tracking examples).

Yes, this is a much larger underlying issue which we'll need to spend time to unravel. Costing at a pretty large number because of this.

**Comment by waldobronchart** [comment]
What's the latest on this issue? We're running into issues where we want to switch profile depending on platform: Quest, Hololens, Nreal....

**Comment by Alexees** [comment]
> What's the latest on this issue? We're running into issues where we want to switch profile depending on platform: Quest, Hololens, Nreal....

As far as I know, there is still no solution. The quickest and easiest way is to create a new scene for each target device, configured with their required MRTK. Then additively load those at runtime. You could name them all the same, only put them in different folder paths for your custom build pipeline to pick if you have one.

**Comment by fcagnetta** [comment]
@Alexees we do the same at the moment

**Comment by jelmerS2** [comment]
Are there any updates on this? I'm also developing a cross platform app and would like to switch profiles based on platform, if possible without doing scene loads etc.. 
(it also doesn't help that MRTK doesn't want to be a prefab, otherwise one could just spawn a preconfigured prefab based on the runtime platform). 
Could you set the profile at compilation time based on platform?
