### ISSUE TITLE
Adding NETFX_CORE compiler flag

### ISSUE THREAD

**Issue by DominicBoettger** [Microsoft/MixedRealityToolkit-Unity#522]
Hello guys,

i have a app for multiple platforms which I also want to release for Hololens.
To be able to share assets and prefabs I want to use the same project, but I get compiler errors as soon as the Toolkit is included because it's uwp code. I used the #if NETFX_CORE flag a few times and asked myself if you think it would make sense to add this to every c# script in the sources.
What do you think?

Best regards 
Dominic

**Comment by HodgsonSDAS** [comment]
There's already a PR https://github.com/Microsoft/HoloToolkit-Unity/pull/443 addressing some of these concerns (but instead it wraps everything in `#if UNITY_WSA`.

Here's a [poll over on the MSFT Developer forums](https://forums.hololens.com/discussion/6011/should-the-holotoolkit-unity-primarily-focus-on-the-hololens-platform#latest) that asks the community what they think.

IMO I think it's messy and doesn't address the problem very well.  If you need the sharing services for the application to talk to each other, that should port over fine without any extra work.

The downside is that you'd need to import your shared assets into each project which can be time consuming, unless you're using asset packages and have good modules setup in git.

I think the ultimate goal is to make everything compile and play nicely across platforms as some point, but I think the HoloToolkit-Unity has a little ways to go before we can start thinking about optimizations like this.

**Comment by DominicBoettger** [comment]
Should we close that issue as it's duplicated? I understand the decision and of course it's not the best solution to use compiler flags, but maybe it's a workaround as long as the toolkit is not compatible....

**Comment by HodgsonSDAS** [comment]
I wouldn't say it's a duplicate, because of how the issue is worded and it's solution, but I think that's up to you on if it's closed.  If you decide to close it, just be sure to comment your solution in the other issue, so others have a way to see it.

Yeah I think this is something we all need to discuss as a community and see if anyone has some clever ideas to fix this, without touching every class.

With that being said, I think it's super important for us to get cross compatibility at some point.

**Comment by zajako** [comment]
I'd rather messy code than code that prevents building the application on all non-Microsoft operating systems.

**Comment by StephenHodgson** [comment]
While I'm all for making the project cross platform, I think it's important to keep a few things in mind.
1. [Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
2. Maintainability (Messy code could potentially create more work for others in the future).
3. The main page clearly states that this project targets [Windows Holographic](https://github.com/Microsoft/HoloToolkit-Unity/blob/master/README.md).
>  The HoloToolkit is a collection of scripts and components intended to accelerate development of holographic applications targeting Windows Holographic.

**Comment by zajako** [comment]
Just because it targets Windows Holographics doesn't mean it should prevent compiling for other platforms. For example, I have a scene for mobile apps and a scene for hololens. The hololens uses scripts and features from the mobile scene. Due to unity not allowing scripts or folders to be excluded from specific builds, it means we have to do this via pre-compiler tags in the scripts.

Another solution could be to have the entire set of c# scripts compiling into one External Plugin for unity. Which can be excluded from all other platforms.

As for pre-compiler tags being messy, I honestly think all pre-compiler tags look bad, however, they are a requirement for multi-platform and Unity.

**Comment by StephenHodgson** [comment]
> Another solution could be to have the entire set of c# scripts compiling into one External Plugin for unity. Which can be excluded from all other platforms.

I really like this idea. In fact I've played around with the some builds like this and it also helps cut down compile time.

I think the project could be refactored a bit more to to compartmentalize the platform specific stuff a bit more is all.  I think the general focus for MSFT has been Windows 10 Only, which is their OS so it makes sense.  FYI, the [sharing service](https://github.com/Microsoft/HoloToolkit-Unity/tree/master/Assets/HoloToolkit/Sharing) is definitely portable.  IMO it's really the only important part for cross platform support, where all the other features focus on Spatial Understanding and Windows Holographic Input support.

> Also pre-compiler tags are a fact of life for Unity development

😆 Isn't that the truth!

**Comment by StephenHodgson** [comment]
@DominicBoettger is this still an open issue?

**Comment by DominicBoettger** [comment]
Hi @stephenhodgson,

I think this is solved.... 
Thanks!
