### ISSUE TITLE
Copying assembly InputSimulation.Editor.dll failed

### ISSUE THREAD

**Issue by djee-ms** [microsoft/MixedRealityToolkit-Unity#5222]
## Describe the bug

Copying assembly from 'Temp/Microsoft.MixedReality.Toolkit.Services.InputSimulation.Editor.dll' to 'Library/ScriptAssemblies/Microsoft.MixedReality.Toolkit.Services.InputSimulation.Editor.dll' failed

## To reproduce

1. Create a new project with Unity 2019.1.8f1
2. Import MRTK 2.0.0 RC2.1 Foundation + Examples
3. Search in the Assets browser for Slate.prefab
4. Drag it into the Hierarchy view to create an instance

## Expected behavior

No error message

## Your Setup (please complete the following information)

- Unity 2019.1.8f1
- MRTK Version 2.0.0 RC2.1

## Target Platform (please complete the following information)

Editor issue

## Workaround

Restart Unity several times and/or try to manually copy the file. The error message eventually went away.

**Comment by wiwei** [comment]
This is an issue caused by the interplay between some OS code on 1903, and more prevalent on the MRTK because the of the amount of asmdefs we have + other assets that get moved around.

I'm not sure exactly when the OS fix is going to happen, but there's nothing for us on the MRTK that we can do. You can repro the exact same thing with any other arbitrarily large set of code.

**Comment by keveleigh** [comment]
Another workaround is to right click on the offending .asmdef and select `Reimport`:
![image](https://user-images.githubusercontent.com/3580640/60826837-a4c94980-a163-11e9-9c9e-7775b6658640.png)
