### ISSUE TITLE
MRTK 2 generates errors on Hololens 1

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#5226]
## Describe the bug

When starting my application using MRTK 2 on Hololens 1, I get some errors thant does'not occur in the editor (we capture them with a custom log tool). I have not noticed any feature of the MRTK2 that would be affected by this, everything seems to work fine.

```
NullReferenceException: Object reference not set to an instance of an object.
  ?, line 0, in Microsoft.MixedReality.Toolkit.Input.GGVPointer.OnPreSceneQuery ()
  ?, line 0, in Microsoft.MixedReality.Toolkit.Input.FocusProvider.UpdatePointer (Microsoft.MixedReality.Toolkit.Input.FocusProvider+PointerData pointer)
  ?, line 0, in Microsoft.MixedReality.Toolkit.Input.FocusProvider.UpdatePointers ()
  ?, line 0, in Microsoft.MixedReality.Toolkit.Input.FocusProvider.Update ()
  ?, line 0, in Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<UpdateAllServices>b__68_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service)
  ?, line 0, in System.Action`1[T].Invoke (T obj)
  ?, line 0, in Microsoft.MixedReality.Toolkit.MixedRealityToolkit.ExecuteOnAllServices (System.Action`1[T] execute)
  ?, line 0, in Microsoft.MixedReality.Toolkit.MixedRealityToolkit.Update ()
```

and

```
Holographic library PerceptionRemotingPlugin: Failed to load dll
  ?, in Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.BaseWindowsMixedRealitySource:UpdateTriggerData(InteractionSourceState, MixedRealityInteractionMapping)
  ?, in Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.BaseWindowsMixedRealitySource:UpdateController(InteractionSourceState)
  ?, in Microsoft.MixedReality.Toolkit.WindowsMixedReality.Input.WindowsMixedRealityDeviceManager:InteractionManager_InteractionSourceDetected(InteractionSourceDetectedEventArgs)
  ?, in UnityEngine.XR.WSA.Input.InteractionManager:OnSourceEvent(EventType, IntPtr, InteractionSourcePressType)
```

## Expected behavior

No errors

## Your Setup (please complete the following information)

- Unity Version 2019.1.8
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by wiwei** [comment]
@benjamincoven, is this a HL1 remoting scenario? (i.e. connecting to HL1 via holographic remoting?).

Or is this what's happening when deployed to the device?

Do you have any other details on when the exceptions occur (i.e. looking away from an object, starting to look at an object), or anything else that would be helpful in us being to repro this issue?

**Comment by benjamincoven** [comment]
This is not a remoting scenario, WSA Holographic Remoting Supported is unchecked, the application is deployed on the device.

The errors occur at the start of the application.

**Comment by wiwei** [comment]
Alrighty, sorry for the delay here. There are a couple of things here that I can address individually:

1) For the first error (GGV) - I tried this out on latest mrtk_development on a HL1 device, and wasn't hitting this (either in the debug output, or by just setting a debug break on all managed exceptions and watching for it to it). If you have a scene/project/code you can attach that I can use to repro this against the latest mrtk_development, definitely attach that.

2) I think that the second error is a side effect of us checking to see if remoting is active - i.e. in order to the workaround that is mentioned here: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4380/files, we have to check to see if remoting is active, and if so, we have to the engage that workaround. The message itself is benign, and should go away once that underlying Unity issue is fixed (and thus, we can remove the workaround).

I'm going to close this one out for now because I haven't been able to repro the first thing, and the second thing is an artifact (somewhat out of our control, because we need to ask if remoting is active, and the act of doing so causes unity to try to load that DLL, which obviously fails when run on the real device, but utltimately has not negative effect). If you're still seeing this on mrtk_development (or our next upcoming release) please reopen with the stuff you're using to repro it!
