### ISSUE TITLE
Clipping plane not working on Hololens 1 in some cases

### ISSUE THREAD

**Issue by benjamincoven** [microsoft/MixedRealityToolkit-Unity#5239]
## Describe the bug

I am trying to add a clipping plane feature in my application using the MRTK standard shader. It works very well in the editor but once in the Hololens it doesn't.

I tried to build the project with the material gallery demo scene and here the clipping plane works. I surely missed something and maybe it's not a MRTK bug, but I can't figure what is the problem.

## Screenshots

in the editor

![image](https://user-images.githubusercontent.com/12698212/60872397-e544c800-a234-11e9-9fb4-7bda0afe0837.png)

![image](https://user-images.githubusercontent.com/12698212/60872814-a7946f00-a235-11e9-8bc2-3cce53b3e01c.png)

I am using the shader from  #4946

in the Hololens 1

![image](https://user-images.githubusercontent.com/12698212/60872647-5b492f00-a235-11e9-8ea0-8588a16ea39e.png)

## Expected behavior

Clipping plane works as in the editor

## Your Setup (please complete the following information)

- Unity Version 2019.1.8
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- HoloLens 1

**Comment by keveleigh** [comment]
@Cameron-Micka, any ideas?

**Comment by Cameron-Micka** [comment]
@benjamincoven what I'm guessing is going on is that particular shader permutation isn't getting included with the build at build time. Can you check in the material's YAML text if the "_CLIPPING_PLANE" shader keyword is included? It might look something like this: `m_ShaderKeywords: _CLIPPING_PLANE, ...`

Since in your screenshot it looks like you have the "_CLIPPING_PLANE" keyword enabled I'm guessing the ClippingPlane script is turning off that keyword automatically for you (maybe on scene onload?).

I plan to included all the clipping permutations in builds to allow developers to turn these features on dynamically, I just need to verify it doesn't explode our shader permutations.

**Comment by Cameron-Micka** [comment]
One thing to try is check the "Clipping Plane" checkbox to enabled on the material before opening your scene/prefab that has the ClippingPlane component.

**Comment by benjamincoven** [comment]
Thanks for your help.

The material YAML has the _CLIPPING_PLANE keyword, I tried this on one of the MeshRenderer:

```
void Update()
    {
        Debug.Log(Renderer.material.IsKeywordEnabled("_CLIPPING_PLANE"));
    }
```

It's true.
The material Clipping Plane property is true in the project, so it should be already enabled on scene load and the ClippingPlane is also in the scene YAML so it should load also on scene load.

**Comment by Cameron-Micka** [comment]
That's interesting, thank you for checking if the keyword is enabled. I'm about to make a pull request which makes the toggling on/off the clipping primitives at runtime more robust (and should hopefully fix this issue). If you want a preview, here is my branch based off of mrtk_development: https://github.com/Cameron-Micka/MixedRealityToolkit-Unity/tree/clipping_fixes

**Comment by Cameron-Micka** [comment]
@benjamincoven I've created a PR to hopefully address this issue: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5291

**Comment by benjamincoven** [comment]
I confirm that the PR fix this issue. Thank you!

**Comment by Cameron-Micka** [comment]
Yay! Thank you for checking it out.
