### ISSUE TITLE
Tests for objects being disabled or destroyed during interaction

### ISSUE THREAD

**Issue by lukastoenneMS** [microsoft/MixedRealityToolkit-Unity#5243]
ManipulationHandler does not seem to gracefully handle the case where an object gets destroyed while it is manipulated. I assume this situation exists with many other interactions, e.g. buttons being disabled on click.

Augment tests for ManipulationHandler, Touchable, Grabbable, PressableButton, etc. where the GameObject is disabled or destroyed during the interaction, and make sure the handlers catch this case and stop the interaction when needed.

**Comment by julenka** [comment]
@lukastoenneMS or @thalbern  is this something one of you could help with?

**Comment by MenelvagorMilsom** [comment]
There's a couple of little things I've already noticed that I can fix and add tests for. One big thing causing weirdness when you destroy a focused `GameObject` is that you don't get any focus exit events when the object is destroyed:
![image](https://user-images.githubusercontent.com/47415945/63524198-80e37c80-c4f3-11e9-8df9-bfc38db5390a.png)
`pointer.PreviousPointerTarget` and `pointer.CurrentPointerTarget` both go from being the focused `GameObject` one frame to `null` on the next. Because they're never different, no focus change is detected and no focus exit is called.
