### ISSUE TITLE
Windows SDK 18362 on Hololens 1 (build with MRTKv2 RC2.1)

### ISSUE THREAD

**Issue by timgoeij** [microsoft/MixedRealityToolkit-Unity#5246]
## Describe the bug

When building the ObjectCollection sample in unity it builds correct, when deploying in vs2017 to HoloLens 1. I get folowing two errors described in the screenshot. 

## To reproduce

1. Go to 'ObjectCollection Sample.'
2. Place Object Collection Sample in Build Settings
3. Build the application with MRTK Build Menu
4. Open visual studio project in VS2017
5. Deploy application to HoloLens 1
6. See Errors

## Expected behavior

A deploy at HoloLens 1 without compile errors in VS 2017

## Screenshots

![image](https://user-images.githubusercontent.com/16646729/60901312-04138080-a26e-11e9-84b4-c15bd0b71380.png)
![image](https://user-images.githubusercontent.com/16646729/60901465-4e94fd00-a26e-11e9-9c4e-b619c73748c6.png)
![image](https://user-images.githubusercontent.com/16646729/60901508-5fde0980-a26e-11e9-9b8f-e1ff20855d9b.png)

## Your Setup (please complete the following information)

- Unity Version [e.g. 2019.7.1f1]
- MRTK Version [e.g. v2.0.0 RC 2.1]
- VS2017 15.9.13

## Target Platform (please complete the following information)

- HoloLens

## Additional context

I have tried both the recommend settings for MRTK 2.0.0 RC 2.1 and the build settings for HoloLens 1

**Comment by wiwei** [comment]
@timgoeji, can you re-type the Unity version? I think that there's just 2019.1, 2019.2, 2019.3, 2019.4.LTS.

The configuration looks to be okay (i.e. especially the one that says "any device" up top)

**Comment by timgoeij** [comment]
@wiwei

I am sorry, it must be Unity 2019.1.7f1

**Comment by Yoyozilla** [comment]
@wiwei any update?

**Comment by wiwei** [comment]
Sorry for the delay here - I'll have access to my device again tomorrow and will add this to my TODO list for Thursday.

**Comment by wiwei** [comment]
Okay I just gave this a shot on latest 2019.1.xf, I was able to deploy to HL1.

This looks very similar to:
https://developercommunity.visualstudio.com/content/problem/376860/hololens-uwp-app-deploying-to-local-machine-receiv.html

@timgoeij, can we try something here - if the MRTK isn't involved at all (i.e. just build an empty scene and deploy to HL1) do you get the same error?

i.e. if you follow https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-101

This seems like it's probably something to do with Unity/VS/HL1.

It might be worth also sharing out the generated .sln (and assets) so that we can see if we can repro with that (and thus if it's a device issue, or software/configuration issue)

**Comment by timgoeij** [comment]
@wiwei

At the moment I am very busy, I hope I can try it next week.

Also I don't know I can share the project files because this not mine project but for the company I work for. I let you know when I have more info.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by wiwei** [comment]
@timgoeij Understood! Whatever data you can share would be helpful for us.

**Comment by timgoeij** [comment]
@wiwei 

https://we.tl/t-tUtqFDL3jD

With this link you can download the whole the solution that unity has generated from our project with the build files. which vs has made when we deploy to the HL1.

**Comment by Troy-Ferrell** [comment]
@timgoeij, you need an earlier version of the windows 10 SDK installed when building. 
https://blogs.windows.com/windowsdeveloper/2018/10/02/start-developing-on-windows-10-october-2018-update-today/

Then in Visual Studio, not Unity, right click the UWP project -> Properties -> Under General tab in the popup window, change **Target Platform Version** to 10.0.17763.0 or lower

**Comment by Troy-Ferrell** [comment]
@timgoeij
If using the build window, this is probably fixed by #5877 

Try building with regular Unity build: 

In the VS solution, not Unity, right click your UWP project and select Properties. Then under the General tab make sure
Target Platform Version => 10.0.18362.0
Target Platform Min Version => (basically anything but will probably be 10.0.10240.0)

**Comment by IfnoLee** [comment]
Same problem ，but my project using SDK MRTK v2.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6116
