### ISSUE TITLE
Rotation constraints are ignored during one handed movement

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5305]
## Overview
Manipulationhandler has section "constraints on rotation". These are applied when doing two handed rotation, but are ignored when doing one handed movement.

Note: after this bug fix, the rotation mode "gravity aligned face user" is no longer needed, so I would recommend removing it (or marking it as deprecated somehow).

## Steps to reproduce
Configure handler for one handed movement - face user, and then set "rotation constraint" to "y only".

## Expected Behavior
Object will face user, but rotate only about Y axis

## Actual Behavior
Object faces the user, including rotation about the x axis.

**Comment by wiwei** [comment]
@julenka Marking as deprecated/obsolete would be best.

**Comment by thalbern** [comment]
@julenka the current implementation of constraints is that they're only applied to one hand manipulations that don't perform any auto orientations on the object. I suppose that was done because some of the rotation modes wouldn't make sense with the constraints in place. 

So constraints currently work for:
- rotateaboutgrabpoint
- rotateaboutobjectcenter

We could move that code that scales the rotations out of that specific section and apply it to all rotation modes instead

**Comment by julenka** [comment]
> We could move that code that scales the rotations out of that specific section and apply it to all rotation modes instead

That's what I was thinking. I had written the original code, but when I revisited my own design last week I found it confusing / not intuitive that the rotation constraints did not apply to the one hand modes.
