### ISSUE TITLE
The keyboard inserts an extra character into input fields

### ISSUE THREAD

**Issue by joshshadik** [microsoft/MixedRealityToolkit-Unity#5310]
## Describe the bug

When building with Unity 2019.1.9f1, the system keyboard comes up automatically when focusing on text input fields. It has an issue where it will automatically insert a lower-cased version of the first character typed, after hitting another key.

## To reproduce

1. Launch the HandInteractionExamples demo scene
2. Go to the section "Unity UI Interaction"
3. Scroll down to one of the text input fields
4. Click on input field
5. After the keyboard comes up, backspace to clear the input
6. Try typing something with the keyboard

## Expected behavior

The keyboard functions as it normally does

## Screenshots

[20190715_111402_HoloLens.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3392964/20190715_111402_HoloLens.zip)

## Your Setup (please complete the following information)

- Unity Version 2019.1.9f1
- MRTK Version v2.0.0 RC2.1

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by wiwei** [comment]
@joshshadik, have you tried this (and have you hit this) on 2018.4.latest as well? I'm curious to know if this is a 2019-specific issue

**Comment by joshshadik** [comment]
@wiwei Yes, I did try in 2018.4 and did not experience this issue

**Comment by wiwei** [comment]
Okay I'm going to followup with the keyboard owner on the OS side to see what's going on here - this is probably something going wrong between Unity and the underlying platform.

**Comment by FlorianJa** [comment]
This issue also appears in the OpenFileDialog (FilePicker)

**Comment by wiwei** [comment]
@FlorianJa, thanks for the heads up!

**Comment by wiwei** [comment]
Following up on this, we had someone on the Keyboard/Input teams on the HoloLens OS take a look at this, and based on their findings we've filed a Unity bug:

http://fogbugz.unity3d.com/default.asp?1184623_tc8dspq998n6q4ch

I'm closing this issue not because it's not an issue (it is), but because it's not specifically an issue in the MRTK itself (i.e. this is something that the MRTK is not involved in beyond connecting the dots to ensure that the keyboard does get shown).
