### ISSUE TITLE
HoloToolkit-Unity 2017 release plans

### ISSUE THREAD

**Issue by NeerajW** [Microsoft/MixedRealityToolkit-Unity#536]
Hello,

To make the release cadence more predictable and defined, we will mark a release of the code base in the first week of every month.

1. This gives us set timelines to plan our apps and when to move forward.
2. Makes it easier to keep track of what changes are going into every release.
3. You can update to latest more often rather than one big unity package which changed a lot.
4. Folks should also avoid breaking changes as much as possible unless there is huge value in doing so.

Thank you for all the awesome work and feedback!

**Comment by HodgsonSDAS** [comment]
@NeerajW, I think another good way to plan releases is with each Unity Editor update that makes big updates to the HoloLens platform, so we can stay fairly current as well.

**Comment by davidkline-ms** [comment]
I would like to suggest marking any breaking change pull requests using the newly added BREAKING CHANGE label.
This will allow reviewers to easily spot breaking changes.

Thanks@

**Comment by HodgsonSDAS** [comment]
Also having a separate branch just for releases would be good as well.

That will make VS studio build integration easier because I think builds only get triggered from pull requests that are native to the repository.

**Comment by HodgsonSDAS** [comment]
http://www.infoworld.com/article/3171380/cloud-computing/visual-studios-cloud-ide-gets-smarter-about-builds.html

**Comment by NeerajW** [comment]
We should only create branches if we intend to maintain them. We currently don't merge fixes back and forth between branches so I have not found a reason yet. What do you think?

**Comment by HodgsonSDAS** [comment]
I think the Release Branch would only get pushed to trigger builds.

**Comment by HodgsonSDAS** [comment]
@NeerajW, I would like to make sure those sharing services are updated before we make our first 2017 release.

**Comment by thebanjomatic** [comment]
To clarify because the title is a little ambiguous, are we talking releases of HoloToolkit-Unity this year, or are we talking specifically about new release policies starting with the Unity 2017 release in a few months?

**Comment by thebanjomatic** [comment]
Monthly releases sounds OK, but that feels a bit slow to me. Infrequent releases means more changes are going into a given release which increases volatility and makes it harder to update when breaking changes do happen. Additionally, when you are waiting for that one bug fix, its kind of a pain to have to wait an entire month.

I have a couple thoughts on this: 
1. There could be a branch for each release.
2. A best effort would be made to support the current release with bug fixes patched back from master.
3. Anyone who is holding onto an older release due to breaking changes can submit PR's for fixes targeting those branches, though upgrading may be preferable.
4. Patch releases would be made on the stable branch more frequently (weekly? daily? per change?)
5. Features and larger changes would continue to target `master` only, and follow the monthly release schedule.

**Comment by StephenHodgson** [comment]
Should we close https://github.com/Microsoft/HoloToolkit-Unity/issues/217 in favor of this issue?

It addresses everything we were talking about minus the releases on the Asset Store.

**Comment by StephenHodgson** [comment]
This info is now detailed on the main readme page
