### ISSUE TITLE
HandInteractionExamples scene drops to 30 fps after I drop the coffee cup

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5382]
## Overview
The handinteraction scene should always run at 60 fps to provide a good experience on hololens 2. 

To repro:
1. Grab latest mrtk_development
2. Build for arm, Release build.
3. Ensure no hands are up, notice we are at 60 fps.
4. Go over to where the cubes, lunar module, and coffee cup are, and drop all of them.
5. The coffee cube and module may re-appear after you drop them. Keep dropping them until they get to a mode where they don't reappear (they will start moving very quickly).
4. Bring up one hand, notice framerate drops to 33
5. Bring up second hand, notice framerate drops to 18.

**Comment by julenka** [comment]
Argh, this is not reproducing for me after I re-deployed. I'll close for now until I have reliable repro steps.

**Comment by julenka** [comment]
Okay, figured out the repro steps!

**Comment by Troy-Ferrell** [comment]
very interesting, I added a respawn script to bring the coffee cup back to the table after falling some distance. It would probably be good to update that script to also set reset forces, i.e
rigidbody.velocity = Vector3.zero; rigidbody.angularVelocity = Vector3.zero

What do you mean by doesn't re-appear? Because it keeps falling through the table between frames since it's going so fast?

Also it's interesting that the framerate only drops in this scenario when you raise your hands. 

I also wonder what link we have to physics impact also talked about in #4863

**Comment by Yoyozilla** [comment]
@julenka  Is there some fundamental issue that is causing the fps drop? If this is only in the example scene, i would suggest we address this after GA as an update.

**Comment by wiwei** [comment]
Based on the information here so far, I'm removing the GA Blocker tag - we should look into this soonish because it's still the bellweather scene we use to validate that things are good.

**Comment by julenka** [comment]
@yoyozilla I think the problem is not so much with the MRTK input system but with Unity's physics queries getting slow when there are fast moving objects in the scene. The drop to 30 fps happens when the cup drops, falls down to -Float.MaxValue, then wraps around to fall from Float.MaxValue, with some very high speed.

**Comment by wiwei** [comment]
Closing this one out, as @Troy-Ferrell just fixed the coffee cup drop issue.
