### ISSUE TITLE
Cannot Interact With Unity Canvas or Manipulation Handler on Mobile Device / Android

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5390]
## Overview
MRTK supports Android, and therefore touching a button on UnityUI canvas that's in world space should cause the button to respond.

## Steps to reproduce
1. Open MRTK HandInteractionExamples scene
2. Connect to Android device via remoting
3. Make sure the canvas is in world space
4. Try tapping on a button on a UnityUI canvas, and moving an object that has manipulationhandler, and 

## Expected Behavior
1. The button clicks
2. When you drag an object, the object moves.

## Actual Behavior
1. Hover events work (you can move your finger around and the buttons turn orange), but clicking does not work.
2. Dragging finger moves the camera, not manipulationhandler.

## Unity Editor Version
2018.4.4f1

## Mixed Reality Toolkit Release Version
RC2

**Comment by julenka** [comment]
I have a workaround working, need to clean up the code still. Workaround posted here:

https://gist.github.com/julenka/ccb662c2cf2655627c95ffc708cf5a69

**Comment by jbienzms** [comment]
Thank you so much Julia for working on this. Do you know if your fixes address any of the issues outlined in this Stack Overflow post? 

https://stackoverflow.com/questions/56846672/how-can-i-configure-mrtk-to-work-with-touch-input-in-editor-and-on-mobile-device

Or do we need to create a separate issue for these?

1. Dragging on a touch screen with a finger moves the camera (editor). Disabling the InputSimulationService fixes this, but then I'm unable to move the camera...
2. Even with the camera disabled, clicking and dragging does not affect the ManipulationHandler.
3. The debug rays are drawn in the correct direction, but the default touchpointer rays draw in strange positions. I've attached a .gif explaining this. This is using touch input in the editor. The same effect is observed running on device (Android).

**Comment by julenka** [comment]
> Do you know if your fixes address any of the issues outlined in this Stack Overflow post?

I believe the workaround addresses the issue in the SO post.

> Dragging on a touch screen with a finger moves the camera (editor). Disabling the InputSimulationService fixes this, but then I'm unable to move the camera...

My environment did not repro this -- are you on latest? InputSimulationService should not be running on Android or iOS.

> Even with the camera disabled, clicking and dragging does not affect the ManipulationHandler.

I believe the workaround addresses this.

> The debug rays are drawn in the correct direction, but the default touchpointer rays draw in strange positions. I've attached a .gif explaining this. This is using touch input in the editor. The same effect is observed running on device (Android).

Haven't tested this yet.

**Comment by jbienzms** [comment]
Hey @julenka,

> InputSimulationService should not be running on Android or iOS.

I believe Cam was referring to having InputSimulationService running in the editor and the problem of touch rays not doing what is expected in the Unity Editor when running the editor on a machine with a touch screen. I experienced strange behaviors too. I am going to see if I can get Cam to participate in this discussion since he was the original reporter.

Also, for completeness I wanted to capture all of the history and feedback so far that we have discussed.


### Overall

Slack user Cam Newnham was asking for ARFoundation support [here](https://holodevelopers.slack.com/archives/C2H4HT858/p1562649207467900):


### Cameras

Information about what Cam needed to do to get ARCore working with MRTK camera system can be found [here](https://stackoverflow.com/questions/56846672/how-can-i-configure-mrtk-to-work-with-touch-input-in-editor-and-on-mobile-device).


### Touch Input

The MRTK team has already started working on touch screen as input. Specifically the classes [UnityTouchDeviceManager](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.UnityInput.UnityTouchDeviceManager.html) and [IMixedRealityTouchPointer](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.IMixedRealityTouchPointer.html) but Cam says there seem to be issues with touch pointers. Read about how Cam configured MRTK to work with touch as well as the issues he experienced [here](https://stackoverflow.com/questions/56846672/how-can-i-configure-mrtk-to-work-with-touch-input-in-editor-and-on-mobile-device).

Cam started making some edits to the input system to try and fix them. Those edits can be found [here](https://gist.github.com/camnewnham/d0c4d3a8361ace1d3b9c8cdb16820e6c). However, even after incorporating these changes it seems the touch rays do not cast as I would expect them to. Something still seems off.

Finally, be aware that even with these changes, pointers (touch events) still do not raise input actions. I addressed this in #5342 which currently has an outstanding pull request.

**Comment by camnewnham** [comment]
Hi all,
Thanks for looking into this. A couple of things to note:

### Pointers & Debug Rays

I created a custom pointer (same behaviours, different UI) as casting a visible ray from the touch position (or, not from the touch position) on a mobile device seems counter-intuitive. This was as a work around the the issue which I've added here as requested: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5420

### InputSimulation
As far as running the InputSimulationService with touch gestures, an example:
- I create a scene with a simple cube and manipulationhandler, MRTK configured for touchpointers.
- With inputsimulation off, I can use two fingers (on touch screen laptop, running in editor) to manipulate the cube.
- With inputsimulation on, a 'pinch' gesture would also perform a zoom gesture for the camera.

As for the last issue, on world space UnityUI and manipulation handlers, I can can confirm they work as expected in the gist posted by Julia.

And, lastly, I can also confirm that these work on iOS as well using https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5278

**Comment by camnewnham** [comment]
> As for the last issue, on world space UnityUI and manipulation handlers, I can can confirm they work as expected in the gist posted by Julia.

One caveat, specifically with Unity UI. This is a reasonably specific scenario so not a blocker, but I wanted to raise it anyway in case others encounter it. When mixing **screen** UnityUI and **world** UnityUI, I have found that:
- If only one or the other is visible, it works correctly. 
- If there is a canvas overlay on the screen that includes a graphic raycaster, even if the raycast target does not occlude the world canvas, it intercepts/blocks the pointer events.

This is only observed when using MRTK + CanvasUtility, and the same configuration works (with the exception of losing all the MRTK features!) when using the StandaloneInputModule (Unity Default).

See these two images. 
1. A world canvas which functions correctly and handles pointer events.

![image](https://user-images.githubusercontent.com/19278856/61836985-1de7d100-aec6-11e9-9f6f-225f26611275.png)

2. Issue: A canvas overlay with a rect + raycast target image covering any of the screen. I'm unable to interact with the UI on the slate, but colliders in the scene still work (I have a box collider on the title bar).

![image](https://user-images.githubusercontent.com/19278856/61837053-643d3000-aec6-11e9-8e53-d19f64c6fd7f.png)

For clarity, the **overlay** looks like this:
![image](https://user-images.githubusercontent.com/19278856/61837133-c5650380-aec6-11e9-9b31-6cacd0401ca4.png)

![image](https://user-images.githubusercontent.com/19278856/61837141-ceee6b80-aec6-11e9-91e7-8395eb3ce0c6.png)

![image](https://user-images.githubusercontent.com/19278856/61837180-e7f71c80-aec6-11e9-95ea-26778e69f492.png)


And the **slate** looks like this:
![image](https://user-images.githubusercontent.com/19278856/61837208-08bf7200-aec7-11e9-9dad-7f0a72cb8d2c.

**Comment by jbienzms** [comment]
Wow, _impeccable_ detail @camnewnham. Thank you so much for taking the time to document these in such detail.

**Comment by jbienzms** [comment]
Since we are seeing more and more customer projects on the horizon targeting mobile phones, and since the next push will likely include a focus on mobile, I'd like to propose an urgency of 'soon'. I'll go ahead and apply the tag but feel free to re-prioritize as necessary.

**Comment by julenka** [comment]
I think https://www.youtube.com/watch?v=YqCQkL-97nQ contains a video of the interactions we want to support here, David.

**Comment by davidkline-ms** [comment]
I've implemented @julenka's workaround and am, at this point, unable to move an object (non-Unity UI) via the manipulation handler. Continuing to investigate.
