### ISSUE TITLE
UI Slider only pinchable

### ISSUE THREAD

**Issue by Kent1LG** [microsoft/MixedRealityToolkit-Unity#5398]
## Describe the bug

Using Unity UI Slider allows you to air-tap on one value to choose it with the gaze cursor on HoloLens 1 with MRTK 1/HTK . Now with MRTK V2 you have the "Pinch slider" behaviour, the value is handled by your hand position.

## To reproduce

1. Create a Canvas/UI environnement for HoloLens.
2. Place a slider. 
3. Try to air-tap on a specific value to select it.
4. Don't move your gaze and airtap with different hand positions.

## Expected behavior

When you click (air-tap) a value on a UI slider,  this value should be selected.

## Your Setup (please complete the following information)

- Unity Version 2018.3.14f1
- MRTK Version RC2.1

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
@julenka do you know what the usability stuff says about how this should work? i.e. is the snap to location not enabled because of lack of sufficient precision?

**Comment by julenka** [comment]
We haven't yet explored this question. Many sliders in traditional 2D GUI have this behavior. The question is whether it makes sense for a pinch slider, in 3D. I could see it making sense if you instead of pinching the slider poked to a specific value. However whether a pinch should auto snap to a given value is an open question. I would love to see a prototype or a pull request of this as an option in the slider and give it a try! That's the best thing to do. 

Shouldn't be too hard to prototype, however core MRTK devs are pretty focused on fixing existing bugs in behavior and adding docs vs. adding new features for the next month or so. This would be a great bug for somebody interested in contributing to MRTK to try!

**Comment by Zee2** [comment]
I believe all sliders in MRTK2/3 are all pokable and pinchable, with optional snapping.
