### ISSUE TITLE
Can't build HoloLens project after importing MRTK due to missing DLL's

### ISSUE THREAD

**Issue by CookieHael** [microsoft/MixedRealityToolkit-Unity#5469]
## Describe the bug

Building in VS to deploy to HoloLens throws a bunch of errors about not finding MRTK dll's where it expects them. See screenshot for specific errors. Can't seem to reproduce fully on a new project, but at least one error that is thrown in my project also gets thrown.

## To reproduce

1. Make new project, set it up for HoloLens
2. Import MRTK
3. Build in Unity and open the solution that is created in the selected folder in VS, build it there.

## Expected behavior

Build properly

## Screenshots

<img width="726" alt="errors" src="https://user-images.githubusercontent.com/36892196/62130695-dd2ef400-b2d9-11e9-985a-e1ff685969b2.png">

## Your Setup (please complete the following information)

- Unity Version 2018.4.4f1 (.NET backend, set up as explained in the microsoft hololens development docs)
- MRTK Version v2.0.0 RC2.1
- Visual Studio 2019 16.2  (also tried building in 2017, same errors. When doing a manual check the actual missing files are just not present where the solution thinks they are.)

## Target Platform (please complete the following information)

- HoloLens

**Comment by wiwei** [comment]
@CookieHael, this is gonna be weird to ask, but can you try putting your project in a folder closer to the root of the drive?

i.e. instead of c:\very\long\path\to\stuff\woaaaaaaaaaaaaaaaw

Do: c:\src

I think that Unity has trouble with very long paths (i.e. longer than MAX_PATH which is 255 characters - I think that the paths in the image above look to be super long)

If this is the case I'll have to update the docs to make sure we warn off of this

**Comment by CookieHael** [comment]
Hi, I'll try that ASAP, gotta get to our IT guy then cause they have my laptop locked down so I can't get to the C drive. If this is the case, it'd probably also be helpful in preventing the error if you guys shortened down your pathnames as well along with telling people to keep their paths short, since "Microsoft.MixedRealityToolkit.something.something.anotherthing.dll" isn't all too short either hehe ;)

**Comment by CookieHael** [comment]
It looks like that fixed it! Tried moving it to C:\users\rhelsen yesterday but even that was too long apparently! It's building fine now! Thanks 👍

**Comment by wiwei** [comment]
Okay I'll use this bug to track updating the docs about this, so hopefully folks can at least search for the problem if they hit it themselves.

Regarding naming, definitely a possibility, though I have to mention that it's somewhat of a scary thing to change because people depend on the asmdef names (we've broken people in the past with this, so it's not something we can do lightly)

**Comment by CookieHael** [comment]
Hmm yea, does indeed sound like something you should only change when you're not going for backwards compatibility anyways... And then again, in most circumstances it shouldn't be too hard to just move a project to your root folders

**Comment by michel-de-verdelhan** [comment]
we also have the problem on our project and we can't easily reduce our path because we use several application layers between our application and the MRTK.
