### ISSUE TITLE
Interactable Behavior doesn't trigger UX changes applied via profiles for NEAR Interaction.

### ISSUE THREAD

**Issue by Shubham7694** [microsoft/MixedRealityToolkit-Unity#5565]
## Describe the bug
Interactible doesn't execute/apply different profile when performing near interaction. It executes all profiles when performing far interaction.

## To reproduce

1. Launch latest MRTK ( v2-RC2.1 is what i tested) and open interactables example scene
2. Make sure that Coffee Mug game object is present in the scene.
3. Use hand to interact with far. When we press, the coffee color changes in cup and coffee (child element) changes it's position.
4. Repeat the same action from near the coffee cup. The color change happens

## Expected behavior
The coffee cup should show also change color and move below (i.e. appear to be reduced in quantity by changing position) in near interaction mode.
## Screenshots
When user presses cup from far:
![image](https://user-images.githubusercontent.com/7000326/62770115-f7c25380-bab7-11e9-9020-6c4dedb55a61.png)

When user presses cup from near:
![image](https://user-images.githubusercontent.com/7000326/62770113-f6912680-bab7-11e9-9e8c-c96981fd2579.png)

## Your Setup (please complete the following information)

- Unity Version :2018.4.4f1
- MRTK Version : Mixed Reality Toolkit 2.0.0-RC2.1

## Target Platform (please complete the following information)
- HoloLens 2

**Comment by Shubham7694** [comment]
@julenka Please tag some one who can take a look into this issue. Thanks

**Comment by julenka** [comment]
@killerantz do you have some time to investigate this week?

**Comment by killerantz** [comment]
Looking at the Coffee cup in the prerelease branch.

No hand interaction
![image](https://user-images.githubusercontent.com/22085553/62982377-c95ab600-bde0-11e9-8e05-23f5841b06b5.png)

Hand near the cup changes the color (Focus)
![image](https://user-images.githubusercontent.com/22085553/62982391-d24b8780-bde0-11e9-96bf-8a91db07181a.png)

Breaking the plane (touch) causes the coffee to move down (Pressed)
![image](https://user-images.githubusercontent.com/22085553/62982423-ea230b80-bde0-11e9-8d63-ccf5d0adc5fd.png)

The coffee moves up when moving away, (Not Pressed, back to Focus?) but the color does not change back to the dark color until the source is lost, by releasing the shift key which seems like a bug.
![image](https://user-images.githubusercontent.com/22085553/62982455-0626ad00-bde1-11e9-87ec-298566eee1be.png)

These states match up to the far interactions. The coffee cup has a Near Interaction Touchable, so it will only respond to near touch, not grip or close air tap.

**Comment by killerantz** [comment]
The color will change back after touch if something else in the scene receives focus.

**Comment by satorihunter** [comment]
Thanks @killerantz & @julenka for your response, but the problem is with "NearInteractionGrabbable". Kindly find the below given scenario for near interaction grabbable beaviour. Sorry for not mentioning that clearly in the earlier post.

**1.This is the same Interactableexample.unity scene, but i have changed the NearInteractionTouchable component to NearInteractionGrabbable. I have also highlighted the MRTK version on the both the sides.**

![image](https://user-images.githubusercontent.com/18205544/63334027-1c3fea80-c358-11e9-9541-af25dddbed71.png)

**2.Far interaction works fine in both the version of MRTK (focus and pressed state behaves as desired)**

![image](https://user-images.githubusercontent.com/18205544/63334325-d3d4fc80-c358-11e9-894d-db647cfe1fac.png)

**3.The below images shows the near interaction Focus working on both the version (I have enabled the proximity light to make sure the hand is in near interaction range)**

![image](https://user-images.githubusercontent.com/18205544/63334544-43e38280-c359-11e9-89c9-82c43a8c58fd.png)

**4.The below image shows the issue of  NearInteractionGrabbable's Pressed state not working in MRTK2-RC2.1**

![image](https://user-images.githubusercontent.com/18205544/63334778-b8b6bc80-c359-11e9-9c22-7fbfb4423991.png)

Hope this gives better clarity on reproducing the issue. Thanks and I await your response.

**Comment by julenka** [comment]
Hi, @Shubham7684, good news! In our MRTK 2.0.0 release which we just released yesterday, we have fixed this :-) Please have a look [here](https://github.com/microsoft/MixedRealityToolkit-Unity/releases/latest)

**Comment by julenka** [comment]
Just verified that the behavior works as expected (goes to the pressed state) in the latest mrtk_development, which currently is almost the same as 2.0.0 release (no changes to input or interactable yet since it was just released yesterday).

**Comment by satorihunter** [comment]
Thanks a lot, @julenka & @killerantz. will check.
