### ISSUE TITLE
Mouse Pointer does not work

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#5639]
## Describe the bug
When enable MousePointer in the Input > Pointer Profile, The mouse cursor is randomly flying around in the screen.

## To reproduce
1. Go to MRTK Profile > Input > Pointers 
2. Set 'Nothing' to DefaultController
3. Check 'Articulated Hand' in the Mouse Pointer. (Or try Mouse and other inputs)

## Expected behavior
Mouse cursor displayed in the game mode and can be controlled with mouse.

## Screenshots
![2019-08-13 15_29_50-Unity 2018 4 2f1 Personal - PressableButtonExample unity - MRTK-Public-Microsoft](https://user-images.githubusercontent.com/13754172/62982034-d7f49d80-bddf-11e9-9dde-90ec8ae0159c.png)

There are multiple cloned MousePointers.
![2019-08-13 15_07_49-Unity 2018 4 2f1 Personal - PressableButtonExample unity - MRTK-Public-Microsoft](https://user-images.githubusercontent.com/13754172/62982147-243fdd80-bde0-11e9-9a27-95c403d35e28.png)

## Branch
prelease/stabilization_2.0.0

**Comment by thalbern** [comment]
Hi @cre8ivepark, to make the mouse pointer work you have to add a new data provider for it in the input profile 
![image](https://user-images.githubusercontent.com/36998103/63098000-c212e400-bf69-11e9-97e4-9b7cbd0b4df8.png)


Saying that, I checked the docs and it's not very clear what to do there because we're using different terminology. 
Updating docs :)

**Comment by thalbern** [comment]
opened PR with updated docs
