### ISSUE TITLE
Hololense 1 issue with mrtk 2

### ISSUE THREAD

**Issue by iotMice** [microsoft/MixedRealityToolkit-Unity#5681]
## Overview
I am trying to build an application for hololense 1 using MRTKRC2.1 The air tap is not working properly, by making the gesture the cursor does not get small.
3d model in the environment is not stable, it gets re rendered sometimes and hangs

## Expected Behavior
Stability of holograms/3d models in the environment based on spatial mapping.
Air tap should work smooth.

## Actual Behavior
While making air tap gesture, the circle does not gets small. But by saying "select" it works fine.
3d model is not stable and it rerenders some times.
Though I have also set the profile correctly and in Input section changed it to GESTURES from ARTICULATED

## Unity Editor Version
2019.1.10F1

## Mixed Reality Toolkit Release Version
Microsoft.MixedReality.Toolkit.Unity.Foundation-v2.0.0-RC2.1.unitypackage

**Comment by wiwei** [comment]
@iotMice, do you have any video captures of the issue happening?

I think there are a few different things going on here - the hologram stability thing I believe is a general Unity issue that folks are looking into: If you have an .appx you can share, it might be good to follow up here:

https://forum.unity.com/threads/unity-2018-3-and-hololens-holograms-are-not-stable.647734/

Also one more thing, which since we just went up with 2.0.0 (non-RC) - can you check to see if the air tap issue is still happening for you on the latest release?

**Comment by iotMice** [comment]
Thanks for the response. Click  issue is solved for now. but stability still is the issue. and the fps I am getting in hololense is 9-10 fps. I think that is linked with the stability of the holograms. Isnt it?

**Comment by alexdesaint** [comment]
@iotMice, I have the same problem, how did you fix the click issue ?
