### ISSUE TITLE
Build / Deploy window does not autoincrement versions

### ISSUE THREAD

**Issue by XPav** [microsoft/MixedRealityToolkit-Unity#5684]
The build/deploy window, even when Auto Increment is checked, no longer auto increments.

To reproduce:  Build twice, note the same version #.

Using mrtk_development branch 33fd136c8fcbe7af09cf5fe5c1b92fcaef6430ff
Unity 2018.4.6f1

Building for IL2CPP/Release/x86/Solution

**Comment by davidkline-ms** [comment]
@XPav, thanks for the report!

**Comment by wiwei** [comment]
@XPav, can you add some more details on what you're doing to hit this, and also if there are any errors in your console when you hit this?

I just took the latest mrtk_development (and there haven't been build changes since that commit that are interesting) and autoincrement works fine (building a UWP AppX).

The only way that wouldn't work is if it hit some other error prior to setting that here in UpdateAppxManifest, which would make me think you aren't getting a build at all.

**Comment by XPav** [comment]
More information,.

The "Build APPX" button on the AppX Build Options tab does increment the build number.
"Build all, then Install", on the "quick options" does **not**, even though it does produce a proper AppX (with an un-incremented version).

"Build all, then Install", also appears to make a Master build, ignoring the configuration items under Appx Build Options.

**Comment by julianloehr-kg** [comment]
Can you check if #5897 (when checking use at least #5964, due to some follow up fix up) has fixed this issue? From a quick glance through the code it does look like so.

**Comment by davidkline-ms** [comment]
resolving as fixed by #5897
