### ISSUE TITLE
No clear docs on how to build and run MRTK

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#5712]
## Overview
We do not have clear instructions for how to build and run MRTK. Our [Getting Started](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#recommended-build-settings-uwp) page has lots of steps for consuming MRTK and a bit about building and running, but it is not clear.

Our [Contributing](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/CONTRIBUTING.html) page does not have clear steps on how to build and run.

## Suggestion
Say that building the MRTK is just building a UWP app (it's nothing MRTK specific) and link to good resources like: https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1

**Comment by wiwei** [comment]
A few things here:

1) The contributing page is really out of date, and there are plenty of things that it recommends that aren't great. I think that this was probably copied from some older place prior to this docfx setup. I think in general this should be updated so that we don't lead to incorrect information.
2) Building the MRTK is just building a UWP app (it's nothing MRTK specific), which I think was the original question. We should avoid duplicating stuff that isn't MRTK specific, and link to good resources like: https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1

**Comment by julenka** [comment]
Related: #5121

**Comment by julenka** [comment]
Sounds like the main task here is just to update our docs to say "Building the MRTK is just building a UWP app (it's nothing MRTK specific) and link to good resources like: https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base-ch1

**Comment by julenka** [comment]
> 1. The contributing page is really out of date, and there are plenty of things that it recommends that aren't great. I think that this was probably copied from some older place prior to this docfx setup. I think in general this should be updated so that we don't lead to incorrect information.

@wiwei #5718
