### ISSUE TITLE
Redundancy between InputSystemProfile and ControllerVisualizers

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#5820]
For reference, two screenshots first:

Controller Configuration portion of the profile:
![image](https://user-images.githubusercontent.com/32508825/63932802-34022780-ca58-11e9-87f7-cbdde1a84bb5.png)

Visualizer portion:
![image](https://user-images.githubusercontent.com/32508825/63932836-4aa87e80-ca58-11e9-9381-be324904352c.png)

1. both have independent Handedness settings
The serialized field on the visualizer does not make sense, because it gets its handedness assigned during controller assignment. Maybe this is relevant for pointers, but I have not looked into that.

2. The ControllerPoseSynchronizerInspector should be used as fallback

3. ControllerVisualizationType in the MixedRealityControllerVisualizationSetting looks obsolete to me. It's not being assigned from the constructor and it's only used in a method that itself is not references anywhere. And Profile working with this is only referencing the type via its IMixedRealityControllerVisualizer interface.

**Comment by keveleigh** [comment]
>both have independent Handedness settings
The serialized field on the visualizer does not make sense, because it gets its handedness assigned during controller assignment. Maybe this is relevant for pointers, but I have not looked into that.

That's true! Handedness is left editable on a visualizer / synchronizer in case you want to create a prefab in your scene that tracks a specific handedness. Basically, any scenario that doesn't go through the controller / pointer load code in the MRTK. I agree that it doesn't have any effect at runtime to be pre-set to a specific value for controller visualization / pointers, since it's updated at runtime.

>The ControllerPoseSynchronizerInspector should be used as fallback

Agreed! I opened #6385 to support using the default Visualizer inspector for any child classes, like the screenshot above

> ControllerVisualizationType in the MixedRealityControllerVisualizationSetting looks obsolete to me. It's not being assigned from the constructor and it's only used in a method that itself is not references anywhere. And Profile working with this is only referencing the type via its IMixedRealityControllerVisualizer interface.

This type is used when controller models are loaded from the platform's SDK. For WMR, it happens at https://github.com/microsoft/MixedRealityToolkit-Unity/blob/2c711ab4d9f059fa0b12761a10188a051c7785b4/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs#L305

For OpenVR, it happens at https://github.com/microsoft/MixedRealityToolkit-Unity/blob/6105960c89ebba85547112d0590c1c1faec508b8/Assets/MixedRealityToolkit.Providers/OpenVR/GenericOpenVRController.cs#L256

This type is added to any models that get loaded from an API at runtime. If a prefab is defined (I believe this is how Oculus handles controller models), the type is ignored, since it's assumed the prefab will already be set up with its visualization scripts.

**Comment by Alexees** [comment]
> This type is used when controller models are loaded from the platform's SDK

You're right. Must have had looked this up in the wrong MRTK version...
