### ISSUE TITLE
Grabbing objects with Xbox Controller will catapult them into infinity

### ISSUE THREAD

**Issue by thalbern** [microsoft/MixedRealityToolkit-Unity#5829]
## Describe the bug

If you're trying to manipulate an object that has ManipulationHandler attached with your XBox controller the object will suddenly disappear.

What happens is that the pointer position in case of the XBox Controller equals the head position, which results in a division by zero in the ManipulationHandler move logic. 

## To reproduce

Open Hand Interaction Scene and grab the left green gem or the cheese with your xbox controller.

## Expected behavior

The object stays put and doesn't disappear into space (boldly goes where no other gem/cheese has gone before)

## Your Setup (please complete the following information)

MRTK v2.0.0

## Target Platform (please complete the following information)

Unity Editor + XBox Controller

**Comment by wiwei** [comment]
It might be worth spending a future iteration handling xbox controller related issues:

https://github.com/microsoft/MixedRealityToolkit-Unity/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+xbox

Could have worth in doing them all at once, rather than piecemeal (would also be a good time to maybe add some test infra for xbox controllers, so that we can simulate that as well as we do hands)
