### ISSUE TITLE
The mouse device manager does not surface the profile's speed property

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#5838]
It is a common scenario on PC devices for users to modify the speed of the mouse cursor. While the mouse device profile has a speed value is not easily accessed / modified in code.

I propose exposing the profile's MouseSpeed property and consider adding a DoubleClickSpeed as well (to more closely match configuration options on Windows and other operating systems).

Unfortunately, this is a breaking change as it modifes the IMixedRealityMouseDeviceManager interface and the MixedRealityMouseInputProfile (though this may be containable using default data).

**Comment by wiwei** [comment]
I think there's a low likelihood that IMixedRealityMouseDeviceManager is actually being extended in crazy ways externally from the MRTK (i.e. this is probably a case where folks are just using the default).

If someone is extending/greatly modifying it, posting here would be great, but otherwise it seems like these changes are additive and should be okay.

The main thing here is that the profiles changes we make should be backwards compatible (using a combination of default data + FormerlySerializedAs). If this is not honored, we should chat to figure out how to make sure folks aren't broken by this.

**Comment by davidkline-ms** [comment]
> The main thing here is that the profiles changes we make should be backwards compatible (using a combination of default data + FormerlySerializedAs).

I believe i can implement in such a way as to maintain profile compat.

**Comment by Tom-Wells-NW** [comment]
I think this is a great idea. The backwards profile compatibility would be important.
