### ISSUE TITLE
Camera sticks on "floor" after teleportation?

### ISSUE THREAD

**Issue by jazzendev** [microsoft/MixedRealityToolkit-Unity#5966]
`float height = targetPosition.y;
targetPosition -= CameraCache.Main.transform.position - MixedRealityPlayspace.Position;
targetPosition.y = height;

MixedRealityPlayspace.Position = targetPosition;`

Source code copied from "MixedRealityTeleportSystem.cs", seems there is nowhere to adjust height after teleportation?

**Comment by Alexees** [comment]
There's usually no need to adjust the height after this. The Camera is always a child of the MixedRealityPlayspace, usually with the correct offset from it, like 1,8 on y if that's how tall you are. Unless you're using teleportation on devices like the Hololens, which basically starts at the floor level, but is not supposed to use teleportation.

**Comment by JSWorkspace1** [comment]
Is there a way to explicitly set this offset? I had some instances where the camera was stuck at floorlevel after teleporting in my VR application. I couldn't reliably recreate it. Maybe it was due to tracking loss or something, but it would be nice to rule  the possibility out entirely. Maybe set an allowed minimum height for the camera.

**Comment by jazzendev** [comment]
@Alexees It is supposed to have the correct offset on MixedRealityPlayspace, but so far the Main Camera is always sticking on the ground in my VR project, like the image below
![image](https://user-images.githubusercontent.com/11206872/65210377-91c0e700-dacd-11e9-8394-dfc34e8bc817.png)

Like @JSWorkspace1 mentioned, maybe it is due to tracking loss, I think to set an offset after teleportation or offer an entry to manually adjust the offset between MixedRealityPlayspace and Camera would be better.

**Comment by Alexees** [comment]
The fact that the Main Camera's position is nearly 0,0,0 confirms the fact that it's not a MRTK issue but a tracking problem. As soon as tracking is back, at least the y value should jump to the correct height. The fact that a tracking loss causes this is bad enough and shouldn't be happening at all, since, in case of Microsoft's portal still manages to keep the head up when in the cliff house for example. For some reason it feeds 0 values to Unity...
Way back, I reported this but it did not seem to matter too much or was in the wrong place:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/1455

Maybe it's a Unity problem, or even a vendor software problem not feeding in correct values on lost tracking even though outside the software you're above floor level.

**Comment by JSWorkspace1** [comment]
I still think it would be a good feature if the height Offset  was made accessible.
 This would allow  developers to create fallbacks in case the other systems fail.
