### ISSUE TITLE
MRTK Input system does not bubble events

### ISSUE THREAD

**Issue by rupeshpamaihgari** [microsoft/MixedRealityToolkit-Unity#5975]
## Describe the bug

**interactable.cs is not allowing raycast to hit boundingbox.cs object while I am trying to use both.**

I have a requirement to rotate a parent object by dragging a child gameobject which has interactable.cs. For this to achieve, I have used boundingbox example of tree given in example scenes.

## To reproduce

1. Go to bounding box examples scene where we have "tree/coffee cup/cheese etc"
2. select child of tree model named "node_id30"
3. put layer of "node_id30" to "IgnoreRaycast"
4. Go to child object of "node_id30" which is text and add a "box collider" component to it and "interactable.cs"  component.
5. Add a tag to text object as "HelixButton" (to detect the child object in boundingbox.cs)
6. Open Boundingbox.cs component of "node_id30" and add the code to the method OnPointerDown as shown in "fig1" 
![fig1](https://user-images.githubusercontent.com/9622328/65079358-9b0e5e80-d9bc-11e9-9922-0e407bae84d8.png)

## Expected behavior
I have used Focus and FocusOff functions for child gameobject (text). Hence the expected behavior is that the child object's interactable behaviour should work along with rotation of parent object when dragged by focusing on child object. 

I am able to rotate parent gameobject by dragging child gameobject if I disable interactable.cs component of child gameobject. But not able to rotate if I enable ineractable.cs of child object
 

## Your Setup (please complete the following information)

- Unity Version [2019.1.10f1]
- MRTK Version [v2.0]

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by wiwei** [comment]
@julenka @CDiaz-MS @thalbern @MenelvagorMilsom what is the general consensus here regarding the "stackability" of the various types of manipulation and interaction that we have in the MRTK?

AFAIK the model really is currently a "the first one to handle it wins" though it seems like in each case it probably wouldn't be that "hard" to update this so that things can be configured to not mark input events as handled, allowing things to bubble up and then chain.

That being said, this does mean that the whole interaction models would probably need to be defined (i.e. what does it mean to have a manipulation handler within a bounding box within an interactable)

**Comment by wiwei** [comment]
@rupeshpamaihgari I suspect that you might be able to work around this in interactable by removing eventData.Use(); calls (which will allow events to keep going up) but obviously only on the thing that you want to not eat the input event.

The greater question of the overall philosophy/reasoning still needs to be enumerated.

**Comment by julenka** [comment]
I read through the description a few times and to be honest still am not fully understanding the use case. Could you maybe share an example scene, or a git branch, or maybe share a video of the expected and actual behavior? Code is always best. I think the default behavior to have interactable consume events is probably what we want to keep. If I can understand your repro better, it will help me come up with a workaround.

**Comment by rupeshpamaihgari** [comment]
> I read through the description a few times and to be honest still am not fully understanding the use case. Could you maybe share an example scene, or a git branch, or maybe share a video of the expected and actual behavior? Code is always best. I think the default behavior to have interactable consume events is probably what we want to keep. If I can understand your repro better, it will help me come up with a workaround.

@julenka Please find [link ](https://drive.google.com/open?id=1gsQnsZXOuyFVQRgV98Itu54IdBc7XFOk)  below for videos explaining behavior "Rotation working when interactables disabled" and "Rotation  not working when interactables enabled".

**Comment by julenka** [comment]
Ah okay, thank you, I understand now. MRTK has an unusual way of dispatching events, which is causing the problem. The event dispatch will send events until it hits an object that handles the event. In this case, Interactable is below bounding box in the hierarchy, so it handles the event first. The expected behavior would be for the event to continue to propogate upward unless some event handler calls "eventData.use()" to force the propogation to stop.

Graphically, I believe the expected behavior that rupeshpamaihgari has is:

![image](https://user-images.githubusercontent.com/168492/65299331-fb6be000-db23-11e9-8fb3-8b1ca163abb0.png)

This also matches the expected behavior for input dispatch systems such as [how JavaScript dispatches mouse events](https://www.sitepoint.com/event-bubbling-javascript/)

However, MRTK does this: 

![image](https://user-images.githubusercontent.com/168492/65299418-50a7f180-db24-11e9-9a85-5200096d430a.png)

Thinking more on this, I think it would be better for us to follow common patterns in UI systems and bubble up events until they are explicitly used / stopped.

**Comment by rupeshpamaihgari** [comment]
Thanks @julenka for considering this issue. I just have to achieve very basic interaction "rotating parent gameobject by dragging the child gameobject without using boundingbox.cs". It would be really helpful if there is any documentation or code for it.

**Comment by thalbern** [comment]
assigning to @vaoliva as this will be needed for scrolling object collection to work properly

**Comment by polar-kev** [comment]
@elbuhofantasma, this should be fixed based on the PR that was merged. Can you confirm?

**Comment by keveleigh** [comment]
@polar-kev That PR was merged into a feature branch which hasn't yet made its way into the main branch.

![image](https://user-images.githubusercontent.com/3580640/116927424-81ad3b00-ac10-11eb-8401-b9da1d4f386f.png)

**Comment by RogPodge** [comment]
As we move onto XRI, we're moving the handling of input events onto Unity's side of things. The feature branch will still be available here, and we'd love it if community members took and interest in refreshing this PR for the v2 input system.

https://github.com/microsoft/MixedRealityToolkit-Unity/tree/feature/event_propagation
