### ISSUE TITLE
Missing function in Interactable.cs (  T AddReceiver<T>() where T : ReceiverBase, new ()  )

### ISSUE THREAD

**Issue by timgoeij** [microsoft/MixedRealityToolkit-Unity#6007]
## Overview
At runtime I create dynamically buttons to going deeper in a hierarchy. I have it working now with the default click event from the Interactable.cs For touch events I saw in the documentation examples to add extra receivers at runtime with the Interactable.AddReceiver<T>() function. 

I look in Interactable.cs but cannot find the function.

## Expected Behavior
A **T AddReceiver<T>() where T : ReceiverBase, new()** function as described in the documentation and Api documentation in Interactable.cs.

https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.UI.Interactable.html#Microsoft_MixedReality_Toolkit_UI_Interactable_AddReceiver__1

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_Interactable.html#interactable-events-example

## Actual Behavior
An Interactable.cs without a **T AddReceiver<T>() where T : ReceiverBase, new()** as described in the documentation.

## Steps to reproduce
_(Links to sample github project preferred)_
Search in the MRTK for Interactable.cs
Look in the file and you cannot find: **T AddReceiver<T>() where T : ReceiverBase, new()**

## Unity Editor Version
Unity 2019.2.5f1
## Mixed Reality Toolkit Release Version
MRTK 2.0.0

**Comment by keveleigh** [comment]
The documentation you linked to is specifically the documentation generated out of the development branch, where this function does exist: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9ee199814af7a248a42abbb4b19924b436958060/Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs#L135

In the top right, by the search bar, there's a dropdown allowing you to select different docs versions:
![image](https://user-images.githubusercontent.com/3580640/65265968-f6c50e80-dac6-11e9-8a39-f90dce01ecd4.png)

@thalbern, I wonder if we should make the most recent release the default documentation, instead of the dev branch.

**Comment by timgoeij** [comment]
@keveleigh Sorry, my mistake i hadn't see the version dropdown, than this issue can be closed. I had already found a workaround for what I wanted the do.

**Comment by Troy-Ferrell** [comment]
@davidkline-ms / @keveleigh , how do we update the mrtk docs to default to latest release?

This is the second person who has run into this issue
