### ISSUE TITLE
MRTK  support hololens1？ but HoloLens1 can not upgrade to 1809

### ISSUE THREAD

**Issue by zhudaxing** [microsoft/MixedRealityToolkit-Unity#6070]
I use MRTK make a project  ，it need 18962，but my HoloLens can not up to  version 1809， Now，I can not install packdge into HoloLens1

**Comment by davidkline-ms** [comment]
@zhudaxing

You are likely encountering an issue with how MRTK v2.0.0 is specifying the minimum operating system version (the issue will be fixed in v2.1.0). You can work around this, in Visual Studio, by changing the minimum SDK to 10240 and recompiling. This will fix the manifest and allow your application to run on the first generation HoloLens.

The Windows SDK requirement is to enable accessing HoloLens 2 features at compile time and does not indicate an operating system version requirement. The MRTK performs the necessary runtime checks to ensure that unsupported APIs are not called.

**Comment by zhudaxing** [comment]
sorry， I set min sdk to10240 in VS—Project—Retarget Projects, and  build new package .when install app, it also show "The package requires OS version 10.0.18362.0 or higher on the Windows.XboxSRA device family. The device is currently running OS version 10.0.17763.737. Failure text: A Prerequisite for an install could not be satisfied. (0x80073cfd)"
