### ISSUE TITLE
Clean up Interactable Enable/Disable Design

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6078]
## Describe the bug

The current enable/disable design for Interactable can be improved.  Interactable can be disabled many ways:

- Disabling the gameObject Interactable is attached to 
- Disabling the Interactable script component
- Setting Enabled property to false in Interactable
- Calling SetDisabled(true)

There also exists an IsDisabled property which has the potential to be confusing when there is also an Enabled property.

## Your Setup 

- Unity Version: 2018.4.11f1
- MRTK Version 2.0

## Target Platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by julenka** [comment]
@CDiaz-MS  @Troy-Ferrell what is the bug? Doesn't seem inherently wrong that you can disable things multiple ways. And, then proposed solution?

**Comment by Troy-Ferrell** [comment]
1) No documentation explaining difference of different types of disable and what they truly mean
2) There is Enabled and IsDisabled properties and you can get/set on each but they don't properly control items and again duplicated code basically
3) Enabled is just a blank get/set. When disabling Interactable we need to reset states because it should not respond or set input states when disabled. 

Work currently in:
https://github.com/Troy-Ferrell/MixedRealityToolkit-Unity/tree/users/trferrel/interactable-interface-fixes
