### ISSUE TITLE
Bounding box grab handles flicker when nearing 15cm far pointer threshold and disappear when the threshold is crossed

### ISSUE THREAD

**Issue by shubhamarora28** [microsoft/MixedRealityToolkit-Unity#6220]
## Describe the bug
The following are two issues noticed with the bounding box component when the activation behavior is set to Activate By Proximity And Pointer.

1. Bounding box flickers when the hand is approximately 15cm away from it.
2. There's a dead zone between 0cm - 15cm range of the bounding box. The far pointer ray disappears because the hand is in a 15cm radius of a collider. The bounding box grab handles are not visible because the hand is not yet colliding with it.

[Posting both issues in a single ticket as they're closely related and might be dependent]

## To reproduce

1. Go to the "BoundingBoxExamples" scene in MRTK examples.
2. Play the scene.
3. Point the hand ray to "CoffeeCup4" gameobject (far interaction).
4. Scroll the mouse wheel to move the hand ray towards the cup.
5. [Issue 1] The bounding box grab handles will start flickering at the 15cm threshold.
6. [Issue 2] Scroll the mouse wheel further towards the cup by approx 1-2 cm. The grab handles will disappear and only appear when the hand's index tip collides with the bounding box.

## Expected behavior
For the first issue (Flickering): Flickering should not happen when the transition from far to near pointer transition is happening.

For the second issue: The grab handles should not disappear as long as the far/near ray is hitting the bounding box.

## Screenshots

![bounding_box_issues](https://user-images.githubusercontent.com/14876006/66254108-7d4c4200-e78f-11e9-876f-fa435a8c0f3d.gif)

## My Setup

- Unity Version 2018.4.9f1
- MRTK Version v2.0

## Target Platform

- HoloLens 2 (Can be simulated in the editor as well)

**Comment by Troy-Ferrell** [comment]
@thalbern
I can repo in stabilization branch. Appears to happen on transition but also when focus is on the BB handles
![flickering](https://user-images.githubusercontent.com/25975362/66336676-63774000-e8f2-11e9-883c-751203261441.gif)
 only

**Comment by MenelvagorMilsom** [comment]
I've done some investigations into the cause of this bug. The reason this happens is because of a combination of behaviours in the focus system, near pointers and the bounding box. Here's the problem:

- The hand is quite close to the `BoudingBox` but just not close enough for near interaction.
- The `ShellHandRayPointer` gives focus to the `BoundingBox` causing the handles to become active.
- The handles are closer to the hand, close enough for near interaction, so the `SpherePointer` returns true for `IsNearObject`.
- This causes the `ShellHandRayPointer` to become inactive in `DefaultPointerMediator`.
- With the `ShellHandRayPointer` inactive, and the `SpherePointer` not close enough to give focus, the `BoundingBox` loses focus and the handles become inactive again.
- With the handles deactivated, the `SpherePointer` now returns false again and so the `ShellHandRayPointer` becomes active again.
- We are now in the same state we started with, so return to the first step and loop.

So potential fixes for this that myself and @thalbern thought about:
1. making it so that the handles are not detected by the `SpherePointer`, so that focus remains on the root `BoundingBox` object.
2. Making it so that the handles are never deactivated, simply made invisible, so that they cannot suddenly disable far interaction by becoming active.

Method 1 has the problem that it disables near interaction grab on the handles, which is definitely undesirable.

Method 2 has the problem that it potentially introduces 20 new active colliders per `BoundingBox` object in the scene, which may have performance implications.

We could do a hacky fix in the `BoundingBox` that checks if this flickering is occurring and stops it there, but it would be treating the symptoms, rather than fixing the problem and we'd still have a few frames of flicker before it was detected and stopped. 

With no obvious solution at the moment we may not fix this for 2.3, as the issue is not that severe, and solutions may require large fundamental or dangerous changes.

**Comment by thalbern** [comment]
I moved this issue to 2.4.0 for now
