### ISSUE TITLE
Select event on PressableButtonHoloLens2 fire up to its parent containers

### ISSUE THREAD

**Issue by tletie** [microsoft/MixedRealityToolkit-Unity#6375]
## Overview
When a container or a sibling gameobject (having collier & Manipulation handler) that is behind the PressableButtonHololens, then when user select the button, the event also trigger the container or the sibling game object behind.
## Expected Behavior
It shouldn't not trigger the behind game object with some of the configuration setting in profile for example.
## Steps to reproduce
Create a MixedReality scene as usual with default configuration profile.
Add a PressableButtonHololens and then another gameobject behind the button. Add  box collider and Manipulation handler to this gameobject and set "One and Two handed", Move Rotate Scale.
Now play the scene and then interact with the button, you will see the game object will move/rotate/scale.

## Unity Editor Version
2019.2
## Mixed Reality Toolkit Release Version
v2.1

**Comment by keveleigh** [comment]
@vaoliva This sounds like something that might be addressable with #7550? Or a potential follow-up?

**Comment by vaoliva** [comment]
@keveleigh this is related to propagation but slightly different. As I understand , the manipulation handler is catching a pointer event before the button interactable catches input down, just because pointers are global listeners for input. I believe we need a way of using the event but they are different events. We could def keep this issue as a follow up for propagation pr.

**Comment by vaoliva** [comment]
@tletie I was trying to reproduce the issue as you described, using separate game objects, a pressable button and a manipulation handler. Could you please confirm if they are at the same level ? Could only reproduce it with pressable button being child of manipulation handler object.
