### ISSUE TITLE
CursorModifier does not hide cursor on focus

### ISSUE THREAD

**Issue by Nakda** [Microsoft/MixedRealityToolkit-Unity#638]
Unless I missed something, ICursorModifier.GetCursorVisibility() does not seem to be called so the CursorModifier.HideCursorOnFocus property is useless at the moment.

Also, as it is implemented, GetCursorVisibility() returns HideCursorOnFocus which seems quite misleading as I would expect it to return !HideCursorOnFocus.

**Comment by killerantz** [comment]
That seems to be undeveloped at the moment. I would like to add a property for HideCursorOnGesture or HideCursorOnPress so that when a gesture begins I can hide the cursor and show some gesture feedback UI. In this case, the cursor would check GetCursorVisibility() to see if the cursor should be visible or not based on the current cursor state and the HideCursorOnFocus and HideCursorOnPress values.

**Comment by davidkline-ms** [comment]
We should continue to investigate.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
