### ISSUE TITLE
mrtk CI is failing, times out at 90 minutes

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6381]
## Describe the bug
Our CI is regularly failing because the build is taking longer than 90 minutes.

For example:
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=6214

This is preventing us from identifying real regressions, as devs are beginning to just ignore these error emails.

**Comment by julenka** [comment]
@keveleigh, I'm re-opening this because the increase from 90 to 120 didn't actually work -- MRTK CI is still failing :-(

**Comment by keveleigh** [comment]
With the .NET build currently turned off, we _shouldn't_ hit this (removes ~20 minutes from our pipeline run). Would be good to keep this open for investigation though, due to the desire to turn the .NET build back on at some point.

**Comment by keveleigh** [comment]
I'm going to close this issue in favor of #6383, since the short term issue of CI continuously timing out has been resolved by turning off the .NET build. This build was re-enabled for PR validation in #6418, so I think we have good coverage without it in our CI for now.

![image](https://user-images.githubusercontent.com/3580640/67901349-e1122280-fb23-11e9-94f4-c28872ba819d.png)
