### ISSUE TITLE
How to occlude part of placeable object that intersect room mesh?

### ISSUE THREAD

**Issue by paulcanning** [Microsoft/MixedRealityToolkit-Unity#641]
Seeing as object are placed using their transform origin, how can I occlude any part of the mesh that intersects the room mesh and would appear "outside" the room?

Example; make a sphere and add TapToPlace script. You can place this around the room, but half of it will be "behind" the room mesh, as it's origin is in the middle of the sphere.

In addition, let's say I have a cylinder, aiming straight up, with its base at ZY 0, 0. If you place it on the floor, it would point straight up, fine. But if you place it on a wall (vertical mesh/plane) how would you make it lie horizontally, following the orientation of the mesh it is placed on?

**Comment by jessemcculloch** [comment]
You are asking about 3 different questions here.  My suggestion would be to move them into the official forums at https://forums.hololens.com

As for occluding the half of your object that is behind your mesh, you want to use an occlusion shader on your spatial mesh.

You can use the Mesh Renderer to find the bounds of your object for placement, rather than using the origin.

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
