### ISSUE TITLE
Toggle button's front plate shows unexpected behavior when used with InteractableToggleCollection.cs

### ISSUE THREAD

**Issue by cre8ivepark** [microsoft/MixedRealityToolkit-Unity#6489]
## Describe the bug
When multiple PressableButtonHoloLens2Toggle buttons are used with InteractableToggleCollection.cs, the front highlight plate(white square line) keeps highlighted on hand detection even if it is not focused or hovered.

Since the 'See-it, Say-it (Say Button)' component also remains visible, it looks like the button has the focus.

![2019-11-05 18_30_43-Unity 2018 4 12f1 Personal -  PREVIEW PACKAGES IN USE  - PressableButtonExample](https://user-images.githubusercontent.com/13754172/68263504-065ad100-fffb-11e9-853c-2879945a977a.png)

## To reproduce
1. Created an empty game object
2. Assign GridObjectCollection.cs and update layout 
3. Assign InteractableToggleCollection.cs 
4. Add multiple PressableButtonHoloLens2Toggle.prefabs
5. Assign PressableButtonHoloLens2Toggle prefabs onto the InteractableToggleCollection.cs
6. Run and press buttons.

![2019-11-05 18_31_15-Sent Items - DongYoon Park@microsoft com - Outlook](https://user-images.githubusercontent.com/13754172/68263630-4b7f0300-fffb-11e9-9b1f-b7bc63ff987a.png)

FYI - in the button prefab, HighlightPlate is the one under FrontPlate. 
![2019-11-05 18_44_24-MixedRealityToolkit - Microsoft Visual Studio](https://user-images.githubusercontent.com/13754172/68264129-b4b34600-fffc-11e9-88c8-36192d17b519.png)

**Comment by Railboy** [comment]
Strange. Looks like both issues are caused by toggle buttons remaining in a 'Focus' state even after they have been un-toggled and focus has exited the button. Sometimes button can be reset to a default state by un-toggling them, then entering / exiting focus. Other times they remain stuck regardless of subsequent focus events.

**Comment by Railboy** [comment]
I'm able to repro this by toggling a button and destroying the pointer that toggled it while still focusing on the button. (I do this by disabling the simulated hand.)

It looks like the toggled button retains a reference to the destroyed pointer. In the inspector I'm drawing all the FocusingPointers and these never go away:

![FocusingPointers](https://user-images.githubusercontent.com/9789716/68323103-9c354100-0079-11ea-9013-88e2b261735b.PNG)

@julenka @killerantz in FocusProvider.UnregisterPointer a focus changed event is fired as expected, but Interactable ignores this event because CanInteract returns false due to ButtonMode being set to Toggle.

Removing the CanInteract check solves the problem, but what side effects can we expect from making that change?

**Comment by julenka** [comment]
>what side effects can we expect from making that change?

I'm not sure, @Troy-Ferrell and @CDiaz-MS  have been in that code much more than me. One thing you can do is remove the code and see if any of the automated interactable tests fail, they might help highlight unintended side effects.

**Comment by Troy-Ferrell** [comment]
Yes, I have looked into focusingpointers/CanInteract before when I was doing the Interactable refactor. I filed the item #6100 because there was already so much churn, I wanted to leave some things to the side
