### ISSUE TITLE
Holographic Emulation doesn't work.

### ISSUE THREAD

**Issue by SoundGuy** [microsoft/MixedRealityToolkit-Unity#6490]
## Describe the bug

I'm trying to run the diagnostic scene on a bare vanilla project with only MRTK included and it doesn't work. 

## To reproduce

Setup a new project
Install MRTK foundation and MRTK examples
open up the diagnostic scene.
open up the holographic emulator tab, 
open up the hologaphic emulator on the holollens
connect to hololens 1
hit play

error.

## Expected behavior
i would expect this to work like it did in holokit 1

## Screenshots

![image](https://user-images.githubusercontent.com/1455515/68281395-3e582780-0080-11ea-9a5b-6efccc284350.png)

## Your Setup (please complete the following information)

- Unity Version 2019.2.11
- MRTK Version 2.0.0 / 2.1.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by Axelius89** [comment]
I have the same problem.

I tried also Unity 2019.2.2 and 2019.2.13 and MRTK Version 2.0.0 and 2.1.0.

The weird thing is: Sometimes holographic emulation works! I've been troubleshooting with removing/installing the MRTK again, leaving our the MRTK altogether, switching platform back and forth, disabling/enabling VR support, disabling/enabling WSA Holographic Remoting Support, removing/adding back Windows Mixed Reality as the VR SDK, changing/removing/reinstalling the Windows Mixed Reality Package. And on three occasions so far, holographic emulation suddenly worked. I was not able to pinpoint what configuration leads to this. Especially weird is, that after a Unity restart it again does not work (even though after the config worked I did not change anything).

If anybody knows of a workaround I would be very happy.

**Comment by Axelius89** [comment]
**We have apparently discovered a workaround** which makes me able to use Unity 2019.2 with Holographic Emulation reliably.

Apparently, when the "Holographic Emulation" tab is active, or set to "Remote to Device" or something when Unity is started up, it does not work. But after removing the tab, and then re-adding it from Window->XR->Holographic Emulation it works!

So either make sure to remove this tab before closing Unity, so that it is not there when you start up Unity again, or just close it and add it back.

I could not find a corresponding Editor Script etc which creates this tab, to see if they changed something since 2018.2, or something else somewhere else was modified.

BTW, if you cannot disconnect from the HoloLens any more because the "Disconnect" Button is greyed out, you can also remove the tab and add it back, which enables the button again. However under some circumstances this seems to crash the editor.
