### ISSUE TITLE
Add packages required in docs (ARFoundation, ARCore, ARKit)

### ISSUE THREAD

**Issue by CDiaz-MS** [microsoft/MixedRealityToolkit-Unity#6574]
Make sure to include that users need to add ARFoundation, ARCore and ARKit when they import the MRTK Unity packages in the docs.

If using Unity 2018, AR Foundation is not there by default, steps to reveal ARFoundation in the Package Manager:
- Window > Package Manager > Advanced > Show Preview Packages

**Comment by Alexees** [comment]
May I suggest instead of forcing someone to install AR features into his project that he might not even need that the feature starts off completely disabled and the docs tell you how to enable it?
Steps to fully disable:
- exclude every platform in Microsoft.MixedReality.Toolkit.Providers.UnityAR and /-Editor
- remove the UnityARCameraSettingsProfile from the Camera settings provider list in MRTK profile

If the user WANTS to use it he can simply install the packages, uncheck the exludes in the ASMDEFs, and set the profile
