### ISSUE TITLE
Bounding box in HandInteractionExamples: BoxColliders does not support negative scale or size.

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6582]
## Describe the bug

One of the bounding boxes in the HandInteractionExamples causes warnings when the scene is played.

Possibly a side effect of #6528. In this specific case, the rotation handles are spheres instead of cubes.

## To reproduce

1. Open HandInteractionExamples.unity
2. Press play
3. Observe warnings

## Screenshots

![image](https://user-images.githubusercontent.com/3580640/68819887-514d9780-063e-11ea-9c4e-b0e5c88ff158.png)

## Your Setup
- Latest 2.2 stabilization

**Comment by gilbdev** [comment]
i'll have a look

**Comment by gilbdev** [comment]
definitely a side effect of my code ..need to dig into 3D math again to rotate properly the Bounds ...
revert previous PR if blocking mrtk 2.2 for too long.

any advice to rotate a unity Bounds structure welcome :)

**Comment by julenka** [comment]
@gilbdev, I'm curious, what are your thoughts on whether this is something we could have caught with a test? Is there something we could add to the test infra that would have made this bug easier to find? FYI @wiwei

**Comment by gilbdev** [comment]
@julenka
If i had to write a test, I would probably try to test that some point in space are inside or outside the handle bounding box (after putting all into world space).
This is a bit tricky due to the fact that there are some gameobject hierarchy involved(visual is a child of the object containing the handle box collider), together with bounds center and size (which are a headache to make math with Transforms), add some scale and rotation into that and this get quickly out of hands ^^.

But something like checking that :
Take scale corner position (corner of the target object bounding box), take computed handle bounding box, move it to world space, apply bounds center offset, move on each axis of the bounds size.
test those points are within handle position+handle size+handle collider padding. Add 0.001 and test those are outside the bounds.
- Repeat for rotation.

Make several tests with different visual rotation, scales and different target rotation and scales.
