### ISSUE TITLE
MRTK 2.2  reference to non-existent assembly 'Unity.XR.ARFoundation' 

### ISSUE THREAD

**Issue by julenka** [microsoft/MixedRealityToolkit-Unity#6709]
## Describe the bug
I'm getting the following error after importing the Foundation and Extensions packages for 2.2:
 
```
Assembly has reference to non-existent assembly 'Unity.XR.ARFoundation' (Assets/MixedRealityToolkit.Staging/UnityAR/Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef)
```

## To reproduce

1. Open Unity 2018.4.12f1
2. Import 2.2 packages
3. See error

**Comment by CDiaz-MS** [comment]
@julenka did you also import the UnityAR package?  I just tested importing the Foundation, Extensions, Tools and Example packages and this error did not show up.  This error should only occur if the UnityAR package is imported because it needs a ref to AR Foundation which can be installed through UPM.

**Comment by julenka** [comment]
Oh! That's the "Providers.UnityAR" package, yes I do think I imported that. Closing because it's user error!
