### ISSUE TITLE
A default asset was created for 'Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/DotNetAdapter.csproj' because the asset importer crashed on it last time.

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#6806]
## Describe the bug

The MSBuildForUnity project prints this on load. It might be a bug in that project, or it might be an issue with the layout of our csproj, so I'm filing it here for tracking.

## To reproduce

1. Open the repo or import MRTK 2.2
2. Mixed Reality Toolkit Menu -> Utilities -> Configure Unity Project
3. Ensure `Enable MSBuild for Unity` is enabled
4. Observe the log in the console

## Expected behavior

No issue with the asset importer.

## Screenshots

![image](https://user-images.githubusercontent.com/3580640/70266439-525f7980-1751-11ea-9024-bb762afc5bc0.png)

**Comment by wiwei** [comment]
+1, the log is somewhat confusing.

Also related is this message:

D:\src\MixedRealityToolkit-Unity\Assets\MixedRealityToolkit.Providers\WindowsMixedReality\DotNetAdapter> dotnet msbuild DotNetAdapter.csproj -restore  -v:minimal -p:NuGetInteractive=true  -t:Build -p:Configuration=Release
UnityEngine.Debug:Log(Object)
Microsoft.Build.Unity.<ExecuteMSBuildAsync>d__17:MoveNext() (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:403)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<ExecuteMSBuildAsync>d__17&)
Microsoft.Build.Unity.MSBuildProjectBuilder:ExecuteMSBuildAsync(String, String, String, IProgress`1, CancellationToken)
Microsoft.Build.Unity.<BuildProjectAsync>d__16:MoveNext() (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:396)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildProjectAsync>d__16&)
Microsoft.Build.Unity.MSBuildProjectBuilder:BuildProjectAsync(String, BuildEngine, String, IProgress`1, CancellationToken)
Microsoft.Build.Unity.<BuildProjectsAsync>d__10:MoveNext() (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:289)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<BuildProjectsAsync>d__10&)
Microsoft.Build.Unity.MSBuildProjectBuilder:BuildProjectsAsync(IReadOnlyCollection`1, String, String, IProgress`1, CancellationToken)
Microsoft.Build.Unity.MSBuildProjectBuilder:BuildProjects(IReadOnlyCollection`1, String, String) (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:173)
Microsoft.Build.Unity.MSBuildProjectBuilder:BuildProject(MSBuildProjectReference, String, String) (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:310)
Microsoft.Build.Unity.MSBuildProjectImporter:OnImportAsset(AssetImportContext) (at Library/PackageCache/com.microsoft.msbuildforunity@0.8.3/Editor/ProjectBuilder/MSBuildProjectImporter.cs:36)
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)

Maybe we should just try to avoid this logging (or make it conditional on some verbose/debug stuff that we set so that we see it, but others who are building off of it don't see it)

**Comment by jasonhbartlett** [comment]
Trying not to open a new issue but find already logged issue related to enabling MSBuild
Unity version 2018.4.20f1
MRTK Release 2.3.0  (latest)

Steps to reproduce:
Create new project in Unity 2018.4
Import MRTK 2.3.0 packages
Let MRTK > Configure Unity Project > Enable MSbuild for Unity
Set target to UWP

Close Unity and Reopen:

Getting the mentioned warning, but ALSO getting this ERROR:

```
MSBUILD : error MSB1008: Only one project can be specified.
UnityEngine.Debug:LogError(Object)
Microsoft.Build.Unity.MSBuildProjectBuilder:LogProgressMessage(String, ProgressMessageType) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:385)
Microsoft.Build.Unity.<>c__DisplayClass13_0:<BuildProjects>b__1(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:213)
Microsoft.Build.Unity.DelegateProgress`1:Report(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.<>c__DisplayClass14_0:<BuildProjectsAsync>b__1(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:330)
Microsoft.Build.Unity.DelegateProgress`1:Report(ValueTuple`2) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:516)
Microsoft.Build.Unity.<>c__DisplayClass21_0:<ExecuteMSBuildAsync>b__0(Object, DataReceivedEventArgs) (at Library/PackageCache/com.microsoft.msbuildforunity@0.9.1-20200131.14/Editor/ProjectBuilder/MSBuildProjectBuilder.cs:462)
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()
```


Is having MSBuild for Unity required for using MRTK?  Or is this an optional thing.  I discovered this problem when I was upgrading my project from MRTK v2.2.0 to 2.3.0.  But still get this error on a clean empty project for UWP.

**Comment by keveleigh** [comment]
This file has been removed, so I'm leaving this issue closed.
