### ISSUE TITLE
MRTK 2.2 : Grid newly created have incorrect default values

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#6814]
## Describe the bug
Following #6804, asset version is updated to 1 and changes the layout.

But asset version is still 0 for new grids, so new component will go through the process of updating to version 1 and will have rowthencolumn by default (instead of columnthenrow).
`private int assetVersion = 0;`

(This is non-critical bug)

## To reproduce

1. Create a grid object collection
2. observe the default layout value

## Expected behavior

Default layout should still be columnthenrow for newly created grids

## Your Setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2 stabilization post #6804 merge]

**Comment by keveleigh** [comment]
Since I think the serialized asset version is new in this release, it seems like it has to default to 0, otherwise we'd miss both old and new assets.

I wonder if it would make sense to change the default layout to rowthencolumn in order to prevent the upgrade behavior / logging. Or if you can think of another way to detect new assets / existing ones.

**Comment by gilbdev** [comment]
> it seems like it has to default to 0, otherwise we'd miss both old and new assets.

ahah, you're right...
i don't see an easy solution there to have new assets have version 1 and older one version 0 ...
maybe play with ISerializationCallbackReceiver ?

**Comment by julenka** [comment]
> I wonder if it would make sense to change the default layout to rowthencolumn in order to prevent the upgrade behavior / logging. Or if you can think of another way to detect new assets / existing ones.

The advantage of this is it would remove the confusing log statements for all new gridobjectcollections. See a tiny disadvantage that in most UI toolkits grid layout is column then row. This is minor because it's not hard to switch to column then row. 

Advantages outweigh the disadvantages. I'll prepare a PR.

**Comment by julenka** [comment]
FYI @davidkline-ms I'm going to prepare a pr for this targeting stabilization, in case we have time.

**Comment by julenka** [comment]
Fixed
