### ISSUE TITLE
Mixed Reality Toolkit component doesn't display correctly, rendering MRTK configuration unusable for the duration of the project.

### ISSUE THREAD

**Issue by FlyingFlambe** [microsoft/MixedRealityToolkit-Unity#6867]
## Describe the bug

When switching between configuration profiles, there's a chance for the MRTK component to glitch out, causing it to not be usable at all. Restarting Unity and/or removing and re-adding it to scene doesn't fix the issue.

## To reproduce

I'm not exactly certain what causes it, but I do know that if I'm messing with configuration settings long enough, the bug will reproduce itself. What I was doing at the time:

1. 2019.2.15f1: Was toggling between Default and Hololens1 configuration profiles repeatedly (was in the middle of reporting a different bug where the Hololens1 configuration is either missing default features or uses Hololens2 defaults).
2. 2019.3.0f1: Deleted a custom configuration profile from the CustomProfiles folder.

## Expected behavior

MRTK script component is still displayed as usual.

## Screenshots

![image](https://user-images.githubusercontent.com/22328598/70666386-200fb980-1c34-11ea-8736-68afe8e3bbf2.png)

## Your Setup (please complete the following information)

- Unity v2019.2.15f1 (also occurred on 2019.3.0f1)
- MRTK v2.2.0

## Target Platform (please complete the following information)

- HoloLens

**Comment by CubicVR** [comment]
Having the same issue. Nothing under camera settings after cloning MRTK Configuration Profile.
![Capture](https://user-images.githubusercontent.com/23468274/70677739-008d8680-1c5e-11ea-9d3d-2d5448c13037.JPG)

**Comment by Troy-Ferrell** [comment]
@FlyingFlambe thanks for filing this. Were there are console errors or warnings fired when this happened?

**Comment by FlyingFlambe** [comment]
@Troy-Ferrell There weren't any warnings, no.

**Comment by wiwei** [comment]
Going through some old issues, @FlyingFlambe can you reopen this if you're seeing this on a more recent Unity (i.e. 2019.2.x) or have some consistent repro that you can share out? I don't think I've ever seen this before (or have heard of anyone else who's hit this before), and without additional info it's hard to get further here.

I'm closing this just because of lack of reproducibility (even though this looks super interesting to dig into), but if you have more info definitely reopen this with that data.
