### ISSUE TITLE
Data Provider systems destroys dataproviders on disable()?

### ISSUE THREAD

**Issue by Troy-Ferrell** [microsoft/MixedRealityToolkit-Unity#6920]
## Describe the bug

Both the MixedRealitySpatialAwarenessSystem and MixedRealityInputSystem, destroy all of their data providers when disable() is called on them. via the protected `UnregisterDataProvider()` function.

However, MixedRealityCameraSystem does not perform this way and only calls disable() on it's data provider children.

## To reproduce

Look at code

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9091059ce6cf337b88086502cb4fff2be95ddd85/Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs#L111

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9091059ce6cf337b88086502cb4fff2be95ddd85/Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs#L325

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9091059ce6cf337b88086502cb4fff2be95ddd85/Assets/MixedRealityToolkit.Services/CameraSystem/MixedRealityCameraSystem.cs#L164

## Expected behavior

I would imagine that dataproviders are only destroyed when the service is called via service.destroy(). This seems a bit odd that all references to observers are lost when calling disable().

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.11f1]
- MRTK Version - dev latest

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

**Comment by Troy-Ferrell** [comment]
@keveleigh / @davidkline-ms  FYI, any knowledge of why they are currently set-up this way?

**Comment by wiwei** [comment]
Going through some old issues - @davidkline-ms might be best to address this question if only because he added the latest usage here: 

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6344

I'm guessing that this distinction here isn't actually intentional - looking at the input system (older than camera provider stuff), the way enable/disable are currently setup it really does depend on creating/destroying, and I assume that at this point changing them up to only "pause" and "resume" is probably not worth the change (i.e. risk of regression, probably not a lot of value aside from consistency with some of the new stuff).

For others, feel free to correct me if I'm wrong - this feels like a case of unintentional divergence.
