### ISSUE TITLE
Option to not instantiate MixedRealityPlayspace in the editor

### ISSUE THREAD

**Issue by MrMatthias** [microsoft/MixedRealityToolkit-Unity#6930]
## Describe the problem
I have a project for multiple platforms and only need the MRTK for the HoloLens, but a MixedRealityPlayspace is constantly instantiated, causing 2 cameras to be present when i forget to delete it. For HoloLens builds I instantiate the prefabs at runtime.

## Describe the solution you'd like
I would like to have an option to disable this behaviour

**Comment by genereddick** [comment]
I'll second this. In projects that implement parts of the MRTK but have a separate camera system I also end up with an extra camera getting added to the scene, which I don't usually notice until I run or, worse, after deploying.

**Comment by wiwei** [comment]
I was chatting with someone else who was hitting this on an older version of MRTK, and I remember doing looking at some changes since then that actually stopped automatically the MixedRealityPlayspace in scenes where the MixedRealityToolkit object didn't exist.

I'm having a little trouble fishing out that specific change because I remember that wasn't the primary goal (or even mentioned secondary goal) of the change wasn't around MixedRealityPlayspace.

This should be resolved in newer builds (if you grab mrtk_development, or wait for 2.3 to come out). If you're still seeing this on a newer package definitely reactivate with repro steps + versions.
