### ISSUE TITLE
speech keyword question

### ISSUE THREAD

**Issue by oneSitDown** [microsoft/MixedRealityToolkit-Unity#6936]
[SpeechMixedRealitySpeechCommandsProfile.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/3981725/SpeechMixedRealitySpeechCommandsProfile.zip)

## Describe the bug

I added more than four hundred keywords to my profile and speech recognition didn't work properly. Can you tell us what is the upper limit of this speech recognition keyword? In other words, what do we need to pay attention to. Shouldn't keywords have too many similar sentences?
my profile is upload

## Your setup (please complete the following information)

- Unity Version [e.g. 2018.3.14f1]
- MRTK Version [e.g. v2.1]

## Target platform (please complete the following information)

- HoloLens

**Comment by oneSitDown** [comment]
I enter fewer keywords and speech recognition works fine

**Comment by davidkline-ms** [comment]
@oneSitDown, I took a quick look at the profile you kindly attached and i noted there were several dozen instances of "Toggle Profiler".

We have not yet fully investigated possible limitations to the keyword system (MRTK, Unity or Windows), though reducing the duplication is likely to result in improved performance.

**Comment by wiwei** [comment]
Closing this out - based on the information that I'm seeing above, it sounds like this was a case of a duplicated keyword that led to the issue here.

Beyond that, the limits here AFAIK are based on the limits of the underling UWP speech APIs (https://docs.microsoft.com/en-us/uwp/api/windows.media.speechrecognition.speechrecognizer), which AFAICT don't have any specific documented limits (though I wouldn't be surprised if there were some unspoken limits i.e. MAX_PATH or something else like that).

This is an area that folks on the MRTK don't have direct access to - also if you have four hundred keywords or more, it might be an indication that there could be a different solution needed (i.e. instead of commands, you actually care about understanding intent between the different words). There are ways of doing this using other cloud speech APIs: https://azure.microsoft.com/en-us/services/cognitive-services/speech-services/ (for example)

To some degree this is probably something you could try experimenting with (i.e. for expediency, using Unity directly without MRTK, since it probably wouldn't be too crazy to whip up a script that would grep an english dictionary and then create some code that would initialize the KeywordRecognizer with that list)
