### ISSUE TITLE
Breaking Change: Fix RotateAboutGrabPoint and RotateAboutObjectCenter far interaction #6510

### ISSUE THREAD

**Issue by MichealReed** [microsoft/MixedRealityToolkit-Unity#6946]
## Describe the bug

After upgrading to 2.2.0, my MagicLeap control could grab and move, but the controller rotation would no longer effect the manipulated object. I tracked it to Issue #6510, and after reverting `TwoHandMoveLogic.cs ` and `ManipulationHandler.cs` to previous versions, my issue was solved and controller rotation effected the object as before.

I cannot test with WindowMR controllers, but this change may affect them as well.

## To reproduce

- Create a lumin project with MRTK 2.2.0
- https://github.com/HoloLabInc/MRTKExtensionForMagicLeap add this to project
- Run in zero iteration or build an mpk

## Expected behavior

The controller's movement will work, but the rotation of the controller will not have any effect on the object.

## Your setup (please complete the following information)

- Unity Version 2019.2.7f2
- MRTK Version v2.2

## Target platform (please complete the following information)

MagicLeap

## Additional context

tagging @MenelvagorMilsom

**Comment by MenelvagorMilsom** [comment]
@MichealReed hey, I just got a chance to check this on Windows Mixed Reality 6dof controllers and it appears to be working fine. I imagine that this may be an issue with MRTKExtensionForMagicLeap. `RotateAboutGrabPoint` and `RotateAboutObjectCenter` use [`TryGetGripRotation`](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/567a7c3c212986e67a5b7371c943eb06afcf839c/Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs#L948) in order to get the controller rotation. This is used to differentiate the pointer rotation and the hand pose rotation for articulated hands. However this should still provide the correct rotation for other controllers. Seeming as the this controller is implemented in the extension, I think it should be raised with them.

**Comment by wiwei** [comment]
Closing this issue out - looking at @MenelvagorMilsom's comment there looks to be an issue in the extension, though it seems like probably exacerbated/triggered by the change there. We don't currently support Magic Leap - it would probably be best at this very moment to file an issue on the ML extension repo.
