### ISSUE TITLE
Hand tracking not correctly notified of coordinate space resets

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#6974]
From holodevelopers.slack.com:

Anand Mulay 
Does anybody knows how to keep hand tracking mesh in position, i notice that as the scene changes hand mesh and it controls like finger point which require to press the button goes away at some distance and it work from there in respective of physical hand.

Eric Provencher  
I noticed this too. It’s a HoloLens 2 unity integration bug I reported ages ago.
Basically, when you change scenes, unity triggers a coordinate space reset, and it doesn’t notify the hand tracking system. What happens is that the hands move by the amount your body moved between the scenes.
The fix is to initialize the MRTK instance in a base scene when the app starts, and then never unload that. Then, additively load your first scene, and then unload it before loading your next scene. If you do a regular scene load, it’ll reset the MRTK instance and reset the coordinate space

Eric Provencher
@David Kline (MS) FYI 

Gilles Boulard
The fix is to initialize the MRTK instance in a base scene when the app starts, and then never unload that.
this is clearly the recommended way :slightly_smiling_face:

Eric Provencher
Right it's recommended to do that, but the hand origin shouldn't be offset from the camera origin when you change scenes in a way that Unity still supports

Anand Mulay 
Wohh, it helped me a lot, now it feels good to use hand inputs and pressable and grabbable things. Kudos

**Comment by camnewnham** [comment]
I've found this too. It affects other tools as well - for example locating a MediaFrameReference in unity space - it works correctly until the scene is changed whereby all the coordinates are offset.

I've worked around this in the past by creating my own coordinate systems when the scene changes. It must be called on the first frame of a scene change or in awake as otherwise the location will be incorrect. For example: https://gist.github.com/camnewnham/b0f450b37d7fcf77ebede0d710eb40f8#file-hololenscoordinatesystem (excuse the lazy singleton)

In my experience this performs the same function as the MRTK function `public static SpatialCoordinateSystem SpatialCoordinateSystem` but correctly updates the coordinates.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/b7b9fb91f2361721d088371abada8432f18b6bae/Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs

**Comment by camnewnham** [comment]
Here's my current solution to this: https://gist.github.com/camnewnham/ed99ec79c6bc48684c75d0f7d535826f

As a workaround we use `WindowsMixedRealityUtilities` as a singleton instantiated in the scene. On first load, we use the Unity provided coordinate system via `INativeSpatialCoordinateSystemPointer` (as in MRTK). On subsequent scene loads, we use `SpatialLocator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem()` to create a new coordinate system. 

In my tests (we also did the same thing on HoloLens 1) this works well. One uncertainty I have is the exact time when Unity _should_ be creating/caching the coordinate system, so `Awake` may be too late since it's called after the new scene is fully loaded. So there may be issues where moving very fast during the scene load could cause an offset. YMMV.

**Comment by ForrestTrepte** [comment]
This issue keeps cropping up for us. The additive scene loading workaround seems viable, but requires changes to apps that use regular scene switching.

It really would be much better if this automatically worked correctly. Any possibility of fixing this inside MRTK or getting a fix on the Unity side?

**Comment by keveleigh** [comment]
From my testing, #7205 (which will be part of the 2.3 release) looks to have fixed this issue. Please let me know if you're still seeing this in the 2.3 release!
