### ISSUE TITLE
excptptr.cpp missing

### ISSUE THREAD

**Issue by praptoumache** [microsoft/MixedRealityToolkit-Unity#7021]
## Describe the problem

i am trying to debug my Hololens 1 Project.
i followed this tutorial: https://docs.microsoft.com/en-us/windows/mixed-reality/managed-debugging-with-unity-il2cpp
as soon the Project is built and deployed via VS on the Hololens. VS Popup appears that searching for "excptptr.cpp" 

## Describe the solution you'd like
i tried copying the Projectfolder closer to root (cause i red about to long foldernames)

## Describe alternatives you've considered

Is there another good way to debug my Hololensaspp with Unity?

## Additional context
![grafik](https://user-images.githubusercontent.com/57391596/72076722-ea6ef680-32ed-11ea-9880-d118b2e72536.png)

**Comment by wiwei** [comment]
Reading over this issue, this doesn't look like it's related to MRTK - it seems like what's probably happening is you're hitting an exception in some STL code, and VS is trying to find the source code file as it switches to the debugging view.

I'm closing this out because this isn't related to MRTK (please reopen if this is specific to MRTK).

On you side I would try to just create an empty file called excptptr.cpp, point it at that, and see what VS is trying to do (at that point you might get a callstack which you can use to figure out more stuff)

**Comment by praptoumache** [comment]
uninstalling VS and Unity and reinstalling fixed it.
Now i can deploy from VS to Hololens.
Also can attach to The running process of the unityplayer in the hololens.
but where do i find the console Logs ?!?
