### ISSUE TITLE
MRTK 2.2 Hand cursor stops working when focused object changes scale

### ISSUE THREAD

**Issue by michalek-marcin** [microsoft/MixedRealityToolkit-Unity#7101]
## Describe the bug

Hand cursor stops working when an object on which it is focused changes scale (change scale to zero with Lerp function).

## To reproduce

- Import my unitypackage [HandRaycastProblem.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/4090604/HandRaycastProblem.zip) to empty project with MRTK and open HandRaycastProblem scene. 
- Click using hand cursor on "Hide window" button.
- Try click the button in the second window.

## Expected behavior

After minimize "animation" user can still use hand to interact with objects.

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.2.17f1]
- MRTK Version [e.g. v2.2.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by MenelvagorMilsom** [comment]
@thalbern or myself can triage this one.

**Comment by MenelvagorMilsom** [comment]
@michalek-marcin there appear to be some missing script references when I load the scene you've provided. Is it only MRTK scripts used in this repro scene?

**Comment by michalek-marcin** [comment]
Yes, it is only MRTK scripts on scene and my HandRaycastProblem script. I've cloned MRTK repo and inported my unitypackage and everything works.

In the meantime I found workaround for my problem. I disable NearInterTouchableUnityUI component just before firing animation, and bring it back when window appears again. But it's only work around.

**Comment by davidkline-ms** [comment]
There have been a large number of changes in hand tracking since MRTK v2.2. There is a strong likelihood that this has been addressed between then and the current v2.8.1 release. Please reactivate it this is still an issue.

In addition, the MRTK team is primarily focused on the upcoming MRTK3 release and the entire underlying input architecture has been replaced by Unity's input system and XR Interaction Toolkit (with customizations on top). Please feel free to check out the https://github.com/microsoft/MixedRealityToolkit-Unity/tree/mrtk3 branch or one of the preview packages, available via the Mixed Reality Feature Tool.
