### ISSUE TITLE
ManipulationHandler works with grab instead of select

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7104]
## Describe the problem

Sometimes, you might have something you want to be movable, but it's interactable throughout at the same time (browser window). Since we have a grab button on the side of any 6DOF MotionController, it would be nice to directly interact with select and move it around with grab. The problem is, that the ManipulationHandler handles it's interactions all by itself. Instead of being called from a script on how to operate things it deals with them in its own right (it implements the interaction interfaces directly).
One can not specify what the action is that moves it. Furthermore, only OnPointerDown respects the eventData's use property. This means, you cannot even reroute the OnPointerUpdate through another script.

## Describe the solution you'd like

ManipulationHandler should be handling the movement, orientation, constraints etc. The logic for where the input comes from should be put into another script. The ManipulationHandler knows what Input it needs so the current OnPointer* calls could be replaced and called from outside. The we would have control over where the input comes from and what type it is.

## Describe alternatives you've considered

I'll see if I modify the DefaultControllerPointer so it does react to the grab action in addition to the select action.
I also might hack something to mimic selection with the grab input, alter the ManipulationHandler so it does not listen itself and then also call into the DefaultControllerPointer so it looks as if select was pressed.

## Additional context
Maybe there is an existing way, I could not find one

**Comment by RogPodge** [comment]
There is currently a PR pending approval which adds near interactions to controllers, making it so that the users can use the grab action on 6dof controllers and move objects via near manipulation with the grab button.

I'm not sure if this issue is also asking for using the grab button for far interactions, but a more complicated set of effort would be required on that front, since each pointer is only associated with one pose action, and adding a redundant far pointer would warrant some performance considerations. 

@Alexees if you have more context on the original scenario, please reach out and let us know!

**Comment by RogPodge** [comment]
Related: #10057

**Comment by RogPodge** [comment]
marking a closed due to #10057 and v 3.0 improvements to object manipulation.
