### ISSUE TITLE
Rebuilding Handmesh with the Hand joints data? OR Input simulation record and playback the Hand mesh data.

### ISSUE THREAD

**Issue by pampas93** [microsoft/MixedRealityToolkit-Unity#7154]
## Describe the problem
Using the Input simulation feature, I hacked a couple of parts of MRTK, and I can now record my hand joints and playback on UWP player (HoloLens 2). But the input simulation only saves the joints, and while playback, only plays the joints movement. My Question is, would this same feature be possible with Hand mesh?

Reason I ask, it would best to showcase and teach the new/custom gestures to the users within the app. For now, I can playback the gestures, but shows hand joints only. If we can playback with the hand mesh, that would be more intuitive way to teach new gestures to the user.

Can someone explain as to how exactly is the app getting the `HandMeshInfo` after implementing the `IMixedRealityHandMeshHandler` ? Or is it possible to create the Hand mesh by using just the Hand joints data?

## Describe alternatives you've considered

Alternative was create animations using rigged hands on other 3D softwares, import and play within Unity. it just using the input simulation would be a better solution.

**Comment by wiwei** [comment]
I believe that the hand mesh is actually coming from the system itself (i.e. the HL2 device as being the current system that exposes hand mesh data). As a result, in editor when you use input simulation (playback/recording/live) all you have are access to the joints, which are 'faked' via just their joint positions.

@keveleigh do you happen to know if other platforms also expose their hand mesh via XR SDK going forward (i.e. would only work on device)?

I think that we've also chatted about having hand mesh in-editor (and also on device) that isn't tied to your actual hand controllers, so that we could do teaching things (i.e. teach a person how to use a hand menu, etc).

Definitely something we could consider doing if there's a lot of demand for this.

**Comment by keveleigh** [comment]
>do you happen to know if other platforms also expose their hand mesh via XR SDK going forward (i.e. would only work on device)?

As far as I'm aware, there isn't built-in support for hand mesh in XR SDK. For our support in MRTK, I'm going around to the Windows APIs in order to load the hand mesh for HL2.

**Comment by rolandsmeenk** [comment]
Rigged hand visualizer #7993

**Comment by Zee2** [comment]
#7993 should have resolved this. If this use case is still not resolved, please reopen.
