### ISSUE TITLE
Hand tracking continuous GC Alloc resulting in fps drop

### ISSUE THREAD

**Issue by gilbdev** [microsoft/MixedRealityToolkit-Unity#7170]
## Describe the bug

When hand are tracked, MRTK is allocating memory continuously, resulting in a 10fps drop per hand.

This is in HL2 headset, Release build and unity profiler active.

## To reproduce

1. build a version for HL2 in release
2. launch on device and connect unity profiler
3. show both hands to have them track and ovserve fps dropping + 

## Expected behavior

no GC alloc during Update.

## Screenshots

![image](https://user-images.githubusercontent.com/49415246/73250757-c5b4c300-41b7-11ea-8ba7-38e54387b335.png)

## Your setup (please complete the following information)

- Unity Version [2018.4.13f1]
- MRTK Version [v2.2.0]

## Target platform 

- HoloLens 2

## Additional context

apparently this is an issue that's coming again (#5572 , #5107), this could have a unit test ?

**Comment by provencher** [comment]
@gilbdev when you say "show both hands " do you mean show the hand mesh? Because that will almost certainly generate tons of garbage.

Just the tracking should not cause this level of GC allocation however.

**Comment by gilbdev** [comment]
taht's indeed the default hand mesh provided by MRTK. i didn't yet  deep dive into it to know if problem is from rendering or process, but i don't see any reason for the defualt behavior to provdie such leak and memory alloc each frame.

**Comment by wiwei** [comment]
When we looked into this before, there is alloc occuring when getting data from the underlying system APIs that provide the meshes - i.e. we ask for meshes, it gives meshes which end up getting copied due to how certain data types end up getting duplicated on assignment.

@keveleigh had some ideas on newer Unity features that might make this more performant, but we haven't looked into this (and as a result, we recommend in our docs and everything to disable the hand mesh)

**Comment by keveleigh** [comment]
Hand mesh performance tracking issue, with some additional info: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5097

**Comment by provencher** [comment]
2019.3 does have native mesh apis, that allow updating mesh data without re-allocating. It is also possible to update mesh data from a job, to avoid clogging the main thread.
