### ISSUE TITLE
MixedRealityKeyboard.OnHideKeyboard is never called when someone *cancels* the system keyboard

### ISSUE THREAD

**Issue by LocalJoost** [microsoft/MixedRealityToolkit-Unity#7179]
The Microsoft.MixedReality.Toolkit.Experimental.UI.MixedRealityKeyboard has three events:

- OnShowKeyboard - called when the keyboard appears
- OnCommitText - called when the user presses the enter key
- OnHideKeyboard - called when the keyboard disappears (but not always)

OnHideKeyboard is _only_ called when someone presses ENTER key on the system keyboard. First OnCommitText is called, then OnHideKeyboard. When someone _cancels_ the keyboard - by pressing the X button right top - no event is called.

As a consequence, the MixedRealityKeyboardPreview is never hidden, although the code suggest that it should be. And this happens correctly when one presses the Enter key.
 
## To reproduce

- Build app from MRKT2 source for x86 or x64, 
- make HandInteractionExamples scene one and only scene
- Select the Keyboard button
![image](https://user-images.githubusercontent.com/4129183/73355324-39c69800-4298-11ea-9e14-ac460120889b.png)
- Keyboard and MixedRealityKeyboardPreview appear
- Cancel keyboard
- Keyboard disappears, MixedRealityKeyboardPreview not

## Expected behavior

In the last step, I expect the MixedRealityKeyboardPreview to disappear as well.

## Your setup (please complete the following information)

- Unity Version 2018.3.13f1
- MRTK Version 2.20

## Target platform
- HoloLens
- HoloLens 2 (NOT TESTED)
- WMR immersive

## Additional context

The issue seems to stem from Microsoft.MixedReality.Toolkit.Experimental.UI.MixedRealityKeyboard. The inputPane events are just never called.

**Comment by LocalJoost** [comment]
There seems to an issue with InputPane events indeed... https://stackoverflow.com/questions/14919458/inputpane-showing-hiding-never-called

**Comment by wiwei** [comment]
I took a look at this today, and it looks like this is something where we're kinda SOL because of underlying OS bugs.

There are known issues where the keyboard doesn't notify the app when the keyboard gets hidden, and I was hoping that it would at least update its state (so that if you queried if it were visible, you could get the right answer):

So I tried a few things, where this was the final attempt out of several:

@@ -23,7 +24,7 @@ public class MixedRealityKeyboard : MonoBehaviour
         /// <summary>
         /// Returns true if the keyboard is currently open.
         /// </summary>
-        public bool Visible { get { return state == KeyboardState.Showing; } }
+        public bool Visible { get { return state == KeyboardState.Showing || state == KeyboardState.Shown; } }

         /// <summary>
         /// Returns the committed text.
@@ -84,6 +85,7 @@ private enum KeyboardState
             Hiding,
             Hidden,
             Showing,
+            Shown,
         }

         private KeyboardState State
@@ -106,6 +108,8 @@ private KeyboardState State
         private TouchScreenKeyboard keyboard;
 #if !UNITY_EDITOR && UNITY_WSA
         private InputPane inputPane = null;
+        private float lastInvokeTime = 0;
+        private const float InvokeCooldownSeconds = 2.0f;
 #endif //!UNITY_EDITOR && UNITY_WSA
         private bool multiLine = false;

@@ -131,9 +135,11 @@ protected virtual void Start()
         /// </summary>
         protected virtual void Update()
         {
+            ReconcileHiddenState();
             switch (State)
             {
                 case KeyboardState.Showing:
+                case KeyboardState.Shown:
                     {
                         UpdateText();
                     }
@@ -182,7 +188,12 @@ public virtual void ShowKeyboard(string text = "", bool multiLine = false)
             {
                 keyboard.text = Text;
 #if !UNITY_EDITOR && UNITY_WSA
-                UnityEngine.WSA.Application.InvokeOnUIThread(() => inputPane?.TryShow(), false);
+                UnityEngine.WSA.Application.InvokeOnUIThread(() =>
+                {
+                    inputPane?.TryShow();
+                    State = KeyboardState.Shown;
+                    lastInvokeTime = Time.time;
+                }, false);
 #endif
             }
             else
@@ -306,6 +317,41 @@ private void MovePreviewCaretToEnd()
             CaretIndex = Text.Length;
         }

+        /// <summary>
+        /// This function exists to workaround a HoloLens 1 OS bug, where
+        /// some sytem keyboard hides do not trigger the InputPane.Hiding
+        /// event. This can put our internal state in a bad situation where
+        /// this code also does not know to trigger the OnHideKeyboard event
+        /// </summary>
+        private void ReconcileHiddenState()
+        {
+#if !UNITY_EDITOR && UNITY_WSA
+            // Note that because this InvokeOnUIThread doesn't wait for the
+            // operation to finish, there's a race condition where in ShowKeyboard
+            // the time between when Show is called to when the other thread
+            // gets around to actually showing the keyboard, another Update() call
+            // will happen (which will trigger a hide). As a result, we need to
+            // wait for the KeyboardState to actually be Shown.
+            if (State == KeyboardState.Shown)
+            {
+                UnityEngine.WSA.Application.InvokeOnUIThread(() =>
+                {
+                    // Only do this workaround if:
+                    // 1. We've already tried to shown the keyboard
+                    // 2. Enough time has passed since the keyboard has shown (i.e. the show keyboard function
+                    // is async and even after claling it, inputPane.Visible may not have been updated)
+                    // 3. The InputPane is now no longer visible.
+                    // Without #2, it's possible that we can immediately transition to "hiding" because the OS itself
+                    // is still asynchronously transitioning to the non-Visible state.
+                    if (State == KeyboardState.Shown && (Time.time - lastInvokeTime) > InvokeCooldownSeconds && !inputPane.Visible)
+                    {
+                        State = KeyboardState.Hiding;
+                    }
+                }, false);
+            }
+#endif // !UNITY_EDITOR && UNITY_WSA
+        }
+
         private void OnKeyboardHiding()
         {
             if (State != KeyboardState.Hidden)

Note that the keyboard APIs as async, and showing/hiding involves some "waiting" for the show/hide to actually animate/state change to happen. Unfortunately once it has shown and you press the cancel button, the InputPane.visible state is never updated (to not visible) so there isn't really much that we can do (i.e. we have to rely on the OS APIs to be right).

AFAIK there might be some update/fixes coming in some future OS update but until then unfortunately the underlying APIs themselves are still broken (in a way that we cannot really workaround)

**Comment by LocalJoost** [comment]
Yeah. The underlying Windows API is broken. I spent quite some time on this and came to the same conclusion. I think the NonNativeKeyboard is the best option for now

Joost van Schaik

Windows Development MVP & Windows Insider MVP
Sent from my Surface Go

"The world as I envision it in my head is such a more interesting place"
