### ISSUE TITLE
selectedObject in eventData causes a null reference exception when read.

### ISSUE THREAD

**Issue by Liam-Fologram** [microsoft/MixedRealityToolkit-Unity#7187]
## Describe the bug

User can trigger a null reference exception when accessing the `selectedObject` value within events that inherit `UnityEngine.EventSystems.BaseEventData`.

## To reproduce

Access `selectedObject` in any way from an MRTK event.
```
public void OnPointerDown(MixedRealityPointerEventData eventData)
{
    if (eventData.selectedObject == null) return;
    // null reference just reading.
}
```

## Expected behavior

- Accessing `selectedObject` should be a shortcut that returns the `CurrentPointerTarget` from the events `Pointer.Result` , if one exists.

for example:
```
public new GameObject selectedObject { get => Pointer.Result.CurrentPointerTarget }
```

## Screenshots
![image](https://user-images.githubusercontent.com/60453617/73411312-07c93a80-4359-11ea-9aca-19932a11e8c3.png)

## Setup

- Unity Version 2018.4.14f1
- MRTK Version 2.2.0

## Target platform
- HoloLens
- HoloLens 2

**Comment by wiwei** [comment]
Interesting - I don't think that we've really considered using this field in the past because we only really use BaseEventData as a mechanism for sending out events (but don't REALLY care about the actual fields that it has).

i.e. as you mention, everything's on Pointer/Result/other stuff that isn't BaseEventData.

There are a few thoughts here:
1) I think that having selectedObject be null to 'force' access on the actual richer information may be the intent - otherwise fitting the "richer' information of the currentPointerTarget into selectedObject does drop information (i.e. if you're coding using autocomplete, you now don't see/consider previousPointerTarget).
2) At the same time, selectedObject and currentPointerTarget are kinda the same thing, so maybe that's not that bad. We could obviously add comments saying that it's just a redirect for this other thing and give where to get additional information.
3) Accessing a member (any member) shouldn't trigger a NullRerferenceException.

@julenka @keveleigh  thoughts?
