### ISSUE TITLE
Scrolling Object Collection with complex container children.

### ISSUE THREAD

**Issue by mikecancelosi** [microsoft/MixedRealityToolkit-Unity#7228]
## Describe the problem

The scrolling object collection script does not work properly with complex objects. For example, I have an empty parent with multiple children that have mesh renderers. For some reason the touch area doesn't scale properly with this setup.

## Describe the solution you'd like

Having a separate object that defines the touch area that can be manually positioned and scaled would a better solution.

## Describe alternatives you've considered

An alternative to the above solution would be to base the scale on all mesh renderers found in children of the Container object

**Comment by vaoliva** [comment]
Hi @mikecancelosi . Are you able to scale the touch area / scrolling area by customizing the values on tiers, viewable area, cellWidth, CellHeight?

**Comment by JYBA1** [comment]
Also I have noticed that the scrolling does not work at all when the top element isn't the interactable. The ScrollingObjectCollection checks if the interacted element is in the NodeList and it's not because it's actually it's parent that is in the list.

Ideally it should check if it or it's parents are in the collection.

**Comment by mikecancelosi** [comment]
Unfortunately I have switched jobs and no longer have access to the h
