### ISSUE TITLE
Every package install opens the MRTK Project Configurator

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedRealityToolkit-Unity#7332]
Currently every time I install or upgrade a package on Unity 2019.3.1f1 and MRTK 2.3 the MRTK Project Configurator opens. All settings have already been applied. Click apply again or close it, and next time I install a package it reopens.

Unity 2019.3.1f1
MRTK 2.3

**Comment by davidkline-ms** [comment]
Thanks for the report!

**Comment by genereddick** [comment]
Actually opens it whenever I save a C# file as well.

**Comment by wiwei** [comment]
Ah man, it looks like the fix that we took here: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7251 wasn't fully complete. We missed the part modifying the config getters/setters (i.e. they were still active, even if they didn't have a corresponding toggle, there was still code checking to see if we needed to apply MSB4U.

**Comment by CDiaz-MS** [comment]
This issue exists in the 2.4 packages in 2019.3 still.

**Comment by keveleigh** [comment]
Does it look like any of the settings are unchecked when the configurator pops up?
Also are you set up for the legacy backend or XR SDK?

**Comment by CDiaz-MS** [comment]
When you import the foundation package, the first time the project configurator comes up, it looks like this:
![image](https://user-images.githubusercontent.com/53493796/81458894-cfa07780-9151-11ea-9912-4b21619add3e.png)

The second time like this:
![image](https://user-images.githubusercontent.com/53493796/81458928-f8c10800-9151-11ea-85ad-969868cda11b.png)

Then each time it comes up after that, the options are greyed out.

I am not changing any of the settings on import, so it looks like I am using legacy backend.

**Comment by keveleigh** [comment]
If I had to guess, it's likely because the Audio spatializer is set to None, which shows up as an unconfigured spatializer:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/82d0983fd6c90f5899e382244bd86c8b4cea55cc/Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs#L38-L43

@davidkline-ms?

**Comment by davidkline-ms** [comment]
note: this was reported against mrtk 2.3. i believe @wiwei is on the right track that we are still looking to set MSB4U

**Comment by keveleigh** [comment]
>note: this was reported against mrtk 2.3

I think this is just a reused issue that describes similar behavior as what's being seen in 2.4.
@wiwei's observation should have been fixed with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7349, and a follow-up issue with `XR enabled` on XR SDK was fixed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7655.

>I can make a change to allow for null

Do we want to allow for null? If so, then the only case we're checking against is when some other spatializer (but not no spatializer) is set, which feels like the most common case when you'd want to ignore this warning (if you explicitly set a different spatializer, you probably know what you're doing and are using your own spatializer or a platform-specific non-Windows spatializer for a reason?).

Maybe we should still show the spatializer dropdown in the configurator, but not use it at all for checking if things are properly configured?

**Comment by davidkline-ms** [comment]
hmmmm... good point.

this WAS the intended design then

**Comment by RogPodge** [comment]
I think with this change we only check if the configured spatializer is installed (and the only reason it wouldn't be is if it got uninstalled at some point), or when the number of installed spatializers changed. 

Ignoring the null check still preserves the drop down menu though so we don't have to worry about that case
