### ISSUE TITLE
Add IsPropertyAvailable and IsTypeAvailable to WindowsApiChecker class

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7426]
Similar to the new IsMethodAvailable(), add IsPropertyAvailable and IsTypeAvaliable.

Once added, update references to ApiInformation.Is<Property|Type>Present in the MRTK code.

**Comment by julenka** [comment]
Can you explain please *why* we need to make this change?

**Comment by keveleigh** [comment]
It provides an MRTK-abstracted API for devs to call, instead of needing to manage `#define`s and the DotNetWinRT adapter themselves.

The `Is[*]Present` platform API is important so we don't call APIs on older OSs where the API might not exist. For example, making sure we don't try to call the hand joint APIs on an OS pre-18362.

To account for the possibility of API backports, it's better to code for the existence of the API instead of the existence of a specific UWP version, which is what we were doing pre-https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7402. This follow-up issue fills out the availability APIs past just `Method`.
