### ISSUE TITLE
Extension services run even when not in playmode

### ISSUE THREAD

**Issue by FejZa** [microsoft/MixedRealityToolkit-Unity#7474]
## Describe the problem

As discussed in the mrtk slack channel I am bringing up to discussion here, whether extension services / systems should get the `Initialize()` call even if the editor is NOT playing. While the core services seem to work the way they are with custom services created by MRTK users it's likely people run into issues, since they don't expect any of the service lifecycle methods to run when no playing.

The call path is: `MixedRealityToolkit.OnValidate() -> RegisterInstance() -> InitializeInstance() -> InitializeServiceLocator() -> InitializeAllServices()`

## Describe the solution you'd like

Do not initialize extension services when not running the player.

## Describe alternatives you've considered

Keep it the way it is and work around it using

```
if (!Application.isPlaying)
{
  return;
}
```

**Comment by davidkline-ms** [comment]
Excellent question and feedback @FejZa! We will look into this.

**Comment by keveleigh** [comment]
This is currently by-design, yeah. There are some services that require edit-time set-up, which is why `Initialize` gets called even when the editor isn't playing. It feels like an asymmetrical pattern to prevent this from being possible with extension services.

It may be that this is poorly documented and something we should make sure is obvious. It may also be necessary to reevaluate this action. I know @wiwei had been specifically investigating that `OnValidate()` call, especially with the frequency it happens.

**Comment by FejZa** [comment]
I see. I agree in that case a note in the extension services docs might help. Currently the only way of learning about it is running into errors when some null reference exceptions or whatever get thrown in the `Initialize()` call.

**Comment by marek-stoj** [comment]
The more I use MRTK and look under its hood, the more it seems to me that Extension Services were meant to be what their name suggests - to extend the framework itself rather than use them as business/application-level services. I think the fact that some services need to do some initialization work in Edit mode adds to this point.

I wonder what will happen with the idea of standalone services which are currently implemented as Experimental and which I don't believe have this problem. See this discussion: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3545#issuecomment-508883850

**Comment by keveleigh** [comment]
> I agree in that case a note in the extension services docs might help.

I'll add a note to the interface method to clarify when this method will be called and how it can be used. Your code snippet above with `Application.isPlaying` is the same pattern we've adopted in various parts of the MRTK, and I'm also going to work that into our docs.
