### ISSUE TITLE
Not all MRTK standard materials have the proximity light enabled

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7481]
Review and update all MRTK standard materials to enable the proximity light to help improve user confidence and consistency.

**Comment by Troy-Ferrell** [comment]
@davidkline-ms me and @Cameron-Micka were actually discussing this recently. We noticed that the MRTK standard materials are inconsistent in some of their default properties. 

However, we were thinking the proximity light should be disabled by default. The proximity light(s) code is actually quite wasteful when the keyword is enabled because the vast majority of time, we aren't coloring anything. The majority of time holograms aren't close enough for the proximity light to impact color but we are calculating for it every frame and every pixel in the fragment shader.

**Comment by Cameron-Micka** [comment]
I agree with @Troy-Ferrell, the Proximity Light setting should be **disabled** on most materials (sans explict UI ones).

While we are on this topic, I know we agreed that the Hover Light setting should be **enabled** by default for everything (current behavior) eons ago. Might be good to reel that back too and only explicitly enable it for UI materials? @cre8ivepark what do you think?
