### ISSUE TITLE
TextMeshPro Shader Renders Black Background When Before Other Shader with higher Render Queue

### ISSUE THREAD

**Issue by ILikeCreamCheese** [microsoft/MixedRealityToolkit-Unity#7523]
## Describe the bug

If a TextMeshPro with the MRTK TMP Shader that has Depth Write enabled is rendered before a hologram with the MRTK standard shader and a higher Render Queue, a black background becomes visible behind the characters. This sort of looks like a black mail text. The text is positioned closer to the camera than the hologram.

## Screenshots
![image](https://user-images.githubusercontent.com/15211584/76433861-38b77900-63b5-11ea-9cb9-a9100a0a6476.png)

## To reproduce

1. Add a 3D Cube and add the MRTK Shader to it with a Render Queue of 3001+
2. Add a TextMeshPro before the Cube use the MRTK TextMeshPro Shader with Depth Write enabled
3. Notice the black background appearing behind the characters.

## Expected behavior

A clear background would be expected like this:
![image](https://user-images.githubusercontent.com/15211584/76434678-43bed900-63b6-11ea-9c5c-c5df15681bdb.png)

## Your setup (please complete the following information)

- Unity Version 2019.2.17f1
- Using MRTK version 2.3

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2

**Comment by keveleigh** [comment]
@Cameron-Micka, any ideas?

**Comment by Cameron-Micka** [comment]
Hi @ILikeCreamCheese unfortunately this is expected behavior due to the render queue sort order and depth settings. If you look at the Text Mesh Pro (built in and MRTK) shaders they are in the _Transparent_ render queue (which has a value of 3000). So, if you have a Cube with a MRTK material with a render queue of 3001+ (and writes depth) and a Text Mesh Pro material (which also writes depth), this is what Unity will do in a scene organized like above:

1) First the Text Mesh Pro text will be drawn because it has a render queue of 3000. The text will write a value to the depth buffer (because it has been marked to write depth). Note, each glyph will write a rectangular "block" to the depth buffer since that is the underlying geometry (you can see this if you look at the text in wireframe mode).

2) Second the Cube will render because it has a render queue of 3001. The cube tests for depth and **fails the depth test** because the text is closer to the camera. So, any pixels the text wrote to that overlap the cube will not be colored by the cube and the background will be visible.

Here is an example following your repo steps:

![image](https://user-images.githubusercontent.com/13305729/76458832-60e4af00-6398-11ea-9fb4-0e25eae81d65.png)

There are a number of ways to resolve this. I would recommend option 'A' if possible for your project.

A) Don't modify the render queue of the Cube. Keep it at it's default value so that it renders before the Text Mesh Pro Text.

B) Don't have the Text Mesh Pro text write to depth (don't hit the "Fix Now" button). This may cause holographic stabilization issues if your text is not near another hologram that writes depth.

C) Modify the "Mixed Reality Toolkit/TextMeshPro" shader to render at a higher render queue than 3000. If you need this for your project I would love to know the use case and we can make it a feature in the MRTK!

D) Modify the "Mixed Reality Toolkit/TextMeshPro" shader to not write depth for pixels which are transparent. You can see what this would look like if you enable the _UNITY_UI_ALPHACLIP_ keyword on your material. This may cause extra aliasing on your text which may not be desirable?

Please let me know if any of these options work for you!

**Comment by ILikeCreamCheese** [comment]
Thank you so much for the detailed explanations! 

Ah, I need to correct that the before mentioned black background is actually just the clear flag color of my camera.

A bit more about the use case:
We didnt go with A) because we have UI that the user can place and that becomes invisible when inside a specific kind of hologram in our app. Maybe there's a different solution though?

Cube With <3000 RenderQueue (what we dont want)
![image](https://user-images.githubusercontent.com/15211584/76506311-46b7d900-644b-11ea-918f-2feec8f6da2f.png)
Cube With 3000+ RenderQueue (the look we want)
![image](https://user-images.githubusercontent.com/15211584/76506293-369ff980-644b-11ea-8c6a-5548d9b22086.png)

B) we tried as well and because of the stabilization issue we didnt go with it.

C) fixed the issue, however TMP UGUIs using that same material are not rendered when under a mask component. I think I can workaround this with a different material for those.

D) Also fixed the issue. Didnt find any Aliasing issues (yet?)

So for I now Im going with option D, Im going to test some more on the glasses to see if any other issues come up.

Thank you @Cameron-Micka !

**Comment by Cameron-Micka** [comment]
That's great option 'D' worked for you! If you need your UI elements to always render "on top of" other holograms you can also make sure the UI elements are on a high render queue (for example Overlay which is 4000) and then mark the UI to not depth test "Always." This will ensure your UI gets rendered last and doesn't care about the contents of the depth buffer while still writing depth. (Note, you may need to sort you individual items render queues still so they do not write over each other.)
