### ISSUE TITLE
Obsolete SetupDefaultInteractions is now broken

### ISSUE THREAD

**Issue by Alexees** [microsoft/MixedRealityToolkit-Unity#7528]
## Describe the bug

This method is now broken instead of just obsolete, the method is not called anymore.

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/13d811186503310ab5d69aac43d8a9b3db86dda0/Assets/MRTK/Core/Providers/BaseController.cs#L173

Shouldn't the method be removed instead of being marked as obsolete as it does not even work anymore?

## To reproduce

1. In my case it was the Oculus Go controller, which is symmetrical and uses the same mapping for left and right. The handedness is either left or right but what i need is the DefaultInteractions, which are not picked because the parameter of the obsolete method is not used.

## Expected behavior

obsolete does not mean break and should still work

## Your setup (please complete the following information)

- Unity Version 2018.3.15f1
- MRTK Version mrtk_development

## Target platform (please complete the following information)

- Oculus Go

**Comment by keveleigh** [comment]
Yeah, this one's on me for removing the implementation. All of our controller implementations followed some best practices around handedness (that we should really document more), so I made assumptions based on those. I have some ideas based on those existing practices that I'd love your feedback on:

1. All of the MRTK-defined controllers that use the same interactions between hands override the `Left`/`Right` implementations to make that explicit: 
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/733e7615c4adfd9c4878c0a125dbc77a8f18d877/Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/BaseWindowsMixedRealitySource.cs#L28
This could be moved down into base controller, and then only `DefaultInteractions` would need overriding instead of all three.
2. Reinstate the old implementation. Would lead to some duplicate code but would prevent what you're seeing.

I'm leaning towards number 1, since it removes some work on the side of controller implementers.

**Comment by Alexees** [comment]
> 1. All of the MRTK-defined controllers that use the same interactions between hands override the `Left`/`Right` implementations to make that explicit

Assuming, that you need "some" mapping, no matter what, I suggest to check the handedness for an overridden implementation in the base controller and if it does not exist, pick DefaultInteractions. Then there won't be the need for explicitly overriding both hands. If you have explicit hands, override their implementation. If you don't, override DefaultInteractions:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/733e7615c4adfd9c4878c0a125dbc77a8f18d877/Assets/MRTK/Core/Providers/BaseController.cs#L178-L192

**Comment by keveleigh** [comment]
Good idea @Alexees! I opened https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7552 which should allow for that
