### ISSUE TITLE
Missing the link to 'Visualization of visual attention' documentation in MRTK 2.3.0 documentation

### ISSUE THREAD

**Issue by madhawap** [microsoft/MixedRealityToolkit-Unity#7542]
## Describe the issue
The subtopic "Visualization of visual attention" is not linked in https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/EyeTracking/EyeTracking_ExamplesOverview.md#visualization-of-visual-attention

## Feature area
Eye tracking examples in MRTK has 4 main examples. 
1. Eye-Supported Target Selection
2. Eye-Supported Navigation
3. Eye-Supported Positioning - The link here says "This content will be updated soon!" Looking forward to it. 
4. Visualization of visual attention - This subtopic is not linked to further explanations. Looking forward to any documentation if available. 

## Existing doc link
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Documentation/EyeTracking/EyeTracking_ExamplesOverview.md#visualization-of-visual-attention

**Comment by wiwei** [comment]
@sostel FYI, I think this was something that was put into the outline but never actually made it in.

I'm going to remove the link/outline in the interim because I think that having a teaser or broken link is worse than having nothing at all (it gets your hopes up only to dash them immediately).

@sostel if you have any other guidance/things written up I'm also happy to condense them into written form
