### ISSUE TITLE
MRC error in editor

### ISSUE THREAD

**Issue by amfdeluca** [microsoft/MixedRealityToolkit-Unity#7573]
_I don't know if this is the right place to post my issue. If not, I kindly ask you to delete my thread as well and accept my apologies._

## Describe the bug

Unity gives me error while VS doesn't, i've tryed to follow the steps from https://docs.microsoft.com/en-us/windows/mixed-reality/mixed-reality-capture-for-developers

## To reproduce

1. In VS try to reference the "HolographicDisplay" class
2. Add the "using Windows.Graphics.Holographic" namespace
3. See error in Unity editor while in VS is all ok

## Expected behavior

Unity Editor reference correctly the namespace so i can try the MRC feature

## Screenshots

![Screenshot (56)](https://user-images.githubusercontent.com/56428422/77321607-b616ae00-6d12-11ea-83f0-c8551dbc5303.png)
![Screenshot (55)](https://user-images.githubusercontent.com/56428422/77321623-ba42cb80-6d12-11ea-8b4f-f0fbd8032df6.png)

## Your setup

- UWP
- Unity Version 2019.2.21f1
- MRTK Version v2.3.0
- Visual Studio 2019
- Windows SDK 18362

## Target platform

- HoloLens 2

**Comment by keveleigh** [comment]
Ah yes, since you're referencing an API in a `Windows.` namespace, this isn't callable by default in Unity.

There's some info here about a plug-in you can import which adapts these APIs for use in-editor: https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-namespace-with-unity-apps-for-hololens#mixed-reality-apis

We also have built-in support for that plug-in in MRTK, but our NuGet importer (MSBuild for Unity) wasn't working well with Unity 2019 so we temporarily disabled it for the MRTK 2.3 release. If you import the plug-in manually using the steps linked above, you [can use this setting](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CameraSystem/WindowsMixedRealityCameraSettings.html#render-mixed-reality-capture-from-the-photovideo-camera) if you [add the correct `#define`](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#dotnetwinrt_present-define-written-into-player-settings).

**Comment by keveleigh** [comment]
Also, in response to 

>I don't know if this is the right place to post my issue.

these types of questions we typically look on [StackOverflow](https://stackoverflow.com/questions/tagged/mrtk) for. That way, both questions and answers are more easily findable than in the issues list of a GitHub project.

**Comment by amfdeluca** [comment]
> Ah yes, since you're referencing an API in a `Windows.` namespace, this isn't callable by default in the Unity editor.
> 
> There's some info here about a plug-in you can import which adapts these APIs for use in-editor: https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-namespace-with-unity-apps-for-hololens#mixed-reality-apis
> 
> We also have built-in support for that plug-in in MRTK, but our NuGet importer (MSBuild for Unity) wasn't working well with Unity 2019 so we temporarily disabled it for the MRTK 2.3 release. If you import the plug-in manually using the steps linked above, you [can use this setting](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/CameraSystem/WindowsMixedRealityCameraSettings.html#render-mixed-reality-capture-from-the-photovideo-camera) if you [add the correct `#define`](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#dotnetwinrt_present-define-written-into-player-settings).

Hi thank you, this solved my issue, yesterday i was working with the !UnityEngine_Editor properties, so building a new project each time, but now i can play and test my scripts also in play mode. Thank you :)
