### ISSUE TITLE
GridObjectCollection object is offset from Anchor on Cell Height change

### ISSUE THREAD

**Issue by tank-t-bird** [microsoft/MixedRealityToolkit-Unity#7666]
## Describe the bug

If the Anchor on a GridObjectCollection is set to Upper Left, Upper Right or Upper Center and the Cell Height is changed, the top of the uppermost object will not remain in place. Similarly, when it is set to Bottom Left, Bottom Right or Bottom Center, the bottom object will change position on changing the Cell Height. 

## To reproduce

1. Create an Empty Game Object
2. Add a GridObjectCollection component
3. Add a Pressable Button prefab and duplicate it several times
4. Set the Cell Height to a small value such as 0.05
5. Set the Anchor value to Upper Left
6. Click Update Collection and note where the top of the topmost object is.
7. Change the Cell Height to a larger value such as 0.1 or more
8. Click Update Collection and note that the top of the object is now at a different height.

## Expected behaviour

The expected behaviour is that the top or bottom object will remain fixed in place while the spacing changes for the other objects. 

## Your setup (please complete the following information)

- Unity Version 2019.3.4f1
- MRTK Version v2.3

## Target platform (please complete the following information)

- HoloLens 2

## Additional Notes

This is related to feature request in #4777 and merged in v2.2, but the slight offset from the anchor position makes it not as useful for the use case mentioned in #4777, that is, making a list of buttons "drop down" from a fixed position in a collection.

**Comment by keveleigh** [comment]
@RogPodge is this something that might be addressed by https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7664?

**Comment by RogPodge** [comment]
My PR doesn't quite address this issue. As I understand it, the collection currently aligns the object in the grid by the following logic.

Each item in the grid is contained within a cellWidth x cellHeight square like so.

![image](https://user-images.githubusercontent.com/39840334/79375732-f29e8980-7f0d-11ea-90f5-affe5c801281.png)

Using the UpperX or BottomX anchor will then position objects such that the anchor is located along the top or bottom of the cell, which causes shifting behavior when increasing the cell height due to increasing the margin between the object and the cell border.

![image](https://user-images.githubusercontent.com/39840334/79376076-79ebfd00-7f0e-11ea-85f9-827d8760891a.png)

As I understand it, we want to anchor objects like this instead?

![image](https://user-images.githubusercontent.com/39840334/79376138-925c1780-7f0e-11ea-876f-57e3135e1c5c.png)


@julenka @tank-t-bird thoughts?

**Comment by tank-t-bird** [comment]
Hello @RogPodge and @julenka thanks for the feedback request. Attached is a clip of where my expectations for the alignment behaviour came from, Unity's Vertical Layout Group component. 

 ![Ideal](https://user-images.githubusercontent.com/1682012/79455393-15ec3600-7fed-11ea-9d76-8daf7add7fb3.gif)

**Comment by RogPodge** [comment]
We have a PR addressing this now :)

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7676
