### ISSUE TITLE
Community feedback: controller mapping profiles incomplete

### ISSUE THREAD

**Issue by davidkline-ms** [microsoft/MixedRealityToolkit-Unity#7728]
The community has pointed out that, using the default profiles, motion controller mappings arent complete.

See http://dotnetbyexample.blogspot.com/2020/04/migrating-to-mrtk2-configuring.html for an example.

We should complete the action mappings collection so that it is easier to use all controls.

**Comment by keveleigh** [comment]
I think the main reason the rest of the buttons aren't mapped is that we don't really want to map them as "touchpad pressed" or whatever, but actual context-relevant names. That way, controllers that don't have a touchpad can still map the same action, but it's not confusing and using button-specific terminology, if that makes sense. Since we can't really predict the action names like that, we only implemented the subset required by MRTK and left the rest to the dev to implement and map according to their app's needs.

We might be able to provide a more filled out action mapping profile, but we should be intentional with the naming to show best practices instead of just naming them according to the button. If we wanted it to work like that, we wouldn't need action mappings at all and could just be returning button names! But then the benefits of the action mapping abstraction disappears.
