### ISSUE TITLE
WMR immersive not working as expected in standalone when using XRSDK

### ISSUE THREAD

**Issue by JBrentJ** [microsoft/MixedRealityToolkit-Unity#7905]
## Describe the bug
When building a standalone application in Unity 2019.3.13f1 with an XRSDK backend to test WMR immersive functionality and using the HandinteractionExamples.scene, There are three issues:
1. The controllers do not show up and there is no input available 

- (Note: when pressing home button the menu and controllers do show up correctly and disappear when returning to app)

- The controllers function in play mode but do not have mesh, just tracking axis.

2. The environment is not at the correct height but "on the ground".

3. There is no floor to the environment or Skybox.  It is a black void. 

## To reproduce

1. Start a new Unity project in 2019.3.x
2. Add MRTK 2.3 foundation and examples
3. follow instructions to add XRSDK support with MRTK described here: [MRTK + XRSDK](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html) 
4. Open HandInteractionsExample.scene
5. Build with target "Standalone"
6. Launch application and observe off center environment, no use of controllers, and black void

## Expected behavior
When running standalone application, user expects to experience the following:
1. HandInteractionExample objects are at correct height in front of user
2. Controllers are tracking and can interact with objects
3. User sees a beautiful sunny Unity skybox day, not the cold black void of nothingness.

## Screenshots

Could not get snipping to work with WMR Immersive

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.3.13f1]
- MRTK Version [e.g. v2.3]

## Target platform (please complete the following information)

- WMR immersive

**Comment by keveleigh** [comment]
>The controllers do not show up and there is no input available
>(Note: when pressing home button the menu and controllers do show up correctly and disappear when returning to app)

I believe this is a problem with the WMR XR SDK assembly being marked for UWP-only. I'll take a look at that and see if there are any side effects of going all-in on Windows Standalone with it.

>The controllers function in play mode but do not have mesh, just tracking axis.

This is currently expected. I need to finish implementing the APIs needed to load the model in-editor in DotNetWinRT before we can do this.

> The environment is not at the correct height but "on the ground".

This has been an ongoing discussion around porting the [SceneContentAdjuster](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit/Boundary/Scripts/SceneContentAdjuster.cs) to MRTK. We haven't done it yet, but it might be time.

>There is no floor to the environment or Skybox. It is a black void.

This should be fixed by #7904.

**Comment by keveleigh** [comment]
>The environment is not at the correct height but "on the ground".

is now tracked by https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7913
