### ISSUE TITLE
Hololens 2 remoting : ProtocolVersionMismatch

### ISSUE THREAD

**Issue by ninjanoka** [microsoft/MixedRealityToolkit-Unity#7910]
## Overview
Problem when connecting to the HoloLens over WIFI & also USB with the app
## Expected behavior
Connect to the HoloLens 2 without problems
## Actual behavior
Console error message:  Disconnected with error ProtocolVersionMismatch
## Steps to reproduce
_(Links to sample github project preferred)_
Windows > Holographic emulation > Select Remote to device > Select HoloLens 2 > Fill in ip > Press connect
## Unity editor version
2019.3.13f1
## Mixed Reality Toolkit release version
2.3.0

**Comment by keveleigh** [comment]
This isn't MRTK related, but I believe there's currently a bug around the error Unity reports when remoting is unable to connect. If I'm remembering correctly, `ProtocolVersionMismatch` maps to the error when the IP address you're trying to connect to is unreachable. I'd recommend double checking the IP address and ensuring your remoting player is running on the HoloLens and up to date from the store.

It also might be worth making sure your Windows package is up to date in the Unity Package Manager, as some remoting issues have been fixed in the last few releases.

**Comment by InitusJames** [comment]
I've been using Unity for years, never seen this issue before. I started using the MRTK a day ago with Unity and I get this error constantly. It's frustrating to deal with because a restart of Unity is required.

I find the MRTK very buggy and causes Unity to be extremely unresponsive.

Has there been any other reports of this?

Does the MRTK work best on any earlier versions of Unity, I am using 2019.2.21f1

**Comment by julesra** [comment]
I am having the same error and it looks different than the IP error given if I tell Unity to connect to Hololens1 vs Hololens2.
I have a Hololens2. Unity 2018.4.21f1
Here are the differences in errors:
1. In the Holographic tab, select "Remote to Device", select "Hololens2", enter correct IP address. Click "Connect". See error "Disconnected with error ProtocolVersionMismatch"
2. Select "Hololens1 (1st Gen)", enter correct IP address. Click "Connect". See error "Disconnected with error Unreachable".

**Comment by julesra** [comment]
I am having the same error.

The error is identical if a wrong IP address is provided; but it looks different than the IP error given if I tell Unity to connect to Hololens1 vs Hololens2.

I have a Hololens2. Unity 2018.4.21f1. Developer mode is enabled on HL2 and I can access the device portal through my browser.

Here's my exploration:
1. In the Holographic tab, select "Remote to Device", select "Hololens2", enter correct IP address. Click "Connect". See error "Disconnected with error ProtocolVersionMismatch"
2. Enter an incorrect IP address, click "Connect". The operation takes a bit longer but the same error is displayed: "Disconnected with error ProtocolVersionMismatch"
2. Select "Hololens1 (1st Gen)", click "Connect". See different error "Disconnected with error Unreachable". 

Could it be something to do with the Hololens2 security settings not allowing incoming connections ?

**Comment by ninjanoka** [comment]
It seemed to be the usb 3.0 connections. Sometimes a build worked, mostly it didn't. Using usb2 is fixing this issue but my laptop only has usb3.0 connectors so that's a loss

**Comment by julesra** [comment]
I don't know about the USB cable - my issue happens over Wifi without using any USB.
