### ISSUE TITLE
SceneContentAdjuster (or similar) should be ported from HTK

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#7913]
## Describe the problem

There is a need to adjust the scene content depending on if the application is running on HL or VR.

On HoloLens the camera starts at the scene origin, but for VR apps the camera is adjusted based off of the floor height ([world scale vs room/standing/seated scale](https://docs.microsoft.com/en-us/windows/mixed-reality/coordinate-systems#mixed-reality-experience-scales)). This can make it difficult to position content for a single app that's expected to run on both types of devices.

## Describe the solution you'd like

Either port [SceneContentAdjuster](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit/Boundary/Scripts/SceneContentAdjuster.cs) or investigate a new method of aligning the scene based on where the coordinate system root is.

**Comment by xwipeoutx** [comment]
I've thought a bit about this one - I think I have a fairly elegant solution, happy to PR it - just looking for a quick confirmation from someone (@keveleigh ?).

Can we have an enum `ManualCameraControlOrigin` with `Eye` and `Floor` (similar to Quests's origin tracking type), which will essentially set the camera position to `1.7m` higher if set to "floor" - which is the distance from the floor to the eye (on average).

Alternatively, instead of an enum, we can have a `ManualCameraOffset`, a float.

This adjustment would simply be applied on `Awake` and BOOM done.  Of course, default to offset of 0 for backwards compat.

**Comment by eusebiu** [comment]
I think it should be automatic (if possible) based on real (i.e. Hardware) input  vs. simulated (i.e. mouse/keyboard) input .

1. Simulated input - camera should be positioned at a user-defined value (e.g. the Y value from MixedRealityPlayspace/Main Camera).
2. Real/Hardware input - always override user defined value (as it is now).

**Comment by xwipeoutx** [comment]
Agreed - the setting would be in `MixedRealityInputSimulationProfile`

**Comment by JSWorkspace1** [comment]
duplicate issue #6786

**Comment by keveleigh** [comment]
Fixed by #9428 and [MixedRealitySceneContent](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/main/Assets/MRTK/Core/Utilities/SceneContent/MixedRealitySceneContent.cs)!
