### ISSUE TITLE
ClippingScene errors on Android when using SpectatorView

### ISSUE THREAD

**Issue by neur19** [microsoft/MixedRealityToolkit-Unity#8011]
## Describe the bug

When running Spectatorview on Android to spectate HoloLens scenes, Everything works perfectly except the models setup in the clipping scripts. This can be easily seen by running the Clipping example where the 'Heart' in the scene is by default not seen from the android. 

## To reproduce

Setup Spectatorview codebase and MRTKv2 on a Project.
Build and run Clipping scene example on HoloLens and Android.
Connect Android to HoloLens via Azure Spatial Anchors.

## Expected behavior

The clipping of 3D models happen perfectly aligned on Android as well as HoloLens

## Your setup (please complete the following information)

- Unity Version [2018.4.21f1]
- MRTK Version [ v2.0]

## Target platform (please complete the following information)

- HoloLens
- Android

**Comment by keveleigh** [comment]
@Cameron-Micka Might be a shader issue on Android?

@neur19 The issue report says you're using MRTK 2.0. We've made some improvements to the shader over the last few releases for increased compatibility on Android, if you're able to update.

**Comment by Cameron-Micka** [comment]
Thank you for the report! What graphics API is the Android phone using (ie Open GL ES 3.1)? Do you see any shader compilation errors/warnings in the Unity build log when you build for Android? Also, a screenshot of what you see on Android would be helpful (if possible).

Also, to echo @keveleigh's question, it would be good to know if you are on MRTK v2.0 or a later version?

Also, adding @chrisfromwork since spectator view was mentioned. I've not seen Android issues around primitive clipping. But, maybe Chris has?

**Comment by neur19** [comment]
@keveleigh @Cameron-Micka The exact version of MRTK is MRTKv2.2. And the graphics API is OpenGLES3.

**Comment by neur19** [comment]
@keveleigh @Cameron-Micka  I have tried the clippingscene on android alone without using spectatorview, It works fine. The problem is during Spectatorview integration.

**Comment by Cameron-Micka** [comment]
Thank you @neur19 for the additional info, it's very helpful! I might defer to @chrisfromwork since he is familiar with spectator view (and I don't have an Android device handy). But, please mention me if you are able to track down a specific shader issue, warning, erroc, etc.
