### ISSUE TITLE
calibration of rgb cameras and the Holo Coordinate System

### ISSUE THREAD

**Issue by zhangyk18** [microsoft/MixedRealityToolkit-Unity#8043]
Hello,

I have a task: the rgb cameras capture object, eg. Checkerboard, then Hololens can process the pictures and produce the space information, eg. R and T, of the object. So I can place a virtual object at the same location of the Holographic System.

My question is: is there any APIs in MRTK can achieve this? Or If I achieve the calibration through OpenCV to get the R and T, but the R and T are based on RGB cameras, how to associate RGB cameras and Holographic System (e.g. the 3D coordinate of RGB cameras in Holographic System)?

Thanks very much for any tips!

**Comment by wiwei** [comment]
Closing this out because this isn't an MRTK specific question (nor does this repo contain stuff around OpenCV + calibration for aligning real + world space).

There's another project under mixed reality that does do some of the things mentioned above which you can check out:

https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.VideoCamera.html
https://github.com/microsoft/MixedReality-SpectatorView

**Comment by zhangyk18** [comment]
> Closing this out because this isn't an MRTK specific question (nor does this repo contain stuff around OpenCV + calibration for aligning real + world space).
> 
> There's another project under mixed reality that does do some of the things mentioned above which you can check out:
> 
> https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.VideoCamera.html
> https://github.com/microsoft/MixedReality-SpectatorView

ok, I also just found the **spectatorView**, it's helpful to me.

Anyway ,thanks a lot!
