### ISSUE TITLE
ObjectManipulator Dependency on NearInteractionGrabbable is not obvious

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8083]
I debated whether to submit this as a bug or a docs issue (or even at all). Feel free to disregard if you feel this is documented well enough.
 
## Describe the bug

It was not intuitive to me that I needed to add **NearInteractionGrabbable** for **ObjectManipulator** to work in near mode. For example, even though there is a checkbox to "Allow Far Manipulation", **ObjectManipulator** simply does not work in near mode without **NearInteractionGrabbable**. There is also no warning if **NearInteractionGrabbable** is missing.

## Expected behavior

Though **ObjectManipulator**s dependency on **NearInteractionGrabbable** is [documented](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/README_ObjectManipulator.html), it's not readily apparent in the editor. It's also kind of difficult to tell if you're doing Far or Near interactions in the editor since the virtual hand collider has to be inside the object for Near. This means that you might not realize things aren't working until you deploy to the device. And when it doesn't work, it's not obvious why. You must read the docs to figure out what's missing.

If **NearInteractionGrabbable** is a true dependency, perhaps add a **RequireComponent** attribute to make sure it's there. If it's not a true dependency, I would at least like a small block of hint text in the inspector of **ObjectManipulator** telling you to add it if you want near interactions. 

At runtime, if "Allow Far Manipulation" is false but there's no **NearInteractionGrabbable**, consider adding a warning or error to the Unity log.

## Your setup (please complete the following information)

- Unity Version 2019.2.21f1
- MRTK Version 2.4

## Target platform (please complete the following information)

- HoloLens 2

**Comment by polar-kev** [comment]
@CDiaz-MS, what are your thoughts on this?

**Comment by CDiaz-MS** [comment]
@polar-kev I do not think we should add a require component since NearInteractionGrabbable is not a dependency.  Instead to communicate the need for the extra component for near interaction support, we can add a foldout with a button + message:

**Foldout closed:**
![image](https://user-images.githubusercontent.com/53493796/105073027-558ff480-5a3b-11eb-803a-2870941b1dea.png)

**Foldout opened:**
![image](https://user-images.githubusercontent.com/53493796/105073090-722c2c80-5a3b-11eb-9d78-817402a46ccf.png)

**Foldout appearance after near interaction grabbable is attached to the object:**
![image](https://user-images.githubusercontent.com/53493796/105073180-9425af00-5a3b-11eb-86cf-aadb53fc16cd.png)

**Comment by jbienzms** [comment]
Oh wow @CDiaz-MS, this is beautiful! Well beyond what I was expecting but greatly appreciated. I figured it would just be an error message in the log, but this is fantastic.

I think the only concern I have with the current implementation is that the error is only displayed in the log if `AllowFarManipulation` is set to false. I don't think this is necessarily right though. The component missing will be a problem any time a near manipulation is attempted, whether or not far manipulation is enabled. I will add comments to the commit as a code review and we can go from there. Thank you for working on this!
