### ISSUE TITLE
OnSourceLost is invoked when hand is activated on Unity 2019 play mode.

### ISSUE THREAD

**Issue by krishnan-unni** [microsoft/MixedRealityToolkit-Unity#8112]
## Describe the bug
When I turn on the hand simulation in Unity and test with it in play mode, the OnSourceLost gets fired immediately when the hand is activated (spacebar) and OnSourceDetected is never fired. 

## To reproduce
Create a new Unity project
Add and Configure MRTK toolkit
Configure Input data providers and enable input simulation for hands as well
Add a simple cube to the scene
Add a script to it and have this code:

```
public class CubeController : MonoBehaviour, IMixedRealitySourceStateHandler
{
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
    }

    public void OnSourceDetected(SourceStateEventData eventData)
    {
        var hand = eventData.Controller as IMixedRealityHand;
        if (hand != null)
        {
            Debug.Log("Hand detected");
        }
    }

    public void OnSourceLost(SourceStateEventData eventData)
    {
        if (eventData.Controller is IMixedRealityHand)
        {
            Debug.Log("Hand moved away");
        }
    }
}
```

- Press play in unity

- Press spacebar to activate right hand.
- In the console only "Hand moved away" is displayed. OnSourceDetected is never triggered

- When you add the following:

```
private void OnEnable()
    {
        // Instruct Input System that we would like to receive all input events of type IMixedRealitySourceStateHandler
        CoreServices.InputSystem?.RegisterHandler<IMixedRealitySourceStateHandler>(this);
    }
```
then OnSourceDetected is invoked once and OnSourceLost is invoked twice. Makes me believe global events are firing and dispatched properly.

## Expected behavior
When  hand is activated OnSourceDetected should be invoked.

## Screenshots

![image](https://user-images.githubusercontent.com/14880339/85957012-b1881400-b957-11ea-9351-295ad72ce891.png)

## Version
- Unity Version 2019.3.15f1
- MRTK Version 2.4

## Target platform 
- HoloLens 2

**Comment by wiwei** [comment]
So this is actually a really interesting/tricky issue which has a number of different factors at play. For the purposes of what you're trying to do, the best thing is to use the global handler (i.e. 

```c#
CoreServices.InputSystem?.RegisterHandler<IMixedRealitySourceStateHandler>(this);
```

And registering using some singleton on a single monobehaviour)

The way that source detected works is that when it fires, it's super, super early in the input stack - i.e. it's the first location in the code where things know that a hand or some other controller exists, and it only knows about the presence of this new thing. This early in the process, there hasn't been any work done to process the later concepts of "what is in focus" (i.e. at this point, the system is like "oh hey I have this new thing, let me tell other people there's this new thing). In fact, it basically takes until the next frame for the other concepts of "what is in focus" to actually get evaluated.

This is partially due to the fact that what's considered "in focus" is actually driven by a different component which has its own Update loop (i.e. FocusProvider.cs) - why this is, historical (it probably could have been more deterministic with the rest of the input system and how it is run, i.e. opting to run the focus reconiliation logic FIRST upon detection of a source and then raising the source detected information.

I would argue that the source events themselves are things that are separate from focus (i.e. they happen disconnected with any objects in the scene i.e. a handle will materialize SOMEWHERE in the scene when the hardware itself finds out about a hand and starts tracking it, and you never could really depend on it materializing on a specific object and then getting a paired lost event - i.e. your hand could have moved away from the object), so the fact that you even get a source lost event on the object is frankly kinda weird.

I'm going to add some comments to the docs and code to explain this, so that we can avoid this confusion going forward.

We could in theory change things to support having the source detected fire for the object it is detected on in the same frame, but that would be a fairly large/risky change for this issue (i.e. I don't believe that this event actually makes sense on a per-focused object scenario anyway)

**Comment by krishnan-unni** [comment]
I agree with you that source lost and detected event has less impact on per object based situations. Alhtough I am surprised at the Lost event firing consistently for the object. Also it would make more sense to make the documentation changes appropriately as this is shown as one of the primary ways to get hand pose information.
