### ISSUE TITLE
In Unity editor, EyeTrackingDemo-00-RootScene causes errors but still runs 

### ISSUE THREAD

**Issue by julesra** [microsoft/MixedRealityToolkit-Unity#8125]
## Describe the bug

First, let me say that the HandInteractionExamples scene works fine without any errors.

But when running the EyeTrackingDemo-00-RootScene I get first error "DefaultCursor (UnityEngine.GameObject) does not have IMixedRealityPointer component. Cannot create and utilize pointer" and second error "No Mixed Reality Configuration Profile found, cannot initialize the Mixed Reality Toolkit". In this scene there is a MixedRealityToolkit object with a valid profile, but the object contains no children (see screenshot below).

## To reproduce

1. Download the MRTK Foundations.2.4.0 and Examples.2.4.0 from here https://github.com/Microsoft/MixedRealityToolkit-Unity/releases
2. Create a new Unity project, import these 2 packages, switch to UWP.
3. Follow all the instructions for adding eyetracking examples to build settings, as described at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_ExamplesOverview.html 
4. Run the EyeTrackingDemo-00-RootScene.
5. Observe errors, but the example still runs as described in the page from step 3. 

## Expected behavior

Ideally no errors should be thrown, simimlar to the HandInteractionExamples scene.
However, if errors can't be avoided, then there should be some sort of message that says "IGNORE THESE ERRORS", either in the unity debug log or in the scene or in the instructions webpage at https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/EyeTracking/EyeTracking_ExamplesOverview.html 

## Screenshots

Included at the end

## Your setup (please complete the following information)

- Unity Version 2018.4.21f1
- MRTK Version 2.4.0

## Target platform (please complete the following information)

- Unity Editor, set up for UWP ARM deployment

## Additional context

Screenshot from the editor. 

![image](https://user-images.githubusercontent.com/10662283/86175829-ffd11a80-baf1-11ea-9204-458e42755359.png)

**Comment by jbienzms** [comment]
I can confirm this issue. In fact, I started with a brand new project and simply set my MRTK profile to **EyeTrackingDemoConfigurationProfile** to receive this message.

The error is thrown from **BaseInputDeviceManager.cs** line **308**. The `PointerOption` being passed in for sure does specify **DefaultCursor** rather than **EyeGazeCursor** (which is what is specified in the profile).

Note that neither **DefaultCursor** or **EyeGazeCuros** have any components that implement `IMixedRealityPointer`. They both have an `AnimatedCursor` component which has a property of type `IMixedRealityPointer`, but it does not implement `IMixedRealityPointer` itself.

It appears the code in **BaseInputDeviceManager.cs** may be the culprit. I suspect it should be instead getting `IMixedRealityCursor` and asking the cursor for the pointer instead. But I'm unclear why this is only happening with the **EyeTrackingDemoConfigurationProfile**. It does not happen with **DefaultHoloLens2ConfigurationProfile** even though it is using the same **DefaultCursor** prefab.

Tagging @wiwei, @keveleigh and @davidkline-ms who have recent commits to **BaseInputDeviceManager.cs** and may have some insight.

**Comment by Zee2** [comment]
This appears to have been fixed by #8244. If it was not, please reopen this issue.
