### ISSUE TITLE
Before jumping into this, could you please answer 1 question?

### ISSUE THREAD

**Issue by masterchop** [microsoft/MixedRealityToolkit-Unity#8220]
How hard would be to jump into a AR HMD not listed as supported?
The HMD already has Unity Support and has the following , 6DoF and Hand Tracking.
is it possible to use this SDK or should i should request an integration to it?

Thanks

**Comment by wiwei** [comment]
Over the past 6ish months we've added support for a couple of other platforms - you can see how this is done with LeapMotion:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7639

The most interesting part is under the MRTK/Providers/LeapMotion folder.

There's also the Oculus Quest (Controllers) integration here:

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8088

Note that if you haven't done this before, this is probably not going to be "easy" because you'd still be learning how to do the integration (even though referencing the two things above would help). However because we have a ton of other integrations, it can, to some degree, mostly be mechanical (i.e. implementing the right interfaces/objects.

**Comment by wiwei** [comment]
Feel free to open a new issue w/ a feature request for the platform, or if you want help trying to stand this up (i.e. you wanna try this yourself) let us know.

**Comment by masterchop** [comment]
Thank you ill check it out.
