### ISSUE TITLE
Unnecessary Raycasting for EyeTrackingTarget

### ISSUE THREAD

**Issue by jbienzms** [microsoft/MixedRealityToolkit-Unity#8242]
## Describe the bug

`EyeTrackingTarget` calls method `UpdateHitTarget` on every `Update`. `UpdateHitTarget` performs a raycast (lines 256 - 259). This means that if there are 10 objects in the scene with `EyeTrackingTarget` applied, there will be 10 raycasts performed _in every frame_. From what I can tell, each of the 10 raycasts will be for the exact same ray. There also doesn't appear to be any difference in the layer mask.

[IMixedRealityEyeGazeProvider](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.IMixedRealityEyeGazeProvider.html) inherits from [IMixedRealityGazeProvider](https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.IMixedRealityGazeProvider.html) which already provides `HitInfo`, `HitNormal` and `HitPosition`. Wouldn't it be more efficient to use those precalculated values rather than doing new raycasts for each instance on each frame? Or am I missing something important?

## Your setup (please complete the following information)

- MRTK Version: **mrtk_develop** branch as of 2020-80-01

**Comment by jbienzms** [comment]
Tagging @julenka and @davidkline-ms who have recent commits to this behavior.

**Comment by keveleigh** [comment]
Yeah, this does seem unnecessary now. My best guess is this was left over from the initial port, before eye tracking was integrated into the gaze provider. I can't think of a reason this result would be different than what gaze provider gives you.

If the target used `LatestEyeGaze` instead, I could see a reason, since the gaze provider _will_ provide head gaze when ET isn't available, but in this case it seems fine to remove this raycast.

**Comment by polar-kev** [comment]
@RogPodge can you let us know what the effort for this would be?

**Comment by RogPodge** [comment]
My initial investigations showed that it should be as straightforward as removing the raycast calls and having the various Eyetracking components query the EyeGazeProvider, since the eye gaze does get updated by MRTK systems in the two scenarios that are enabled for it (Input simulation and when using the WMREyeGazeProvider).

Will try implementing it and see open a PR if there's no deeper issues.
