### ISSUE TITLE
MRTK doesn't work in Unity 2020.2

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedRealityToolkit-Unity#8269]
## Describe the bug

Due to Unity's removal of the legacy XR APIs in Unity 2020.2, many MRTK scripts fail to compile. This issue will track the work being done to unblock MRTK use on Unity 2020.

This work started with #7795.

**Comment by keveleigh** [comment]
This should be good to go now, after I merged the last of my PRs yesterday. There will still be some follow-ups to support #7514/#7513, but at least now we're compiling.

**Comment by Rive4** [comment]
Hello,

I am having problems when I try to import MRTK 2.6.0 and Leap Motion's Core module (v4.7.1) on Unity 2020.2.
I am following the documentation steps as I made with previous versions in Unity 2019.4 and the errors are the following:

```
Assembly with name 'LeapMotion' already exists (Assets/Plugins/LeapMotion/LeapMotion.asmdef)
Assembly with name 'LeapMotion' already exists (Assets/Plugins/LeapMotion/Core/Scripts/LeapMotion.asmdef)
```

Regards,

**Comment by keveleigh** [comment]
@CDiaz-MS Has Leap started shipping their own asmdefs?

**Comment by CDiaz-MS** [comment]
Hi @Rive4, the current versions of the Leap Motion Core modules compatible with MRTK are 4.5.0 and 4.5.1 which are outlined at the top of the documentation page here: 
https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/features/cross-platform/leap-motion-mrtk

In your project, instead of importing the 4.7.1 unity modules, import the 4.5.1 modules: https://github.com/leapmotion/UnityModules/releases/tag/UM-4.5.1

The release notes for the 4.5.1 modules indicate that you also need to import the Oculus XR package while using Unity 2020.2 for Spatial Tracking support and you might also need to add UnityEngine.SpatialTracking as a reference in the LeapMotion.asmdef. 
![image](https://user-images.githubusercontent.com/53493796/110509195-b42a3400-80b6-11eb-9515-eb9127dff0a6.png)

@keveleigh yes leap does ship [their own asmdef](https://github.com/leapmotion/UnityModules/blob/develop/Assets/Plugins/LeapMotion/Core/Plugins/LeapCSharp/LeapMotion.LeapCSharp.asmdef) , in the configuration process we are creating our own asmdefs placing them in leap directories and modifying references.

Support for the 4.7.1 Leap Motion Unity Modules would be a new addition to MRTK.
