### ISSUE TITLE
MRTK Toolbox UI - Either no longer exists or is a planned feature?

### ISSUE THREAD

**Issue by laultman** [microsoft/MixedRealityToolkit-Unity#8366]
## Describe the issue
This does not seem to [exist](https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/README_Toolbox.html)

## Feature area
What's incorrect? What's missing? The Toobox UI.

## Existing doc link
If this is about something in an existing document, please provide link
https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/README_Toolbox.html

**Comment by wiwei** [comment]
It's right there:

![image](https://user-images.githubusercontent.com/5840182/91191717-fa372180-e6a9-11ea-97fb-763f4e9218d3.png)

Did you install the Tools package per the instructions on that doc page:
https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.4.0/Documentation/README_Toolbox.html#installing-the-toolbox

Note that the order within the dropdown might be different depending on the order in which you imported the packages for the specific instance of Unity when things are initially added - once you shutdown/restart Unity it should get to the order shown in that picture.

If you're actually just getting started with everything here, it would be best to install all of the packages to see the complete lay of the land, instead of trying to grab specific packages here or there.
