### ISSUE TITLE
UX controls don't work when rigid body is attached to parent object

### ISSUE THREAD

**Issue by AWSi-DR-TS** [microsoft/MixedRealityToolkit-Unity#8465]
## Bug description

I use UX controls (buttons in this case) to controll something in my menu hierarchy. A rigid body is attached to the top game object of the menu to trigger OnTriggerEnter events. 

It seems that buttons and other UX controls won't work if there's a rigid body attached to any of their parent objects.

Is there any solotion for this problem?

Kind regards.

## To reproduce

1. Add a game object to the scene and apply a rigid body to it.
2. Attach a button as a child of the game object with this rigid body.
3. Try to click the button in play mode with the hand simulation.
4. OnClick event won't be fired.

## Expected behavior

Button should be clickable although there's a rigid body attached to a parent object.

## My setup

- Unity Version: 2019.3.0f6]
- MRTK Version 2.4

## Target platform 

- HoloLens 2

**Comment by CDiaz-MS** [comment]
Hi @AWSi-DR-TS To resolve this issue, check the Focus Individual Compound Collider setting in the Input Profile:   
![image](https://user-images.githubusercontent.com/53493796/92634376-141b5b80-f289-11ea-9477-5ad00f2bbcd6.png)

The rigid body as a parent of a button interferes with the main hit result.  When Focus Individual Compound Collider is true, the main raycast hit object will be the child button game object.

This detail needs to be documented for other users, as this issue came up with our Bounding Box component: #4901
