### ISSUE TITLE
Slate PanZoom example is panning vertically with horizontal hand movement

### ISSUE THREAD

**Issue by vaoliva** [microsoft/MixedRealityToolkit-Unity#8563]
## Describe the bug

On HandInteractionExampleScene, the pan-zoom slate pans vertically even if interaction is only by horizontal hand click and drag. This is a regression from 2.4

## Screenshots

![SlatePan](https://user-images.githubusercontent.com/16922045/93230425-8e5b4c80-f76f-11ea-8e93-11cd1ded264a.gif)

## Your setup (please complete the following information)

- Unity Version [2019.3]
- MRTK Version 2.5 - .unitypackages

## Target platform (please complete the following information)

- Editor or XR Emulator

**Comment by cre8ivepark** [comment]
@vaoliva Somehow, it works in 2018. The symptom shows up in 2019. (SlateExamples scene has both vertical and horizontal examples)

**Comment by wiwei** [comment]
This is the same as https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8206

When I was fixing this, I was trying to get our Unity 2019 CI setup (which was running 2019.4.something) - I hadn't tested the fix on 2019.3, and since the LTS release was out (where we usually just go for LTS support exclusively once its out), I didn't try to also apply it to 2019.3
