### ISSUE TITLE
Hand Interaction Examples displays generic message above the piano keys

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#8567]
## Describe the bug

When you load into the Hand Interaction Examples scene, the piano initializes with a generic message. The message says 'Debug Message'. Once you press a piano key, that message goes away and the expected messaging is displayed.

## To reproduce

1. Import all MRTK UPM packages
2. Import TMP Essentials
3. Open Hand Interaction Examples scene and build for HoloLens 2
4. Deploy to HoloLens 2
4. Look at the piano keys

## Expected behavior

The messaging in the scene should be meaningful and not generic.

## Screenshots

![Debug message](https://user-images.githubusercontent.com/65038391/93248440-abc6f100-f744-11ea-92a4-2efcfef64d8c.jpg)

## Your setup (please complete the following information)

- Unity Version 2019.4.10f1
- MRTK Version 2.5.0-preview.20200910.3

## Target platform (please complete the following information)

- Unity in-editor player
- HoloLens 2
- UWP
- Visual Studio 2019
   - Master
   - ARM64
   - Remote machine

**Comment by wiwei** [comment]
I believe this thing has actually been in since 2.0 or earlier (or something way back - even our documentation image which was generated long ago has it):

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html#run-the-handinteractionexamples-scene-in-the-unity-editor
