### ISSUE TITLE
How to locate a launched browser to the specified location?   How to launch several web browsers simultanousely? 

### ISSUE THREAD

**Issue by csxbwang** [microsoft/MixedRealityToolkit-Unity#8603]

**Comment by BinaryNate** [comment]
Hi, @csxbwang  👋 . I'm Nate, the creator of the Vuplex 3D WebView asset. I'm trying to get a hold of you because you left the following review on my 3D WebView for Hololens asset:

![image](https://user-images.githubusercontent.com/4952192/95004590-18524480-05bb-11eb-81ed-5f8901615898.png)

Can you please contact me at nate@vuplex.com so that I can help you? As an independent developer, negative reviews can have a very adverse affect on my business. So, your cooperation is greatly appreciated. I just released v3.9 of 3D WebView which may fix your issue, and if it doesn't, I can track it down.

**Comment by wiwei** [comment]
There's not a lot of information in this issue, please reopen with more details

**Comment by keveleigh** [comment]
This sounds related to the "Launch browser" buttons in our hand interaction examples scene.
I don't believe specific placement of the resulting app slate is a feature currently supported by the OS.
