### ISSUE TITLE
ScrollingObjectCollection doesn't mask Umlaute correctly

### ISSUE THREAD

**Issue by TheRisenPhoenix** [microsoft/MixedRealityToolkit-Unity#8624]
## Describe the bug

When using the ScrollingObjectCollection with an item that contains an Umlaut (ä, ö, ü) in the text, it isn't completely masked out. If you're showing 5 items, and the 6th contains an Umlaut, the button itself will be invisible, but the Umlaut (and only this one character) is not. If the item is on 7th position, it's (correctly) completely invisible (but the bug will then occur if you scroll up so it's at the 6th position).

## To reproduce

1. Create a ScrollingObjectCollection
2. Add some items, the last one with an Umlaut
3. Deploy and test it
4. When scrolling up, only the Umlaut will be visible when the button itself is invisible, but one position before getting inside the viewable area

## Expected behavior

All characters should be invisible.

## Screenshots

![image](https://user-images.githubusercontent.com/43245438/93858777-fd2f2d00-fcbc-11ea-9c40-f740f522fca8.png)
(Inside the visible area, everything is fine)

![image](https://user-images.githubusercontent.com/43245438/93858816-0ae4b280-fcbd-11ea-9d02-c6e3194261cc.png)
(One position beneath it, it isn't)

## Your setup

- Unity Version 2019.4.10f1
- MRTK Version 2.4.0

## Target platform

- HoloLens 2
- Same behaviour in the editor play mode

**Comment by vaoliva** [comment]
Hi @TheRisenPhoenix. The issue seems to be related to some TMPro font material not really rendering the umlaut properly.
I was able to have working umlauts by using the LiberationSans font material. For using with scroll just remeber to change shader to use Mixed reality Toolkit / TextmeshPro. I'm using MRTK 2.4, Unity 2019.3 and TMPro 1.4.1.
![umlaut](https://user-images.githubusercontent.com/16922045/93882411-1beeed00-fcd8-11ea-8e65-67e415f34c98.gif)

**Comment by TheRisenPhoenix** [comment]
Okay, it indeed seems to work with the other font.
Thanks for your help! =)
