### ISSUE TITLE
Render mrtk hand shader as opposed to Oculus avatar or Controllers.

### ISSUE THREAD

**Issue by A1igator** [microsoft/MixedRealityToolkit-Unity#8745]
## Describe the problem

I realize it's not your fault, but Oculus avatar has been crippled for a while as far as I know, because it doesn't support URP out of the box. This means neither does the controller hand for mrtk because you use Oculus avatar hand. Hand tracking hand mesh is fine which makes me believe you use your own mesh there.

## Describe the solution you'd like

I believe mrtk-quest rendered the same mesh and shaders for both hand tracking and controller, so an option for that would be nice as it appears relying on Oculus avatar isn't a good idea.

## Describe alternatives you've considered

There seems to be a paid asset to fix the issue so maybe you can implement a similar code by yourself if you still wanna use Oculus avatars: https://assetstore.unity.com/packages/vfx/shaders/urp-avatar-shaders-for-oculus-quest-176279

## Additional context

N/A

**Comment by keveleigh** [comment]
I believe the plan is to move to MRTK-based visualization once https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8730 is resolved. @RogPodge

**Comment by keveleigh** [comment]
@RogPodge Is this still an issue, or are MRTK rigged hands an option for Oculus now?

**Comment by RogPodge** [comment]
This has not been addressed since this issue primarily concerns the "hand avatar" visualization when using the oculus controllers (not hand tracking). I'm unsure if the Oculus Integration Package has an update that fixes this issue, though my initial gut instinct is to advise users to manually change Oculus's Hand Avatar prefab rather than us manually strip it out and replace it with out own.

Will keep this top of mind as we look into improving our controller visualization options

**Comment by RogPodge** [comment]
Closing as Oculus itself has deprecated its old hand avatar system: https://developer.oculus.com/downloads/package/unity-integration/39.0#deprecation

We advise users to use OpenXR for Quest compatibility for Unity 2020 and beyond
