### ISSUE TITLE
UnityEngine.XR.XRDevice.GetNativePtr() return null

### ISSUE THREAD

**Issue by ShanguUncle** [microsoft/MixedRealityToolkit-Unity#8771]
## Overview
When use new XR follow 
https://microsoft.github.io/MixedRealityToolkit-Unity/version/releases/2.5.0/Documentation/usingupm.html
the API
UnityEngine.XR.WSA.WorldManager.GetNativeISpatialCoordinateSystemPtr() return null
UnityEngine.XR.XRDevice.GetNativePtr() return null
can not work！
## Steps to reproduce
_(Links to sample github project preferred)_

## Unity editor version
2019.4.11f1
## Mixed Reality Toolkit release version
2.5.0

**Comment by keveleigh** [comment]
If you're using Unity's new XR plug-in system (using [XR Management](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-unity) instead of the legacy VR player settings), this is expected. That API isn't used by the new XR system.

Depending on what you're trying to get out of it, various platform packages have specific native ptrs now, like `OriginSpatialCoordinateSystem` under [WindowsMREnvironment](https://docs.unity.cn/Packages/com.unity.xr.windowsmr@2.3/api/UnityEngine.XR.WindowsMR.WindowsMREnvironment.html).

**Comment by ShanguUncle** [comment]
Thanks, it worked.

**Comment by huangzejie0810** [comment]
> Thanks, it worked.

UnityEngine.XR.XRDevice.GetNativePtr() return IntPtr.Zero。 I also encountered the same problem, I use unity version is 2021.3.5, May I ask how to finally how to solve, thank you！

**Comment by huangzejie0810** [comment]
> If you're using Unity's new XR plug-in system (using [XR Management](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#required-in-unity) instead of the legacy VR player settings), this is expected. That API isn't used by the new XR system.
> 
> Depending on what you're trying to get out of it, various platform packages have specific native ptrs now, like `OriginSpatialCoordinateSystem` under [WindowsMREnvironment](https://docs.unity.cn/Packages/com.unity.xr.windowsmr@2.3/api/UnityEngine.XR.WindowsMR.WindowsMREnvironment.html).

UnityEngine.XR.XRDevice.GetNativePtr() return IntPtr.Zero。 I also encountered the same problem, I use unity version is 2021.3.5, May I ask how to finally how to solve, thank you！
