### ISSUE TITLE
Question: difference between MRTK and "Win Mixed Reality" plug-in in "XR Plug-in Management"

### ISSUE THREAD

**Issue by dnqbob** [microsoft/MixedRealityToolkit-Unity#8899]
Hi, and I am new to MRTK, I have a question on MRTK:

There is a "Windows Mixed Reality plug-in" in "XR Plug-in Management":
![1](https://user-images.githubusercontent.com/13763394/98060442-8624b100-1e84-11eb-9e15-8f385be8f65a.PNG)

what is the different between those two? Does "Windows Mixed Reality plug-in" in "XR Plug-in Management" represent a driver that allow project use Windows Mixed Reality, while MRTK is a SDK?

**Comment by dnqbob** [comment]
Second question:

I have equipment support OpenVR/SteamVR, which they say should use OpenVR SDK but it confused me because I find MRTK also support OpenVR, which is strange for me because in this case maybe I can just use MRTK in developing (windows only).

**Comment by eusebiu** [comment]
The Windows Mixed Reality in the XR Plug-in Management is the platform (and runtime based on Windows 10) that the app will run on. The same stands for Oculus (which is Android based) and the rest. All these platforms have some native plugins (you can see them in the packages) with a specific API that Unity expects - you can see them either in Unity [docs](https://docs.unity3d.com/Packages/com.unity.xr.management@3.2/manual/index.html) or just simply load them in a dependency viewer app.

MRTK is a toolkit that "provides a set of components and features, used to accelerate cross-platform MR app development in Unity" - it is not a platform or a runtime.

In order to support a new platform (like OpenVR/SteamVR) you need first to have a Unity XR SDK Plugin for that platform. There is one for [OpenVR](https://github.com/ValveSoftware/unity-xr-plugin) and one for [SteamVR](https://github.com/ValveSoftware/steamvr_unity_plugin) but, unfortunately, none of them work properly with MRTK (see https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8835).

OpenVR is here: https://github.com/ValveSoftware/openvr.

MRTK is like a cool wrapper over all these platforms/runtimes like Oculus, OpenVR, Hololens (1&2), etc which allows us to design & write code once (well, ideally) and then (with minor changes) deploy on all these hardware. E.g. I am using MRTK to target Oculus (Link and Standalone), Hololens2 and I am looking to add SteamVR.

**Comment by eusebiu** [comment]
Please take a look at this picture:
![image](https://user-images.githubusercontent.com/414589/98485589-347f7c00-2220-11eb-858d-5902bd84a286.png)

MRTK is at the level of Developer tools.

**Comment by dnqbob** [comment]
> In order to support a new platform (like OpenVR/SteamVR) you need first to have a Unity XR SDK Plugin for that platform. There is one for OpenVR and one for SteamVR but, unfortunately, none of them work properly with MRTK (see #8835).

Also get the same bug here. Weird.

**Comment by dnqbob** [comment]
So as for Oculus, does it also has its own develop tools or its develop tools integrated with the SDK?

**Comment by eusebiu** [comment]
Unity redesigned the XR layer into the new so called XR SDK (that has now the XR Plugin Management you pointed earlier).
SteamVR Unity Plugin uses OpenVR plugin behind the scenes. You can see that installing SteamVR  Unity Plugin which will also install OpenVR XR SDK. SteamVR Unity Plugin is at Developer tools level, OpenVR XR SDK/Plugin is at implementation layer ("SteamVR" alone is the runtime + the SteamVR app you can install&start from Steam).

OpenVR APIs can be implemented by various runtimes - the main one is SteamVR.

**Comment by eusebiu** [comment]
A first implementation of this can be seen here:
https://github.com/eusebiu/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MRTK/Providers/SteamVR/XRSDK
@dnqbob

**Comment by dnqbob** [comment]
> A first implementation of this can be seen here:
> https://github.com/eusebiu/MixedRealityToolkit-Unity/tree/mrtk_development/Assets/MRTK/Providers/SteamVR/XRSDK
> @dnqbob

So now can the MRTK also support SteamVR runtime?

**Comment by eusebiu** [comment]
It works if you download that folder and add it to your project and follow the steps here - https://holodevelopers.slack.com/archives/C2H4HT858/p1605096911294600?thread_ts=1605096911.294600&cid=C2H4HT858

**Comment by dnqbob** [comment]
will try it late.

**Comment by polar-kev** [comment]
Closing this issue since the questions have been answered.
