### ISSUE TITLE
Update Holographic Remoting documentation to be explicit about XR plugin settings

### ISSUE THREAD

**Issue by RogPodge** [microsoft/MixedRealityToolkit-Unity#8990]
## Describe the issue
Holographic Remoting on Unity 2019.4 doesn't work unless you install the dotnetwinRT library from Nuget and set the correct OpenXR settings in under the Standalone set of settings. Tracking updating the documentation to reflect those necessary steps.

![image](https://user-images.githubusercontent.com/39840334/100678988-5ea9f280-3323-11eb-9e2c-147e2c911335.png)

**Comment by MaxWang-MS** [comment]
Hmm... My understanding is the dotnetwinrt library is only required when using legacy XR pipeline and is not required for XRSDK pipeline. @keveleigh Could you help verify that? If that is the case, then I think [our doc](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html) is good (currently mentions that library is required for legacy XR and requires checking the correct boxes in the XR plug-in management tab as showed above).

**Comment by MaxWang-MS** [comment]
But I do support changing the narrative to recommend NuGet over MSBuild.

**Comment by keveleigh** [comment]
>My understanding is the dotnetwinrt library is only required when using legacy XR pipeline and is not required for XRSDK pipeline.

This is true. There are other features that depend on DotNetWinRT though, like changing the depth lsr format, but none that are needed specifically for remoting that I can think of.

**Comment by RogPodge** [comment]
@keveleigh Katherine and I were unable to get holographic remoting working without DotNetWinRT yesterday though :(

**Comment by keveleigh** [comment]
@RogPodge Using XR SDK? What wasn't working?

**Comment by RogPodge** [comment]
@CDiaz-MS since I didn't get a chance to specifically test the config without DotNetWinRT

**Comment by CDiaz-MS** [comment]
Remoting was not working for me on 2019.4.12 yesterday using only XRSDK.  Although I just tested again today and now it is working. I went over the [XRSDK set up steps](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithMRTKAndXRSDK.html#windows-mixed-reality) and it looks like updating the **XR Legacy Input Helpers** and **XR Plugin Management** UPM packages resolved the issue.

When searching UPM to add the packages initially, the button to add the package was titled "Update to Version" instead of "Install" so the assumption was that the package was already in the project.

![image](https://user-images.githubusercontent.com/53493796/100797635-4e534f80-33d7-11eb-80c4-bfd0ebdd4ddb.png)
