### ISSUE TITLE
Holotoolkit Remote Mapping cannot send meshes

### ISSUE THREAD

**Issue by LexieMeng** [Microsoft/MixedRealityToolkit-Unity#913]
I tried to build RemoteMapping and I can see the wireframe mesh appear in my HoloLens but can not get any meshes sent from Hololens to Unity. I wonder if there is something wrong with my server IP. Does anyone know what address should I put in Server IP? I just use the IPv4 address of wireless LAN adapter Wi-Fi. If I use the correct address, is there any other issue may cause this situation?

What I have done:
1. Build the scene as shown in test scenes.
2. Enable the SpatialPerception,InternetClientServer, PrivateNetworkClientServer, and Microphone capabilities.
3. Check the state of connection port is Listening.

Anything missing?

**Comment by angelaHillier** [comment]
It's been a while since I've tried this (I now use the Windows Device Portal for capturing meshes instead), but have you opened port 11000 in your firewall?

Here's the relevant excerpt from the SpatialMapping Readme:
The RemoteMapping scene uses the SpatialMapping and RemoteMapping prefabs to send spatial mapping data between the HoloLens and the app running in the Unity editor. To run this test, you must first open port 11000 on your firewall and then set the IPv4 address of your PC in the 'RemoteMeshTarget' and 'RemoteMeshSource' components. You can then build and deploy to the HoloLens. Once you see the wireframe mesh appear in your HoloLens, press the 'play' button in Unity to run the app in Editor. Ensure that the 'Game view' has focus, and then press the 'N' key (RemoteMappingKey) to switch to using the network as the spatial mapping source in the Editor. Once you are confident that you have a good mesh, say the 'Send Meshes' (SendMeshesKeyword) to send the meshes from the HoloLens to the Unity Editor. Press the 'S' key (SaveFileKey) to save the mesh to your PC. Press the 'play' button to stop the app from running in the Unity editor. Now, press 'play' one more time to restart the app. This time, press the 'L' key (LoadFileKey) to load the mesh that you previously saved into the Editor.

**Comment by LexieMeng** [comment]
@angelaHillier 
I checked the state of the port 11000 is listening. Is that correct? If not, what state of the port is expected?

**Comment by LexieMeng** [comment]
I opened the port on my firewall and it works. Thank you very much. @angelaHillier

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
