### ISSUE TITLE
Slider sound does not check tick mark passing

### ISSUE THREAD

**Issue by FlorianJa** [microsoft/MixedRealityToolkit-Unity#9172]
## Describe the bug

The sound for the pinch slider is actually not triggered by passing a tick. The sound is played on a "random" position on the slider.

## To reproduce

1. Open the SliderExample scene.
2. Play it
3. Move the Slider between to ticks. DO NOT touch the tick mark
4. Listen to the tick sound

The "bug" is caused by the SliderSound script. It does not check if the handle passed a tick, it just accumulates the distance the slider was moved. If the slider is small and the tick marks are close to each other, it is hard to reproduce and may not happen in real use cases. 

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/5dc2cebcaed9a90d8019cda3d4933df03beb0bcd/Assets/MRTK/SDK/Features/UX/Scripts/Sliders/SliderSounds.cs#L79-L98

## Expected behavior

The tick sound should only play if the handle really passes the tick mark.

## Your setup

- Unity Version 2018.4.31f1
- MRTK Version latest dev commit

**Comment by RogPodge** [comment]
Adjusting the prefab to line up the tick marks with the default tick every interval, also made the tick sound play at each "step" when using the step divisions aspect of the slider.

It's not entirely feasible to adjust the number of tick visuals to the tickEvery parameter, since other gameobjects which use this component may not want to use tick mark visuals.
