### ISSUE TITLE
ManipulationHandler/ObjectManipulator kind of gimbal lock

### ISSUE THREAD

**Issue by raggnic** [microsoft/MixedRealityToolkit-Unity#9209]
## Describe the bug

In our project we are using ManipulationHandler to pan a map using near/far interactor. In some case I've noticed weird behaviour, esp. when looking a bit down. 

https://user-images.githubusercontent.com/28299760/106609744-34b0be80-6566-11eb-8961-af1d1ee66bac.mp4

I hope it's visible in the video
In the camera inspector the UIRaycast camera is renderered and I've noticed it happens when the pointer cross around the nadir of the view point

I've tried to switch to ObjectManipulator in hope to fix this but there is the same kind of behaviour.

## To reproduce

1. Open ObjectManipulator scene
2. Scale up the floor and disable gravity on the sphere
3. move the camera up and look down, and try to move the sphere horizontally.
4. Around nadir it is moving erratically. In our case we tried to clamp y but there's still an issue on other coordinates

https://user-images.githubusercontent.com/28299760/106610463-1bf4d880-6567-11eb-87b8-7e1e3c88dfc2.mp4

## Expected behavior

We'd like the manipulator to move the target in a linear way, or maybe an alternative way to move objects

## Your setup (please complete the following information)

- Unity Version 2019.4.14
- MRTK Version 2.5.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by CDiaz-MS** [comment]
Here is the behavior for far and near interactions with a MoveAxisContraint on the Y axis:
| Far Interaction | Near Interaction |
|---|---|
|![FarInteractionObjectManip](https://user-images.githubusercontent.com/53493796/108246101-e7a41f00-7105-11eb-9009-a90434d69fb2.gif)|![NearInteractionObjectManip](https://user-images.githubusercontent.com/53493796/108246412-41a4e480-7106-11eb-8b94-44fa4afe0221.gif)|

The behavior does feel a bit off when the manipulation point approaches the camera raycast point.

Another option instead of directly manipulating the plane for the panning movement  is a more indirect approach.  You can place an Object Manipulator on a designated plane movement object (a cube).  Then change the `Host Transform` on the Object Manipulator to the Plane instead of itself.

Steps:

1. Create a Plane
2. Create a Cube
3. Add an Object Manipulator to the Cube
4. Change the Host Transform on the Cube's Object Manipulator to the Plane
 
![image](https://user-images.githubusercontent.com/53493796/108247135-1ff82d00-7107-11eb-813a-9b2cbb30ef4e.png)

5. Add a Move Axis Constraint on the Y axis 
![image](https://user-images.githubusercontent.com/53493796/108247298-4f0e9e80-7107-11eb-875c-1db49c49554a.png)

Result:
| Far Interaction | Near Interaction |
|---|---|
|![FarInteractionObjectManipIndirect](https://user-images.githubusercontent.com/53493796/108248094-4e2a3c80-7108-11eb-9ccf-bcd8e82db707.gif)| ![NearInteractionObjectManipIndirect](https://user-images.githubusercontent.com/53493796/108248177-600bdf80-7108-11eb-91e3-da1cfec45657.gif)|

To move the plane, you act on the cube which then moves the plane.  For now, this approach seems to result in more consistent movement for the target objects.  More investigation for the direct manipulation behavior in the first set of gifs would be needed.

**Comment by raggnic** [comment]
Thank you for your answer I will test this approach in our application
