### ISSUE TITLE
Incompatible instructions about XR packages

### ISSUE THREAD

**Issue by julesra** [microsoft/MixedRealityToolkit-Unity#9234]
## Describe the issue

These instructions: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#xr-sdk-setup-instructions

are not compatible with these instructions: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02

I followed the 2nd link first, and then proceeded to do the 1st link because I wanted Holographic remoting. But the first link requires installation of some newer XR packages which seem to conflict with the legacy packages from the 2nd link, and Unity keeps popping up complaints about incompatibility. Now I don't know if my fresh MRTK project is configured correctly.

## Feature area

The instructions for Holographic remoting need to be updated or removed if they are not compatible with the new MRTK.

## Existing doc link

There are two doc links, please see the description above.

Thanks for fixing.

## MRTK Versions
Unity: 2019.4.19f1
MRTK: 2.5.1

**Comment by MaxWang-MS** [comment]
In Unity 2019 there are two XR pipelines: Legacy XR and XRSDK (see the very top of the page of the first link). The second link uses the Legacy XR pipeline and thus when you go back to the first link you should go to the [Legacy XR setup instructions section](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html#legacy-xr-setup-instructions) instead of the XR SDK setup instructions section that you are pointing to in the link. To be safe I would suggest you start fresh again and follow the instructions for Legacy XR at all times.

**Comment by julesra** [comment]
Yes thanks. My comment was that the instructions for a new project ( https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02 ) and others like it should be very clear about which pipeline is being created or assumed for the instructions. I followed the instructions without knowing anything about pipelines, and then didn't really understand what to do for Holographic remoting.
Perhaps there can be a label on the documentation, just like the existing label showing which version of MRTK the documentation applies to. But this label would be about pipeline. Or at the very least, the instructions should say "In these steps you are about to create an MRTK project with the legacy pipeline"

**Comment by polar-kev** [comment]
Hi @julesra, moving forward, all MRTK docs are being maintained on docs.microsoft.com. We've updated our documentation there to include pipeline specific instructions in different tabs.
