### ISSUE TITLE
Shader : Artifact with transparent image and rendering mode set to Fade

### ISSUE THREAD

**Issue by samoteph** [microsoft/MixedRealityToolkit-Unity#9247]
## Overview

Artefacts appear when texture with alpha is applied and Rendering Mode is set to Fade. 

![ImageArtefact](https://user-images.githubusercontent.com/19349553/107233024-691ef180-6a22-11eb-8e6b-30ad3cffd8cc.png)

## Expected behavior

No artefacts appear

## Steps to reproduce

1. Add a Quad on the scene
2. Add a MRTK Standard Shader on the Quad
3. Add a png image with transparency on the Albedo. The image must have opaque pixels at the bottom and transparents pixels at the top. 
4. Set the Rendering mode to Fade

## Unity editor version
2019.4.16f1

## Mixed Reality Toolkit release version
2.5.1

**Comment by keveleigh** [comment]
@Cameron-Micka Have you seen this?

**Comment by Cameron-Micka** [comment]
Thank you @samoteph for flagging this. There could be a few reasons why this is happening. The first thing that comes to mind is the texture's "wrap mode" might need to be adjusted. What happens if you select the texture and set it's wrap mode to clamp?

![image](https://user-images.githubusercontent.com/13305729/107311286-ed816c80-6a42-11eb-878e-a0bef564b862.png)

Because texture's are accessed using floating point numbers UVs can often bleed slightly below 0 or above 1 even when you specify those exact values in your modeling program (Unity's importer may also massage the numbers).

If that doesn't fix it, would it be possible for you to upload the texture to this issue? Else, I would be curious if the issue occurs with Unity's standard shader when set to fade?

**Comment by samoteph** [comment]
Hello @Cameron-Micka, thanks a lot to take the time to resolve this problem. 
The Wrap Mode set to Clamp fix the problem but as I use the texture to create an infinite scroll with the help of the Tiling property it's not an option for me. 
The problem occurs also in the standard shader when set to fade. 
Am I doomed to set the Y offset to -0.001?

![rocks2](https://user-images.githubusercontent.com/19349553/107340079-a1274280-6abd-11eb-89fe-f29dc932a1e4.png)

**Comment by Cameron-Micka** [comment]
Glad you found a fix! That does make sense that rounded corners would be problematic with UV tiling. The rounded corner feature assumes UVs are between 0 and 1. This is something I should document a bit better.

If you need rounded corners with UV tiling I bet it wouldn't be too hard to add. For instance here is a 4x4 tile with rounded corners currently:

![image](https://user-images.githubusercontent.com/13305729/107395480-b5654280-6ab1-11eb-8f95-26153ad8561a.png)

Then after these shader changes:
![image](https://user-images.githubusercontent.com/13305729/107395208-7505c480-6ab1-11eb-9e33-34d736807289.png)

![image](https://user-images.githubusercontent.com/13305729/107395041-543d6f00-6ab1-11eb-8294-e9647cb4274c.png)

Does this satisfy your use case? Or do you need rounded corners across the entire quad? If that's the case then it would require larger changes such as a second UV set.

**Comment by samoteph** [comment]
In fact I'm most interested by rounded corners across the entire quad.I'm pretty sure that it's the most common case for an application designer. At this point I use a rounded corner quad but this is a linked to my specific project.

**Comment by Cameron-Micka** [comment]
Thank you for the feedback, that makes sense. That would be a new feature request, but something I'll keep in mind for future iterations.
