### ISSUE TITLE
Hand Interaction Gesture Events example does not switch from GGV pointer

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9369]
## Describe the bug

When using the in-editor player to run the Hand Interaction Gesture Events example scene and attempts to use the Input Simulation to simulate hand tracking, the scene will not switch from the GGV pointer to the Hand Tracking pointers. A video and a screenshot are attached to better articulate the issue.

## To reproduce

1. Create a new Unity project and import the Foundation, Extensions, and Examples packages
2. Choose your XR pipeline
3. Open the HandInteractionGestureEventsExample scene (do not switch profiles)
4. Attempt to use the simulated hands to interact with the scene

## Expected behavior

When the simulated hands are enabled, the example scene should switch from the GGV pointer to the Hand Tracking pointers.

## Screenshots

![image](https://user-images.githubusercontent.com/65038391/108924832-4ed33f00-75f0-11eb-818c-c23777599f04.png)

https://user-images.githubusercontent.com/65038391/108925394-62cb7080-75f1-11eb-9f69-8e2cd5a58482.mp4

## Your setup (please complete the following information)

- Unity Version 2019.4.20f1, 2018.4.31f1
- Legacy XR
- XR SDK

## Target platform (please complete the following information)

- UWP
- in-editor player

**Comment by CDiaz-MS** [comment]
The absence of the articulated hand tracking pointers (default controller ray, poke pointer, etc.) appears to be intentional in this scene.  This scene has a modified Input Simulation Profile (GestureEventsInputSimulationProfile) that has switched the Default Controller Simulation Mode property to `Hand Gestures` instead of the default `Articulated Hand` value. 

| Default Input Simulation Profile |  Input Simulation Profile for the HandInteractionGestureEventsExample scene |
|---|---|
| ![image](https://user-images.githubusercontent.com/53493796/109074902-3ecd6500-76ad-11eb-950f-9208a33ad6f9.png) | ![image](https://user-images.githubusercontent.com/53493796/109074850-24938700-76ad-11eb-8ccf-5c0a5eccaced.png)|

This scene appears to be intentionally simulating HoloLens 1 style input.

**Comment by elbuhofantasma** [comment]
Thank you for the information @CDiaz-MS, glad to know that this was intentional. When running this scene on HoloLens 2 with the same configuration profile, it was a different experience for the pointers.

**Comment by RogPodge** [comment]
Closing this since the intended usage seems to be Hololens 1 if that's ok with everyone
