### ISSUE TITLE
Creating World Anchor application

### ISSUE THREAD

**Issue by santosluiz** [Microsoft/MixedRealityToolkit-Unity#937]
Hi guys,

First, congrats for amazing project, the Mixed Reality Toolkit for Unity o/

I'm building a project with World Anchor but I can't find a tutorial with makes what I want.

I want build an application exactly like this: https://www.youtube.com/watch?v=a0-9KosgAXY&t=1s

I'm using the latest version of Unity and Visual Studio.

Someone can help me?
How I can build it?

**Comment by jasonhbartlett** [comment]
Hi, it's been awhile but this was one of the first things I tried when developing a Hololens app.  That was about 6 months ago, so the new MRTK may have update the way they handle it.  The way I was able to accomplish was something like this.  (Assuming you already have the basic Hololens stuff, like the Hololens camera, and cursor prefabs in your scene.)

1. Add an empty game object and attache the WorldAnchorManager.cs script to that.
2. Add your 3D object (cube) that you want to move.  Make sure it has some kind of collider attached (like a box collider) so that it is intractable.
3. Add a new script to this object called "AnchorObject.cs"  This script will need a string field to hold a unique ID which you can set at any time.  This unique string is what the WorldAnchorManager will use to find and retrieve your object between app cycles, so you don't want to change it during runtime.  That AnchorObject.cs will look something like this:

`using System;
using UnityEngine;
using HoloToolkit.Unity.InputModule;
    /// <summary>
    /// Simple Script that allows a World Anchor to be:
    ///     1. Atached at Start()
    ///     2. Detached at OnManipulationStarted()
    ///     3. Attached again at OnManipulationCompleted()
    /// Means that the object will save it's position between app cycles
    /// </summary>
    public class AnchorObject : MonoBehaviour,
                                IManipulationHandler,
                                IFocusable
    {
        public string AnchorName = 123456789;
        public bool Undo = false;

        private Vector3 SavedPosition;
        private Quaternion SavedRotation;
        private Vector3 OldPosition;
        private Quaternion OldRotation;

        void Start()
        {
            OldPosition = SavedPosition = this.gameObject.transform.position;
            OldRotation = SavedRotation = this.gameObject.transform.rotation;

            WorldAnchorManager.Instance.AttachAnchor(this.gameObject, AnchorName);
            Debug.Log("Anchor attached for: " + this.gameObject.name + " - AnchorID: " + AnchorName);
        }

        void Update()
        {
            if(Undo)
            {
                WorldAnchorManager.Instance.RemoveAnchor(this.gameObject);
                RestoreBackupAnchor();
                Undo = false;
            }
        }

        public void RestoreBackupAnchor()
        {
            this.gameObject.transform.position = OldPosition;
            this.gameObject.transform.rotation = OldRotation;
            WorldAnchorManager.Instance.AttachAnchor(this.gameObject, AnchorName);
        }

        public void OnFocusEnter()
        {
        }

        public void OnFocusExit()
        {
            SavedPosition = this.gameObject.transform.position;
            SavedRotation = this.gameObject.transform.rotation;
        }

        public void AttachAnchor()
        {
            OldPosition = SavedPosition = this.gameObject.transform.position;
            OldRotation = SavedRotation = this.gameObject.transform.rotation;

            WorldAnchorManager.Instance.AttachAnchor(this.gameObject, AnchorName);
            Debug.Log("Anchor attached for: " + this.gameObject.name + " - AnchorID: " + AnchorName);
        }

        public void UpdatePositionAndRemoveAnchor()
        {
            OldPosition = SavedPosition = this.gameObject.transform.position;
            OldRotation = SavedRotation = this.gameObject.transform.rotation;
            WorldAnchorManager.Instance.RemoveAnchor(this.gameObject);
        }

        public void OnManipulationStarted(ManipulationEventData eventData)
        {
            //Debug.LogFormat("OnManipulationStarted\r\nSource: {0}  SourceId: {1}\r\nCumulativeDelta: {2} {3} {4}",
            //    eventData.InputSource,
            //    eventData.SourceId,
            //    eventData.CumulativeDelta.x,
            //    eventData.CumulativeDelta.y, 
            //    eventData.CumulativeDelta.z);

            WorldAnchorManager.Instance.RemoveAnchor(this.gameObject);
            Debug.Log("OnManipulationStarted - Anchor Removed");
            OldPosition = SavedPosition;
            OldRotation = SavedRotation;
        }

        public void OnManipulationUpdated(ManipulationEventData eventData)
        {
            //if (LogGesturesUpdateEvents)
            //{
            //    Debug.LogFormat("OnManipulationUpdated\r\nSource: {0}  SourceId: {1}\r\nCumulativeDelta: {2} {3} {4}",
            //        eventData.InputSource,
            //        eventData.SourceId,
            //        eventData.CumulativeDelta.x,
            //        eventData.CumulativeDelta.y,
            //        eventData.CumulativeDelta.z);
            //}
        }

        public void OnManipulationCompleted(ManipulationEventData eventData)
        {
            //Debug.LogFormat("OnManipulationCompleted\r\nSource: {0}  SourceId: {1}\r\nCumulativeDelta: {2} {3} {4}",
            //    eventData.InputSource,
            //    eventData.SourceId,
            //    eventData.CumulativeDelta.x,
            //    eventData.CumulativeDelta.y,
            //    eventData.CumulativeDelta.z);

            WorldAnchorManager.Instance.AttachAnchor(this.gameObject, AnchorName);
            Debug.Log("OnManipulationCompleted - Anchor Attached");
        }

        public void OnManipulationCanceled(ManipulationEventData eventData)
        {
        //    Debug.LogFormat("OnManipulationCanceled\r\nSource: {0}  SourceId: {1}\r\nCumulativeDelta: {2} {3} {4}",
        //        eventData.InputSource,
        //        eventData.SourceId,
        //        eventData.CumulativeDelta.x,
        //        eventData.CumulativeDelta.y,
        //        eventData.CumulativeDelta.z);
        }
    }`


Note that the WorldAnchorManager.cs is a Singleton and is referenced by it's instance:
    WorldAnchorManager.Instance.AttachAnchor(this.gameObject, AnchorName);

Also note that the AttachAnchor method has some commentary:
/// <summary>
        /// Attaches an anchor to the game object.  If the anchor store has
        /// an anchor with the specified name it will load the anchor, otherwise
        /// a new anchor will be saved under the specified name.
        /// </summary>

This is where the magic happens so that when the app starts when it tries to attach the anchor, it will first see if it already exists.  If so then it loads the anchor which positions the object wherever it had saved it last time the app ran.

Also, note that I have incorporated a way of undoing the last move by saving the previous position and rotation of the object.

4. Now if you want to be able to grab and move the cube you will need to add the HandDraggable.cs script to the cube.  Keep in mind however that you cannot add the HandDraggable.cs script to an object that has a Rigidbody component attached.  If you have an object that has a rigidbody that you want to move then you'll have to code some way of removing the rigidbody component before adding the HandDraggable component.  But that's not a problem if your not using a rigidbody, just something I ran into.

Hope this helps.  It's all I got.  Thanks!

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
