### ISSUE TITLE
Input Manager & BaseEventData uses parameter that hides inherited property

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#940]
the `tag` property when initializing event data hides inherited `UnityEngine` property `tag`.

**Comment by StephenHodgson** [comment]
Also, what is this even being used for?

**Comment by keveleigh** [comment]
The idea was to allow devs to pass *something* in with an InputManager event.

The example I was given (and is being used in an app):
```         
if (Input.GetButtonDown(mapping.Axis))
{
    InputManager.Instance.RaiseSourceDown(this, sourceId, mapping.PressKind, tag: mapping.Command);
}
```

**Comment by StephenHodgson** [comment]
I'm not sure if I see the benefit here, could you explain a bit more?

Would it be possible to make this an `object` array so people can pass any number of things?

**Comment by mrbobbybobberson** [comment]
Hey @StephenHodgson, I used `tag` on a project a few months ago where we had to support 6DoF controllers, Xbox gamepads, and airtap.  I created an enum called `AppCommand` with different high-level, app-specific commands (`Teleport`, `QueryData`, `PlaceSensor`, etc).  In my Unity project's input settings, I defined Unity axes and mapped Xbox gamepad buttons to them.  I made a `UnityInputSource` class that inherited from `BaseInputSource` that processed the Unity axes and mapped them to the correct `AppCommand`.  I augmented `InteractionSourceInputSource` to assign the correct `AppCommand` for 6DoF controller and airtap input.  Then, in all of my input handlers, I just asked which `AppCommand` to decide how to interpret the input.

That being said, I hear recent Unity betas may have started routing 6DoF controller buttons (and maybe even airtap and clicker?) through its Unity axes as well, which would make my distinction of the `UnityInputSource` and the `InteractionSourceInputSource` break down, since I wouldn't be able to tell which Unity axis inputs were from an Xbox gamepad versus a 6DoF controller.  I'm not sure how I would have handled that... maybe I would have defined a Unity axis for each joystick number and then queried unity for the joystick name to decide what type of controller it was, but at that point, it would get pretty cumbersome, and a different solution might work better.

As for an array of objects, since everything including arrays inherits from `object`, you can pass an `object[]` in as the tag.  In your handlers, you just need to know to cast tag back to `object[]` similar to how I had to cast back to an `AppCommand`.

I hope that helps explain some of the rationale behind the tag.

**Comment by StephenHodgson** [comment]
@mrbobbybobberson, thanks for the details!

>That being said, I hear recent Unity betas may have started routing 6DoF controller buttons (and maybe even airtap and clicker?) through its Unity axes as well, which would make my distinction of the UnityInputSource and the InteractionSourceInputSource break down, since I wouldn't be able to tell which Unity axis inputs were from an Xbox gamepad versus a 6DoF controller.

Yeah I actually just pushed an update that handles exactly that. Building a list of recognized controllers and handling them appropriately.  Check out [`GamePadInputSource.cs`](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Input/Scripts/InputSources/GamePadInputSource.cs#L53) on the master branch.

Although, I'm really interested to see how the new Unity Input System is supposed to handle controllers in the future.

**Comment by mrbobbybobberson** [comment]
Very cool!  I'll take a look at GamePadInputSource, now :)
