### ISSUE TITLE
Improve SceneLauncher

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit-Unity#951]
- [ ] Add an easier way to add all the scenes in the project and enabling the buttons on the prefab.
- [ ] Determine if we want to have _all_ the toolkit scenes in the editor build settings.
    - [See Comments](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/747#discussion_r137913245)

**Comment by ForrestTrepte** [comment]
I see three goals for scene management of the scene(s) when you build and run on device:
1) Make it easy to run the **current scene** that you're working. This currently works well because when there are no scenes in the build settings, builds automatically use the current scene.
2) Run **all scenes** in HoloToolkit. This can be used for testing multiple scenes so that you don't have to build and run each scene individually. It is currently cumbersome to do this, requiring a number of manual steps in both the build settings and the SceneLauncher settings.
3) **New user experience**. I'm guessing that new users would want to run on device and see demos of various scenes from HoloToolkit. Although experienced users can configure option 1 or 2 above, how to do so may be discoverable for new users. What should the default be if you get HoloToolkit for the first time? I'm thinking SceneLauncher with all scenes would be the best outcome, but I worry this conflicts with the first option because then it would be more difficult to run a single scene.

I'd be curious to hear opinions about which of these goals is highest priority or ideas for how we can meet goal 3 without making 1 more difficult.

**Comment by wiwei** [comment]
Closing issues older than 180 days. If this is still an issue, please reactivate with recent information.
