### ISSUE TITLE
Sharing service cloud Hosting procedure

### ISSUE THREAD

**Issue by RaoAM** [Microsoft/MixedRealityToolkit-Unity#953]
Hi, I want to host the sharing service on azure cloud, is it possible? if so, I would like know the procedure to setup. Thanks in advance.

**Comment by edwinckc** [comment]
1. Download [SharingService.exe](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/External/HoloToolkit/Sharing/Server).
2. Right-click the folder where you downloaded the exe, and select Properties.
In the Security tab, Edit > Add, add "SERVICE", and give it full control. This is necessary to run the service, otherwise you will get error 5 (access denied).
3. Open console and run the exe with the -install flag. `SharingService.exe -install`

Open UDP ports 20600-20605 in the Windows firewall.*
Open the same ports in Azure management portal, through the security group.

*The ports work for me, but I'm not certain on exactly which ports are needed. Also, it looks like [20607-20609 are used for Profiling](https://github.com/Microsoft/MixedRealityToolkit/blob/345cac1d24391924db3e1b12d4e0fae20e15cc72/Sharing/Src/Source/Common/Public/CommonSettings.h#L17). Maybe you only need 20602 for the Sessions Server if you aren't using auto-discovery.

When you run the server as a service, you won't have the console logging. I find the [Session Manager](https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/External/HoloToolkit/Sharing/Tools/SessionManager) tool particularly useful, since it shows the server status, has logging, and shows open sessions/rooms.

**Comment by RaoAM** [comment]
Hi, The service setup on azure not working because of the following reason.

Sharing Service is running on NIC ip address, but in azure we are getting NAT behind ip only to NIC ( ex: 192.168.1.X). But if we want to run from Internet we need to run service on Direct WAN IP.

Is there way to come over the hurdle. Thanks

**Comment by yacuzo** [comment]
That sounds like a generic Azure issue, not really something related to SharingService. Why not use the free url (yourAppName.cloudapp.yourRegion.azure.com or something like that)?

**Comment by StephenHodgson** [comment]
Going to close this.  It's probably been archived by google by now.
