### ISSUE TITLE
Rotation Axis Constraint Ignored By Title Bar

### ISSUE THREAD

**Issue by Waffle1434** [microsoft/MixedRealityToolkit-Unity#9531]
## Describe the bug

The `Rotation Axis Constraint` component is sometimes ignored for the "Grab to manipulate the entire scene" panel title bar. This is particularly annoying as the entire scene pitches up and down to face the camera (verified to happen in build in Hololens 2). Switching to/from `Manual Constraint Selection` (the act of hitting the button itself) magically makes the constraint work as intended.

## To reproduce

1. Open any example scene with a "Grab to manipulate the entire scene" title bar (`HandInteractionExamples` for example).
![image](https://user-images.githubusercontent.com/8021358/111843580-b19dba80-88be-11eb-9a6e-8b719ec76d93.png)

2. Use far proximity manipulation to move the title bar up and down / forward and back.
3. Notice the panel and scene is pitching up and down on X axis to satisfy the `Face User Constraint`, but not the rotation constraint.
![grab](https://user-images.githubusercontent.com/8021358/111844810-f591bf00-88c0-11eb-8e9b-b4948f4741f6.gif)

## Expected behavior

"Grab to manipulate the entire scene" has a Rotation Axis Constraint which should only allow Y axis yaw rotation

## "Solution"
1. In the `Constraint Manager` in the TitleBar change the constraint selection mode. The act of hitting one of the buttons seems to correct the issue.
2. Use far proximity manipulation to move the title bar up and down / forward and back.
3. Notice the panel and scene now respect the constraint and only rotate on the Y axis.

## Setup

- Unity 2019.4.21f1
- MRTK v2.6.0

## Target platform

- HoloLens
- HoloLens 2

## Additional context

Something is extra cursed about this issue. After cycling between manual and automatic mode, in some scenes the issue is fixed even after restarting the project. In other scenes it *always* happens, and I have to set the selection mode to manual.

**Comment by Zee2** [comment]
Thanks for reporting this @Waffle1434. This is due to our constraints executing in a non-deterministic order. We test for the correctness of multiple constraints when they do not interfere with each other, but in this case, the two constraints directly affect each other.

In your case, in one order, the two constraints sometimes executed in the "correct" (i.e., obtaining expected result) order, but sometimes did not. This is because the constraints are backed by an unordered hashset.

I have a fix for this coming soon, which should allow for configurable execution order of constraints.
