### ISSUE TITLE
DotNetWinRT not supporting SpatialAnchor

### ISSUE THREAD

**Issue by qian256** [microsoft/MixedRealityToolkit-Unity#9542]
## Describe the problem

The DotNetWinRT package is said to support Windows.Spatial.Perception namespace (https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/using-the-windows-namespace-with-unity-apps-for-hololens) but it looks like it does not include SpatialAnchor related APIs. As a result, it is not possible to call SpatialAnchor APIs in Unity editor just hitting "Play".

On the other hand, when I inspect the NuGet DotNetWinRT package, the XML file listed the SpatialAnchor API, which is very weird.

Although this is not directly related to MRTK, but I couldn't find a better place than here to post this request. Thanks!

## Describe the solution you'd like

Extend the DotNetWinRT API to include SpatialAnchor 

## Describe alternatives you've considered

Is there any other workaround that we could do to use SpatialAnchor in editor mode?

**Comment by davidkline-ms** [comment]
thanks @qian256 ! I will forward to the correct people

**Comment by dfields-msft** [comment]
@qian256 thanks for raising this issue! The API coverage is a bit piecemeal, driven by scenario requirements, and we haven't had a need to support SpatialAnchor so far since Unity provides the [XRAnchor](https://docs.unity3d.com/Packages/com.unity.xr.arsubsystems@3.0/api/UnityEngine.XR.ARSubsystems.XRAnchor.html) API for this (or [ARAnchor](https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@3.0/api/UnityEngine.XR.ARFoundation.ARAnchor.html) if you're using ARFoundation). Could you provide some additional context and details on your scenario for using the native SpatialAnchor APIs directly?

**Comment by qian256** [comment]
In our scenario, we don't use Unity ARSubsyustem or ARFoundation. The API that we find in Unity is UnityEngine.XR.WSA.WorldAnchor, which behaves weird on HoloLens. e.g. it does not show up in the anchorstore. So we sticked to the UWP SpatialAnchor API. As a result, it does not work in editor.

**Comment by keveleigh** [comment]
Hey @qian256! Can you clarify the Unity version and XR package you're using please?

**Comment by qian256** [comment]
Unity 2019.3.1 and legacy XR

**Comment by keveleigh** [comment]
>The API that we find in Unity is UnityEngine.XR.WSA.WorldAnchor, which behaves weird on HoloLens. e.g. it does not show up in the anchorstore. 

This would be very surprising and a definite regression. Were you using the [WorldAnchorStore API](https://docs.unity3d.com/2018.4/Documentation/ScriptReference/XR.WSA.Persistence.WorldAnchorStore.html) to save it in the anchor store?

**Comment by qian256** [comment]
Could I email you for further discussion?

**Comment by MaxWang-MS** [comment]
Please reopen the issue if you are still encountering it.
