### ISSUE TITLE
IconSet does not show Vector Sprites in Preview

### ISSUE THREAD

**Issue by mbentley-uk** [microsoft/MixedRealityToolkit-Unity#9557]
## Describe the bug

An iconset containing vector sprites will not show a preview of the icons when attempting to assign them using the Button Config Helper 

## To reproduce

1. Add package Vector Graphics 2.0.0-preview.14
2. Add an SVG as an asset and in the inspector set the Generated Asset Type to Vector Sprite
![image](https://user-images.githubusercontent.com/81427518/112646489-70b62080-8e3f-11eb-8692-005d10b34eea.png)
3. Add an IconSet as an asset
4. In the IconSet inspector increase the Sprite Icons to 1 and drag the vector sprite into Element 0
![image](https://user-images.githubusercontent.com/81427518/112646898-dc988900-8e3f-11eb-9458-53525340d517.png)
5. An error is reported:
![image](https://user-images.githubusercontent.com/81427518/112646981-f3d77680-8e3f-11eb-8e62-c3f7c721e187.png)
6. Add a PressableButtonHoloLens2... into the scene
7. In the button Button Config Helper component Icon section:
- Set Icon style to Sprite
- Icon Set to the icon set just created
8. The icon is not displayed in the preview button. The preview button can be selected and the icon will show on the Pressable Button
![image](https://user-images.githubusercontent.com/81427518/112648433-701e8980-8e41-11eb-9fd4-36fa871027f6.png)

## Expected behavior

The preview button should contain a preview of the icon

## Your setup (please complete the following information)

- Unity Version [e.g. 2019.4.21f1]
- MRTK Version [e.g. v2.6.0]

## Target platform (please complete the following information)

- HoloLens 2

**Comment by RogPodge** [comment]
Unfortunately it looks like unity's implementation of the Vector Sprite currently does not provide a way to access it's textures. Usually, Texture2Ds have the ability to toggle a Read/Write flag, which seems to be absent from the Vector sprite implementation.

There is a workaround for this, you can import the icons as a Textured Sprite if you want to see the preview. 

![Vector](https://user-images.githubusercontent.com/39840334/122623280-595a8e00-d050-11eb-93c9-ef105759f70e.gif)

Otherwise, the best we can do is suppress the excess of unity console warnings and instead display something in the configurator.
