### ISSUE TITLE
isKinematic turns off on rigidbody objects.

### ISSUE THREAD

**Issue by reeseras** [microsoft/MixedRealityToolkit-Unity#9626]
## Describe the bug

An object with Networked Manipulator, rigidbody and with Realtime Transform from Normcore turn off isKinematic after moving the object. It's not very consistent.

## To reproduce

Create an empty with 2 objects (cube and cylinder). Create an empty as a child of the cylinder and add a collider to it (check "isTrigger" and move the collider so the cube could touch it when moved). Add the following components to the cube: Rigidbody (gravity is off, kinematic is on), Realtime Transform, Networked Manipulator, Object Manipulator, and Near Interaction Grabbable. Now here's the inconsistent part: pick up the cube from a distance and move it rapidly over/through/around/inside the trigger collider. You might have to let go of it a few times inside the collider (or outside the collider?) Eventually, the cube will start to float. Inspect the cube to see isKinematic is turned off. Resetting the game turns it back on.

## Expected behavior

isKinematic should either stay on when moving the object, or turn back on after it's turned off (preventing the object from floating away).

## Your setup (please complete the following information)

- Unity Version: 2019.1.18f1
- MRTK Version: Quest 2.5

## Target platform (please complete the following information)

- HoloLens
- HoloLens 2
- WMR immersive
- OpenVR

## Additional context

Normcore's response:
![image](https://user-images.githubusercontent.com/26148056/113785867-35480b80-96f5-11eb-9dcb-f643506dcce4.png)

**Comment by RogPodge** [comment]
Looking at the Object Manipulator code, we always ensure that the isKinematic state is preserved. One thought is that there may be some state desync when operating over a network, though it's hard to say for sure.

I'm not seeing Networked Manipulator within our API, is this part of Normcore?

**Comment by reeseras** [comment]
> Looking at the Object Manipulator code, we always ensure that the isKinematic state is preserved. One thought is that there may be some state desync when operating over a network, though it's hard to say for sure.
> 
> I'm not seeing Networked Manipulator within our API, is this part of Normcore?

Yes, that's part of Normcore. As well as Realtime Transform.

**Comment by RogPodge** [comment]
@reeseras based on the response that Normcore gave, I think this issue is ultimately a network race condition problem. What might be happening is that we release an object, or revert of isKinematic to it's previous state may be getting overridden by the synchronization being done by the Networking library. 

This is difficult to test and reproduce on our end since we're not currently using Normcore, is it ok if I close this issue?

**Comment by reeseras** [comment]
> @reeseras based on the response that Normcore gave, I think this issue is ultimately a network race condition problem. What might be happening is that we release an object, or revert of isKinematic to it's previous state may be getting overridden by the synchronization being done by the Networking library.
> 
> This is difficult to test and reproduce on our end since we're not currently using Normcore, is it ok if I close this issue?

Sure, but just to be clear: Are we deciding it's ultimately a problem that can't be fixed individually by Normcore or MRTK teams?

**Comment by RogPodge** [comment]
On the MRTK side of things I don't think there's much we can do immediately.

The best solution I think might be adding events to OnManipulationStarted and OnManipulationEnded to sync the object's state, since aggressively syncing all of the properties during play might be resulting in unforseen race conditions

![image](https://user-images.githubusercontent.com/39840334/115293086-bf3b9f80-a10b-11eb-8ea5-99183c8c80b8.png)


https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs#L792-L802

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/265a0ea3621c84b88e4b02e7fcd1b5682afef56a/Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs#L828-L838

**Comment by reeseras** [comment]
I've tried setting the object's velocity to zero and isKinematic to true upon starting &/ ending a manipulation. I'd like to say it helped but it didn't entirely solve the problem. I feel like the bug happened less often, but I can't be sure. I think that's clear enough to close the issue, thanks for your help!
