### ISSUE TITLE
Setting up Photon Unity Networking，the type or namespace name "Azure" does not exist in the namespace“Microsoft”

### ISSUE THREAD

**Issue by iluvian** [microsoft/MixedRealityToolkit-Unity#9647]
## Describe the bug

Follow the tutorial to import the following content, the tutorial error has been cleared, my error still exists
![image](https://user-images.githubusercontent.com/39895100/114387562-2c5bac00-9bc5-11eb-98a7-c46499564e9d.png)

## To reproduce

The step is this link  https://github.com/MicrosoftDocs/mixed-reality/blob/docs/mixed-reality-docs/mr-dev-docs/develop/unity/tutorials/mr-learning-sharing-02.md
![image](https://user-images.githubusercontent.com/39895100/114387396-f61e2c80-9bc4-11eb-8f3a-e48aa53e672b.png)

## Expected behavior

No error

## Your setup (please complete the following information)

- Unity Version 2019.4.8f1
- MRTK Version 2.4.0

## Target platform (please complete the following information)

- HoloLens 2

## Additional context

ARFoundation，PUN2 has been added

**Comment by RogPodge** [comment]
Hey there,

These errors generally occur when the wrong ASA package(s) are being used in the project or are missing altogether. Since you are using Unity 2019.4, so you should target ASA SDK 2.8.1 or lower. For deploying to HoloLens, the Unity project will need to have both the ASA SDK Core package and the ASA SDK Windows package.

Let us know if you still see these issues after double checking the configuration!

**Comment by polar-kev** [comment]
Hi @iluvian, I'm closing this issue since the response above should resolve it. Please reopen the issue if the proposed solution does not work.
