### ISSUE TITLE
Remove GLTF/GLB out of Foundation - It blocks TriLib editor time model importer

### ISSUE THREAD

**Issue by rubit0** [microsoft/MixedRealityToolkit-Unity#9653]
## Describe the bug

1. MRTK GLFT asset importer blocks TriLibs own GLTF importer
2. MRTK Foundation should not have a GLTF importer to beginn with, but in in Extensions or Tools.

## To reproduce

Having MRTK package and TriLib package installed the same time.

## Your setup (please complete the following information)

Any recent Unity and MRTK version

## Target platform (please complete the following information)

- Any Platform

## Additional context

TriLib package in question:
https://assetstore.unity.com/packages/tools/modeling/trilib-2-model-loading-package-157548

**Comment by WikkidEdd** [comment]
Just to add a little to this so the MRTK team don't need to get TriLib in order to reproduce the issue.

The problem is that both MRTK and TriLib use the [ScriptedImporterAttribute](https://docs.unity3d.com/ScriptReference/AssetImporters.ScriptedImporterAttribute.html) in order to support edit time importing of gltf/glb files.  Unity only allows one imported for each file extension, so there is a conflict between TriLib and MRTK. 

Locally I've modified MRTK to wraped the ScriptedImportedAttribute in an #if MRTK_GLTF_IMPORT so one can enable that functionality if desired.

However, I fully agree with @rubit0 that a model import library shouldn't be part of the foundation of MRTK.

**Comment by keveleigh** [comment]
Responded on Slack but I'll copy here too for visibility:

A couple reasons MRTK has a glTF loader/importer:
1. Runtime controller render models return from [the Windows API](https://docs.microsoft.com/en-us/uwp/api/windows.ui.input.spatial.spatialinteractioncontroller.trygetrenderablemodelasync?view=winrt-19041) as a glTF 2.0 Core binary file stream, so we need some way to load those
1. WinMR supports a feature called [3D app launchers](https://docs.microsoft.com/en-us/windows/mixed-reality/distribute/3d-app-launcher-design-guidance) which use glTF files. We use our importer to determine which files are suitable for this feature.

I could see us wrapping the importer with a `#define`, like you mentioned, for 2.x, but it'd likely continue to be enabled by default to not change the flow for those using it. We've had discussions about splitting this out into its own package for MRTK 3.x.
