### ISSUE TITLE
Spatial Mapping issues when moving too fast (usage in a car)

### ISSUE THREAD

**Issue by niklas87** [Microsoft/MixedRealityToolkit-Unity#978]
Hi all,

you can mark this as question, because I think I'm not using the HoloLens as intended but I'll be great if anyone has an idea how to fix this issue.

To describe my problem let me give you some background information on the purpose of the application: I've been doing my masters thesis over the last months and was able to "play" with the HoloLens for about a year. My goal was to create a customizable framework which allows to display different information coming from a vehicle bus or a vehicle prototyping framework. An example: All objects detected by the car's sensors should be marked at their real world position so the testing engineer can verify that these objects are detected correctly.

In theory, I wanted to use the inside-out tracking capabilities of the HoloLens to let it orient within the vehicle cockpit. This means I don't need the HoloLens to scan it's whole surroundings, I'll only need it to look as far as the dashboard and the vehicle headliner. The positions of the objects are received via a vehicle interface and superimposed on the users position in the vehicle.

I tried to restrict the spatial mapping observer to a volume of 1x1x1 m to prevent the HoloLens from trying to scan the space outside. But as soon as I started moving too fast, the holograms started drifting respectively staying at a locked world position and, therefore, drifting though my car.

As far as I could understand - and please correct me if I'm wrong - the set volume of the spatial mapping observer only affects the volume which is passed to the application. But the scanning itself is done on a deeper level, the operating system. So I can technically restrict the application to receive a bigger volume from the OS, but I can not prevent the HoloLens itself to scan a volume as big as it does when sitting in a car. Or, maybe, I'm not using the correct approach for that (say: High Level API instead of Low Level API).

It would be great if you can tell me what I can try to make this work out or even tell me if this isn't possible at all.

Best regards

**Comment by StephenHodgson** [comment]
Probably not possible. Try upping the scan interval, but I doubt that would help too much.

**Comment by smattiso** [comment]
This is amazing. I wonder why there are videos about Ford, Volvo, and other vehicle manufacturers engaging in Hololens development when this issue was brushed off without a second thought. Is there literally nothing that can be done? Nothing in, say, [Holograms 230](https://docs.microsoft.com/en-us/windows/mixed-reality/holograms-230) that remotely helps with this? Even using Limited Mode?

**Comment by smattiso** [comment]
Upon initial experimentation with vehicles in a controlled environment, it appears that the Hololens is better at registering surfaces within environments that have a brighter (non-black) interior or vehicles that are used outdoors rather than in a well-lit garage or carpark (the contrast between the interior and exterior has to be high, with the interior more 'well lit' than the outside environment which should be very bright or very dark). It also helps if you are mostly staring at the vehicle's dashboard or the floor of the vehicle rather than the windows.

This probably won't be a big help to anyone who wants to "place a hologram on the hood of the car" or whatnot but hopefully, this is helpful to someone. Until some engineer figures out how to limit a HoloLens to spatial mapping within a certain range, it will have to do.

**Comment by smattiso** [comment]
Another idea: Attach an AR Card to the windshield, the dashboard, and/or other areas of the vehicle. So long as the Holo's cameras can interpret them in the glare of the sun or the darkness of the interior, they should be able to overlay a fixed mixed reality on top of them.

**Comment by bluntcoder** [comment]
Hi @niklas87 , curious if you had any progress on this front? The AR Card that @smattiso suggested seems promising.

**Comment by niklas87** [comment]
Hi all,

please excuse my late answer - I've been working on other projects recently. The AR Card approach is worth a try, I think. This requires to use a card recognition and tracking framework such as Vuforia, right? I then should be able to place holograms relatively to the recognized cards. But I'm still not sure if things get messy again if I start moving because it always felt like the rapidly changing environments messes up the tracking on OS level which leads to system-based tracking fault overlays.

But I'll try...!

**Comment by Waffle1434** [comment]
Any update on this? I've been considering using Hololens 2's support for QR based anchors

**Comment by JonasKonrad** [comment]
Please have a look [here](https://www.dlr.de/content/en/articles/news/2021/01/20210202_maritime-helicopter-missions.html).
