### ISSUE TITLE
Disable teleport on HoloLens by default

### ISSUE THREAD

**Issue by sloh-ms** [microsoft/MixedRealityToolkit-Unity#9807]
## Describe the bug

I keep getting a red "teleport" line like we use in VR, emitted from my hands while I'm in our app on HL2. We could work around this by turning off the parabolic teleport pointer in the articulated hands controller - but this probably is the wrong default for HoloLens.

## To reproduce

If you're like me, just wave your hands around naturally and the pointer will come.  :-P  Otherwise do the gesture that brings it up intentionally.  Since it's not easy to discover how to turn this on or off, and not much use on HoloLens, we should disable it by default.

See also: 33229717.

## Expected behavior

No teleport pointer

## Your setup (please complete the following information)

- Unity Version 2019.4.21f1
- MRTK Version 2.6.1

## Target platform (please complete the following information)

- HoloLens 2

**Comment by RogPodge** [comment]
Hey there, we've decided to not move forward with disabling teleport on Hololens due to it already being a publically used an requested feature.

If you want to disable teleport for your project, you can do so by disabling the Teleport system under the MRTK profile in the MixedRealityToolkit Gameobject in your scene.

![image](https://user-images.githubusercontent.com/39840334/118342072-a76ef580-b4d6-11eb-96ca-61e75353bc2a.png)
