### ISSUE TITLE
Example scenes generate "CanvasRenderer components are no longer necessary" warnings

### ISSUE THREAD

**Issue by elbuhofantasma** [microsoft/MixedRealityToolkit-Unity#9811]
## Describe the bug

When opening the listed example scenes below in Unity 2020, "CanvasRenderer components are no longer necessary" warnings are generated.

## To reproduce

1. Create a new Unity 2020 project
2. Import the MRTK with either the .unitypackages or UPM packages
3. Import TMP Essentials
4. Open an effected example scene
5. See Unity console output

## Screenshots

**WindowsMicrophoneStreamDemo 3 warnings**
![image](https://user-images.githubusercontent.com/65038391/118153883-3ee72200-b3cb-11eb-8458-8d57c16c320a.png)

**Gltf-Loading-Demo 1 warning**
![image](https://user-images.githubusercontent.com/65038391/118155785-722ab080-b3cd-11eb-952d-acab3acc39b4.png)

**HandCoachExample 44 warnings**
![image](https://user-images.githubusercontent.com/65038391/118156389-275d6880-b3ce-11eb-8385-d387e92674ce.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.7
- MRTK Version 2.7

## Target platform (please complete the following information)

- UWP
- OpenXR

## Additional context

This issue occurs with both .unitypackages and UPM packages. I have not tested this on Unity 2018 or Unity 2019 yet.

**Comment by cre8ivepark** [comment]
@elbuhofantasma It seems this only happens in 2020? I just tried in 2019 but couldn't see the warnings.

**Comment by cre8ivepark** [comment]
Somehow, I don't see the CanvasRenderer component in the objects that gives warnings. Not sure if this is something related to TextMesh Pro issue on a specific version.

**Comment by CDiaz-MS** [comment]
This warning is logged in TextMeshProVersion 3.0.4, 3.0.3 while using Unity 2020.


The warnings are not present in Unity 2019 or Unity 2018 because the default TMP versions depend on the Unity version.  For example, Unity 2019 uses TMP 2.x and Unity 2020 uses TMP 3.x:
![image](https://user-images.githubusercontent.com/53493796/119021348-2db28e00-b954-11eb-8cf0-29cef72b05cf.png)




In TMP 3.0 the following changes were stated in the change log: https://docs.unity3d.com/Packages/com.unity.textmeshpro@3.0/changelog/CHANGELOG.html#changes-3

![image](https://user-images.githubusercontent.com/53493796/119022306-59824380-b955-11eb-9857-37a2de7e7e61.png)

**Comment by CDiaz-MS** [comment]
- [ ] Update release notes informing Unity 2020 users of the TMP warnings
