### ISSUE TITLE
Hand tracking not working in Unity 2019 when using Legacy XR and targeting ARM64

### ISSUE THREAD

**Issue by MaxWang-MS** [microsoft/MixedRealityToolkit-Unity#9817]
## Describe the bug

The hand tracking is not functioning properly (i.e. no hand mesh, no hand ray, gaze cursor does not go away, cannot trigger button etc.) when the Legacy XR is used and ARM64 is set as the target. The issue cannot be reproduced when targeting ARM or using the WinXR Plugin.

## To reproduce

1. Make sure Legacy XR is used
2. Build the hand interaction example scene
3. In VS select release & ARM64

## Your setup (please complete the following information)

- Unity Version 2019.4.25
- MRTK prerelease 2.7

## Target platform (please complete the following information)

- HoloLens 2

**Comment by elbuhofantasma** [comment]
I can confirm that I am seeing this issue when following these steps. I think I have narrowed the cause down to IMixedRealityInputDeviceManager not registering the OpenXR input data providers, which causes it to be unable to calculate the bounds and tracking origin. I am putting the debug and release logs in this response to show what I am seeing, as well as the Unity Console output. 

As a side note, ARM64-Debug Hand Tracking works, but near interaction does not work. Only far interaction is usable in the Debug build.

**ARM64-Release log**
`
Logging to C:/Data/Users/v-alfloy/AppData/Local/Packages/Template3D_pzq3xp76mxafg/TempState/UnityPlayer.log
Loading native plugins
  Loading AudioPluginMsHRTF.dll
Module information:
 Built with Compiler Ver '191627012'
 Built from '2019.4/staging' branch
 Version is '2019.4.25f1 (01a0494af254)'
 Release build
 Application type 'D3D'
 OS 'Windows 10 (10.0.19041)'
PlayerConnection initialized from C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Template3DVS.Release_ARM64.v-alfloy/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55463
Multi-casting "[IP] 192.168.1.139 [Port] 55463 [Flags] 2 [Guid] 6182266 [EditorId] 0 [Version] 1048832 [Id] UWPPlayerARM(HOLOLENS-U1IEO1) [Debug] 0 [PackageName] Template3D_pzq3xp76mxafg [ProjectName] <no name>" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55463]
PlayerConnection already initialized - listening to [0.0.0.0:55463]
[Subsystems] Discovering subsystems at path C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Template3DVS.Release_ARM64.v-alfloy/Data/UnitySubsystems
[Subsystems] No descriptors matched for  examples in UnitySubsystems/MicrosoftOpenXRPlugin/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/MicrosoftOpenXRPlugin/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  displays in UnitySubsystems/MicrosoftOpenXRPlugin/UnitySubsystemsManifest.json.
[Subsystems] 1 'meshings' descriptors matched in UnitySubsystems/MicrosoftOpenXRPlugin/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  examples in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json
[Subsystems] 1 'displays' descriptors matched in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json
[Subsystems] No descriptors matched for  meshings in UnitySubsystems/UnityOpenXR/UnitySubsystemsManifest.json.
[Subsystems] No descriptors matched for  examples in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json.
[Subsystems] 1 'inputs' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
[Subsystems] 1 'displays' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
[Subsystems] 1 'meshings' descriptors matched in UnitySubsystems/WindowsMRXRSDK/UnitySubsystemsManifest.json
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Qualcomm(R) Adreno(TM) 630 GPU (ID=0x45373230)
    Vendor:   
    VRAM:     1932 MB
Initialize engine version: 2019.4.25f1 (01a0494af254)
D3D11 device created for Microsoft Media Foundation video decoding.
Created eye textures with a "texture array" layout.  The "single-pass instancing" stereo mode will be used.

Windows Mixed Reality spatial locatability state changed to Active. 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 324)

The referenced script (Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile) on this Behaviour is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 199)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

A scripted object (probably Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile?) has a different serialization layout when loading. (Read 72 bytes but expected 116 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts? 
(Filename: C:\buildslave\unity\build\Runtime/Serialize/SerializedFile.cpp Line: 2342)

UnloadTime: 3.652500 ms
Unable to register IMixedRealityInputDeviceManager data provider (OpenXR XRSDK Device Manager) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unable to register IMixedRealityInputDeviceManager data provider (OpenXR XRSDK Eye Gaze Provider) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Tracking origin unable to be set.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.XRSDK.XRSDKBoundarySystem:SetTrackingSpace()
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Failed to calculate boundary bounds.
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:CalculateBoundaryBounds()
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
`

**ARM64-Debug log**
`
Logging to C:/Data/Users/v-alfloy/AppData/Local/Packages/Template3D_pzq3xp76mxafg/TempState/UnityPlayer.log
Loading native plugins
  Loading AudioPluginMsHRTF.dll
Module information:
 Built with Compiler Ver '191627012'
 Built from '2019.4/staging' branch
 Version is '2019.4.25f1 (01a0494af254)'
 Debug build
 Application type 'D3D'
 OS 'Windows 10 (10.0.19041)'
PlayerConnection initialized from C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Template3DVS.Debug_ARM64.v-alfloy/Data (debug = 0)
PlayerConnection initialized network socket : 0.0.0.0 55232
Multi-casting "[IP] 192.168.1.139 [Port] 55232 [Flags] 2 [Guid] 3190335073 [EditorId] 0 [Version] 1048832 [Id] UWPPlayerARM(HOLOLENS-U1IEO1) [Debug] 0 [PackageName] Template3D_pzq3xp76mxafg [ProjectName] <no name>" to [225.0.0.222:54997]...
Started listening to [0.0.0.0:55232]
PlayerConnection already initialized - listening to [0.0.0.0:55232]
[Subsystems] Discovering subsystems at path C:/Data/Users/DefaultAccount/AppData/Local/DevelopmentFiles/Template3DVS.Debug_ARM64.v-alfloy/Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Successfully created d3d11 device with debug flag.
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Qualcomm(R) Adreno(TM) 630 GPU (ID=0x45373230)
    Vendor:   
    VRAM:     1932 MB
Initialize engine version: 2019.4.25f1 (01a0494af254)
[AudioManager] InitNormal(tryDeviceDefaults = false, preferredOutputType = FMOD_OUTPUTTYPE_AUTODETECT) attempt with hardAudioDisable: false
[AudioManager] Setting output to FMOD_OUTPUTTYPE_AUTODETECT
[AudioManager] InitNormal succeeded with output "FMOD_OUTPUTTYPE_WASAPI". Driver name is "Speakers (Analog Feature Audio Driver (WDM) - AFAD)". Speaker mode is "FMOD_SPEAKERMODE_STEREO"
D3D11 device created for Microsoft Media Foundation video decoding.
The following GlobalManagers were stripped from the build (Either because they're not used or not supported on this platform):
  ClusterInputManager
  UnityConnectSettings
Created eye textures with a "texture array" layout.  The "single-pass instancing" stereo mode will be used.

Windows Mixed Reality spatial locatability state changed to Active. 
(Filename: C:\buildslave\unity\build\Modules/VR/HoloLens/HoloLensWorldManager.cpp Line: 324)

The referenced script (Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile) on this Behaviour is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Scripting/ManagedReference/SerializableManagedRef.cpp Line: 199)

The referenced script on this Behaviour (Game Object '<null>') is missing! 
(Filename: C:\buildslave\unity\build\Runtime/Mono/ManagedMonoBehaviourRef.cpp Line: 334)

A scripted object (probably Microsoft.MixedReality.Toolkit.XRSDK.Oculus.Input.OculusXRSDKDeviceManagerProfile?) has a different serialization layout when loading. (Read 72 bytes but expected 116 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts? 
(Filename: C:\buildslave\unity\build\Runtime/Serialize/SerializedFile.cpp Line: 2342)

End showing splash screen.
UnloadTime: 11.185937 ms
Unable to register IMixedRealityInputDeviceManager data provider (OpenXR XRSDK Device Manager) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Unable to register IMixedRealityInputDeviceManager data provider (OpenXR XRSDK Eye Gaze Provider) because the value of concreteType is null.
This may be caused by code being stripped during linking. The link.xml file in the MixedRealityToolkit.Generated folder is used to control code preservation.
More information can be found at https://docs.unity3d.com/Manual/ManagedCodeStripping.html.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProviderInternal(Boolean, Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem:RegisterDataProvider(Type, String, SupportedPlatforms, Object[])
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:CreateDataProviders()
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Failed to calculate boundary bounds.
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:LogWarning(Object)
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:CalculateBoundaryBounds()
Microsoft.MixedReality.Toolkit.Boundary.BaseBoundarySystem:Initialize()
Microsoft.MixedReality.Toolkit.<>c:<InitializeAllServices>b__68_0(IMixedRealityService)
System.Action`1:Invoke(T)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:ExecuteOnAllServicesInOrder(Action`1)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeAllServices()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeServiceLocator()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:InitializeInstance()
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:RegisterInstance(MixedRealityToolkit, Boolean)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit:Awake()
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
`

**Unity Console output for Holographic Remoting**
![image](https://user-images.githubusercontent.com/65038391/118342907-6e388480-b4da-11eb-9cf0-15f94a3ca9b8.png)

![image](https://user-images.githubusercontent.com/65038391/118342920-7abcdd00-b4da-11eb-88f6-131746f6b3af.png)

![image](https://user-images.githubusercontent.com/65038391/118342931-890af900-b4da-11eb-970e-1dc7593271af.png)

![image](https://user-images.githubusercontent.com/65038391/118342939-94f6bb00-b4da-11eb-8ec7-2277e02627ff.png)

![image](https://user-images.githubusercontent.com/65038391/118342943-9de78c80-b4da-11eb-9c75-bd219839211a.png)

**Comment by keveleigh** [comment]
I'm not able to repro this :/ I have full hand mesh and hand joint support running on-device with legacy XR and building Release/ARM64 as described

**Comment by MaxWang-MS** [comment]
The issue cannot be reproduced after Visual Studio is updated to 16.9.5. Marking as external and closing for now.

**Comment by MaxWang-MS** [comment]
Just managed to create a reliable repro (at least on my end)
Environment: OS 10.0.19042, Unity 2019.4.26, VS 2019 16.9.6, HL2 OS 21H1 20346.1002
UPM package used: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=18985&view=artifacts&pathAsName=false
Steps to repro:
1. Create a new Unity 2019.4.26 project
2. Switch to UWP platform
3. Import the standard assets and foundation UPM packages
4. In the configurator that pops up, choose legacy XR, check and apply all recommended settings (including the spatializer), import TMP
5. Import the extension and examples package
6. Import hand interaction scene from the example package
7. Open that scene. Note there is a * appearing after the scene name in hierarchy. Double click the scene in the project window to open it again so that there is no *
8. Open up the build window, add the scene and click build (the min plat version is 10.0.10240.0 and the target SDK version is set to latest installed (the latest one appeared in the dropdown is 10.0.19041.0))
9. Open the solution, start debugging using the ARM64+Master configuration
10. See issue

**Comment by keveleigh** [comment]
Looking at the logs and tracing through, I _think_ this is to do with the scenario described at https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9681#discussion_r616305946. At the time, we chose not to take action.

I think the reason we're hitting it with these repro steps is that, by default, Unity builds the app using Template3D as the package name. Windows caches the subsystems list based on package name. This means that if you've ever run a default app (without changing the package name manually) with XR SDK, you'll be unable to use legacy.

**Comment by MaxWang-MS** [comment]
Fixed via #9869
