### ISSUE TITLE
Weird hand pose - InputSimulationService

### ISSUE THREAD

**Issue by cwule** [microsoft/MixedRealityToolkit-Unity#9831]
## Describe the bug

When recording hand input via the `InputRecordingService `on the Hololens 2 and playing it via the `InputPlaybackService`, the joint poses are usually correct while I often observe weird handposes of the hand mesh (screenshot below). I don't observe that weird behaviour during testing in the Unity editor, only when deployed to the Hololens 2. 

## To reproduce

Record and play hand input on the Hololens 2 using `InputRecordingService `and `InputPlaybackService`.

![hand2](https://user-images.githubusercontent.com/8062837/118607849-e9659900-b76d-11eb-85e5-ec9db70ef90f.PNG)

## Your setup (please complete the following information)

- Unity Version 2020.3.6f1
- MRTK Version 2.7.0
- Mixed Reality OpenXR Plugin 0.9.3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by keveleigh** [comment]
Woah, that's weird! @RogPodge @cre8ivepark have you ever seen anything like this?

**Comment by cwule** [comment]
Also to note my comment above, since this is not so clear from the screenshot, only the hand mesh is affected, the joints are correct.

**Comment by RogPodge** [comment]
Yikes I never encountered this while recording the new set of hand poses. It might have to do with the joint rotations being weird even though the joint positions are correct? (Since the mesh deforms based on the rotations)

I don't think we have the time currently to dive deep into this, so for now I'd recommend just using the hand joint visualization for recording playback. We're looking to improve our hand pose recording system and expand on using it in the future, so stay tuned!

**Comment by cwule** [comment]
- It is not only the hand pose that is affected, the recorded camera pose also occasionally flips by 180deg.
- The hand tracking error can also be observed via holographic remoting.

**Comment by RogPodge** [comment]
can you provide a video that describes the recorded camera pose issue that you are seeing?
if there's any error logs or can provide the hand data/hand animation data that would also help identify the issue!

**Comment by cwule** [comment]
[Here is a video](https://youtu.be/jAuhiX9f5XA) showing both the weird hand poses and the camera flipping back and forth.

**Comment by austinbhale** [comment]
Hi, I have tried a few different MRTK setups and am encountering this exact same issue with the head and joint rotations on playback. 

### Setup ###
Unity Version 2020.3.11f1
MRTK Version 2.7.0, 2.6.1, 2.5.4
Mixed Reality OpenXR Plugin 0.9.5

Attached is a quick, similar video showing the hand mesh deformations: [video demo](https://drive.google.com/file/d/13U0pZamt9e2x_EomeEKzTZATCAF0rJzx/view?usp=sharing).

**Comment by austinbhale** [comment]
I believe one notable cause for this issue occurs in the optimization of the animation curves:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L534
Which, in this case, leads to the optimization of rotation curves defined here: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L1216

The RotationW keys are removed during this optimization and the length of the RotationW curves for certain joints become 1. Then, when you playback an animation file, some joints have a repeated `w` rotation curve leading to this glitch.

I'm wondering if the [OptimizeRotationCurve](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L1216) function should have the following small changes:
1. #### Replace ####
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L1240
with `outCurveW.AddKey(curveW[curveW.length - 1]);`

2. #### Replace ####
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L1250
with `outCurveW.AddKey(curveW[j]);`

3. #### Insert a line under ####
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/119f16f59e7b4cd54142be29845c846bc2a2db12/Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs#L1294
with `outCurveW.AddKey(inCurveW[bestIndex]);`

Here is a [video](https://youtu.be/hmLoHjKyRNs) showing the following scenarios:
- Before changes
- Before changes AND commenting out `animation.Optimize(profile);`
- After changes

You can find the animation files here: https://drive.google.com/drive/folders/1iF---Gtd78hd6QTnKHgsyaqKIRiVw-3w?usp=sharing

Notice that although the animation performs much smoother with latter two scenarios, the glitch may still occur. It is just much more infrequent. I didn't create a pull request because it doesn't fix all the recorded quaternions, but I hope it's a step in the right direction.

**Comment by cre8ivepark** [comment]
Tested and experiencing the same issue. Attached Recording vs Playing video.
https://user-images.githubusercontent.com/13754172/123022255-60540a00-d38a-11eb-8e03-07d79ffb1520.mp4

**Comment by RogPodge** [comment]
Hey @austinbhale sorry for the late response getting to this, I tried out your fix and it works really well. I'll be opening a PR with it today!

![RecordingFix](https://user-images.githubusercontent.com/39840334/123167709-c17fea00-d42b-11eb-8975-54386604876e.gif)

**Comment by austinbhale** [comment]
@RogPodge Sounds great, thank you!
