### ISSUE TITLE
Object which contains BoundsControl.cs is crashing the app

### ISSUE THREAD

**Issue by Rive4** [microsoft/MixedRealityToolkit-Unity#9833]
## Describe the bug
I am using BoundsControl.cs in order to modify the shape of a normal cube. I set up the GameObject as the following images:

![Captura1](https://user-images.githubusercontent.com/25901929/118681091-989e8080-b7ff-11eb-96cc-6c6c6c23458c.PNG)
![Captura2](https://user-images.githubusercontent.com/25901929/118681099-9b00da80-b7ff-11eb-8d4c-006a70eb701c.PNG)

The parts of the script I am not showing is because I didn't do any changes to them.
I also added a custom script which avoids y-axis scale and translation:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class LockScaleYAxis : MonoBehaviour
{

    float y_scale;
    Vector3 currentScale;

    // Start is called before the first frame update
    void Start()
    {
        y_scale = this.transform.localScale.y;
    }

    // Update is called once per frame
    void Update()
    {
        currentScale = this.transform.localScale;
        this.transform.localScale = new Vector3(currentScale.x, y_scale, currentScale.z);
        this.transform.position = new Vector3(transform.position.x, -0.05f, transform.position.z);
    }
}
```

When I run in Unity Editor it works, but when I build it for Hololens 2, the application crashes when I open the scene which contains this object.

## To reproduce

1. Make all the setup for Hololens 2 application.
2. Create a basic cube.
3. Add BoundControls.cs to the cube
4. Set up BoundControls as the images above.
5. Build the application for Hololens 2 and run it in the device.

## Expected behavior

Scale the object without crashing the application.

## Your setup (please complete the following information)

- Unity v2019.4.2f1
- MRTK 2.5.3

## Target platform (please complete the following information)

- HoloLens 2

**Comment by CDiaz-MS** [comment]
Hi @Rive4,
 
> I also added a custom script which avoids y-axis scale and translation:

You can achieve this behavior within Bounds Control

Add a y axis scale constraint: 

![image](https://user-images.githubusercontent.com/53493796/118692009-7fc1ab00-b7be-11eb-9e9a-124353522248.png)


Adding a move constraint: 

![image](https://user-images.githubusercontent.com/53493796/118691114-987d9100-b7bd-11eb-861d-0a5a383c8671.png)

![image](https://user-images.githubusercontent.com/53493796/118691189-a9c69d80-b7bd-11eb-897c-85a4fc7f3119.png)


Does the app crash if you modify Bounds Control directly instead of modifying transform values via script?

**Comment by MaxWang-MS** [comment]
Hi @Rive4, could you also confirm whether you are targeting ARM or ARM64 in Visual Studio when building and deploying? If it's ARM64 then you can try switching that to ARM and see if the crash goes away.

**Comment by Rive4** [comment]
Hello,

@CDiaz-MS , I have tried to do what you did but I don't have "Uniform scale on flattened axis" button (maybe because of the MRTK version?).
Furthermore, when I set "Flatten Y", the handles disappear from the cube so I can't resize it.
Should I upgrade to v2.6.1?

@MaxWang-MS I have compiled targeting ARM in Visual Studio instead of ARM64 and seem it works. Is there any explanation for this? (just to take into account for upcoming compilations)

Thank you to both of you.

**Comment by MaxWang-MS** [comment]
Glad to know that ARM worked for you. We have seen some infrequent cases where ARM64 builds do not work as intended potentially due to some external (e.g. compiler) issues, so I suggested that you try ARM instead. In general, I would still suggest you use ARM64 but since you are hitting this issue you can probably just target ARM before you update to a newer version of MRTK, which in some cases solve the problem and allow you to use ARM64 again. Also generally speaking, we recommend staying on the latest version of MRTK to get the latest bug fixes and features.
